import type { ClinicalModuleTerminalContract } from "../lib/clinical-module-terminal-contract";

export const PILOT_MODULE_TERMINAL_CLASSIFICATION: readonly ClinicalModuleTerminalContract[] = [
  {
    protocolId: "avc_agudo_2024",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale:
      "AVC é linha de cuidado completa: reconhecimento, reperfusão/controle, reavaliação e destino assistencial fazem parte do próprio protocolo.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "anaphylaxis_v3",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale:
      "Anafilaxia começa no diagnóstico e termina em alta, observação/internação ou cuidado intensivo conforme resposta e gravidade.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "tep_2024",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "TEP inclui diagnóstico, estratificação, tratamento e destino conforme risco/resposta.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "choque",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Choque é linha de cuidado sindrômica e precisa terminar em observação, internação crítica ou outro destino assistencial explícito.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "insuficiencia_respiratoria",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Insuficiência respiratória conduz avaliação, suporte, etiologia e decisão de destino conforme gravidade.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "tce",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "TCE inclui estratificação de risco, imagem/monitorização e destino assistencial.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "mal_epileptico",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Crise convulsiva/mal epiléptico inclui estabilização, controle, investigação e destino conforme recuperação e refratariedade.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "eap_2024",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "EAP acompanha resposta ao suporte/vasodilatação e define destino conforme gravidade e necessidade de VM/vasoativos.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "sca_acs_2023",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "SCA conduz diagnóstico, estratégia de reperfusão/estratificação, reavaliação e destino após tratamento.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "sepse_ssc_2024",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Sepse/choque séptico é linha de cuidado completa e define cuidado intensivo ou outro destino após estabilização e reavaliação.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "cad_ehh_ada_2024",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "CAD/EHH acompanha correção metabólica, complicações, transição terapêutica e destino conforme gravidade/estabilidade.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "pre_eclampsia_eclampsia_2024",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Pré-eclâmpsia/eclâmpsia inclui estabilização materna, prevenção/tratamento de convulsões, planejamento obstétrico e destino.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "acls_bradycardia_2025",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Bradicardia ACLS conduz estabilidade, tratamento, reavaliação e observação/cuidado intensivo conforme resposta.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "acls_tachycardia_2025",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Taquicardia ACLS conduz estabilidade, cardioversão/tratamento, reavaliação e destino conforme resposta.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "politrauma",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Politrauma é linha de cuidado inicial completa; handoff para cirurgia ou outros módulos não substitui a definição do destino assistencial após a estabilização inicial.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "injuria_renal_aguda",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale: "Injúria renal aguda conduz avaliação etiológica, complicações, tratamento e termina em monitorização ou suporte avançado conforme gravidade.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "isr_rsi_adulto",
    mode: "embedded_care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: true,
    rationale:
      "ISR pode ser aberta diretamente e terminar em observação monitorizada ou UTI pós-intubação; quando chamada por outro protocolo, deve preservar o contexto e devolver o controle após estabilizar a via aérea.",
    reviewedAt: "2026-09-02",
  },
  {
    protocolId: "vm_adulto_2024",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale:
      "Ventilação mecânica invasiva conduz ajuste, estratégia por patologia, segurança, troubleshooting, desmame e termina em UTI com VM contínua ou observação monitorizada pós-extubação.",
    reviewedAt: "2026-09-03",
  },
  {
    protocolId: "intoxicacoes_exogenas",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale:
      "Intoxicações exógenas conduz estabilização, identificação, descontaminação/antídotos quando indicados e termina em UTI ou observação conforme gravidade e risco residual.",
    reviewedAt: "2026-09-03",
  },
  {
    protocolId: "abdome_agudo",
    mode: "care_pathway",
    requiresClinicalDisposition: true,
    requiresReturnToOrigin: false,
    rationale:
      "Abdome agudo conduz estabilização, exclusão de catástrofes, definição do padrão e termina em tratamento cirúrgico/UTI ou observação com reavaliação seriada.",
    reviewedAt: "2026-09-03",
  },
] as const;
