export const AVC_MOCK_CASES = {
  ischemicWindow: {
    patientName: "Caso AVC isquêmico",
    age: "68",
    sex: "Masculino",
    weightKg: "82",
    systolicPressure: "178",
    diastolicPressure: "96",
    glucoseInitial: "118",
    glucoseCurrent: "118",
    lastKnownWellTime: "08:10",
    arrivalTime: "09:05",
    timePrecision: "exact",
    ctResult: "sem_sangramento",
    ctaPerformed: "yes",
    ctaResult: "oclusao_grande_vaso",
  },
  hemorrhagic: {
    patientName: "Caso AVC hemorrágico",
    age: "59",
    sex: "Feminino",
    weightKg: "70",
    systolicPressure: "214",
    diastolicPressure: "118",
    glucoseInitial: "132",
    glucoseCurrent: "132",
    lastKnownWellTime: "11:40",
    arrivalTime: "12:05",
    timePrecision: "exact",
    ctResult: "hemorragia",
  },
};
