import type {
  ContraindicationDefinition,
  NihssItemDefinition,
  ThrombolyticDefinition,
} from "./domain";

export const AVC_TABS = [
  { id: 0, icon: "🧑", label: "Paciente", step: "1", phaseTitle: "Identificação, tempos e origem", accent: "#0f766e" },
  { id: 1, icon: "🧠", label: "Quadro", step: "2", phaseTitle: "Sintomas, ABC e sinais vitais", accent: "#0369a1" },
  { id: 2, icon: "📏", label: "NIHSS", step: "3", phaseTitle: "Escala neurológica completa", accent: "#7c3aed" },
  { id: 3, icon: "🧪", label: "Imagem", step: "4", phaseTitle: "TC, AngioTC e pendências", accent: "#b45309" },
  { id: 4, icon: "💉", label: "Reperfusão", step: "5", phaseTitle: "Elegibilidade, correções e prescrição", accent: "#be123c" },
  { id: 5, icon: "🏥", label: "Destino", step: "6", phaseTitle: "Destino assistencial, auditoria e fechamento", accent: "#1d4ed8" },
] as const;

export const AVC_SECTION_TO_TAB: Record<string, number> = {
  "Responsável e identificação": 0,
  "Tempos críticos": 0,
  "História clínica relevante": 0,
  "Sintomas e quadro neurológico": 1,
  "Estabilização inicial": 1,
  "Sinais vitais e monitorização": 1,
  "NIHSS — consciência": 2,
  "NIHSS — olhar e visão": 2,
  "NIHSS — face e motricidade": 2,
  "NIHSS — coordenação e sensibilidade": 2,
  "NIHSS — linguagem": 2,
  "Imagem e tempos de TC": 3,
  "Angiotomografia e grande vaso": 3,
  "Laboratório e anticoagulação": 3,
  "Contraindicações absolutas": 4,
  "Contraindicações relativas": 4,
  "Contraindicações potencialmente corrigíveis": 4,
  "Pendências diagnósticas e laboratoriais": 4,
  "Decisão terapêutica e prescrição": 4,
  "Destino, checklist e auditoria": 5,
};

export const AVC_WINDOWS = {
  ivTrombolysisMinutes: 270,
  thrombectomyEarlyMinutes: 360,
  thrombectomyExtendedMinutes: 1440,
  imageAlertMinutes: 20,
  tPaMaxPressure: { systolic: 185, diastolic: 110 },
  postTpaPressure: { systolic: 180, diastolic: 105 },
  thrombectomyPressure: { systolicMax: 220, diastolicMax: 120 },
  glucoseHypoMgDl: 50,
  glucoseHyperMgDl: 400,
};

export const THROMBOLYTICS: ThrombolyticDefinition[] = [
  {
    id: "alteplase",
    label: "Alteplase",
    doseMgPerKg: 0.9,
    maxDoseMg: 90,
    roundingStepMg: 0.1,
    bolusFraction: 0.1,
    infusionMinutes: 60,
    note: "Dose total 0,9 mg/kg; 10% em bolus e 90% em infusão contínua por 60 minutos.",
  },
  {
    id: "tenecteplase",
    label: "Tenecteplase",
    doseMgPerKg: 0.25,
    maxDoseMg: 25,
    roundingStepMg: 0.1,
    bolusOnly: true,
    note: "Dose em bolus único; confirmar alinhamento com protocolo local e estratégia de trombectomia.",
  },
];

export const NIHSS_ITEMS: NihssItemDefinition[] = [
  {
    id: "nihss1a",
    label: "1a. Nível de consciência",
    shortLabel: "LOC",
    description: "Resposta global ao estímulo.",
    options: [
      { score: 0, label: "Alerta", description: "Paciente desperto e responsivo." },
      { score: 1, label: "Sonolento", description: "Desperta ao estímulo mínimo." },
      { score: 2, label: "Requer estímulo repetido", description: "Necessita estímulos vigorosos." },
      { score: 3, label: "Coma / sem resposta", description: "Resposta apenas reflexa ou ausente." },
    ],
  },
  {
    id: "nihss1b",
    label: "1b. Perguntas de LOC",
    shortLabel: "Perguntas",
    description: "Acerta mês e idade.",
    options: [
      { score: 0, label: "2 corretas", description: "Mês e idade corretos." },
      { score: 1, label: "1 correta", description: "Acerta apenas uma resposta." },
      { score: 2, label: "0 corretas", description: "Não acerta nenhuma resposta." },
    ],
  },
  {
    id: "nihss1c",
    label: "1c. Comandos de LOC",
    shortLabel: "Comandos",
    description: "Obedece abrir/fechar olhos e apertar/soltar mão.",
    options: [
      { score: 0, label: "2 corretos", description: "Obedece ambos os comandos." },
      { score: 1, label: "1 correto", description: "Obedece apenas um comando." },
      { score: 2, label: "0 corretos", description: "Não obedece comandos." },
    ],
  },
  {
    id: "nihss2",
    label: "2. Melhor olhar conjugado",
    shortLabel: "Olhar",
    description: "Desvio do olhar ou limitação.",
    options: [
      { score: 0, label: "Normal", description: "Sem paralisia ocular." },
      { score: 1, label: "Parcial", description: "Paralisia parcial do olhar." },
      { score: 2, label: "Desvio forçado", description: "Desvio tônico ou ausência total." },
    ],
  },
  {
    id: "nihss3",
    label: "3. Campos visuais",
    shortLabel: "Visão",
    description: "Perda visual por confronto.",
    options: [
      { score: 0, label: "Sem perda", description: "Campos visuais preservados." },
      { score: 1, label: "Hemianopsia parcial", description: "Perda parcial." },
      { score: 2, label: "Hemianopsia completa", description: "Perda completa hemicampo." },
      { score: 3, label: "Hemianopsia bilateral", description: "Cegueira cortical / bilateral." },
    ],
  },
  {
    id: "nihss4",
    label: "4. Paralisia facial",
    shortLabel: "Face",
    description: "Movimento facial voluntário.",
    options: [
      { score: 0, label: "Normal", description: "Simetria facial." },
      { score: 1, label: "Mínima", description: "Assimetria discreta." },
      { score: 2, label: "Parcial", description: "Paresia facial inferior evidente." },
      { score: 3, label: "Completa", description: "Paralisia facial completa." },
    ],
  },
  {
    id: "nihss5a",
    label: "5a. Braço esquerdo",
    shortLabel: "Braço E",
    description: "Mantém elevação por 10 segundos.",
    options: [
      { score: 0, label: "Sem queda", description: "Mantém o membro." },
      { score: 1, label: "Queda parcial", description: "Queda antes de 10 s sem tocar leito." },
      { score: 2, label: "Algum esforço", description: "Não sustenta contra gravidade." },
      { score: 3, label: "Sem esforço", description: "Movimento sem vencer gravidade." },
      { score: 4, label: "Sem movimento", description: "Sem movimento voluntário." },
    ],
  },
  {
    id: "nihss5b",
    label: "5b. Braço direito",
    shortLabel: "Braço D",
    description: "Mantém elevação por 10 segundos.",
    options: [
      { score: 0, label: "Sem queda", description: "Mantém o membro." },
      { score: 1, label: "Queda parcial", description: "Queda antes de 10 s sem tocar leito." },
      { score: 2, label: "Algum esforço", description: "Não sustenta contra gravidade." },
      { score: 3, label: "Sem esforço", description: "Movimento sem vencer gravidade." },
      { score: 4, label: "Sem movimento", description: "Sem movimento voluntário." },
    ],
  },
  {
    id: "nihss6a",
    label: "6a. Perna esquerda",
    shortLabel: "Perna E",
    description: "Mantém elevação por 5 segundos.",
    options: [
      { score: 0, label: "Sem queda", description: "Mantém o membro." },
      { score: 1, label: "Queda parcial", description: "Queda antes de 5 s sem tocar leito." },
      { score: 2, label: "Algum esforço", description: "Não sustenta contra gravidade." },
      { score: 3, label: "Sem esforço", description: "Movimento sem vencer gravidade." },
      { score: 4, label: "Sem movimento", description: "Sem movimento voluntário." },
    ],
  },
  {
    id: "nihss6b",
    label: "6b. Perna direita",
    shortLabel: "Perna D",
    description: "Mantém elevação por 5 segundos.",
    options: [
      { score: 0, label: "Sem queda", description: "Mantém o membro." },
      { score: 1, label: "Queda parcial", description: "Queda antes de 5 s sem tocar leito." },
      { score: 2, label: "Algum esforço", description: "Não sustenta contra gravidade." },
      { score: 3, label: "Sem esforço", description: "Movimento sem vencer gravidade." },
      { score: 4, label: "Sem movimento", description: "Sem movimento voluntário." },
    ],
  },
  {
    id: "nihss7",
    label: "7. Ataxia",
    shortLabel: "Ataxia",
    description: "Ataxia desproporcional à fraqueza.",
    options: [
      { score: 0, label: "Ausente", description: "Sem ataxia." },
      { score: 1, label: "1 membro", description: "Ataxia em um membro." },
      { score: 2, label: "2 membros", description: "Ataxia em dois membros." },
    ],
  },
  {
    id: "nihss8",
    label: "8. Sensibilidade",
    shortLabel: "Sensibilidade",
    description: "Perda sensitiva hemisférica.",
    options: [
      { score: 0, label: "Normal", description: "Sem perda." },
      { score: 1, label: "Leve/moderada", description: "Perda parcial." },
      { score: 2, label: "Grave", description: "Perda severa ou total." },
    ],
  },
  {
    id: "nihss9",
    label: "9. Linguagem",
    shortLabel: "Linguagem",
    description: "Afasia e produção de linguagem.",
    options: [
      { score: 0, label: "Normal", description: "Sem afasia." },
      { score: 1, label: "Leve", description: "Afasia leve/moderada." },
      { score: 2, label: "Grave", description: "Afasia grave." },
      { score: 3, label: "Mudo", description: "Mudo ou afasia global." },
    ],
  },
  {
    id: "nihss10",
    label: "10. Disartria",
    shortLabel: "Disartria",
    description: "Articulação da fala.",
    options: [
      { score: 0, label: "Normal", description: "Sem disartria." },
      { score: 1, label: "Leve/moderada", description: "Disartria compreensível." },
      { score: 2, label: "Grave", description: "Fala ininteligível ou anártrica." },
    ],
  },
  {
    id: "nihss11",
    label: "11. Extinção / negligência",
    shortLabel: "Negligência",
    description: "Neglect visual ou tátil.",
    options: [
      { score: 0, label: "Ausente", description: "Sem negligência." },
      { score: 1, label: "Parcial", description: "Extinção parcial." },
      { score: 2, label: "Profunda", description: "Negligência grave." },
    ],
  },
];

export const CONTRAINDICATIONS: ContraindicationDefinition[] = [
  {
    id: "ct_hemorrhage",
    category: "absolute",
    name: "Hemorragia intracraniana na TC",
    description: "Qualquer hemorragia na neuroimagem inicial.",
    impact: "Proíbe trombólise intravenosa.",
    correctable: false,
    blocksThrombolysis: true,
    blocksThrombectomy: false,
  },
  {
    id: "active_bleeding",
    category: "absolute",
    name: "Sangramento ativo importante",
    description: "Sangramento gastrointestinal, geniturinário ou outro sangramento relevante em curso.",
    impact: "Proíbe trombólise até resolução e revisão especializada.",
    correctable: false,
    blocksThrombolysis: true,
  },
  {
    id: "recent_major_surgery",
    category: "absolute",
    name: "Cirurgia maior / trauma recente",
    description: "Cirurgia maior ou trauma cranioencefálico recente conforme protocolo local.",
    impact: "Aumenta risco hemorrágico grave com trombólise.",
    correctable: false,
    blocksThrombolysis: true,
  },
  {
    id: "known_coagulopathy",
    category: "absolute",
    name: "Coagulopatia incompatível",
    description: "Plaquetas baixas, INR elevado, anticoagulação ativa incompatível ou TTPa prolongado relevante.",
    impact: "Bloqueia trombólise.",
    correctable: true,
    correctionGuidance: "Rever tipo de anticoagulante, tempo da última dose, exames e possibilidade de reversão.",
    blocksThrombolysis: true,
  },
  {
    id: "severe_hypertension",
    category: "correctable",
    name: "PA acima do limite para trombólise",
    description: "PAS > 185 mmHg ou PAD > 110 mmHg.",
    impact: "Exige controle pressórico antes de qualquer trombólise.",
    correctable: true,
    correctionGuidance: "Controlar PA, registrar horário e reavaliar elegibilidade.",
    blocksThrombolysis: true,
  },
  {
    id: "critical_glucose",
    category: "correctable",
    name: "Glicemia extrema não corrigida",
    description: "Hipoglicemia ou hiperglicemia que possa mimetizar ou agravar o quadro.",
    impact: "Bloqueia decisão automática até correção e reavaliação neurológica.",
    correctable: true,
    correctionGuidance: "Corrigir glicemia, repetir medida e reavaliar déficit neurológico.",
    blocksThrombolysis: true,
    blocksThrombectomy: true,
  },
  {
    id: "unknown_time",
    category: "diagnostic_pending",
    name: "Tempo de início/LKW desconhecido",
    description: "Sem hora confiável de início dos sintomas ou última vez normal.",
    impact: "Impede recomendação automática de reperfusão padrão.",
    correctable: false,
    blocksThrombolysis: true,
    blocksThrombectomy: true,
  },
  {
    id: "pending_ct",
    category: "diagnostic_pending",
    name: "Hemorragia não excluída por TC",
    description: "TC ainda não realizada, sem laudo/interpretação ou inconclusiva.",
    impact: "Trombólise proibida até excluir hemorragia adequadamente.",
    correctable: true,
    correctionGuidance: "Acelerar neuroimagem e registrar horário de interpretação.",
    blocksThrombolysis: true,
  },
  {
    id: "pending_labs_anticoag",
    category: "lab_pending",
    name: "Exames pendentes em usuário de anticoagulante",
    description: "Exames essenciais não disponíveis em contexto de anticoagulação ou coagulopatia suspeita.",
    impact: "Mantém decisão em revisão até completar dados.",
    correctable: true,
    correctionGuidance: "Obter exames e revisar anticoagulante/última dose.",
    blocksThrombolysis: true,
  },
  {
    id: "minor_non_disabling",
    category: "relative",
    name: "Déficit menor e potencialmente não incapacitante",
    description: "NIHSS baixo sem claro déficit incapacitante.",
    impact: "Exige discussão clínica; não liberar automaticamente.",
    correctable: false,
    blocksThrombolysis: false,
  },
  {
    id: "seizure_mimic",
    category: "relative",
    name: "Crise convulsiva / mimetizador de AVC",
    description: "Déficit pode ser pós-ictal ou mimetizador.",
    impact: "Exige revisão clínica e imagem antes de reperfusão.",
    correctable: false,
    blocksThrombolysis: false,
    blocksThrombectomy: false,
  },
  {
    id: "needs_lvo_imaging",
    category: "diagnostic_pending",
    name: "Suspeita de oclusão de grande vaso sem avaliação vascular",
    description: "CTA ainda não feita ou sem resultado apesar de suspeita clínica.",
    impact: "Trombectomia depende de imagem vascular/neurologia.",
    correctable: true,
    correctionGuidance: "Solicitar/interpretar angiotomografia e acionar neurologia/intervenção.",
    blocksThrombolysis: false,
    blocksThrombectomy: true,
  },
];

export const AVC_DESTINATION_LABELS: Record<string, string> = {
  uti: "UTI / neurointensivismo",
  unidade_avc: "Unidade de AVC",
  sala_vermelha: "Sala vermelha / observação monitorizada",
  transferencia_trombectomia: "Transferência para centro de trombectomia",
  enfermaria: "Enfermaria",
  observacao: "Observação",
};
