import { StyleSheet } from "react-native";

import { AppDesign } from "../../constants/app-design";

/** Painel interior azul — continuidade com hub / landing */
const shellPanel = {
  marginHorizontal: 12,
  marginTop: 6,
  marginBottom: 8,
  padding: 18,
  paddingBottom: 200,
  gap: 14 as number,
  backgroundColor: "#dfeafe",
  borderRadius: 34,
  borderWidth: 1,
  borderColor: "rgba(122,167,247,0.42)",
  maxWidth: 560,
  width: "100%" as const,
  alignSelf: "center" as const,
  shadowColor: "#021113",
  shadowOpacity: 0.18,
  shadowRadius: 28,
  shadowOffset: { width: 0, height: 14 },
  elevation: 10,
};

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: AppDesign.canvas.tealBackdrop,
  },
  content: {
    flexGrow: 1,
    justifyContent: "flex-start",
    ...shellPanel,
    paddingBottom: 200,
    gap: 18,
  },
  card: {
    backgroundColor: "rgba(251,248,242,0.97)",
    borderRadius: AppDesign.radius.xl,
    padding: 24,
    borderWidth: 1,
    borderColor: "#bfd0ea",
    shadowColor: "#03181a",
    shadowOpacity: 0.09,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  actionCard: {
    borderLeftWidth: 6,
    borderLeftColor: "#b91c1c",
  },
  questionCard: {
    borderLeftWidth: 6,
    borderLeftColor: AppDesign.accent.primary,
  },
  endCard: {
    borderLeftWidth: 6,
    borderLeftColor: AppDesign.accent.primary,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  eyebrow: {
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#b91c1c",
    marginBottom: 10,
  },
  stateBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    color: AppDesign.accent.teal,
    backgroundColor: AppDesign.accent.primaryMuted,
    marginBottom: 10,
  },
  urgencyBanner: {
    marginBottom: 12,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#edf4ff",
    gap: 4,
  },
  urgencyBannerDanger: {
    backgroundColor: "#fee2e2",
    borderWidth: 1,
    borderColor: "#fca5a5",
  },
  urgencyBannerWarning: {
    backgroundColor: "#ffedd5",
    borderWidth: 1,
    borderColor: "#fdba74",
  },
  urgencyBannerInfo: {
    backgroundColor: "#dbeafe",
    borderWidth: 1,
    borderColor: "#93c5fd",
  },
  urgencyBannerLabel: {
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#7f1d1d",
  },
  urgencyBannerDetail: {
    fontSize: 14,
    lineHeight: 20,
    color: "#334155",
  },
  title: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "900",
    color: "#13263c",
    textAlign: "left",
    marginTop: 4,
  },
  actionTitle: {
    color: "#7f1d1d",
  },
  questionTitle: {
    color: AppDesign.accent.teal,
  },
  endTitle: {
    color: AppDesign.accent.teal,
  },
  detailsTitle: {
    fontSize: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#475569",
    marginBottom: 2,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#13263c",
    marginBottom: 4,
  },
  detailsBlock: {
    marginTop: 18,
    gap: 10,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#d5e2f5",
    backgroundColor: "#f4f8ff",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  focusSummaryBlock: {
    marginTop: 16,
    gap: 8,
    paddingVertical: 4,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  detailBullet: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#b91c1c",
    marginTop: 8,
  },
  detailText: {
    fontSize: 17,
    lineHeight: 24,
    color: "#2a4056",
    flex: 1,
  },
  timerBadge: {
    marginTop: 20,
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderRadius: 24,
    backgroundColor: "#223d6a",
    borderWidth: 1,
    borderColor: "rgba(180,205,255,0.32)",
    alignItems: "center",
  },
  timerSection: {
    gap: 10,
  },
  timerLabel: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: "#cbd5e1",
    marginBottom: 6,
  },
  timerValue: {
    fontSize: 46,
    fontWeight: "800",
    color: "#ffffff",
    lineHeight: 50,
  },
  voiceTopRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "flex-start",
    gap: 10,
    marginTop: -6,
  },
  voiceCompactCard: {
    maxWidth: 260,
    backgroundColor: "rgba(251,248,242,0.96)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#bfd0ea",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  voiceCompactTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  voiceCompactChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  voiceCompactChip: {
    borderRadius: 999,
    backgroundColor: AppDesign.accent.primaryMuted,
    borderWidth: 1,
    borderColor: "#a5f3fc",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  voiceCompactChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#0e7490",
  },
  voiceQuickToggleButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#bfd0ea",
    backgroundColor: "#f4f8ff",
    shadowColor: "#0f172a",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  voiceQuickToggleButtonActive: {
    borderColor: "#0f766e",
    backgroundColor: "#ccfbf1",
  },
  voiceQuickToggleButtonText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0f6b61",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  voiceQuickToggleButtonTextActive: {
    color: "#115e59",
  },
  timerHint: {
    marginTop: 4,
    fontSize: 12,
    color: "#e2e8f0",
  },
  timerSubHint: {
    marginTop: 6,
    fontSize: 12,
    color: "#f8fafc",
    fontWeight: "700",
  },
  primaryActions: {
    gap: 10,
  },
  primaryActionsTop: {
    marginVertical: 16,
    gap: 10,
  },
  actions: {
    gap: 14,
  },
  screenWrapper: {
    flex: 1,
    backgroundColor: AppDesign.canvas.tealBackdrop,
  },
  screenContent: {
    ...shellPanel,
  },
  prolongedResuscitationCard: {
    backgroundColor: "#fff7ed",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#fb923c",
    padding: 14,
    gap: 4,
  },
  prolongedResuscitationTitle: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#c2410c",
  },
  prolongedResuscitationText: {
    fontSize: 14,
    color: "#7c2d12",
    lineHeight: 20,
  },
  phaseIndicator: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    gap: 6,
  },
  phaseProgressBar: {
    flexDirection: "row",
    gap: 4,
  },
  phaseSegment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
  },
  phaseSegmentActive: {
    backgroundColor: AppDesign.accent.lime,
  },
  phaseSegmentInactive: {
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  phaseLabel: {
    fontSize: 12,
    fontWeight: "900",
    color: AppDesign.accent.lime,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  sepsisTopBar: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    backgroundColor: "#102128",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: 16,
    gap: 10,
  },
  sepsisTopBarPhase: {
    gap: 4,
  },
  sepsisTopBarInfo: {
    gap: 3,
  },
  sepsisTopBarStep: {
    fontSize: 16,
    fontWeight: "900",
    color: "#ffffff",
    lineHeight: 22,
  },
  sepsisTopBarHint: {
    fontSize: 14,
    color: "#a9c1c7",
    lineHeight: 20,
    fontWeight: "600",
  },
  dkaHhsRoteiroCard: {
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#fffbeb",
    borderWidth: 1,
    borderColor: "#fde68a",
    gap: 10,
  },
  dkaHhsRoteiroTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#92400e",
    letterSpacing: 0.3,
  },
  dkaHhsRoteiroHeading: {
    fontSize: 12,
    fontWeight: "700",
    color: "#78350f",
    marginTop: 4,
  },
  dkaHhsRoteiroLine: {
    fontSize: 11,
    color: "#451a03",
    lineHeight: 16,
    paddingLeft: 8,
  },
  dkaHhsRoteiroFoot: {
    fontSize: 10,
    color: "#a16207",
    fontStyle: "italic",
    marginTop: 4,
  },
  stepHeaderBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  stepBadge: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: AppDesign.accent.primary,
  },
  stepCard: {
    backgroundColor: "#ffffff",
    borderRadius: AppDesign.radius.xl,
    padding: 20,
    borderWidth: 1,
    borderColor: AppDesign.border.subtle,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    gap: 12,
  },
  stepCardTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#0b1f40",
    lineHeight: 32,
  },
  stepCardInstruction: {
    fontSize: 17,
    color: "#334155",
    lineHeight: 24,
  },
  progressLabel: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#6b7280",
  },
  progressTrack: {
    height: 6,
    backgroundColor: "#e2e8f0",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressIndicator: {
    height: 6,
    backgroundColor: AppDesign.accent.primary,
  },
  stepNextStep: {
    fontSize: 14,
    color: "#2563eb",
    fontWeight: "600",
  },
  actionPanel: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    gap: 8,
  },
  actionPanelTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  actionChecklist: {
    gap: 6,
  },
  actionChecklistItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  actionChecklistBullet: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#2563eb",
  },
  actionChecklistText: {
    fontSize: 14,
    color: "#1f2937",
    fontWeight: "600",
  },
  decisionGrid: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  decisionButton: {
    flex: 1,
    minHeight: 72,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    backgroundColor: "#ffffff",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: 16,
  },
  decisionButtonPrimary: {
    borderColor: AppDesign.accent.primary,
    backgroundColor: AppDesign.accent.primaryMuted,
  },
  decisionButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  voiceStatusBar: {
    backgroundColor: "#f8fbff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 16,
    gap: 10,
    shadowColor: "#0b1f40",
    shadowOpacity: 0.08,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  voiceStatusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  voiceStatusTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0f172a",
  },
  voiceStatusBadgeLight: {
    backgroundColor: "#e0f2fe",
    color: "#0c4a6e",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: "700",
  },
  voiceCommandPins: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  voiceCommandPin: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#f8fafc",
    fontSize: 13,
    color: "#0f172a",
    fontWeight: "600",
  },
  voiceCommandNote: {
    fontSize: 13,
    color: "#334155",
    fontWeight: "600",
  },
  voiceToggleButton: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2563eb",
    paddingVertical: 8,
    alignItems: "center",
    backgroundColor: "#eff6ff",
  },
  voiceToggleButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2563eb",
  },
  fixedFooterAction: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 18,
    borderRadius: 999,
    backgroundColor: "#0f172a",
    height: 64,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  fixedFooterText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  backButton: {
    minHeight: 50,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8f5ef",
    borderWidth: 1.5,
    borderColor: "#c4d5cd",
    paddingHorizontal: 18,
  },
  backButtonText: {
    color: "#334155",
    fontSize: 16,
    fontWeight: "900",
  },
  suggestedNextStepCard: {
    backgroundColor: "#eff6ff",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#93c5fd",
    gap: 8,
  },
  suggestedNextStepEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: AppDesign.accent.teal,
  },
  suggestedNextStepTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  suggestedNextStepText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#334155",
  },
  suggestedNextStepButton: {
    marginTop: 4,
    minHeight: 52,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0f172a",
    paddingHorizontal: 18,
  },
  suggestedNextStepButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  modeSwitchRow: {
    flexDirection: "row",
    gap: 10,
  },
  modeSwitchSection: {
    gap: 6,
    alignItems: "flex-end",
  },
  modeSwitchTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  modeSwitchHint: {
    fontSize: 13,
    lineHeight: 18,
    color: "#64748b",
  },
  voiceCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    gap: 12,
  },
  voiceCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  voiceCardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  voiceControlCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e2e4ea",
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  voiceControlHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  voiceControlTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  voiceStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#e2e8f0",
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  voiceStatusListening: {
    backgroundColor: "#fee2e2",
    color: "#991b1b",
  },
  voiceStatusActive: {
    backgroundColor: "#dcfce7",
    color: "#155e47",
  },
  voiceStatusInactive: {
    backgroundColor: "#fffbeb",
    color: "#92400e",
  },
  voiceDescription: {
    fontSize: 13,
    lineHeight: 19,
    color: "#475569",
  },
  voicePrimaryButton: {
    minHeight: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0f172a",
    paddingHorizontal: 18,
  },
  voicePrimaryButtonDisabled: {
    backgroundColor: "#cbd5e1",
  },
  voicePrimaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  voicePrimaryButtonTextDisabled: {
    color: "#475569",
  },
  voiceTranscriptBox: {
    borderRadius: 14,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 12,
    gap: 4,
  },
  voiceTranscriptBoxHighlighted: {
    backgroundColor: "#eff6ff",
    borderColor: "#60a5fa",
  },
  voiceTranscriptLabel: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#64748b",
  },
  voiceTranscriptText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#0f172a",
  },
  voiceFeedbackText: {
    fontSize: 13,
    lineHeight: 19,
    color: "#0f172a",
    fontWeight: "700",
  },
  voiceConfirmationCard: {
    borderRadius: 14,
    backgroundColor: "#fff7ed",
    borderWidth: 1,
    borderColor: "#fdba74",
    padding: 12,
    gap: 10,
  },
  voiceSection: {
    backgroundColor: "#f1f5f9",
    borderRadius: 22,
    padding: 20,
    gap: 18,
    borderColor: "#cbd5e1",
    borderWidth: 1,
  },
  voiceInstructionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  voiceInstructionText: {
    flex: 1,
    fontSize: 14,
    color: "#475569",
  },
  voiceConfirmationTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#9a3412",
  },
  voiceConfirmationActions: {
    flexDirection: "row",
    gap: 8,
  },
  voiceConfirmationButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#9a3412",
  },
  voiceConfirmationButtonAlt: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#fdba74",
  },
  voiceConfirmationButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#ffffff",
  },
  voiceConfirmationButtonTextAlt: {
    fontSize: 14,
    fontWeight: "800",
    color: "#9a3412",
  },
  modeSwitchButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eef2f7",
    borderWidth: 1,
    borderColor: "#dbe4ee",
    cursor: "pointer",
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  modeSwitchButtonActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  modeSwitchButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#334155",
  },
  modeSwitchButtonTextActive: {
    color: "#ffffff",
  },
  modeSwitchButtonSubtext: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
  },
  modeSwitchButtonSubtextActive: {
    color: "#cbd5e1",
  },
  secondaryActions: {
    gap: 12,
    position: "relative",
    zIndex: 3,
  },
  secondaryActionsFooter: {
    gap: 12,
    marginTop: 24,
    marginBottom: 12,
  },
  toolsToggleCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#0f172a",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  toolsToggleTitle: {
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#475569",
  },
  toolsToggleText: {
    marginTop: 2,
    fontSize: 13,
    color: "#64748b",
  },
  toolsToggleAction: {
    fontSize: 13,
    fontWeight: "800",
    color: "#334155",
    textTransform: "uppercase",
  },
  toolsSectionCard: {
    gap: 14,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe4ea",
    shadowColor: "#0f172a",
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  toolsSectionHeader: {
    gap: 4,
  },
  toolsSectionEyebrow: {
    fontSize: 11,
    fontWeight: "800",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  toolsSectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  toolsButtonsGrid: {
    gap: 10,
  },
  sepsisPanelCard: {
    backgroundColor: "#fdfdfa",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e6ecf6",
    gap: 12,
  },
  sepsisPanelTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  sepsisPanelGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  sepsisMetricItem: {
    width: "47%",
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: "#dbe4ea",
  },
  sepsisMetricLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#64748b",
  },
  sepsisMetricValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  auxiliaryPanelCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 14,
  },
  auxiliaryPanelTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  auxiliaryPanelDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: "#475569",
  },
  auxiliarySectionCard: {
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 12,
    gap: 10,
  },
  auxiliarySectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#334155",
  },
  auxiliaryFields: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  auxiliaryFieldGroup: {
    width: "48%",
    gap: 6,
  },
  auxiliaryFieldGroupFullWidth: {
    width: "100%",
  },
  auxiliaryFieldLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
  },
  auxiliaryInput: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: "#0f172a",
    backgroundColor: "#ffffff",
  },
  auxiliaryFieldHelper: {
    fontSize: 12,
    color: "#64748b",
  },
  auxiliaryUnitRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  auxiliaryUnitButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#cbd5e1",
  },
  auxiliaryUnitButtonActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  auxiliaryUnitButtonText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#334155",
  },
  auxiliaryUnitButtonTextActive: {
    color: "#ffffff",
  },
  auxiliaryPresetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  auxiliaryPresetButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#e0f2fe",
    borderWidth: 1,
    borderColor: "#7dd3fc",
  },
  auxiliaryPresetButtonActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  auxiliaryPresetButtonText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0c4a6e",
  },
  auxiliaryPresetButtonTextActive: {
    color: "#ffffff",
  },
  auxiliaryMetrics: {
    gap: 8,
  },
  auxiliaryRecommendations: {
    gap: 10,
  },
  auxiliaryRecommendationCard: {
    backgroundColor: "#eef6ff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    padding: 14,
    gap: 8,
  },
  auxiliaryRecommendationCardWarning: {
    backgroundColor: "#fff7ed",
    borderColor: "#fdba74",
  },
  auxiliaryRecommendationTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0f172a",
  },
  auxiliaryRecommendationLine: {
    fontSize: 13,
    lineHeight: 19,
    color: "#334155",
  },
  auxiliaryStatusList: {
    gap: 10,
  },
  auxiliaryStatusItem: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "#dbe4ea",
  },
  auxiliaryStatusHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  auxiliaryStatusLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: "#0f172a",
  },
  auxiliaryStatusValue: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    color: "#334155",
    backgroundColor: "#e2e8f0",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  auxiliaryStatusButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  auxiliaryStatusButton: {
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: "transparent",
    minWidth: "31%",
    alignItems: "center",
    justifyContent: "center",
  },
  auxiliaryStatusPending: {
    backgroundColor: "#f3f4f6",
    borderColor: "#d1d5db",
  },
  auxiliaryStatusPendingSelected: {
    backgroundColor: "#374151",
    borderColor: "#111827",
  },
  auxiliaryStatusRequested: {
    backgroundColor: "#dbeafe",
    borderColor: "#60a5fa",
  },
  auxiliaryStatusRequestedSelected: {
    backgroundColor: "#2563eb",
    borderColor: "#1d4ed8",
  },
  auxiliaryStatusDone: {
    backgroundColor: "#dcfce7",
    borderColor: "#4ade80",
  },
  auxiliaryStatusDoneSelected: {
    backgroundColor: "#15803d",
    borderColor: "#166534",
  },
  auxiliaryStatusSelected: {
    borderColor: "#0f172a",
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  auxiliaryStatusButtonText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0f172a",
  },
  auxiliaryStatusButtonTextSelected: {
    color: "#ffffff",
  },
  auxiliaryMetricItem: {
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 12,
    gap: 4,
  },
  auxiliaryMetricLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#64748b",
  },
  auxiliaryMetricValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  auxiliaryActions: {
    gap: 10,
  },
  auxiliaryActionButton: {
    backgroundColor: "#0f172a",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  auxiliaryActionButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  documentationButton: {
    minHeight: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1f2937",
    paddingHorizontal: 18,
    position: "relative",
    zIndex: 4,
    cursor: "pointer",
  },
  documentationButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    userSelect: "none",
  },
  secondaryButton: {
    minHeight: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe4ea",
    paddingHorizontal: 18,
    shadowColor: "#0f172a",
    shadowOpacity: 0.02,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
    cursor: "pointer",
  },
  secondaryButtonText: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
  primaryButton: {
    minHeight: 58,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#102128",
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    shadowColor: "#021113",
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 0.2,
  },
  optionButton: {
    minHeight: 66,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eff6ff",
    borderWidth: 2,
    borderColor: "#93c5fd",
    paddingHorizontal: 22,
    shadowColor: "#1d4ed8",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  optionButtonText: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  causeCard: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 16,
    marginTop: 16,
    gap: 12,
  },
  causeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  causeTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    color: "#6b7280",
    backgroundColor: "#f3f4f6",
  },
  statusSuspected: {
    color: "#92400e",
    backgroundColor: "#fef3c7",
  },
  statusAddressed: {
    color: "#166534",
    backgroundColor: "#dcfce7",
  },
  causeActions: {
    gap: 8,
  },
  causeActionText: {
    fontSize: 15,
    lineHeight: 21,
    color: "#374151",
  },
  causeNotesGroup: {
    marginTop: 12,
    gap: 8,
  },
  causeNoteLabel: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#475569",
  },
  causeNoteInput: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: "#0f172a",
    backgroundColor: "#ffffff",
  },
  causeButtons: {
    flexDirection: "row",
    gap: 10,
  },
  causeButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1f2937",
    paddingHorizontal: 12,
  },
  causeButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  assistantCard: {
    marginTop: 14,
    borderRadius: 16,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    padding: 16,
    gap: 12,
  },
  assistantCardEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#1d4ed8",
  },
  assistantCardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  assistantCauseItem: {
    gap: 6,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#dbeafe",
  },
  assistantCauseHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  assistantCauseTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: "#0f172a",
  },
  assistantCauseBadge: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    color: "#1e3a8a",
    backgroundColor: "#dbeafe",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  assistantCauseText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#334155",
  },
  assistantCauseHint: {
    fontSize: 13,
    lineHeight: 18,
    color: "#1d4ed8",
  },
  aiAssistantCard: {
    marginTop: 14,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 16,
    gap: 12,
  },
  aiAssistantHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  aiAssistantHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  aiAssistantEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#0f766e",
  },
  aiAssistantTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  aiAssistantRefreshButton: {
    minHeight: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    paddingHorizontal: 12,
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  aiAssistantRefreshButtonText: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "800",
  },
  aiAssistantNote: {
    fontSize: 13,
    lineHeight: 18,
    color: "#475569",
  },
  aiAssistantContent: {
    gap: 10,
  },
  aiAssistantSection: {
    gap: 6,
  },
  aiAssistantSectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    color: "#0f766e",
  },
  aiAssistantBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "#334155",
  },
  aiAssistantListItem: {
    fontSize: 14,
    lineHeight: 20,
    color: "#0f172a",
  },
  aiAssistantRationale: {
    fontSize: 13,
    lineHeight: 19,
    color: "#475569",
  },
  aiAssistantSafety: {
    fontSize: 13,
    lineHeight: 19,
    color: "#0f766e",
    fontWeight: "700",
  },
  aiAssistantError: {
    fontSize: 13,
    lineHeight: 19,
    color: "#b91c1c",
    fontWeight: "700",
  },
  logEntry: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 14,
    marginTop: 14,
    gap: 6,
  },
  logTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
  },
  logDetails: {
    fontSize: 14,
    lineHeight: 20,
    color: "#4b5563",
  },
  emptyText: {
    fontSize: 15,
    color: "#6b7280",
  },
  summaryCard: {
    marginTop: 14,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    gap: 8,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  summaryText: {
    fontSize: 15,
    lineHeight: 21,
    color: "#374151",
  },
  compactSectionCard: {
    borderRadius: 22,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 18,
    gap: 10,
    shadowColor: "#0f172a",
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  compactSectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#475569",
  },
  urgentMedicationCard: {
    minHeight: 86,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
  },
  urgentMedicationCardDanger: {
    backgroundColor: "#fff1f2",
    borderColor: "#fda4af",
  },
  urgentMedicationCardWarning: {
    backgroundColor: "#fff7ed",
    borderColor: "#fdba74",
  },
  urgentMedicationEyebrow: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: "#9f1239",
  },
  urgentMedicationTitle: {
    marginTop: 2,
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  urgentMedicationDetail: {
    marginTop: 4,
    fontSize: 13,
    color: "#4b5563",
  },
  urgentMedicationAction: {
    fontSize: 14,
    fontWeight: "800",
    color: "#7f1d1d",
    textTransform: "uppercase",
  },
  inlineDocumentationActions: {
    gap: 8,
  },
  inlineDocumentationPassiveList: {
    gap: 8,
  },
  inlineDocumentationPassiveItem: {
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe4ee",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inlineDocumentationPassiveText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#334155",
  },
  inlineDocumentationButton: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe4ee",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  inlineDocumentationButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0f172a",
  },
  inlineDocumentationHint: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
  },
  recordsSectionCard: {
    borderRadius: 20,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 16,
    gap: 10,
  },
  recordsToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  recordsToggleTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0f172a",
  },
  recordsToggleText: {
    fontSize: 12,
    color: "#64748b",
  },
  recordsToggleAction: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    color: AppDesign.accent.primary,
  },
  recordsActionsList: {
    gap: 8,
  },
  recordsActionButton: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  recordsActionButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#334155",
  },
  exportButton: {
    marginTop: 8,
    minHeight: 46,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0f172a",
    paddingHorizontal: 16,
  },
  exportButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  reportButton: {
    minHeight: 46,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    paddingHorizontal: 16,
  },
  reportButtonText: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
  debriefGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
  },
  debriefActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  debriefMetricCard: {
    width: "48%",
    backgroundColor: "#f8fafc",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    gap: 4,
  },
  debriefMetricLabel: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#64748b",
  },
  debriefMetricValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  debriefSection: {
    marginTop: 18,
    gap: 8,
  },
  debriefSectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  debriefListItem: {
    backgroundColor: "#f8fafc",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#dbe4ea",
    padding: 12,
    gap: 4,
  },
  debriefListItemCritical: {
    borderColor: "#fca5a5",
    backgroundColor: "#fff7ed",
  },
  debriefListTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0f172a",
  },
  debriefListText: {
    fontSize: 13,
    lineHeight: 19,
    color: "#475569",
  },
  debriefHint: {
    fontSize: 13,
    lineHeight: 19,
    color: "#334155",
    fontWeight: "700",
  },
  debriefTimelineItem: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    paddingVertical: 4,
  },
  debriefTimelineTime: {
    width: 52,
    fontSize: 12,
    fontWeight: "800",
    color: "#64748b",
  },
  debriefTimelineContent: {
    flex: 1,
    gap: 2,
  },
  replayFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  replayFilterButton: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  replayFilterButtonActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  replayFilterButtonText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#334155",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  replayFilterButtonTextActive: {
    color: "#ffffff",
  },
  debriefBlockTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  endText: {
    textAlign: "center",
    fontSize: 16,
    color: "#4b5563",
  },
  sepsisHubContainer: {
    gap: 14,
  },
  sepsisHubHeader: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  sepsisPatientCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 18,
    gap: 6,
  },
  sepsisHubEyebrow: {
    textTransform: "uppercase",
    fontSize: 11,
    letterSpacing: 0.4,
    fontWeight: "800",
    color: "#0f172a",
  },
  sepsisHubTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#031b4e",
  },
  sepsisHubSubText: {
    fontSize: 13,
    color: "#475569",
  },
  sepsisHubMetric: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
  },
  sepsisHubSummary: {
    fontSize: 12,
    color: "#475569",
  },
  sepsisHubPatientList: {
    marginTop: 10,
    gap: 3,
  },
  sepsisHubPatientText: {
    fontSize: 12,
    color: "#475569",
  },
  sepsisTimerCard: {
    width: 180,
    borderRadius: 20,
    padding: 16,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  sepsisTimerCardAlert: {
    backgroundColor: "#b91c1c",
  },
  sepsisTimerCardDisabled: {
    width: 180,
    borderRadius: 20,
    padding: 16,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  sepsisTimerLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#fef2f2",
    textTransform: "uppercase",
  },
  sepsisTimerValue: {
    fontSize: 32,
    fontWeight: "900",
    color: "#fff",
    marginTop: 4,
  },
  sepsisTimerHint: {
    fontSize: 11,
    color: "#fee2e2",
  },
  sepsisTimerSubtext: {
    fontSize: 11,
    color: "#fee2e2",
  },
  sepsisBundleCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    gap: 12,
  },
  sepsisBundleCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sepsisBundleCardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  sepsisBundleCardSubtext: {
    fontSize: 13,
    color: "#475569",
  },
  bundleRow: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 12,
    gap: 8,
  },
  bundleRowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bundleRowTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0f172a",
  },
  bundleRowValue: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0f172a",
  },
  bundleRowHelper: {
    fontSize: 12,
    color: "#475569",
  },
  bundleRowActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  bundleStatusButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#cbd5f5",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#ffffff",
  },
  bundleStatusButtonPending: {
    borderColor: "#cbd5f5",
  },
  bundleStatusButtonRequested: {
    borderColor: "#60a5fa",
  },
  bundleStatusButtonDone: {
    borderColor: "#34d399",
  },
  bundleStatusButtonActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  bundleStatusButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0f172a",
  },
  bundleStatusButtonTextActive: {
    color: "#ffffff",
  },
  sepsisFocusCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 18,
    gap: 12,
  },
  sepsisFocusTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  sepsisFocusHint: {
    fontSize: 13,
    color: "#475569",
  },
  sepsisFocusItem: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 12,
    gap: 8,
  },
  sepsisFocusItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sepsisFocusItemTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  sepsisFocusActions: {
    gap: 4,
  },
  sepsisFocusActionText: {
    fontSize: 13,
    color: "#475569",
  },
  sepsisFocusButtons: {
    flexDirection: "row",
    gap: 8,
  },
  sepsisFocusButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#93c5fd",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    backgroundColor: "#eff6ff",
  },
  sepsisFocusButtonAlt: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#10b981",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    backgroundColor: "#ecfccb",
  },
  sepsisFocusButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
  },
  statusPending: {
    backgroundColor: "#f3f4f6",
    color: "#0f172a",
  },
  secondarySection: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#ffffff",
    padding: 14,
    elevation: 0,
    shadowColor: "transparent",
    marginTop: 12,
  },
});

export { styles };
