const WEB_AUDIO_CUES: Record<string, number> = {
  reconhecimento_inicial: require("../assets/audio/final-acls/reconhecimento_inicial.mp3"),
  checar_respiracao_pulso: require("../assets/audio/final-acls/checar_respiracao_pulso.mp3"),
  monitorizar_com_pulso: require("../assets/audio/final-acls/monitorizar_com_pulso.mp3"),
  inicio: require("../assets/audio/final-acls/inicio.mp3"),
  preparar_monitorizacao: require("../assets/audio/final-acls/preparar_monitorizacao.mp3"),
  avaliar_ritmo: require("../assets/audio/final-acls/avaliar_ritmo.mp3"),
  tipo_desfibrilador: require("../assets/audio/final-acls/tipo_desfibrilador.mp3"),
  choque_bi_1: require("../assets/audio/final-acls/choque_bi_1.mp3"),
  choque_mono_1: require("../assets/audio/final-acls/choque_mono_1.mp3"),
  rcp_1: require("../assets/audio/final-acls/rcp_1.mp3"),
  avaliar_ritmo_2: require("../assets/audio/final-acls/avaliar_ritmo_2.mp3"),
  choque_2_bifasico: require("../assets/audio/final-acls/choque_2_bifasico.mp3"),
  choque_2_monofasico: require("../assets/audio/final-acls/choque_2_monofasico.mp3"),
  rcp_2: require("../assets/audio/final-acls/rcp_2.mp3"),
  avaliar_ritmo_3: require("../assets/audio/final-acls/avaliar_ritmo_3.mp3"),
  choque_3_bifasico: require("../assets/audio/final-acls/choque_3_bifasico.mp3"),
  choque_3_monofasico: require("../assets/audio/final-acls/choque_3_monofasico.mp3"),
  rcp_3: require("../assets/audio/final-acls/rcp_3.mp3"),
  nao_chocavel_epinefrina: require("../assets/audio/final-acls/nao_chocavel_epinefrina.mp3"),
  nao_chocavel_ciclo: require("../assets/audio/final-acls/nao_chocavel_ciclo.mp3"),
  avaliar_ritmo_nao_chocavel: require("../assets/audio/final-acls/avaliar_ritmo_nao_chocavel.mp3"),
  nao_chocavel_hs_ts: require("../assets/audio/final-acls/nao_chocavel_hs_ts.mp3"),
  pos_rosc: require("../assets/audio/final-acls/pos_rosc.mp3"),
  pos_rosc_via_aerea: require("../assets/audio/final-acls/pos_rosc_via_aerea.mp3"),
  pos_rosc_hemodinamica: require("../assets/audio/final-acls/pos_rosc_hemodinamica.mp3"),
  pos_rosc_ecg: require("../assets/audio/final-acls/pos_rosc_ecg.mp3"),
  pos_rosc_neurologico: require("../assets/audio/final-acls/pos_rosc_neurologico.mp3"),
  pos_rosc_destino: require("../assets/audio/final-acls/pos_rosc_destino.mp3"),
  pos_rosc_concluido: require("../assets/audio/final-acls/pos_rosc_concluido.mp3"),
  encerrado: require("../assets/audio/final-acls/encerrado.mp3"),
  reminder_reavaliar_ritmo: require("../assets/audio/final-acls/reminder_reavaliar_ritmo.mp3"),
  reminder_epinefrina: require("../assets/audio/final-acls/reminder_epinefrina.mp3"),
  reminder_antiarritmico_1: require("../assets/audio/final-acls/reminder_antiarritmico_1.mp3"),
  reminder_antiarritmico_2: require("../assets/audio/final-acls/reminder_antiarritmico_2.mp3"),
};

export { WEB_AUDIO_CUES };
