import type { ClinicalTransitionContract } from "./clinical-transitions";

/**
 * Primeiras arestas reais classificadas a partir das árvores atuais.
 *
 * `module` descreve passagens navegáveis entre protocolos do app.
 * `external_service` descreve handoff definitivo para recurso assistencial que
 * não é um módulo, como centro cirúrgico, angioembolização ou neurocirurgia.
 */
export const CLINICAL_TRANSITION_CONTRACTS: readonly ClinicalTransitionContract[] = [
  {
    id: "ira-abcde-a-isr",
    from: "injuria_renal_aguda",
    to: "isr-rapida",
    trigger: "Via aérea ameaçada ou não protegida na triagem da IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação da injúria renal após proteger a via aérea",
  },
  {
    id: "ira-abcde-b-vm",
    from: "injuria_renal_aguda",
    to: "ventilacao-mecanica",
    trigger: "Hipoxemia ou esforço respiratório importante na triagem da IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após sustentar oxigenação e ventilação",
  },
  {
    id: "ira-abcde-b-eap",
    from: "injuria_renal_aguda",
    to: "edema-agudo-pulmao",
    trigger: "Congestão como causa da insuficiência respiratória na IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após estabilizar a congestão",
  },
  {
    id: "ira-abcde-c-choque",
    from: "injuria_renal_aguda",
    to: "choque",
    trigger: "Hipotensão ou má perfusão na triagem da IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após sustentar perfusão e pressão",
  },
  {
    id: "ira-abcde-c-vasoativos",
    from: "injuria_renal_aguda",
    to: "drogas-vasoativas",
    trigger: "Necessidade de suporte vasoativo na instabilidade associada à IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após iniciar/titular o suporte hemodinâmico",
  },
  {
    id: "ira-abcde-c-bradicardia",
    from: "injuria_renal_aguda",
    to: "bradicardia-acls",
    trigger: "Bradicardia com repercussão na triagem da IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após tratar o ritmo",
  },
  {
    id: "ira-abcde-c-taquicardia",
    from: "injuria_renal_aguda",
    to: "taquicardia-acls",
    trigger: "Taquicardia com repercussão na triagem da IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após tratar o ritmo",
  },
  {
    id: "ira-abcde-d-isr",
    from: "injuria_renal_aguda",
    to: "isr-rapida",
    trigger: "Rebaixamento que ameaça proteção da via aérea",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após garantir a via aérea",
  },
  {
    id: "ira-abcde-d-convulsao",
    from: "injuria_renal_aguda",
    to: "crises-convulsivas",
    trigger: "Convulsão em curso ou recente na triagem da IRA",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à avaliação renal após controlar a crise",
  },
  {
    id: "politrauma-tce",
    from: "politrauma",
    to: "tce",
    trigger: "Alteração neurológica ou trauma cranioencefálico significativo durante avaliação do politrauma",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar ao politrauma após estabilização e definição da conduta neurotraumática",
  },
  {
    id: "eap-ventilacao",
    from: "eap_2024",
    to: "ventilacao-mecanica",
    trigger: "Edema agudo de pulmão com necessidade de ventilação mecânica",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar ao EAP após iniciar e estabilizar o suporte ventilatório",
  },
  {
    id: "eap-vasoativos",
    from: "eap_2024",
    to: "drogas-vasoativas",
    trigger: "Choque cardiogênico ou necessidade de suporte vasoativo no EAP",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar ao EAP após iniciar ou titular o suporte hemodinâmico",
  },
  {
    id: "anafilaxia-ventilacao",
    from: "anaphylaxis_v3",
    to: "ventilacao-mecanica",
    trigger: "Intubação realizada na anafilaxia com necessidade de ajuste ventilatório",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à anafilaxia após estabilizar ventilação e oxigenação",
  },
  {
    id: "anafilaxia-isr",
    from: "anaphylaxis_v3",
    to: "isr-rapida",
    trigger: "Estridor, edema progressivo de via aérea, falha de oxigenação ou decisão de intubação",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à anafilaxia após proteger a via aérea",
  },
  {
    id: "anafilaxia-vasoativos",
    from: "anaphylaxis_v3",
    to: "drogas-vasoativas",
    trigger: "Choque refratário na anafilaxia com necessidade de infusão vasoativa",
    mode: "returnable",
    destinationKind: "module",
    returnLabel: "Voltar à anafilaxia após iniciar ou titular o suporte vasoativo",
  },
  {
    id: "politrauma-damage-control",
    from: "politrauma",
    to: "centro-cirurgico-ou-angioembolizacao",
    trigger: "Sangramento ativo não controlado com ausência de resposta sustentada à reanimação inicial",
    sourceNodeId: "damage_control",
    mode: "terminal",
    destinationKind: "external_service",
    externalLabel: "Centro cirúrgico / angioembolização para controle definitivo da hemorragia",
    preserves: ["horario_txa", "hemocomponentes", "resposta_reanimacao", "suspeita_fonte_hemorragica"],
  },
  {
    id: "tce-neurocirurgia",
    from: "tce",
    to: "neurocirurgia",
    trigger: "Lesão intracraniana com efeito de massa, desvio de linha média ou indicação cirúrgica",
    sourceNodeId: "neurocirurgia",
    mode: "terminal",
    destinationKind: "external_service",
    externalLabel: "Neurocirurgia imediata / centro neurocirúrgico",
    preserves: [
      "glasgow",
      "pupilas",
      "resultado_tc",
      "horario_tc",
      "anticoagulacao",
      "reversao_antitrombotica",
      "pressao_arterial",
      "oxigenacao",
      "pic_ppc",
      "osmoterapia_ultima_dose_horario",
      "ventilacao_paco2",
      "sedacao_bnm",
      "crise_antisseizure",
      "evd_configuracao",
    ],
  },
  {
    id: "taquicardia-sem-pulso-pcr-terminal",
    from: "acls_tachycardia_2025",
    to: "pcr-adulto",
    trigger: "Perda de pulso durante taquiarritmia ou após cardioversão",
    mode: "terminal",
    destinationKind: "module",
    preserves: [
      "ritmo_pre_parada",
      "energia_ultima_cardioversao",
      "numero_cardioversoes",
      "antiarritmico_em_curso",
      "tempo_perda_pulso",
      "suspeita_causa_reversivel",
    ],
  },
  {
    id: "bradicardia-sem-pulso-pcr-terminal",
    from: "acls_bradycardia_2025",
    to: "pcr-adulto",
    trigger: "Perda de pulso durante bradicardia grave ou durante suporte cronotrópico/marcapasso",
    mode: "terminal",
    destinationKind: "module",
    preserves: [
      "ritmo_pre_parada",
      "atropina_administrada",
      "marcapasso_em_uso",
      "captura_marcapasso",
      "cronotropico_em_curso",
      "tempo_perda_pulso",
      "suspeita_causa_reversivel",
    ],
  },
] as const;
