/** ES — Abdome agudo: analgesia executável, o par do volvo, as quatro isquemias e o abdome que despista. */
export const abdomeAgudo2026Es: Record<string, string> = {
  "Há peritonite ao exame — abdome em tábua, defesa involuntária, descompressão dolorosa?":
    "¿Hay peritonitis al examen — abdomen en tabla, defensa involuntaria, descompresión dolorosa?",
  "A PERITONITE É A CONDIÇÃO, NÃO O NOME DO DIAGNÓSTICO. Havendo peritonite, a conduta é cirúrgica em qualquer das quatro entidades. Sem ela, o subtipo decide — e um deles é tratamento CLÍNICO.":
    "LA PERITONITIS ES LA CONDICIÓN, NO EL NOMBRE DEL DIAGNÓSTICO. Habiendo peritonitis, la conducta es quirúrgica en cualquiera de las cuatro entidades. Sin ella, el subtipo decide — y uno de ellos es tratamiento CLÍNICO.",
  "SIM — abdome em tábua, defesa involuntária":
    "SÍ — abdomen en tabla, defensa involuntaria",
  "NÃO — abdome ainda mole, dor desproporcional ao exame":
    "NO — abdomen aún blando, dolor desproporcionado al examen",
  "Peritonite na isquemia mesentérica — sala, e a causa junto":
    "Peritonitis en la isquemia mesentérica — quirófano, y la causa junto",
  "Peritonite decide operar, e decide sozinha. Mas não encerra o NOMI.":
    "La peritonitis decide operar, y decide sola. Pero no cierra la NOMI.",
  "CIRURGIA em qualquer das quatro entidades: com peritonite, o manejo não operatório sai de questão — inclusive na trombose VENOSA, que sem peritonite seria clínica.":
    "CIRUGÍA en cualquiera de las cuatro entidades: con peritonitis, el manejo no operatorio queda fuera de discusión — incluso en la trombosis VENOSA, que sin peritonitis sería clínica.",
  "Qual dos quatro — pelo que se vê":
    "Cuál de las cuatro — por lo que se ve",
  "Como começou, e em quem?":
    "¿Cómo empezó, y en quién?",
  "Os quatro separam-se por SINAL OBSERVÁVEL e pelo lugar onde o paciente está, não por classificação. Na dúvida, a angioTC decide — e ela se pede agora.":
    "Las cuatro se separan por SIGNO OBSERVABLE y por el lugar donde está el paciente, no por clasificación. Ante la duda, la angioTC decide — y se pide ahora.",
  "Abrupto, em quem tem FA, infarto recente ou trombo cardíaco":
    "Abrupto, en quien tiene FA, infarto reciente o trombo cardíaco",
  "Arrastado, com dor após comer e perda de peso nos meses anteriores":
    "Arrastrado, con dolor después de comer y pérdida de peso en los meses anteriores",
  "Mais jovem que o típico, com trombofilia, câncer, cirrose ou pancreatite":
    "Más joven que lo típico, con trombofilia, cáncer, cirrosis o pancreatitis",
  "Está em UTI, em choque, pós-parada ou em vasoconstritor":
    "Está en UCI, en choque, pos-paro o con vasoconstrictor",
  "Não reconheço o padrão":
    "No reconozco el patrón",
  "Embolia da artéria mesentérica superior":
    "Embolia de la arteria mesentérica superior",
  "Metade dos casos de isquemia mesentérica aguda.":
    "La mitad de los casos de isquemia mesentérica aguda.",
  "Trombose arterial mesentérica":
    "Trombosis arterial mesentérica",
  "Sobre placa, e a lesão é OSTIAL — o que muda a técnica.":
    "Sobre placa, y la lesión es OSTIAL — lo que cambia la técnica.",
  "Trombose venosa mesentérica":
    "Trombosis venosa mesentérica",
  "⚠️ SEM peritonite, o tratamento é CLÍNICO — é a maior distância de conduta deste módulo.":
    "⚠️ SIN peritonitis, el tratamiento es CLÍNICO — es la mayor distancia de conducta de este módulo.",
  "Isquemia mesentérica não oclusiva (NOMI)":
    "Isquemia mesentérica no oclusiva (NOMI)",
  "Não há trombo: há vasoconstrição esplâncnica por baixo débito.":
    "No hay trombo: hay vasoconstricción esplácnica por bajo gasto.",
  "Padrão vascular não reconhecido — a imagem decide":
    "Patrón vascular no reconocido — la imagen decide",
  "Não reconhecer o padrão não atrasa nada: a angioTC é quem separa as quatro.":
    "No reconocer el patrón no retrasa nada: la angioTC es la que separa las cuatro.",
  "NÃO RECONHECEU O PADRÃO — E ISSO NÃO ATRASA NADA: peça a ANGIOTOMOGRAFIA de abdome AGORA, que é o exame de escolha e é ela quem separa as quatro entidades. ⚠️ NÃO espere exame de sangue para decidir: não há parâmetro laboratorial suficientemente acurado para confirmar ou afastar alça isquêmica, e normal não tranquiliza. Enquanto a imagem não volta, o que vale para as quatro já pode começar — volume, antibiótico de amplo espectro, heparina quando o diagnóstico firmar e não houver contraindicação, e cirurgia vascular e geral avisadas juntas.":
    "NO RECONOCIÓ EL PATRÓN — Y ESO NO RETRASA NADA: pida la ANGIOTOMOGRAFÍA de abdomen AHORA, que es el examen de elección y es ella la que separa las cuatro entidades. ⚠️ NO espere un examen de sangre para decidir: no hay parámetro de laboratorio suficientemente preciso para confirmar o descartar asa isquémica, y lo normal no tranquiliza. Mientras la imagen no vuelve, lo que vale para las cuatro ya puede empezar — volumen, antibiótico de amplio espectro, heparina cuando el diagnóstico se confirme y no haya contraindicación, y cirugía vascular y general avisadas juntas.",
  "⚠️ O QUE A ANGIOTC RESPONDE, E O QUE ELA NÃO RESPONDE. RESPONDE: qual das quatro entidades é — trombo arterial, trombo venoso ou ausência de trombo —, e ONDE está a lesão, que é o que separa bypass de embolectomia (a trombose arterial é tipicamente OSTIAL). Por isso se pede CEDO, sem aguardar peritonite. NÃO RESPONDE duas coisas, e as duas decidem: (1) a VIABILIDADE da alça, que se resolve com second look programado, não com imagem; (2) se opera AGORA — isso é a peritonite ao exame. ⚠️ E O LABORATÓRIO NÃO RESPONDE NADA: a WSES é categórica — não há parâmetro suficientemente acurado para confirmar OU afastar alça isquêmica ou necrótica, e nenhum biomarcador acurado foi identificado. Lactato, leucócitos e D-dímero apoiam quando alterados e NÃO tranquilizam quando normais, porque ELEVAM-SE TARDE.":
    "⚠️ LO QUE LA ANGIOTC RESPONDE, Y LO QUE NO RESPONDE. RESPONDE: cuál de las cuatro entidades es — trombo arterial, trombo venoso o ausencia de trombo —, y DÓNDE está la lesión, que es lo que separa bypass de embolectomía (la trombosis arterial es típicamente OSTIAL). Por eso se pide TEMPRANO, sin aguardar peritonitis. NO RESPONDE dos cosas, y las dos deciden: (1) la VIABILIDAD del asa, que se resuelve con second look programado, no con imagen; (2) si se opera AHORA — eso es la peritonitis al examen. ⚠️ Y EL LABORATORIO NO RESPONDE NADA: la WSES es categórica — no hay parámetro suficientemente preciso para confirmar O descartar asa isquémica o necrótica, y no se ha identificado ningún biomarcador preciso. Lactato, leucocitos y dímero-D apoyan cuando están alterados y NO tranquilizan cuando son normales, porque SE ELEVAN TARDE.",
  "⚠️ SE O PACIENTE ESTÁ EM VASOCONSTRITOR OU EM BAIXO DÉBITO, A CAUSA SE TRATA JUNTO — a cirurgia não substitui a correção hemodinâmica. A WSES põe as duas coisas na mesma recomendação: o FOCO é corrigir a causa e melhorar a perfusão mesentérica, e a alça infartada se ressecca PRONTAMENTE. Operar e manter o vasoconstritor retira a alça que já infartou e deixa de pé o mecanismo que a infartou — corrigir débito e volemia, e reduzir ou retirar o vasoconstritor esplâncnico sempre que possível, corre em PARALELO à sala, não depois dela.":
    "⚠️ SI EL PACIENTE ESTÁ CON VASOCONSTRICTOR O EN BAJO GASTO, LA CAUSA SE TRATA JUNTO — la cirugía no sustituye la corrección hemodinámica. La WSES pone las dos cosas en la misma recomendación: el FOCO es corregir la causa y mejorar la perfusión mesentérica, y el asa infartada se reseca PRONTAMENTE. Operar y mantener el vasoconstrictor retira el asa que ya se infartó y deja en pie el mecanismo que la infartó — corregir gasto y volemia, y reducir o retirar el vasoconstrictor esplácnico siempre que sea posible, corre en PARALELO al quirófano, no después de él.",

  "ANALGESIA NÃO MASCARA O DIAGNÓSTICO nem atrasa a cirurgia — revisão sistemática mostra que a analgesia precoce reduz muito a dor sem aumentar erro diagnóstico, e que o diagnóstico pode até ficar MAIS FÁCIL, ainda que os sinais físicos fiquem menos intensos. A razão é simples: o paciente com dor forte contrai a parede o tempo todo, e a defesa voluntária esconde a involuntária. Tratando a dor, o abdome relaxa e o que sobra de defesa é o que interessa.":
    "LA ANALGESIA NO ENMASCARA EL DIAGNÓSTICO ni retrasa la cirugía — una revisión sistemática muestra que la analgesia precoz reduce mucho el dolor sin aumentar el error diagnóstico, y que el diagnóstico puede incluso volverse MÁS FÁCIL, aunque los signos físicos queden menos intensos. La razón es simple: el paciente con dolor fuerte contrae la pared todo el tiempo, y la defensa voluntaria esconde la involuntaria. Al tratar el dolor, el abdomen se relaja y lo que queda de defensa es lo que importa.",
  "⚠️ TITULE AO CONFORTO, NÃO À DOSE — opioide na dor abdominal se ajusta pela resposta, com reavaliação a cada poucos minutos, e não por uma dose única calculada de uma vez. E ATENÇÃO À OUTRA METADE: analgesia NÃO substitui o reexame. A reavaliação seriada do abdome, de preferência pelo mesmo examinador, continua sendo a conduta — quem trata a dor e para de examinar apenas trocou um erro por outro.":
    "⚠️ TITULE AL CONFORT, NO A LA DOSIS — el opioide en el dolor abdominal se ajusta por la respuesta, con reevaluación cada pocos minutos, y no por una dosis única calculada de una vez. Y ATENCIÓN A LA OTRA MITAD: la analgesia NO sustituye al reexamen. La reevaluación seriada del abdomen, de preferencia por el mismo examinador, sigue siendo la conducta — quien trata el dolor y deja de examinar solo cambió un error por otro.",
  "MORFINA IV — dose inicial 0,1 mg/kg, seguida de 0,025–0,05 mg/kg a cada 5–15 minutos até o conforto (SAEM/CDEM). Antiemético junto, porque náusea e vômito já fazem parte do quadro e o opioide soma.":
    "MORFINA IV — dosis inicial 0,1 mg/kg, seguida de 0,025–0,05 mg/kg cada 5–15 minutos hasta el confort (SAEM/CDEM). Antiemético junto, porque las náuseas y los vómitos ya forman parte del cuadro y el opioide suma.",
  "FENTANIL IV — 1–1,5 mcg/kg, início em 1–2 minutos e meia-vida curta (SAEM/CDEM). ⚠️ E ISTO IMPORTA AQUI MAIS DO QUE EM OUTROS LUGARES: a conduta central do abdome agudo é o REEXAME SERIADO, e a meia-vida curta é justamente o que permite reexaminar sem ter de esperar a droga passar. Onde o abdome vai ser reavaliado de hora em hora — que é sempre —, essa propriedade deixa de ser detalhe farmacológico e vira critério de escolha.":
    "FENTANILO IV — 1–1,5 mcg/kg, inicio en 1–2 minutos y vida media corta (SAEM/CDEM). ⚠️ Y ESTO IMPORTA AQUÍ MÁS QUE EN OTROS LUGARES: la conducta central del abdomen agudo es el REEXAMEN SERIADO, y la vida media corta es justamente lo que permite reexaminar sin tener que esperar a que la droga pase. Donde el abdomen va a ser reevaluado cada hora — que es siempre —, esa propiedad deja de ser un detalle farmacológico y se vuelve criterio de elección.",
  "⚠️ AINE: PENSE DUAS VEZES — e olhe o seu paciente, porque a bula do cetorolaco contraindica exatamente os três estados mais comuns deste módulo. (1) PERFURAÇÃO POSSÍVEL: contraindicado em úlcera péptica ativa e em sangramento ou PERFURAÇÃO gastrointestinal recente — e perfuração é justamente uma das hipóteses que você ainda não excluiu. (2) HIPOVOLÊMICO POR JEJUM, VÔMITO E TERCEIRO ESPAÇO: contraindicado em quem está sob risco de insuficiência renal por depleção de volume — o rim depende de prostaglandina exatamente quando o paciente está seco. (3) LAPAROTOMIA PROVÁVEL: contraindicado como analgésico profilático ANTES de qualquer cirurgia de grande porte e no intraoperatório em que a hemostasia é crítica, porque ele inibe a função plaquetária. NÃO é proibição absoluta do AINE no abdome agudo — a cólica renal já confirmada, em paciente hidratado e sem cirurgia à vista, continua sendo indicação clássica. É que, no abdome agudo indiferenciado, os três estados acima o tiram da mesa quase sempre.":
    "⚠️ AINE: PIÉNSELO DOS VECES — y mire a su paciente, porque el prospecto del ketorolaco contraindica exactamente los tres estados más comunes de este módulo. (1) PERFORACIÓN POSIBLE: contraindicado en úlcera péptica activa y en sangrado o PERFORACIÓN gastrointestinal reciente — y la perforación es justamente una de las hipótesis que usted aún no descartó. (2) HIPOVOLÉMICO POR AYUNO, VÓMITOS Y TERCER ESPACIO: contraindicado en quien está en riesgo de insuficiencia renal por depleción de volumen — el riñón depende de la prostaglandina exactamente cuando el paciente está seco. (3) LAPAROTOMÍA PROBABLE: contraindicado como analgésico profiláctico ANTES de cualquier cirugía mayor y en el intraoperatorio en que la hemostasia es crítica, porque inhibe la función plaquetaria. NO es prohibición absoluta del AINE en el abdomen agudo — el cólico renal ya confirmado, en paciente hidratado y sin cirugía a la vista, sigue siendo indicación clásica. Es que, en el abdomen agudo indiferenciado, los tres estados anteriores lo sacan de la mesa casi siempre.",
  "⚠️ IDOSO, DIABÉTICO, IMUNOSSUPRIMIDO, EM CORTICOIDE OU GESTANTE: O EXAME ENGANA — pode não haver defesa, febre nem leucocitose com víscera já perfurada. O corticoide apaga a resposta inflamatória, a neuropatia diabética apaga a dor, o idoso não monta febre e a gestante tem leucocitose fisiológica que tira o valor do exame. Nesses pacientes, baixe o limiar para imagem e para acionar a cirurgia — e desconfie do seu próprio exame normal, sobretudo quando ele for tranquilizador.":
    "⚠️ ANCIANO, DIABÉTICO, INMUNOSUPRIMIDO, EN CORTICOIDE O EMBARAZADA: EL EXAMEN ENGAÑA — puede no haber defensa, fiebre ni leucocitosis con víscera ya perforada. El corticoide apaga la respuesta inflamatoria, la neuropatía diabética apaga el dolor, el anciano no monta fiebre y la embarazada tiene leucocitosis fisiológica que le quita valor al examen. En esos pacientes, baje el umbral para la imagen y para llamar a cirugía — y desconfíe de su propio examen normal, sobre todo cuando sea tranquilizador.",
  "⚠️ VOLVO: SIGMOIDE E CECAL TÊM A MESMA PALAVRA E O PRIMEIRO PASSO OPOSTO. SIGMOIDE — sem instabilidade, peritonite ou perfuração, a endoscopia baixa é a primeira linha: avalia a viabilidade, destorce e descomprime, e funciona em mais de 90%. CECAL — a redução endoscópica NÃO é recomendada (ASCRS): funciona em 10–15%, tem risco maior de perfuração, e o tempo gasto tentando é o tempo que o intestino não tem. O tratamento do volvo cecal é CIRÚRGICO, e a operação preferida é a RESSECÇÃO SEGMENTAR. ⚠️ ERRAR PARA UM LADO: levar o cecal para a colonoscopia atrasa a cirurgia num paciente que já está com alça sob tensão. ⚠️ ERRAR PARA O OUTRO: operar de imediato o sigmoide sem instabilidade nem peritonite troca um procedimento endoscópico eficaz por uma laparotomia de urgência.":
    "⚠️ VÓLVULO: SIGMOIDE Y CECAL TIENEN LA MISMA PALABRA Y EL PRIMER PASO OPUESTO. SIGMOIDE — sin inestabilidad, peritonitis ni perforación, la endoscopia baja es la primera línea: evalúa la viabilidad, destuerce y descomprime, y funciona en más del 90%. CECAL — la reducción endoscópica NO está recomendada (ASCRS): funciona en 10–15%, tiene mayor riesgo de perforación, y el tiempo gastado intentándolo es el tiempo que el intestino no tiene. El tratamiento del vólvulo cecal es QUIRÚRGICO, y la operación preferida es la RESECCIÓN SEGMENTARIA. ⚠️ ERRAR HACIA UN LADO: llevar el cecal a la colonoscopia retrasa la cirugía en un paciente que ya tiene el asa bajo tensión. ⚠️ ERRAR HACIA EL OTRO: operar de inmediato el sigmoide sin inestabilidad ni peritonitis cambia un procedimiento endoscópico eficaz por una laparotomía de urgencia.",
  "DEPOIS DE DESCOMPRIMIR O SIGMOIDE, A CIRURGIA CONTINUA NA MESA: a descompressão resolve o episódio e não resolve a recidiva. A ASCRS registra que operações SEM ressecção — destorção isolada, sigmoidopexia, mesossigmoidoplastia — são inferiores à colectomia sigmoide para prevenir novo volvo, e que a ressecção urgente é indicada quando a descompressão FALHA ou quando o cólon está inviável ou perfurado. Ou seja: o que se programa não é \"uma cirurgia\", é a ressecção.":
    "DESPUÉS DE DESCOMPRIMIR EL SIGMOIDE, LA CIRUGÍA SIGUE SOBRE LA MESA: la descompresión resuelve el episodio y no resuelve la recidiva. La ASCRS registra que las operaciones SIN resección — destorsión aislada, sigmoidopexia, mesosigmoidoplastia — son inferiores a la colectomía sigmoide para prevenir un nuevo vólvulo, y que la resección urgente está indicada cuando la descompresión FALLA o cuando el colon está inviable o perforado. Es decir: lo que se programa no es \"una cirugía\", es la resección.",
  "⚠️ A DOR DESPROPORCIONAL AO EXAME É O SINAL — e o motivo dela é ANATÔMICO: a isquemia começa na MUCOSA e caminha para a SEROSA. A dor visceral é intensa desde cedo, e a defesa peritoneal só aparece quando a serosa é atingida, o que é tarde. É por isso que o abdome está mole enquanto o paciente grita de dor — e é por isso que esperar a barriga endurecer para acreditar no diagnóstico significa esperar o infarto intestinal. A WSES é explícita: dor abdominal intensa desproporcional ao exame deve ser ASSUMIDA como isquemia mesentérica até prova em contrário.":
    "⚠️ EL DOLOR DESPROPORCIONADO AL EXAMEN ES LA SEÑAL — y su motivo es ANATÓMICO: la isquemia empieza en la MUCOSA y avanza hacia la SEROSA. El dolor visceral es intenso desde temprano, y la defensa peritoneal solo aparece cuando la serosa se compromete, lo que es tarde. Por eso el abdomen está blando mientras el paciente grita de dolor — y por eso esperar a que el vientre se endurezca para creer en el diagnóstico significa esperar el infarto intestinal. La WSES es explícita: el dolor abdominal intenso desproporcionado al examen debe ASUMIRSE como isquemia mesentérica hasta que se demuestre lo contrario.",
  "⚠️ E O QUADRO CLÁSSICO ESTÁ FICANDO MENOS COMUM. A WSES 2022 registra que a apresentação de livro — dor intensa, mal localizada, desproporcional ao exame — vem se tornando menos frequente, enquanto os quadros \"agudo sobre crônico\" são hoje mais típicos e provavelmente SUBDIAGNOSTICADOS. Pergunte por angina intestinal: dor que vem depois de comer, medo de comer e perda de peso nos meses anteriores. Quem espera o quadro clássico para suspeitar perde justamente o paciente mais comum.":
    "⚠️ Y EL CUADRO CLÁSICO SE ESTÁ VOLVIENDO MENOS COMÚN. La WSES 2022 registra que la presentación de libro — dolor intenso, mal localizado, desproporcionado al examen — se está volviendo menos frecuente, mientras que los cuadros \"agudo sobre crónico\" son hoy más típicos y probablemente SUBDIAGNOSTICADOS. Pregunte por angina intestinal: dolor que aparece después de comer, miedo a comer y pérdida de peso en los meses previos. Quien espera el cuadro clásico para sospechar pierde justamente al paciente más común.",
  "⚠️ NENHUM EXAME LABORATORIAL EXCLUI. A WSES é categórica: não há parâmetro de laboratório suficientemente acurado para confirmar OU AFASTAR alça isquêmica ou necrótica, e nenhum biomarcador acurado foi identificado. Lactato, leucócitos e D-dímero apoiam quando alterados e não servem para tranquilizar quando normais — elevam-se tarde. Quem decide é a ANGIOTOMOGRAFIA, e ela deve ser pedida cedo, sem esperar peritonite.":
    "⚠️ NINGÚN EXAMEN DE LABORATORIO LO DESCARTA. La WSES es categórica: no hay parámetro de laboratorio suficientemente preciso para confirmar O DESCARTAR asa isquémica o necrótica, y no se ha identificado ningún biomarcador preciso. Lactato, leucocitos y dímero D apoyan cuando están alterados y no sirven para tranquilizar cuando son normales — se elevan tarde. Quien decide es la ANGIOTOMOGRAFÍA, y debe pedirse temprano, sin esperar la peritonitis.",
  "EMBOLIA DA ARTÉRIA MESENTÉRICA SUPERIOR — METADE dos casos de isquemia mesentérica aguda. Início ABRUPTO, no paciente com fonte embólica: fibrilação atrial, infarto recente, trombo intracavitário, valvopatia, embolia prévia. Conduta: revascularização — embolectomia (aberta ou endovascular) — e ressecção apenas do que já estiver inviável.":
    "EMBOLIA DE LA ARTERIA MESENTÉRICA SUPERIOR — LA MITAD de los casos de isquemia mesentérica aguda. Inicio ABRUPTO, en el paciente con fuente embólica: fibrilación auricular, infarto reciente, trombo intracavitario, valvulopatía, embolia previa. Conducta: revascularización — embolectomía (abierta o endovascular) — y resección solo de lo que ya esté inviable.",
  "TROMBOSE ARTERIAL MESENTÉRICA — sobre placa aterosclerótica, tipicamente na ORIGEM da mesentérica superior, em paciente que costuma ter história de angina intestinal (dor pós-prandial e perda de peso). Instalação menos abrupta que a embolia. Conduta: revascularização, e aqui a lesão é ostial — habitualmente exige BYPASS ou stent, não embolectomia simples.":
    "TROMBOSIS ARTERIAL MESENTÉRICA — sobre placa aterosclerótica, típicamente en el ORIGEN de la mesentérica superior, en un paciente que suele tener historia de angina intestinal (dolor posprandial y pérdida de peso). Instalación menos abrupta que la embolia. Conducta: revascularización, y aquí la lesión es ostial — habitualmente exige BYPASS o stent, no una embolectomía simple.",
  "TROMBOSE VENOSA MESENTÉRICA — ⚠️ SE NÃO HÁ PERITONITE, O TRATAMENTO É CLÍNICO: anticoagulação plena é a primeira linha, e a WSES registra que a trombose venosa mesentérica \"frequentemente pode ser tratada com sucesso com infusão contínua de heparina não fracionada\" (recomendação forte, evidência moderada). Suspeitar em quem é mais jovem que o típico e tem trombofilia, câncer, cirrose, pancreatite, doença inflamatória intestinal ou trombose venosa prévia. ⚠️ A CONDIÇÃO É A PERITONITE, NÃO O NOME DO DIAGNÓSTICO: havendo peritonite, a conduta volta a ser cirúrgica. ⚠️ E QUEM DECIDE É O EXAME, NÃO O LAUDO — a tentação é a oposta, porque o laudo da angiotomografia chega escrito e parece decidir sozinho. Esta é a maior distância entre duas condutas deste módulo: tratamento clínico contra laparotomia, separados pelo abdome que você apalpa.":
    "TROMBOSIS VENOSA MESENTÉRICA — ⚠️ SI NO HAY PERITONITIS, EL TRATAMIENTO ES CLÍNICO: la anticoagulación plena es la primera línea, y la WSES registra que la trombosis venosa mesentérica \"con frecuencia puede tratarse con éxito con infusión continua de heparina no fraccionada\" (recomendación fuerte, evidencia moderada). Sospechar en quien es más joven que lo típico y tiene trombofilia, cáncer, cirrosis, pancreatitis, enfermedad inflamatoria intestinal o trombosis venosa previa. ⚠️ LA CONDICIÓN ES LA PERITONITIS, NO EL NOMBRE DEL DIAGNÓSTICO: si hay peritonitis, la conducta vuelve a ser quirúrgica. ⚠️ Y QUIEN DECIDE ES EL EXAMEN, NO EL INFORME — la tentación es la opuesta, porque el informe de la angiotomografía llega escrito y parece decidir solo. Esta es la mayor distancia entre dos conductas de este módulo: tratamiento clínico contra laparotomía, separados por el abdomen que usted palpa.",
  "ISQUEMIA MESENTÉRICA NÃO OCLUSIVA (NOMI) — não há trombo: há VASOCONSTRIÇÃO esplâncnica por baixo débito. O paciente típico é o grave de UTI — choque, pós-parada, insuficiência cardíaca, diálise, uso de vasoconstritor ou de digital. ⚠️ A CONDUTA É TRATAR A CAUSA: corrigir o débito cardíaco e a volemia, e RETIRAR ou reduzir o vasoconstritor esplâncnico sempre que possível — a WSES coloca a correção da causa precipitante como o princípio central. Alça já infartada se ressecca; o resto não se resolve operando, e sim melhorando a perfusão.":
    "ISQUEMIA MESENTÉRICA NO OCLUSIVA (NOMI) — no hay trombo: hay VASOCONSTRICCIÓN esplácnica por bajo gasto. El paciente típico es el grave de UCI — choque, pos-paro, insuficiencia cardíaca, diálisis, uso de vasoconstrictor o de digital. ⚠️ LA CONDUCTA ES TRATAR LA CAUSA: corregir el gasto cardíaco y la volemia, y RETIRAR o reducir el vasoconstrictor esplácnico siempre que sea posible — la WSES coloca la corrección de la causa precipitante como el principio central. El asa ya infartada se reseca; el resto no se resuelve operando, sino mejorando la perfusión.",
  "PARA AS QUATRO: ressuscitação volêmica, antibiótico de amplo espectro (translocação bacteriana), anticoagulação plena com heparina assim que o diagnóstico for firmado e não houver contraindicação, e discussão CONJUNTA com cirurgia vascular e geral. Alça inviável se ressecca em qualquer uma delas, e a dúvida de viabilidade se resolve com second look programado em 24–48 h — não com observação.":
    "PARA LAS CUATRO: reanimación con volumen, antibiótico de amplio espectro (traslocación bacteriana), anticoagulación plena con heparina apenas se confirme el diagnóstico y no haya contraindicación, y discusión CONJUNTA con cirugía vascular y general. El asa inviable se reseca en cualquiera de ellas, y la duda de viabilidad se resuelve con second look programado en 24–48 h — no con observación.",
  "⚠️ E A INVERSÃO, QUE MATA: ANEURISMA DE AORTA ROTO SE APRESENTA COMO CÓLICA RENAL. Dor lombar ou em flanco de início súbito, irradiando para a virilha, com hematúria — o quadro é o mesmo, e o rótulo \"cólica renal\" é confortável porque é comum. Em quem tem mais de 60 anos, hipertenso, tabagista ou vasculopata, e sobretudo na PRIMEIRA crise de \"cólica renal\" da vida, apalpe o abdome procurando massa pulsátil e faça o ultrassom de aorta à beira do leito antes de aceitar o diagnóstico benigno.":
    "⚠️ Y LA INVERSIÓN, QUE MATA: EL ANEURISMA DE AORTA ROTO SE PRESENTA COMO CÓLICO RENAL. Dolor lumbar o en flanco de inicio súbito, irradiado a la ingle, con hematuria — el cuadro es el mismo, y la etiqueta \"cólico renal\" es cómoda porque es común. En quien tiene más de 60 años, hipertenso, fumador o vasculópata, y sobre todo en la PRIMERA crisis de \"cólico renal\" de la vida, palpe el abdomen buscando masa pulsátil y haga la ecografía de aorta a la cabecera antes de aceptar el diagnóstico benigno.",
};
