/**
 * Alarmes do ventilador (V5) — PT → ES.
 */
export const ES_ALARMES_VENT: Record<string, string> = {
  "CONFIGURAR OS ALARMES antes de sair do leito — ventilador sem alarme ajustado é monitorização que não avisa. Os limites são MARGEM EM TORNO DO QUE ESTE PACIENTE ESTÁ FAZENDO AGORA, não valores fixos de tabela: limite fixo dispara o tempo todo em quem tem pico alto (e acaba silenciado) e nunca dispara em quem tem pico baixo (e a desconexão passa).":
    "CONFIGURAR LAS ALARMAS antes de salir de la cama — un ventilador sin alarmas ajustadas es monitorización que no avisa. Los límites son MARGEN EN TORNO A LO QUE ESTE PACIENTE ESTÁ HACIENDO AHORA, no valores fijos de tabla: un límite fijo se dispara todo el tiempo en quien tiene pico alto (y acaba silenciado) y nunca se dispara en quien tiene pico bajo (y la desconexión pasa).",
  "PRESSÃO DE PICO — alta: 10–20 cmH₂O ACIMA do pico atual do paciente. Dispara em obstrução, mordedura do tubo, secreção, broncoespasmo, queda de complacência ou pneumotórax — é o alarme que pede avaliação IMEDIATA à beira do leito. PRESSÃO baixa: 5–10 cmH₂O ABAIXO do pico atual — dispara em desconexão, vazamento no circuito ou cuff insuflado de menos.":
    "PRESIÓN PICO — alta: 10–20 cmH₂O POR ENCIMA del pico actual del paciente. Se dispara en obstrucción, mordedura del tubo, secreción, broncoespasmo, caída de la distensibilidad o neumotórax — es la alarma que exige evaluación INMEDIATA junto a la cama. PRESIÓN baja: 5–10 cmH₂O POR DEBAJO del pico actual — se dispara en desconexión, fuga en el circuito o cuff poco insuflado.",
  "VOLUME CORRENTE EXALADO — mínimo: cerca de 100 mL abaixo do VC exalado medido. É o que detecta vazamento e desconexão parcial, que a pressão sozinha pode não pegar. VOLUME MINUTO: cerca de 4–6 L/min abaixo e 6–8 L/min acima do medido. FREQUÊNCIA respiratória alta: 15–20 acima da frequência medida — dispara em taquipneia por dor, agitação, acidose ou piora da mecânica.":
    "VOLUMEN CORRIENTE EXHALADO — mínimo: alrededor de 100 mL por debajo del VC exhalado medido. Es lo que detecta fuga y desconexión parcial, que la presión sola puede no captar. VOLUMEN MINUTO: alrededor de 4–6 L/min por debajo y 6–8 L/min por encima del medido. FRECUENCIA respiratoria alta: 15–20 por encima de la frecuencia medida — se dispara en taquipnea por dolor, agitación, acidosis o empeoramiento de la mecánica.",
  "APNEIA: 20 segundos — este é o único limite que NÃO é relativo ao paciente, e por isso é o que se esquece de conferir. Em modo espontâneo ou durante o desmame, é a rede que detecta a parada do drive antes da dessaturação. Alterar só por indicação declarada.":
    "APNEA: 20 segundos — este es el único límite que NO es relativo al paciente, y por eso es el que se olvida verificar. En modo espontáneo o durante el destete, es la red que detecta la parada del drive antes de la desaturación. Modificar solo por indicación declarada.",
  "⚠️ QUANDO O ALARME DISPARA: primeiro OLHE O PACIENTE, não o ventilador. Se houver instabilidade, DESCONECTAR e ventilar com bolsa-válvula-máscara em O₂ 100% resolve e diagnostica ao mesmo tempo — melhora imediata aponta para o circuito/ventilador, ausência de melhora aponta para o paciente (DOPES: Deslocamento do tubo, Obstrução, Pneumotórax, Equipamento, empilhamento de ar/auto-PEEP). NUNCA silenciar alarme repetitivo sem ter identificado a causa: alarme silenciado por incômodo é o defeito que precede o evento.":
    "⚠️ CUANDO LA ALARMA SE DISPARA: primero MIRE AL PACIENTE, no al ventilador. Si hay inestabilidad, DESCONECTAR y ventilar con bolsa-válvula-mascarilla con O₂ al 100% resuelve y diagnostica al mismo tiempo — la mejoría inmediata apunta al circuito/ventilador, la ausencia de mejoría apunta al paciente (DOPES: Desplazamiento del tubo, Obstrucción, Neumotórax, Equipo, atrapamiento aéreo/auto-PEEP). NUNCA silenciar una alarma repetitiva sin haber identificado la causa: alarma silenciada por molestia es el defecto que precede al evento.",
};
