/**
 * Alergia a beta-lactâmico na sepse (S3) — PT → ES.
 */
export const ES_ALERGIA_BL: Record<string, string> = {
  "⚠️ ANTES DE TROCAR, ESTRATIFIQUE — a maioria dos rótulos de \"alergia a penicilina\" não corresponde a alergia mediada por IgE. REAÇÃO NÃO GRAVE (exantema tardio isolado, intolerância gastrointestinal, história vaga ou de infância): o beta-lactâmico pode ser mantido, e trocar por reflexo é decisão com custo — as alternativas são menos eficazes, têm mais efeitos adversos e ampliam o espectro sem necessidade, selecionando MDR. REAÇÃO GRAVE/IMEDIATA (anafilaxia, angioedema, broncoespasmo, hipotensão, urticária em minutos a 1 h, SSJ/NET, DRESS): aí sim, evitar todo beta-lactâmico.":
    "⚠️ ANTES DE CAMBIAR, ESTRATIFIQUE — la mayoría de las etiquetas de \"alergia a penicilina\" no corresponde a alergia mediada por IgE. REACCIÓN NO GRAVE (exantema tardío aislado, intolerancia gastrointestinal, historia vaga o de la infancia): el betalactámico puede mantenerse, y cambiarlo por reflejo es una decisión con costo — las alternativas son menos eficaces, tienen más efectos adversos y amplían el espectro sin necesidad, seleccionando MDR. REACCIÓN GRAVE/INMEDIATA (anafilaxia, angioedema, broncoespasmo, hipotensión, urticaria en minutos a 1 h, SSJ/NET, DRESS): entonces sí, evitar todo betalactámico.",
  "ALERGIA GRAVE/IMEDIATA CONFIRMADA — substituir por: AZTREONAM 2 g IV 8/8h para cobertura Gram-negativa (incluindo Pseudomonas) + VANCOMICINA em dose de ataque para Gram-positivos. Acrescentar METRONIDAZOL 500 mg IV 8/8h se o foco for abdominal (o aztreonam não cobre anaeróbios). Foco pulmonar: LEVOFLOXACINO 750 mg IV/24h cobre atípicos e Gram-negativos, e substitui o par nesse cenário.":
    "ALERGIA GRAVE/INMEDIATA CONFIRMADA — sustituir por: AZTREONAM 2 g IV 8/8h para cobertura Gram-negativa (incluida Pseudomonas) + VANCOMICINA en dosis de carga para Gram-positivos. Agregar METRONIDAZOL 500 mg IV 8/8h si el foco es abdominal (el aztreonam no cubre anaerobios). Foco pulmonar: LEVOFLOXACINO 750 mg IV/24h cubre atípicos y Gram-negativos, y sustituye al par en ese escenario.",
  "⚠️ ÚNICA EXCEÇÃO DO AZTREONAM — CEFTAZIDIMA: o aztreonam NÃO tem reatividade cruzada com penicilinas nem com as demais cefalosporinas, mas compartilha cadeia lateral R1 IDÊNTICA com a ceftazidima. Em alergia CONFIRMADA à ceftazidima, o aztreonam pode reproduzir a reação — nesse caso, cobertura Gram-negativa por outra classe (fluoroquinolona ou aminoglicosídeo, conforme o foco e a função renal).":
    "⚠️ ÚNICA EXCEPCIÓN DEL AZTREONAM — CEFTAZIDIMA: el aztreonam NO tiene reactividad cruzada con penicilinas ni con las demás cefalosporinas, pero comparte una cadena lateral R1 IDÉNTICA con la ceftazidima. En alergia CONFIRMADA a la ceftazidima, el aztreonam puede reproducir la reacción — en ese caso, cobertura Gram-negativa por otra clase (fluoroquinolona o aminoglucósido, según el foco y la función renal).",
  "Alergia grave documentada não automatiza a escolha final: acionar infectologia/farmácia clínica e o protocolo institucional em paralelo ao início do antibiótico — o que NÃO se faz é atrasar a primeira dose esperando o parecer.":
    "La alergia grave documentada no automatiza la elección final: activar infectología/farmacia clínica y el protocolo institucional en paralelo al inicio del antibiótico — lo que NO se hace es retrasar la primera dosis esperando la interconsulta.",
};
