/** ES — AVC: trombólise guiada por imagem, contraindicações relativas e os dois regimes de TNK. */
export const avcImagemEs: Record<string, string> = {
  "Déficit leve e NÃO incapacitante; melhora rápida e sustentada; crise convulsiva no início (se o déficit for atribuível ao pós-ictal); cirurgia de grande porte ou trauma grave < 14 dias; sangramento geniturinário ou digestivo < 21 dias; IAM < 3 meses; punção arterial em sítio não compressível < 7 dias; gestação; PA que responde ao anti-hipertensivo.":
    "Déficit leve y NO incapacitante; mejoría rápida y sostenida; crisis convulsiva al inicio (si el déficit es atribuible al posictal); cirugía mayor o trauma grave < 14 días; sangrado genitourinario o digestivo < 21 días; IAM < 3 meses; punción arterial en sitio no compresible < 7 días; embarazo; PA que responde al antihipertensivo.",
  "Fora das 4,5 h, quem decide é a IMAGEM — e o critério muda conforme o exame disponível.":
    "Fuera de las 4,5 h, quien decide es la IMAGEN — y el criterio cambia según el examen disponible.",
  "Há mismatch em neuroimagem avançada?":
    "¿Hay mismatch en neuroimagen avanzada?",
  "Janela estendida — trombólise guiada por imagem":
    "Ventana extendida — trombólisis guiada por imagen",
  "Não há mismatch, ou não há o exame":
    "No hay mismatch, o no está el examen",
  "Sim — há mismatch e não é candidato a trombectomia":
    "Sí — hay mismatch y no es candidato a trombectomía",
  "⚠️ COM RELATIVA E SEM ABSOLUTA, a decisão é de risco-benefício e depende do TAMANHO DO DÉFICIT: quanto mais incapacitante, mais a balança pende para trombolisar. Déficit leve e não incapacitante é a única relativa que costuma decidir sozinha CONTRA — nele o benefício não se demonstrou, e a conduta é dupla antiagregação. Não adie a decisão para consultar: registre o raciocínio e siga.":
    "⚠️ CON RELATIVA Y SIN ABSOLUTA, la decisión es de riesgo-beneficio y depende del TAMAÑO DEL DÉFICIT: cuanto más incapacitante, más se inclina la balanza a trombolizar. El déficit leve y no incapacitante es la única relativa que suele decidir sola EN CONTRA — en él el beneficio no se demostró, y la conducta es doble antiagregación. No demore la decisión para consultar: registre el razonamiento y siga.",
  "INÍCIO DESCONHECIDO OU AO ACORDAR — critério DWI-FLAIR (WAKE-UP): lesão VISÍVEL na difusão (DWI) e AINDA NÃO VISÍVEL no FLAIR. O mismatch indica lesão recente, provavelmente dentro das 4,5 h, mesmo sem saber a hora. ⚠️ EXIGE RESSONÂNCIA — o ensaio não validou alternativa por TC para este critério. Elegível: trombólise em dose PADRÃO (alteplase 0,9 mg/kg, MÁXIMO 90 mg — 10% em bolus + 90% em 60 min).":
    "INICIO DESCONOCIDO O AL DESPERTAR — criterio DWI-FLAIR (WAKE-UP): lesión VISIBLE en difusión (DWI) y AÚN NO VISIBLE en FLAIR. El mismatch indica lesión reciente, probablemente dentro de las 4,5 h, aun sin saber la hora. ⚠️ EXIGE RESONANCIA — el ensayo no validó alternativa por TC para este criterio. Elegible: trombólisis en dosis ESTÁNDAR (alteplasa 0,9 mg/kg, MÁXIMO 90 mg — 10% en bolo + 90% en 60 min).",
  "SEM RM E SEM TC DE PERFUSÃO — e este é o cenário de boa parte dos serviços: a janela estendida NÃO se abre. Os dois critérios dependem de neuroimagem avançada, e não há substituto validado por TC simples ou por clínica. O que resta: (1) fora de 4,5 h, NÃO trombolisar às cegas — o risco hemorrágico não some porque o exame falta; (2) avaliar OCLUSÃO DE GRANDE VASO com angioTC, que a maioria dos serviços tem, porque a trombectomia tem janela até 24 h e é a terapia que continua na mesa; (3) TRANSFERIR para centro com neuroimagem avançada, se o tempo permitir, é decisão de rede — e é a razão de o transporte precisar começar antes de a conta fechar.":
    "SIN RM Y SIN TC DE PERFUSIÓN — y este es el escenario de buena parte de los servicios: la ventana extendida NO se abre. Los dos criterios dependen de neuroimagen avanzada, y no hay sustituto validado por TC simple ni por clínica. Lo que queda: (1) fuera de 4,5 h, NO trombolizar a ciegas — el riesgo hemorrágico no desaparece porque falte el examen; (2) evaluar OCLUSIÓN DE GRAN VASO con angioTC, que la mayoría de los servicios tiene, porque la trombectomía tiene ventana hasta 24 h y es la terapia que sigue sobre la mesa; (3) TRANSFERIR a un centro con neuroimagen avanzada, si el tiempo lo permite, es decisión de red — y es la razón de que el transporte deba empezar antes de que la cuenta cierre.",
  "⚠️ A JANELA DE TROMBÓLISE GUIADA POR IMAGEM TERMINA EM 9 h (do último-visto-bem, ou do ponto médio do sono). Depois disso, mismatch não abre trombólise: de 9 a 24 h o que resta é TROMBECTOMIA por critério de imagem (DAWN/DEFUSE-3). Este é o ponto em que as duas terapias deixam de correr juntas.":
    "⚠️ LA VENTANA DE TROMBÓLISIS GUIADA POR IMAGEN TERMINA A LAS 9 h (del último-visto-bien, o del punto medio del sueño). Después de eso, el mismatch no abre trombólisis: de 9 a 24 h lo que queda es TROMBECTOMÍA por criterio de imagen (DAWN/DEFUSE-3). Este es el punto en que las dos terapias dejan de correr juntas.",
  "⚠️ ANTES DE TUDO: se há OCLUSÃO DE GRANDE VASO e o paciente é candidato a TROMBECTOMIA, este não é o caminho — vá para a trombectomia. Nos dois ensaios que sustentam a janela estendida (WAKE-UP e EXTEND), ser candidato a trombectomia era critério de EXCLUSÃO. A trombólise guiada por imagem existe para quem NÃO vai para a sala de hemodinâmica — e é a maioria: no WAKE-UP, só 33,7% dos pacientes tinham qualquer oclusão.":
    "⚠️ ANTES DE TODO: si hay OCLUSIÓN DE GRAN VASO y el paciente es candidato a TROMBECTOMÍA, este no es el camino — vaya a la trombectomía. En los dos ensayos que sustentan la ventana extendida (WAKE-UP y EXTEND), ser candidato a trombectomía era criterio de EXCLUSIÓN. La trombólisis guiada por imagen existe para quien NO va a la sala de hemodinamia — y es la mayoría: en el WAKE-UP solo el 33,7% de los pacientes tenía alguna oclusión.",
  "TNK NO AVC ISQUÊMICO — 0,25 mg/kg, TETO DE 25 mg, em bolus único. Este é o regime do AVC, e o teto é METADE do teto do infarto. ⚠️ Trocar os dois erra nas duas direções: a dose do AVC no IAM subdosa a reperfusão; a dose do IAM no AVC sobredosa o cérebro, e o desfecho é hemorragia intracraniana. Confira em qual módulo você está antes de aspirar.":
    "TNK EN EL ACV ISQUÉMICO — 0,25 mg/kg, TECHO DE 25 mg, en bolo único. Este es el régimen del ACV, y el techo es LA MITAD del techo del infarto. ⚠️ Cambiarlos yerra en las dos direcciones: la dosis del ACV en el IAM subdosifica la reperfusión; la dosis del IAM en el ACV sobredosifica el cerebro, y el desenlace es hemorragia intracraneal. Verifique en qué módulo está antes de aspirar.",
  "TNK NO IAM — dose escalonada por peso, até 50 mg, em bolus único. Este é o regime do INFARTO. NÃO é o do AVC.":
    "TNK EN EL IAM — dosis escalonada por peso, hasta 50 mg, en bolo único. Este es el régimen del INFARTO. NO es el del ACV.",
};
