/**
 * Bloco 1 — contraindicações e adjuvantes em fonte única (E6/E2/E3/E8/E9/A4/A5).
 */
export const ES_BLOCO1: Record<string, string> = {
  "⛔ NITRATO É CONTRAINDICADO com inibidor de PDE-5: 24 h após sildenafila ou vardenafila, 48 h após tadalafila (meia-vida 17,5 h). A associação causa hipotensão refratária, e a população do EAP e da SCA é a mesma que usa estes fármacos — PERGUNTE, não presuma. Ninguém informa isso espontaneamente.":
    "⛔ EL NITRATO ESTÁ CONTRAINDICADO con inhibidor de PDE-5: 24 h después de sildenafilo o vardenafilo, 48 h después de tadalafilo (vida media 17,5 h). La asociación causa hipotensión refractaria, y la población del EAP y del SCA es la misma que usa estos fármacos — PREGUNTE, no presuma. Nadie lo informa espontáneamente.",
  "⚠️ USO CRÔNICO PARA HIPERTENSÃO PULMONAR (sildenafila 20 mg 3×/dia — Revatio e genéricos): contraindicação PERMANENTE enquanto o paciente estiver em uso, não janela de 24 h. Esse paciente NUNCA sai da janela — e é justamente quem chega com dispneia e congestão.":
    "⚠️ USO CRÓNICO PARA HIPERTENSIÓN PULMONAR (sildenafilo 20 mg 3×/día — Revatio y genéricos): contraindicación PERMANENTE mientras el paciente esté en uso, no ventana de 24 h. Ese paciente NUNCA sale de la ventana — y es justamente quien llega con disnea y congestión.",
  "Também contraindicado se PAS < 90 mmHg, estenose aórtica grave, ou IAM de ventrículo direito / parede inferior com hipotensão — nesses o nitrato derruba a pré-carga de que o VD depende. Conduta oposta: VOLUME (cristaloide), não vasodilatador.":
    "También contraindicado si PAS < 90 mmHg, estenosis aórtica grave, o IAM de ventrículo derecho / pared inferior con hipotensión — en esos el nitrato derriba la precarga de la que el VD depende. Conducta opuesta: VOLUMEN (cristaloide), no vasodilatador.",
  "⛔ CONTRAINDICAÇÕES À VNI (avaliar ANTES de colocar a máscara): parada cardiorrespiratória ou respiratória; rebaixamento do nível de consciência, sonolência, agitação, confusão ou recusa; instabilidade hemodinâmica com vasopressor, PAS < 90 ou arritmia complexa; obstrução de via aérea superior ou trauma/cirurgia recente de face; tosse ineficaz ou incapacidade de proteger a via aérea; VÔMITO INCOERCÍVEL ou distensão abdominal — risco de aspiração sob máscara; hemorragia digestiva alta.":
    "⛔ CONTRAINDICACIONES A LA VNI (evaluar ANTES de colocar la mascarilla): paro cardiorrespiratorio o respiratorio; deterioro del nivel de conciencia, somnolencia, agitación, confusión o rechazo; inestabilidad hemodinámica con vasopresor, PAS < 90 o arritmia compleja; obstrucción de vía aérea superior o trauma/cirugía reciente de cara; tos ineficaz o incapacidad de proteger la vía aérea; VÓMITO INCOERCIBLE o distensión abdominal — riesgo de aspiración bajo la mascarilla; hemorragia digestiva alta.",
  "⚠️ HIPOTENSÃO — contraindicação relativa que se decide ANTES, não depois: a pressão positiva reduz o retorno venoso e pode derrubar o débito em quem já está no limite. No EAP a VNI costuma ser indicada antes de a PA ser classificada, então a checagem tem de acontecer aqui. PAS limítrofe (90–100): se a VNI for mantida, monitorização contínua e plano de IOT à mão.":
    "⚠️ HIPOTENSIÓN — contraindicación relativa que se decide ANTES, no después: la presión positiva reduce el retorno venoso y puede derribar el gasto en quien ya está al límite. En el EAP la VNI suele indicarse antes de que se clasifique la PA, así que la verificación tiene que ocurrir aquí. PAS limítrofe (90–100): si se mantiene la VNI, monitorización continua y plan de IOT a mano.",
  "Paciente ideal para VNI: alerta, cooperativo, com reflexos de via aérea intactos e hemodinamicamente estável. Ressalva importante: em serviços experientes, o coma HIPERCÁPNICO da DPOC NÃO contraindica — ali a VNI é o tratamento do rebaixamento, não o risco.":
    "Paciente ideal para VNI: alerta, cooperador, con reflejos de vía aérea intactos y hemodinámicamente estable. Salvedad importante: en servicios experimentados, el coma HIPERCÁPNICO de la EPOC NO contraindica — allí la VNI es el tratamiento del deterioro, no el riesgo.",
  "BRONCOESPASMO REFRATÁRIO — adjuvantes, quando o β2 isolado não resolve: acrescentar IPRATRÓPIO inalatório ao salbutamol (broncodilatação por outro mecanismo, aditiva); corticoide sistêmico; e SULFATO DE MAGNÉSIO 2 g IV em 20 min no broncoespasmo grave.":
    "BRONCOESPASMO REFRACTARIO — adyuvantes, cuando el β2 aislado no resuelve: agregar IPRATROPIO inhalado al salbutamol (broncodilatación por otro mecanismo, aditiva); corticoide sistémico; y SULFATO DE MAGNESIO 2 g IV en 20 min en el broncoespasmo grave.",
  "⚠️ NA ANAFILAXIA, NENHUM DESSES SUBSTITUI OU ATRASA A ADRENALINA. São adjuvantes do broncoespasmo que persiste APÓS a adrenalina IM — nunca alternativa a ela. Broncoespasmo refratário em anafilaxia é indicação de repetir a adrenalina e preparar via aérea, não de escalar adjuvante.":
    "⚠️ EN LA ANAFILAXIA, NINGUNO DE ESTOS SUSTITUYE NI RETRASA LA ADRENALINA. Son adyuvantes del broncoespasmo que persiste DESPUÉS de la adrenalina IM — nunca alternativa a ella. El broncoespasmo refractario en anafilaxia es indicación de repetir la adrenalina y preparar la vía aérea, no de escalar adyuvantes.",
  "MORFINA — se usada: 2–4 mg IV lento, repetível a cada 5–15 min conforme a resposta, com TETO de 10–15 mg no total. O teto importa porque a dose é repetível: sem limite escrito, a soma passa despercebida.":
    "MORFINA — si se usa: 2–4 mg IV lento, repetible cada 5–15 min según la respuesta, con TECHO de 10–15 mg en total. El techo importa porque la dosis es repetible: sin límite escrito, la suma pasa desapercibida.",
  "⛔ NÃO usar morfina se: hipotensão ou instabilidade hemodinâmica; rebaixamento do nível de consciência; insuficiência respiratória grave com retenção de CO₂ ou DPOC — a depressão respiratória se soma à falência que já existe; IAM de ventrículo direito com hipotensão (a venodilatação reduz a pré-carga de que o VD depende).":
    "⛔ NO usar morfina si: hipotensión o inestabilidad hemodinámica; deterioro del nivel de conciencia; insuficiencia respiratoria grave con retención de CO₂ o EPOC — la depresión respiratoria se suma a la falla que ya existe; IAM de ventrículo derecho con hipotensión (la venodilatación reduce la precarga de la que el VD depende).",
  "Evitar morfina de rotina; reservar para angústia refratária (ESC 2021 IIb).":
    "Evitar morfina de rutina; reservar para la angustia refractaria (ESC 2021 IIb).",
  "Estatina de alta intensidade: atorvastatina 40–80 mg VO (alternativa: rosuvastatina 20–40 mg).":
    "Estatina de alta intensidad: atorvastatina 40–80 mg VO (alternativa: rosuvastatina 20–40 mg).",
  "Nitrato e morfina só se necessário — e as contraindicações abaixo valem para os dois:":
    "Nitrato y morfina solo si es necesario — y las contraindicaciones siguientes valen para ambos:",
};
