/**
 * Bloco 3 — S/F por pergunta, VNI por cenário, pressão resistiva × resistência,
 * periodicidade da Pplat, modos ventilatórios e corticoides equivalentes.
 */
export const ES_BLOCO3: Record<string, string> = {
  "COMO MEDIR O COMPONENTE RESISTIVO — e são DUAS grandezas com o mesmo protagonista, fáceis de confundir: (1) PRESSÃO RESISTIVA = Ppico − Pplatô, em cmH₂O. Acima de ~10 cmH₂O aponta tubo dobrado ou obstruído, secreção, broncoespasmo ou massa intraluminal. (2) RESISTÊNCIA = essa mesma diferença DIVIDIDA PELO FLUXO, em cmH₂O/L/s — no ventilado com pulmão normal e tubo, raramente passa de 15. Usar o limiar de uma como se fosse da outra troca a conclusão: 10 é muito para a pressão e é normal para a resistência.":
    "CÓMO MEDIR EL COMPONENTE RESISTIVO — y son DOS magnitudes con el mismo protagonista, fáciles de confundir: (1) PRESIÓN RESISTIVA = Ppico − Pmeseta, en cmH₂O. Por encima de ~10 cmH₂O apunta a tubo acodado u obstruido, secreción, broncoespasmo o masa intraluminal. (2) RESISTENCIA = esa misma diferencia DIVIDIDA POR EL FLUJO, en cmH₂O/L/s — en el ventilado con pulmón normal y tubo, rara vez pasa de 15. Usar el umbral de una como si fuera de la otra invierte la conclusión: 10 es mucho para la presión y es normal para la resistencia.",
  "E A REGRA VALE ALÉM DO EAP: na exacerbação de DPOC com acidose respiratória, a VNI de primeira linha reduz intubação e mortalidade — nos ensaios agrupados de UTI, intubação de 63% para 21% e mortalidade de 25% para 9%. ⚠️ O GANHO DEPENDE DO CENÁRIO: em enfermaria o efeito é bem menor que em UTI, e a melhor indicação é a acidose respiratória MODERADA a grave. Acidose muito grave ou rebaixamento por hipercapnia têm alto risco de falha — a VNI ali só com IOT pronta.":
    "Y LA REGLA VALE MÁS ALLÁ DEL EAP: en la exacerbación de EPOC con acidosis respiratoria, la VNI de primera línea reduce intubación y mortalidad — en los ensayos agrupados de UCI, intubación del 63% al 21% y mortalidad del 25% al 9%. ⚠️ LA GANANCIA DEPENDE DEL ESCENARIO: en sala el efecto es bastante menor que en UCI, y la mejor indicación es la acidosis respiratoria MODERADA a grave. La acidosis muy grave o el deterioro de conciencia por hipercapnia tienen alto riesgo de fallo — allí la VNI solo con IOT lista.",
  "MODOS ALÉM DO BÁSICO, e o que cada um resolve: PRVC / VC+ entrega o volume-alvo com limite de pressão — útil quando se quer proteção com adaptação automática; PC-AC controla a pressão e o Vt varia com a complacência, então o Vt tem de ser VIGIADO, não presumido; SIMV NÃO é primeira escolha na instabilidade aguda (o desmame por redução de FR mandatória é mais lento e a assincronia é maior); CPAP não tem I:E nem FR mandatória — é PEEP e FiO₂, para quem ventila sozinho.":
    "MODOS MÁS ALLÁ DEL BÁSICO, y qué resuelve cada uno: PRVC / VC+ entrega el volumen objetivo con límite de presión — útil cuando se busca protección con adaptación automática; PC-AC controla la presión y el Vt varía con la distensibilidad, así que el Vt debe VIGILARSE, no presumirse; SIMV NO es primera elección en la inestabilidad aguda (el destete por reducción de FR mandatoria es más lento y la asincronía es mayor); CPAP no tiene I:E ni FR mandatoria — es PEEP y FiO₂, para quien ventila por sí mismo.",
  "QUANDO REMEDIR: a Pplat não é medida uma vez — remedir a cada mudança de parâmetro e periodicamente (a cada 4–8 h) enquanto o paciente estiver instável. Complacência muda ao longo do dia, e um platô aceitável às 8h não garante o das 14h.":
    "CUÁNDO REMEDIR: la Pmeseta no se mide una sola vez — remedir con cada cambio de parámetro y periódicamente (cada 4–8 h) mientras el paciente esté inestable. La distensibilidad cambia a lo largo del día, y una meseta aceptable a las 8h no garantiza la de las 14h.",
  "SEM GASOMETRIA? A relação SpO₂/FiO₂ substitui a PaO₂/FiO₂, e os DOIS pontos de corte saem da MESMA reta (Rice 2007: S/F = 64 + 0,84 × P/F) — mas respondem a perguntas diferentes, e usar um pelo outro troca diagnóstico por gravidade: S/F ≤ 315 equivale a P/F ≤ 300 e responde «É SDRA?» (sensibilidade 91%, mas especificidade de apenas 56% — superestima); S/F ≤ 235 equivale a P/F ≤ 200 e responde «É SDRA MODERADA ou pior?» (85% / 85%, mais equilibrado). Válido só com SpO₂ ≤ 97%, fora do platô da curva.":
    "¿SIN GASOMETRÍA? La relación SpO₂/FiO₂ sustituye a la PaO₂/FiO₂, y los DOS puntos de corte salen de la MISMA recta (Rice 2007: S/F = 64 + 0,84 × P/F) — pero responden preguntas distintas, y usar uno por otro cambia diagnóstico por gravedad: S/F ≤ 315 equivale a P/F ≤ 300 y responde «¿Es SDRA?» (sensibilidad 91%, pero especificidad de solo 56% — sobreestima); S/F ≤ 235 equivale a P/F ≤ 200 y responde «¿Es SDRA MODERADA o peor?» (85% / 85%, más equilibrado). Válido solo con SpO₂ ≤ 97%, fuera de la meseta de la curva.",
  "ALTERNATIVAS EQUIVALENTES quando a metilprednisolona não estiver disponível: HIDROCORTISONA 200 mg IV (a escolha do Resuscitation Council UK) OU DEXAMETASONA 10 mg IV. As três doses são equivalentes entre si — 125 mg de metilprednisolona ≡ 200 mg de hidrocortisona ≡ 10 mg de dexametasona. Nenhuma muda a posição do corticoide: segue adjuvante, depois da adrenalina, e sem prevenir fase bifásica.":
    "ALTERNATIVAS EQUIVALENTES cuando la metilprednisolona no esté disponible: HIDROCORTISONA 200 mg IV (la elección del Resuscitation Council UK) O DEXAMETASONA 10 mg IV. Las tres dosis son equivalentes entre sí — 125 mg de metilprednisolona ≡ 200 mg de hidrocortisona ≡ 10 mg de dexametasona. Ninguna cambia la posición del corticoide: sigue siendo adyuvante, después de la adrenalina, y sin prevenir la fase bifásica.",
};
