/**
 * Bloco 2 — itens de alcance e lacuna (E1/E4/E5/E7/E10/E12-veto, A1 Kounis,
 * S6 endocardite).
 */
export const ES_BLOCO2: Record<string, string> = {
  "ACESSO CENTRAL é preferencial para a noradrenalina — o extravasamento em veia periférica causa necrose tecidual. Mas NÃO ATRASAR o início por causa do acesso: começar em periférica calibrosa, com vigilância do sítio, e trocar assim que possível.":
    "ACCESO CENTRAL es preferible para la noradrenalina — la extravasación en vena periférica causa necrosis tisular. Pero NO RETRASAR el inicio por el acceso: comenzar en una periférica de buen calibre, con vigilancia del sitio, y cambiar en cuanto sea posible.",
  "NITROGLICERINA SUBLINGUAL — a ponte, enquanto o acesso IV e a bomba são preparados: 0,4 mg SL, repetível a cada 5 min até 3 doses, se PAS > 110. Não substitui a titulação IV; adianta o alívio em minutos.":
    "NITROGLICERINA SUBLINGUAL — el puente, mientras se preparan el acceso IV y la bomba: 0,4 mg SL, repetible cada 5 min hasta 3 dosis, si PAS > 110. No sustituye la titulación IV; adelanta el alivio en minutos.",
  "POSIÇÃO — SENTADO com as pernas pendentes (cabeceira 60–90°, não 30°): reduz o retorno venoso e redistribui o edema, e é a única medida que alivia em segundos, antes de qualquer droga. Deitar o paciente com EAP piora a mecânica na hora.":
    "POSICIÓN — SENTADO con las piernas colgando (cabecera 60–90°, no 30°): reduce el retorno venoso y redistribuye el edema, y es la única medida que alivia en segundos, antes de cualquier fármaco. Acostar al paciente con EAP empeora la mecánica de inmediato.",
  "PREPARO E DILUIÇÃO: as soluções padrão (200 mcg/mL e 100 mcg/mL, a partir da ampola nacional) estão no módulo de Drogas Vasoativas — usar de lá, para não nascer uma segunda tabela de diluição no app.":
    "PREPARACIÓN Y DILUCIÓN: las soluciones estándar (200 mcg/mL y 100 mcg/mL, a partir de la ampolla nacional) están en el módulo de Drogas Vasoactivas — usarlas de allí, para que no nazca una segunda tabla de dilución en la app.",
  "QUEM JÁ USA FUROSEMIDA EM CASA (e sobretudo o DOENTE RENAL CRÔNICO): a dose de ataque é 2,5× a dose oral diária habitual, por via IV — não uma faixa fixa. Na DRC, menos fármaco alcança o túbulo, e a dose que funcionava ontem no ambulatório é insuficiente hoje. O DOSE trial mostrou mais diurese e mais alívio de dispneia com a dose alta, com alteração de creatinina apenas transitória.":
    "QUIEN YA USA FUROSEMIDA EN CASA (y sobre todo el ENFERMO RENAL CRÓNICO): la dosis de ataque es 2,5× la dosis oral diaria habitual, por vía IV — no un rango fijo. En la ERC llega menos fármaco al túbulo, y la dosis que servía ayer en el ambulatorio hoy es insuficiente. El ensayo DOSE mostró más diuresis y más alivio de la disnea con la dosis alta, con alteración de la creatinina solo transitoria.",
  "⚠️ E NÃO PERSIGA UM NÚMERO DE FREQUÊNCIA: na FA que descompensa, taquicardia é em boa parte RESPOSTA à congestão e ao baixo débito. O caminho é tratar a congestão e a causa (e cardioverter se instável) — a frequência cede junto. Alvo de FC sem ferramenta segura é objetivo sem caminho.":
    "⚠️ Y NO PERSIGA UN NÚMERO DE FRECUENCIA: en la FA que descompensa, la taquicardia es en buena parte RESPUESTA a la congestión y al bajo gasto. El camino es tratar la congestión y la causa (y cardiovertir si hay inestabilidad) — la frecuencia cede con ello. Un objetivo de FC sin herramienta segura es una meta sin camino.",
  "⚠️ SE HOUVER REBAIXAMENTO OU IOT, a posição vira 30–45° com proteção de via aérea — sentado sem controle da via aérea é risco de aspiração.":
    "⚠️ SI HAY DETERIORO DE CONCIENCIA O IOT, la posición pasa a 30–45° con protección de la vía aérea — sentado sin control de la vía aérea es riesgo de aspiración.",
  "⛔ NÃO usar BETABLOQUEADOR nem BLOQUEADOR DE CANAL DE CÁLCIO NÃO-DIIDROPIRIDÍNICO (diltiazem, verapamil) IV na descompensação aguda — são inotrópicos NEGATIVOS num coração que já falhou como bomba, e derrubam o débito que sustenta a perfusão. São a escolha correta na FA crônica ambulatorial e a errada aqui; a diferença é a congestão.":
    "⛔ NO usar BETABLOQUEANTE ni BLOQUEANTE DE CANAL DE CALCIO NO DIHIDROPIRIDÍNICO (diltiazem, verapamilo) IV en la descompensación aguda — son inotrópicos NEGATIVOS en un corazón que ya falló como bomba, y derriban el gasto que sostiene la perfusión. Son la elección correcta en la FA crónica ambulatoria y la equivocada aquí; la diferencia es la congestión.",
  "E a conduta carrega uma tensão que precisa ser sabida: a ADRENALINA continua sendo o tratamento da anafilaxia, mas pode agravar o vasoespasmo coronariano. Isso NÃO a contraindica — anafilaxia não tratada mata mais rápido. Significa monitorizar o ECG, evitar dose excessiva e envolver a cardiologia precocemente, sem atrasar a adrenalina.":
    "Y la conducta lleva una tensión que hay que conocer: la ADRENALINA sigue siendo el tratamiento de la anafilaxia, pero puede agravar el vasoespasmo coronario. Eso NO la contraindica — la anafilaxia no tratada mata más rápido. Significa monitorizar el ECG, evitar dosis excesivas e involucrar a cardiología precozmente, sin retrasar la adrenalina.",
  "⚠️ DOR TORÁCICA OU ALTERAÇÃO NO ECG DURANTE A REAÇÃO — pense em SÍNDROME DE KOUNIS (síndrome coronariana ALÉRGICA): os mediadores da degranulação mastocitária causam VASOESPASMO CORONARIANO. Pode haver supra ou infra de ST e troponina elevada. Não descarte a dor como sendo apenas mais um sintoma da reação: colher ECG e troponina.":
    "⚠️ DOLOR TORÁCICO O ALTERACIÓN EN EL ECG DURANTE LA REACCIÓN — piense en SÍNDROME DE KOUNIS (síndrome coronario ALÉRGICO): los mediadores de la degranulación mastocitaria causan VASOESPASMO CORONARIO. Puede haber elevación o descenso del ST y troponina elevada. No descarte el dolor como si fuera solo un síntoma más de la reacción: obtener ECG y troponina.",
  "SUSPEITA DE ENDOCARDITE (sopro novo, prótese valvar, usuário de droga injetável, embolia periférica, febre sem foco): os MESMOS 2 pares já bastam — o critério maior do Duke-ISCVID 2023 é micro-organismo típico em 2 ou mais AMOSTRAS SEPARADAS. A exigência de 3 pares com 30 min de intervalo foi RETIRADA na revisão de 2023; punção separada para cada amostra segue sendo boa prática, mas não é mais requisito. O que muda na suspeita de endocardite é o ECOCARDIOGRAMA precoce e a duração do tratamento, não o número de frascos.":
    "SOSPECHA DE ENDOCARDITIS (soplo nuevo, prótesis valvular, usuario de drogas inyectables, embolia periférica, fiebre sin foco): los MISMOS 2 pares ya bastan — el criterio mayor del Duke-ISCVID 2023 es microorganismo típico en 2 o más MUESTRAS SEPARADAS. La exigencia de 3 pares con 30 min de intervalo fue RETIRADA en la revisión de 2023; la punción separada para cada muestra sigue siendo buena práctica, pero ya no es requisito. Lo que cambia ante la sospecha de endocarditis es el ECOCARDIOGRAMA precoz y la duración del tratamiento, no el número de frascos.",
};
