/**
 * Broncoespasmo na anafilaxia — primeira linha e magnésio refratário (R-42).
 */
export const ES_BRONCO_ANAFILAXIA: Record<string, string> = {
  "BRONCOESPASMO — PRIMEIRA LINHA INALATÓRIA: beta-2 (salbutamol) isolado OU em associação com IPRATRÓPIO. A associação NÃO é conduta de resgate: a fonte de anafilaxia põe o ipratrópio na primeira linha do chiado, ao lado do beta-2 — tratá-lo como adjuvante tardio atrasa o que deveria ser imediato.":
    "BRONCOESPASMO — PRIMERA LÍNEA INHALATORIA: beta-2 (salbutamol) solo O asociado a IPRATROPIO. La asociación NO es conducta de rescate: la fuente de anafilaxia coloca el ipratropio en la primera línea de las sibilancias, junto al beta-2 — tratarlo como adyuvante tardío retrasa lo que debería ser inmediato.",
  "CHIADO REFRATÁRIO ao beta-2 e à adrenalina: SULFATO DE MAGNÉSIO IV — 2 g em 20 min no adulto. ⚠️ PROCEDÊNCIA DA DOSE: a indicação do magnésio no broncoespasmo refratário da anafilaxia é da própria literatura de anafilaxia, mas o REGIME é o da crise asmática grave — a fonte remete a ele em vez de definir dose própria. É analogia declarada, com aval da fonte, não número específico de anafilaxia.":
    "SIBILANCIAS REFRACTARIAS al beta-2 y a la adrenalina: SULFATO DE MAGNESIO IV — 2 g en 20 min en el adulto. ⚠️ PROCEDENCIA DE LA DOSIS: la indicación del magnesio en el broncoespasmo refractario de la anafilaxia proviene de la propia literatura de anafilaxia, pero el RÉGIMEN es el de la crisis asmática grave — la fuente remite a él en vez de definir una dosis propia. Es analogía declarada, con aval de la fuente, no un número específico de anafilaxia.",
  "⚠️ NENHUM DESSES SUBSTITUI OU ATRASA A ADRENALINA. São o tratamento do broncoespasmo que persiste ao lado da adrenalina IM — nunca alternativa a ela. Broncoespasmo refratário em anafilaxia é indicação de REPETIR a adrenalina e preparar via aérea, não de escalar inalatório.":
    "⚠️ NINGUNO DE ESTOS SUSTITUYE NI RETRASA LA ADRENALINA. Son el tratamiento del broncoespasmo que persiste junto a la adrenalina IM — nunca una alternativa a ella. El broncoespasmo refractario en anafilaxia es indicación de REPETIR la adrenalina y preparar la vía aérea, no de escalar inhalatorios.",
  "⚠️ PERGUNTE SE O PACIENTE USA BETABLOQUEADOR — e pergunte AGORA, não quando a adrenalina falhar. O betabloqueio impede a resposta beta-1 à adrenalina, e o uso de betabloqueador/IECA se associa a anafilaxia REFRATÁRIA (OR ≈ 2,5). Se usar: prepare o glucagon junto com a 1ª dose de adrenalina, em vez de buscá-lo depois de duas doses sem resposta. A evidência é debatida — há análises multivariadas em que o betabloqueador não sai como fator independente —, mas a preparação antecipada não custa nada e a busca tardia custa minutos.":
    "⚠️ PREGUNTE SI EL PACIENTE USA BETABLOQUEANTE — y pregunte AHORA, no cuando la adrenalina falle. El betabloqueo impide la respuesta beta-1 a la adrenalina, y el uso de betabloqueante/IECA se asocia a anafilaxia REFRACTARIA (OR ≈ 2,5). Si lo usa: prepare el glucagón junto con la 1ª dosis de adrenalina, en vez de buscarlo tras dos dosis sin respuesta. La evidencia es debatida — hay análisis multivariados en los que el betabloqueante no aparece como factor independiente —, pero la preparación anticipada no cuesta nada y la búsqueda tardía cuesta minutos.",
};
