/** ES — CAD/EHH: os números do consenso ADA/EASD 2024 que substituíram os de 2009,
 *  o bicarbonato de ramo único (D-2) e o que começar antes do exame voltar. */
export const cadEhh2024Es: Record<string, string> = {
  "COMECE AGORA — O QUE NÃO DEPENDE DE NENHUM EXAME: (1) HIDRATAÇÃO, que é o primeiro passo dos três quadros e sozinha já derruba glicemia e osmolalidade — cristaloide balanceado, 500–1.000 mL/h nas primeiras 2–4 h, reduzindo em cardiopata e nefropata; (2) MONITORIZAÇÃO e dois acessos; (3) ECG, que devolve informação de potássio em segundos — onda T apiculada sugere K⁺ alto, achatamento com onda U sugere baixo — enquanto o laboratório não volta; (4) BUSCAR O PRECIPITANTE, que é metade do tratamento: infecção, omissão de insulina, infarto, AVC, pancreatite, gestação, medicamento novo, SGLT2i; (5) COLHER tudo de uma vez — glicemia capilar, gasometria (VENOSA serve), eletrólitos, função renal, cetonas, hemograma, urina, ECG. ⚠️ O QUE DEPENDE DO EXAME, e por isso espera: a CLASSIFICAÇÃO entre CAD, EHH e misto, e a INSULINA — que não começa antes de saber o K⁺, porque insulina com potássio baixo é arritmia. ⚠️ E NÃO ESPERE GASOMETRIA ARTERIAL: a VENOSA basta para o diagnóstico e o acompanhamento da CAD, e é o que costuma chegar primeiro.":
    "EMPIECE AHORA — LO QUE NO DEPENDE DE NINGÚN EXAMEN: (1) HIDRATACIÓN, que es el primer paso de los tres cuadros y por sí sola ya baja la glucemia y la osmolalidad — cristaloide balanceado, 500–1.000 mL/h en las primeras 2–4 h, reduciendo en el cardiópata y el nefrópata; (2) MONITORIZACIÓN y dos accesos; (3) ECG, que devuelve información de potasio en segundos — onda T picuda sugiere K⁺ alto, aplanamiento con onda U sugiere bajo — mientras el laboratorio no vuelve; (4) BUSCAR EL PRECIPITANTE, que es la mitad del tratamiento: infección, omisión de insulina, infarto, ACV, pancreatitis, embarazo, medicamento nuevo, iSGLT2; (5) EXTRAER todo de una vez — glucemia capilar, gasometría (VENOSA sirve), electrolitos, función renal, cetonas, hemograma, orina, ECG. ⚠️ LO QUE DEPENDE DEL EXAMEN, y por eso espera: la CLASIFICACIÓN entre CAD, EHH y mixto, y la INSULINA — que no empieza antes de conocer el K⁺, porque insulina con potasio bajo es arritmia. ⚠️ Y NO ESPERE GASOMETRÍA ARTERIAL: la VENOSA basta para el diagnóstico y el seguimiento de la CAD, y es la que suele llegar primero.",
  "VELOCIDADE DE CORREÇÃO NO EHH (consenso 2024) — três tetos que andam juntos: queda da GLICEMIA não maior que 90–120 mg/dL/h; queda do SÓDIO não maior que 10 mmol/L em 24 h; e queda da OSMOLALIDADE entre 3,0 e 8,0 mOsm/kg/h. A hiperglicemia costuma levar de 8 a 10 h para resolver, e essa lentidão é terapêutica, não demora. ⚠️ O QUE ACONTECE SE CORRIGIR RÁPIDO: a água se desloca para o intracelular e o cérebro edemacia — é a complicação que mata no EHH tratado. Se a queda estiver rápida demais, o freio é o FLUIDO, não a insulina.":
    "VELOCIDAD DE CORRECCIÓN EN EL EHH (consenso 2024) — tres techos que van juntos: caída de la GLUCEMIA no mayor de 90–120 mg/dL/h; caída del SODIO no mayor de 10 mmol/L en 24 h; y caída de la OSMOLALIDAD entre 3,0 y 8,0 mOsm/kg/h. La hiperglucemia suele tardar de 8 a 10 h en resolverse, y esa lentitud es terapéutica, no demora. ⚠️ QUÉ PASA SI SE CORRIGE RÁPIDO: el agua se desplaza al intracelular y el cerebro se edematiza — es la complicación que mata en el EHH tratado. Si la caída va demasiado rápido, el freno es el LÍQUIDO, no la insulina.",
  "NÃO normalizar a osmolalidade em menos de 24–36 h.":
    "NO normalizar la osmolalidad en menos de 24–36 h.",
  "REPOSIÇÃO DE K⁺ — 10–20 mmol/L POR HORA até K⁺ > 3,5 mmol/L, E TAXA MAIOR EXIGE ACESSO VENOSO CENTRAL (consenso 2024). ⚠️ A ressalva é da mesma frase, e não de uma nota adiante: potássio concentrado em veia periférica causa dor intensa, flebite e necrose se extravasar, e é por isso que a via — e não a pressa — é o que limita a velocidade. ⚠️ E A DIREÇÃO DO ERRO IMPORTA: o app trazia 20–40 mEq/h, o DOBRO da taxa da fonte, herdado do protocolo de 2009. Repor rápido demais por veia periférica troca uma hipocalemia tratável por uma lesão de acesso — e não acelera a insulina, que espera o K⁺ chegar a 3,5 de qualquer forma. MANUTENÇÃO, com K⁺ entre 3,5 e 5,0: 10–20 mmol de KCl por LITRO de fluido, mantendo o K⁺ entre 4 e 5.":
    "REPOSICIÓN DE K⁺ — 10–20 mmol/L POR HORA hasta K⁺ > 3,5 mmol/L, Y UNA TASA MAYOR EXIGE ACCESO VENOSO CENTRAL (consenso 2024). ⚠️ La salvedad es de la misma frase, y no de una nota más adelante: el potasio concentrado en vena periférica causa dolor intenso, flebitis y necrosis si se extravasa, y por eso la vía — y no la prisa — es lo que limita la velocidad. ⚠️ Y LA DIRECCIÓN DEL ERROR IMPORTA: la app traía 20–40 mEq/h, el DOBLE de la tasa de la fuente, heredado del protocolo de 2009. Reponer demasiado rápido por vena periférica cambia una hipopotasemia tratable por una lesión de acceso — y no acelera la insulina, que espera a que el K⁺ llegue a 3,5 de todos modos. MANTENIMIENTO, con K⁺ entre 3,5 y 5,0: 10–20 mmol de KCl por LITRO de líquido, manteniendo el K⁺ entre 4 y 5.",
  "ECG contínuo durante a reposição.":
    "ECG continuo durante la reposición.",
  "Infusão contínua (padrão-ouro): insulina regular {insInf} U/h (0,1 U/kg/h). Preparo: 100 UI em 100 mL SF → 1 U = 1 mL.":
    "Infusión continua (patrón de oro): insulina regular {insInf} U/h (0,1 U/kg/h). Preparación: 100 UI en 100 mL de SF → 1 U = 1 mL.",
  "SEM BOLUS DE ROTINA — o bólus não melhora desfecho e aumenta hipoglicemia e hipocalemia. ⚠️ MAS EXISTE UMA EXCEÇÃO, E ELA É A DO SERVIÇO REAL: se houver DEMORA para obter acesso venoso ou para montar a bomba, o consenso 2024 admite uma dose inicial de 0,1 U/kg de insulina de ação rápida — IV OU INTRAMUSCULAR —, seguida da infusão contínua de taxa fixa assim que possível. A via IM é a que resolve o caso em que a veia é o problema. O que não se faz é bólus com a bomba pronta ao lado.":
    "SIN BOLO DE RUTINA — el bolo no mejora el desenlace y aumenta la hipoglucemia y la hipopotasemia. ⚠️ PERO EXISTE UNA EXCEPCIÓN, Y ES LA DEL SERVICIO REAL: si hay DEMORA para obtener acceso venoso o para montar la bomba, el consenso 2024 admite una dosis inicial de 0,1 U/kg de insulina de acción rápida — IV O INTRAMUSCULAR —, seguida de la infusión continua de tasa fija en cuanto sea posible. La vía IM es la que resuelve el caso en que la vena es el problema. Lo que no se hace es un bolo con la bomba lista al lado.",
  "⚠️ CAD LEVE TEM TAXA PRÓPRIA: o consenso 2024 inicia a infusão em 0,05 U/kg/h na CAD leve, e não nos 0,1 U/kg/h da moderada e da grave. É a mesma lógica que separa o EHH: a condição vem ANTES do número. Classifique a gravidade (pH, bicarbonato, cetonas e estado mental) antes de programar a bomba — e lembre que a CAD leve não complicada é também a candidata ao análogo rápido SUBCUTÂNEO, que evita a UTI.":
    "⚠️ LA CAD LEVE TIENE TASA PROPIA: el consenso 2024 inicia la infusión en 0,05 U/kg/h en la CAD leve, y no en los 0,1 U/kg/h de la moderada y la grave. Es la misma lógica que separa al EHH: la condición viene ANTES del número. Clasifique la gravedad (pH, bicarbonato, cetonas y estado mental) antes de programar la bomba — y recuerde que la CAD leve no complicada es también la candidata al análogo rápido SUBCUTÁNEO, que evita la UCI.",
  "BICARBONATO — SÓ SE pH < 7,0, e nunca de rotina. O consenso ADA/EASD 2024 é direto: a administração rotineira NÃO é recomendada, porque hidratação e insulina bastam para resolver a acidose da CAD. Considera-se apenas quando a acidose é GRAVE — pH < 7,0 —, pelo risco de efeitos vasculares adversos. ⚠️ NÃO EXISTE MAIS A FAIXA 6,9–7,0 COM MEIA DOSE: ela é do protocolo de 2009, e o consenso 2024 traz um único limiar e uma única dose.":
    "BICARBONATO — SOLO SI pH < 7,0, y nunca de rutina. El consenso ADA/EASD 2024 es directo: la administración rutinaria NO se recomienda, porque la hidratación y la insulina bastan para resolver la acidosis de la CAD. Se considera únicamente cuando la acidosis es GRAVE — pH < 7,0 —, por el riesgo de efectos vasculares adversos. ⚠️ YA NO EXISTE LA FRANJA 6,9–7,0 CON MEDIA DOSIS: es del protocolo de 2009, y el consenso 2024 trae un único umbral y una única dosis.",
  "⚠️ POR QUE NÃO DE ROTINA — os danos que a fonte nomeia: risco aumentado de HIPOCALEMIA, REDUÇÃO DA CAPTAÇÃO TISSULAR DE OXIGÊNIO, EDEMA CEREBRAL e ACIDOSE PARADOXAL DO SISTEMA NERVOSO CENTRAL. E o benefício não aparece: estudos observacionais e randomizados não mostraram vantagem em desfecho cardíaco ou neurológico, nem na velocidade de recuperação da hiperglicemia e da cetoacidose. Dar bicarbonato porque o pH assusta é trocar um número que melhora por um dano que não aparece no monitor.":
    "⚠️ POR QUÉ NO DE RUTINA — los daños que la fuente nombra: mayor riesgo de HIPOPOTASEMIA, REDUCCIÓN DE LA CAPTACIÓN TISULAR DE OXÍGENO, EDEMA CEREBRAL y ACIDOSIS PARADÓJICA DEL SISTEMA NERVIOSO CENTRAL. Y el beneficio no aparece: estudios observacionales y aleatorizados no mostraron ventaja en desenlace cardíaco o neurológico, ni en la velocidad de recuperación de la hiperglucemia y la cetoacidosis. Dar bicarbonato porque el pH asusta es cambiar un número que mejora por un daño que no aparece en el monitor.",
  "DOSE (consenso 2024): 100 mmol de bicarbonato de sódio (solução a 8,4%) em 400 mL de ÁGUA ESTÉRIL — a diluição é o que torna a solução isotônica —, podendo ser repetida a cada 2 h até atingir pH > 7,0. ⚠️ O KCl JUNTO NÃO VEM DO CONSENSO 2024: vem do protocolo clássico, e a razão está na própria fonte, que lista a HIPOCALEMIA entre os danos do bicarbonato. Repor potássio junto continua sendo prática defensável — mas é procedência diferente, e fica declarada.":
    "DOSIS (consenso 2024): 100 mmol de bicarbonato de sodio (solución al 8,4%) en 400 mL de AGUA ESTÉRIL — la dilución es lo que vuelve isotónica la solución —, pudiendo repetirse cada 2 h hasta alcanzar un pH > 7,0. ⚠️ EL KCl JUNTO NO VIENE DEL CONSENSO 2024: viene del protocolo clásico, y la razón está en la propia fuente, que enumera la HIPOPOTASEMIA entre los daños del bicarbonato. Reponer potasio junto sigue siendo práctica defendible — pero es otra procedencia, y queda declarada.",
  "Monitorar K⁺ de perto — o bicarbonato baixa o potássio, e a hipocalemia é o primeiro dano da lista.":
    "Monitorizar el K⁺ de cerca — el bicarbonato baja el potasio, y la hipopotasemia es el primer daño de la lista.",
  "Reavaliar a gasometria após 2 h; suspender ao atingir pH > 7,0. EHH não tem indicação (sem acidose).":
    "Reevaluar la gasometría a las 2 h; suspender al alcanzar pH > 7,0. El EHH no tiene indicación (sin acidosis).",
  "ACRESCENTAR GLICOSE AOS 250 mg/dL — e não aos 200. O consenso 2024 manda adicionar dextrose a 5% ou 10% ao cristaloide quando a glicemia cai abaixo de 250 mg/dL, reduzindo a insulina para 0,05 U/kg/h. ⚠️ POR QUE O LIMIAR MAIS ALTO É O SEGURO: a glicose no soro não trata a hiperglicemia, ela EXISTE PARA MANTER A INSULINA CORRENDO enquanto a cetose não fecha. Esperar até 200 mg/dL deixa o paciente mais tempo perto da hipoglicemia com insulina em curso — e a saída que se toma quando ela ameaça é desligar a insulina, que é exatamente o que não se deve fazer com a cetoacidose aberta. ALVOS depois disso: CAD, manter 150–200 mg/dL até a resolução; EHH, manter 200–250 mg/dL até a resolução.":
    "AGREGAR GLUCOSA A LOS 250 mg/dL — y no a los 200. El consenso 2024 manda añadir dextrosa al 5% o 10% al cristaloide cuando la glucemia cae por debajo de 250 mg/dL, reduciendo la insulina a 0,05 U/kg/h. ⚠️ POR QUÉ EL UMBRAL MÁS ALTO ES EL SEGURO: la glucosa en el suero no trata la hiperglucemia, EXISTE PARA MANTENER LA INSULINA CORRIENDO mientras la cetosis no cierra. Esperar hasta 200 mg/dL deja al paciente más tiempo cerca de la hipoglucemia con insulina en curso — y la salida que se toma cuando ella amenaza es apagar la insulina, que es exactamente lo que no se debe hacer con la cetoacidosis abierta. OBJETIVOS después de eso: CAD, mantener 150–200 mg/dL hasta la resolución; EHH, mantener 200–250 mg/dL hasta la resolución.",
  "CAD: acrescentar SG 5% ou 10% ao cristaloide; manter a glicemia entre 150 e 200 mg/dL até a resolução.":
    "CAD: agregar SG al 5% o 10% al cristaloide; mantener la glucemia entre 150 y 200 mg/dL hasta la resolución.",
  "EHH: acrescentar SG 5% ou 10%; manter a glicemia entre 200 e 250 mg/dL até a resolução.":
    "EHH: agregar SG al 5% o 10%; mantener la glucemia entre 200 y 250 mg/dL hasta la resolución.",
  "Reduzir a infusão de insulina para {insLow} U/h (0,05 U/kg/h) — e NÃO desligar enquanto a cetoacidose não resolver.":
    "Reducir la infusión de insulina a {insLow} U/h (0,05 U/kg/h) — y NO apagarla mientras la cetoacidosis no se resuelva.",
  "Reavaliar quando a glicemia atingir 250 mg/dL — é o ponto de acrescentar glicose ao soro, nos dois quadros.":
    "Reevaluar cuando la glucemia llegue a 250 mg/dL — es el punto de agregar glucosa al suero, en los dos cuadros.",
  "CAD RESOLVIDA (consenso 2024): cetonas plasmáticas ou capilares < 0,6 mmol/L E (pH venoso > 7,30 OU bicarbonato > 18 mmol/L). ⚠️ NÃO HÁ CRITÉRIO DE GLICEMIA na definição — a glicemia já estará controlada pelo tratamento, e exigir um valor dela apenas atrasa a transição. Se o betaOHB não estiver disponível, usar o fechamento do ânion gap. CETONÚRIA PODE PERSISTIR por horas depois de resolvido (o teste da fita lê acetoacetato, e o betaOHB se converte nele durante a recuperação) — não usá-la como critério isolado. E a própria fonte pede JUÍZO CLÍNICO: não atrasar alta ou mudança de nível de cuidado por um critério não cumprido.":
    "CAD RESUELTA (consenso 2024): cetonas plasmáticas o capilares < 0,6 mmol/L Y (pH venoso > 7,30 O bicarbonato > 18 mmol/L). ⚠️ NO HAY CRITERIO DE GLUCEMIA en la definición — la glucemia ya estará controlada por el tratamiento, y exigir un valor de ella solo retrasa la transición. Si el betaOHB no está disponible, usar el cierre del anión gap. LA CETONURIA PUEDE PERSISTIR horas después de resuelto (la tira lee acetoacetato, y el betaOHB se convierte en él durante la recuperación) — no usarla como criterio aislado. Y la propia fuente pide JUICIO CLÍNICO: no retrasar el alta ni el cambio de nivel de cuidado por un criterio no cumplido.",
  "EHH RESOLVIDO (consenso 2024) — são TRÊS condições, e a terceira costuma ser esquecida: osmolalidade efetiva calculada < 300 mOsm/kg, glicemia < 250 mg/dL, E DÉBITO URINÁRIO > 0,5 mL/kg/h. ⚠️ O DÉBITO URINÁRIO É CRITÉRIO, não detalhe de enfermagem: ele é a prova de que a perfusão renal voltou, e o EHH é, antes de tudo, uma depleção de volume. Paciente com osmolalidade e glicemia arrumadas mas oligúrico não está resolvido — está com o número corrigido e o volume ainda faltando.":
    "EHH RESUELTO (consenso 2024) — son TRES condiciones, y la tercera suele olvidarse: osmolalidad efectiva calculada < 300 mOsm/kg, glucemia < 250 mg/dL, Y DIURESIS > 0,5 mL/kg/h. ⚠️ LA DIURESIS ES CRITERIO, no un detalle de enfermería: es la prueba de que la perfusión renal volvió, y el EHH es, ante todo, una depleción de volumen. Un paciente con osmolalidad y glucemia arregladas pero oligúrico no está resuelto — está con el número corregido y el volumen todavía faltando.",
  "TRANSIÇÃO PARA SUBCUTÂNEA — SOBREPOSIÇÃO OBRIGATÓRIA de 1 a 2 h: mantenha a infusão IV correndo por 1–2 h DEPOIS de aplicar a insulina SC. A insulina IV tem meia-vida de minutos, e desligar sem cobertura devolve a cetoacidose. Em quem já usava insulina, retomar o esquema prévio ajustado. NO RECÉM-DIAGNOSTICADO, o consenso 2024 dá o número: basal de ação longa SC em 0,15–0,3 U/kg, em dose única ou dividida em duas, com o rápido acrescentado conforme a alimentação e a glicemia — e o esquema completo (40–60% da dose total como basal) começa DEPOIS da resolução, não durante.":
    "TRANSICIÓN A SUBCUTÁNEA — SUPERPOSICIÓN OBLIGATORIA de 1 a 2 h: mantenga la infusión IV corriendo 1–2 h DESPUÉS de aplicar la insulina SC. La insulina IV tiene una vida media de minutos, y apagarla sin cobertura devuelve la cetoacidosis. En quien ya usaba insulina, retomar el esquema previo ajustado. EN EL RECIÉN DIAGNOSTICADO, el consenso 2024 da el número: basal de acción prolongada SC en 0,15–0,3 U/kg, en dosis única o dividida en dos, con la rápida agregada según la alimentación y la glucemia — y el esquema completo (40–60% de la dosis total como basal) empieza DESPUÉS de la resolución, no durante.",
  "A glicemia chegou a 250 mg/dL?":
    "¿La glucemia llegó a 250 mg/dL?",
  "Bicarbonato — só na acidose grave":
    "Bicarbonato — solo en la acidosis grave",
  "Dose única do consenso 2024, sempre com monitorização do K⁺.":
    "Dosis única del consenso 2024, siempre con monitorización del K⁺.",
  "O pH arterial está abaixo de 7,0?":
    "¿El pH arterial está por debajo de 7,0?",
  "pH < 7,0 — considerar bicarbonato":
    "pH < 7,0 — considerar bicarbonato",
};
