/**
 * Causas reversíveis — conduta inline na parada e ponteiros de conduta.
 */
export const ES_CAUSAS_PARADA: Record<string, string> = {
  "Confirmar expansão torácica bilateral. Intubar se não resolvido. Causa mais comum em PCR pediátrica. → Via aérea e parâmetros em ISR e Ventilação Mecânica.":
    "Confirmar expansão torácica bilateral. Intubar se não resolvido. Causa mais comum em PCR pediátrica. → Vía aérea y parámetros en ISR y Ventilación Mecánica.",
  "SF 0,9% ou cristaloide em bolus. Em trauma: controle cirúrgico é prioritário — fluidos não substituem hemostasia. → Estratégia de reposição e controle de sangramento em Choque e Politrauma.":
    "SF 0,9% ou cristaloide em bolus. Em trauma: controle cirúrgico é prioritário — fluidos não substituem hemostasia. → Estrategia de reposición y control del sangrado en Choque y Politrauma.",
  "Tricíclicos: bicarbonato 1–2 mEq/kg. Opioides: naloxona 0,4–2 mg IV se o opioide for desconhecido — fentanil e análogos podem exigir mais de 2 mg ou infusão; se a equipe deu o opioide, titular 0,1–0,2 mg. A meia-vida da naloxona é MENOR que a da maioria dos opioides: a depressão respiratória PODE VOLTAR depois de o paciente já ter acordado — vigiar por horas. Organofosforados: atropina em altas doses. Intoxicação grave: considerar ECMO. → O antídoto é específico de cada agente, e listar alguns aqui criaria a mesma lista parcial que este módulo existe para evitar: abrir Intoxicações Exógenas.":
    "Tricíclicos: bicarbonato 1–2 mEq/kg. Opioides: naloxona 0,4–2 mg IV se o opioide for desconhecido — fentanil e análogos podem exigir mais de 2 mg ou infusão; se a equipe deu o opioide, titular 0,1–0,2 mg. A meia-vida da naloxona é MENOR que a da maioria dos opioides: a depressão respiratória PODE VOLTAR depois de o paciente já ter acordado — vigiar por horas. Organofosforados: atropina em altas doses. Intoxicação grave: considerar ECMO. → El antídoto es específico de cada agente, y listar algunos aquí crearía la misma lista parcial que este módulo existe para evitar: abrir Intoxicaciones Exógenas.",
  "Trombolítico durante RCP em ausência de laboratório de hemodinâmica (evidência limitada). Pós-ROSC: ECG urgente; se IAMCSST → hemodinâmica. → Critérios de reperfusão e tempos porta-balão no módulo Síndromes Coronarianas.":
    "Trombolítico durante RCP em ausência de laboratório de hemodinâmica (evidência limitada). Pós-ROSC: ECG urgente; se IAMCSST → hemodinâmica. → Criterios de reperfusión y tiempos puerta-balón en el módulo Síndromes Coronarios.",
  "TAMPONAMENTO CARDÍACO — pericardiocentese de emergência, de preferência GUIADA POR ULTRASSOM (subxifoide ou paraesternal, pela janela em que o derrame aparece maior e mais próximo). Sem ultrassom, via subxifoide às cegas, agulha em 45° apontada para o ombro esquerdo. Aspirar mesmo 20–50 mL já reverte a fisiologia — o objetivo é descomprimir, não drenar tudo. Se houver equipe cirúrgica, a toracotomia é definitiva; a punção é a ponte.":
    "TAPONAMIENTO CARDÍACO — pericardiocentesis de emergencia, preferentemente GUIADA POR ECOGRAFÍA (subxifoidea o paraesternal, por la ventana en que el derrame aparece mayor y más próximo). Sin ecografía, vía subxifoidea a ciegas, aguja a 45° apuntando al hombro izquierdo. Aspirar incluso 20–50 mL ya revierte la fisiología — el objetivo es descomprimir, no drenar todo. Si hay equipo quirúrgico, la toracotomía es definitiva; la punción es el puente.",
  "⚠️ TEP — SE FIBRINOLISAR, O COMPROMISSO É DE 60–90 MINUTOS DE RCP a partir da dose: o trombolítico precisa de tempo E de compressões para alcançar o trombo. Parar antes disso desperdiça a intervenção em vez de apenas arriscá-la. Decida sabendo o que a escolha custa em tempo de equipe. Critérios, dose e alternativas (embolectomia) no módulo TEP.":
    "⚠️ TEP — SI SE FIBRINOLIZA, EL COMPROMISO ES DE 60–90 MINUTOS DE RCP a partir de la dosis: el trombolítico necesita tiempo Y compresiones para alcanzar el trombo. Detenerse antes desperdicia la intervención en vez de solo arriesgarla. Decida sabiendo lo que la elección cuesta en tiempo de equipo. Criterios, dosis y alternativas (embolectomía) en el módulo TEP.",
  "PNEUMOTÓRAX HIPERTENSIVO — descompressão por agulha, e o COMPRIMENTO importa mais que o sítio: agulha de 4,5 cm falha em cerca de 1/3 dos adultos porque a parede torácica excede esse comprimento — usar cateter de pelo menos 7 cm quando disponível. SÍTIO: o ATLS 2018 passou a preferir o 4º/5º EIC na linha axilar anterior; o 2º EIC hemiclavicular segue válido e é a opção MAIS SEGURA À ESQUERDA, pelo risco de lesão cardíaca no sítio lateral. Em obeso, a parede é mais espessa no sítio lateral — ali o 2º EIC pode alcançar melhor. SE A AGULHA NÃO ALCANÇAR — e você saberá porque não sai ar nem há melhora — NÃO repita no mesmo sítio com a mesma agulha: ou troque por cateter mais longo, ou parta direto para a TORACOSTOMIA DIGITAL (incisão no 4º/5º EIC axilar anterior, divulsão romba e dedo na pleura), que é definitiva para o alívio e não depende de comprimento de agulha. Descomprimir é medida PONTE em qualquer via: o tratamento é o dreno torácico.":
    "NEUMOTÓRAX HIPERTENSIVO — descompresión con aguja, y la LONGITUD importa más que el sitio: una aguja de 4,5 cm falla en cerca de 1/3 de los adultos porque la pared torácica excede esa longitud — usar catéter de al menos 7 cm cuando esté disponible. SITIO: el ATLS 2018 pasó a preferir el 4º/5º EIC en la línea axilar anterior; el 2º EIC medioclavicular sigue siendo válido y es la opción MÁS SEGURA A LA IZQUIERDA, por el riesgo de lesión cardíaca en el sitio lateral. En el obeso la pared es más gruesa en el sitio lateral — allí el 2º EIC puede alcanzar mejor. SI LA AGUJA NO ALCANZA — y lo sabrá porque no sale aire ni hay mejoría — NO repita en el mismo sitio con la misma aguja: o cambie por un catéter más largo, o vaya directo a la TORACOSTOMÍA DIGITAL (incisión en el 4º/5º EIC axilar anterior, divulsión roma y dedo en la pleura), que es definitiva para el alivio y no depende de la longitud de la aguja. Descomprimir es medida PUENTE en cualquier vía: el tratamiento es el drenaje torácico.",
};
