/**
 * Causas reversíveis — conduta inline na parada e ponteiros de conduta.
 *
 * ⚠️ DUAS ENTRADAS AQUI TINHAM O VALOR ES **METADE EM PORTUGUÊS** (2026-08-17):
 * quem gravou traduziu só a frase do PONTEIRO ("→ Vía aérea y parámetros…") e
 * deixou a conduta em português. A chave existia, `tr()` funcionava, e a tela
 * mostrava português com o app em espanhol.
 *
 * Nenhuma trava de dicionário pega isto — nenhuma sabe espanhol. Quem pegou foi
 * `e2e/tela-em-espanhol.spec.ts`, que lê a TELA.
 *
 * E a tradução correta já existia em `acls/locales/es-419/strings-generated.ts`
 * para a primeira frase de cada uma: o conserto foi compor as duas metades boas.
 */
export const ES_CAUSAS_PARADA: Record<string, string> = {
  "⚠️ GESTANTE OU PUÉRPERA COM CRISE — PENSE EM ECLÂMPSIA. O benzodiazepínico ABORTA a crise, como em qualquer outra; o SULFATO DE MAGNÉSIO é que TRATA A CAUSA e impede a próxima, e nenhum antiepiléptico o substitui. Detalhe e ponteiro do módulo no passo de estabilização.":
    "⚠️ EMBARAZADA O PUÉRPERA CON CRISIS — PIENSE EN ECLAMPSIA. La benzodiacepina ABORTA la crisis, como en cualquier otra; el SULFATO DE MAGNESIO es el que TRATA LA CAUSA e impide la próxima, y ningún antiepiléptico lo sustituye. Detalle y enlace al módulo en el paso de estabilización.",
  "⚠️ PUÉRPERA QUE CONVULSIONOU — PENSE EM ECLÂMPSIA AGORA QUE A CRISE PASSOU. É o cenário que mais escapa: a pessoa já não está grávida e ninguém pensa nisso, e a eclâmpsia pós-parto TARDIA está descrita além das 48 h, até semanas depois do parto. Vale para GESTANTE OU PUÉRPERA. O benzodiazepínico ABORTOU a crise; o SULFATO DE MAGNÉSIO é que TRATA A CAUSA e impede a próxima — medir a pressão e procurar proteinúria, cefaleia, escotomas e dor epigástrica antes de encerrar.":
    "⚠️ PUÉRPERA QUE CONVULSIONÓ — PIENSE EN ECLAMPSIA AHORA QUE LA CRISIS PASÓ. Es el escenario que más se escapa: la persona ya no está embarazada y nadie lo piensa, y la eclampsia posparto TARDÍA está descrita más allá de las 48 h, hasta semanas después del parto. Vale para EMBARAZADA O PUÉRPERA. La benzodiacepina ABORTÓ la crisis; el SULFATO DE MAGNESIO es el que TRATA LA CAUSA e impide la próxima — medir la presión y buscar proteinuria, cefalea, escotomas y dolor epigástrico antes de cerrar el caso.",
  "⚠️ SE NADA CEDEU, VOLTE ÀS DUAS CAUSAS EM QUE ESCALAR NÃO RESOLVE — isoniazida (piridoxina) e hiponatremia (salina hipertônica), detalhadas no passo da segunda linha. Crise que não cede a nada costuma ter causa que o antiepiléptico não trata.":
    "⚠️ SI NADA CEDIÓ, VUELVA A LAS DOS CAUSAS EN QUE ESCALAR NO RESUELVE — isoniazida (piridoxina) e hiponatremia (solución salina hipertónica), detalladas en el paso de la segunda línea. La crisis que no cede a nada suele tener una causa que el antiepiléptico no trata.",
  "Manter as metas da estabilização: PAS por faixa etária, SpO₂ ≥ 90%, normocapnia e cabeceira a 30°.":
    "Mantener las metas de la estabilización: PAS por franja de edad, SpO₂ ≥ 90%, normocapnia y cabecera a 30°.",
  "Anestésico local (LAST) → EMULSÃO LIPÍDICA 20% — o antídoto é único e não tem substituto; dose e sequência no passo próprio de LAST.":
    "Anestésico local (LAST) → EMULSIÓN LIPÍDICA 20% — el antídoto es único y no tiene sustituto; dosis y secuencia en el paso propio de LAST.",
  "Antídotos do coma: glicose 50% se hipoglicemia; tiamina 100 mg IV (etilista/desnutrido); naloxona se depressão respiratória com miose — ⚠️ a dose depende da PROCEDÊNCIA do opioide, e o regime está no passo da toxíndrome opioide. ⚠️ E A DURAÇÃO DECIDE A VIGILÂNCIA: a meia-vida da naloxona é MENOR que a da maioria dos opioides, a depressão respiratória PODE VOLTAR depois de o paciente já ter acordado, e vigiar por horas — não por minutos — faz parte da prescrição.":
    "Antídotos del coma: glucosa 50% si hay hipoglucemia; tiamina 100 mg IV (alcohólico/desnutrido); naloxona si hay depresión respiratoria con miosis — ⚠️ la dosis depende de la PROCEDENCIA del opioide, y el régimen está en el paso del toxíndrome opioide. ⚠️ Y LA DURACIÓN DECIDE LA VIGILANCIA: la vida media de la naloxona es MENOR que la de la mayoría de los opioides, la depresión respiratoria PUEDE VOLVER después de que el paciente ya despertó, y vigilar por horas — no por minutos — es parte de la prescripción.",
  "Benzodiazepínico → Flumazenil — o teto depende do cenário, o uso é EXCEPCIONAL, e a ressedação é regra; detalhe no passo da toxíndrome sedativo-hipnótica.":
    "Benzodiacepina → Flumazenil — el techo depende del escenario, el uso es EXCEPCIONAL y la resedación es la regla; detalle en el paso del toxíndrome sedante-hipnótico.",
  "Opioide → Naloxona: a dose depende da PROCEDÊNCIA do opioide, não da gravidade — regime completo no passo da toxíndrome opioide.":
    "Opioide → Naloxona: la dosis depende de la PROCEDENCIA del opioide, no de la gravedad — régimen completo en el paso del toxíndrome opioide.",
  "⚠️ SE A REVERSÃO FOR PARCIAL, pense em COINGESTÃO — a regra de que cada antídoto reverte uma classe só está no passo dos antídotos específicos.":
    "⚠️ SI LA REVERSIÓN ES PARCIAL, piense en COINGESTA — la regla de que cada antídoto revierte una sola clase está en el paso de los antídotos específicos.",
  "⚠️ SE O FLUMAZENIL NÃO REVERTER, pense em COINGESTÃO — a regra de que cada antídoto reverte uma classe só está no passo dos antídotos específicos.":
    "⚠️ SI EL FLUMAZENIL NO REVIERTE, piense en COINGESTA — la regla de que cada antídoto revierte una sola clase está en el paso de los antídotos específicos.",

  "Mesmas energias da FV. Se polimórfica (Torsades de Pointes):":
    "Mismas energías que la FV. Si es polimórfica (Torsades de Pointes):",
  "Nenhuma diluição salva. Configure abaixo e toque em \"+ Salvar atual\".":
    "Ninguna dilución guardada. Configure abajo y toque en \"+ Guardar actual\".",

  "Confirmar expansão torácica bilateral. Intubar se não resolvido. Causa mais comum em PCR pediátrica. → Via aérea e parâmetros em ISR e Ventilação Mecânica.":
    "Confirmar la expansión torácica bilateral. Intubar si no se resuelve. Causa más común en el paro pediátrico. → Vía aérea y parámetros en ISR y Ventilación Mecánica.",
  "SF 0,9% ou cristaloide em bolus. Em trauma: controle cirúrgico é prioritário — fluidos não substituem hemostasia. → Estratégia de reposição e controle de sangramento em Choque e Politrauma.":
    "SF 0,9% o cristaloide en bolo. En trauma: el control quirúrgico es prioritario — los líquidos no sustituyen la hemostasia. → Estrategia de reposición y control del sangrado en Choque y Politrauma.",
  "Tricíclicos: bicarbonato 1–2 mEq/kg. Opioides: naloxona 0,4–2 mg IV se o opioide for desconhecido — fentanil e análogos podem exigir mais de 2 mg ou infusão; se a equipe deu o opioide, titular 0,1–0,2 mg. A meia-vida da naloxona é MENOR que a da maioria dos opioides: a depressão respiratória PODE VOLTAR depois de o paciente já ter acordado — vigiar por horas. Organofosforados: atropina em altas doses. Intoxicação grave: considerar ECMO. → O antídoto é específico de cada agente, e listar alguns aqui criaria a mesma lista parcial que este módulo existe para evitar: abrir Intoxicações Exógenas.":
    "Tricíclicos: bicarbonato 1–2 mEq/kg. Opioides: naloxona 0,4–2 mg IV se o opioide for desconhecido — fentanil e análogos podem exigir mais de 2 mg ou infusão; se a equipe deu o opioide, titular 0,1–0,2 mg. A meia-vida da naloxona é MENOR que a da maioria dos opioides: a depressão respiratória PODE VOLTAR depois de o paciente já ter acordado — vigiar por horas. Organofosforados: atropina em altas doses. Intoxicação grave: considerar ECMO. → El antídoto es específico de cada agente, y listar algunos aquí crearía la misma lista parcial que este módulo existe para evitar: abrir Intoxicaciones Exógenas.",
  "Trombolítico durante RCP em ausência de laboratório de hemodinâmica (evidência limitada). Pós-ROSC: ECG urgente; se IAMCSST → hemodinâmica. → Critérios de reperfusão e tempos porta-balão no módulo Síndromes Coronarianas.":
    "Trombolítico durante RCP em ausência de laboratório de hemodinâmica (evidência limitada). Pós-ROSC: ECG urgente; se IAMCSST → hemodinâmica. → Criterios de reperfusión y tiempos puerta-balón en el módulo Síndromes Coronarios.",
  "TAMPONAMENTO CARDÍACO — pericardiocentese de emergência, de preferência GUIADA POR ULTRASSOM (subxifoide ou paraesternal, pela janela em que o derrame aparece maior e mais próximo). Sem ultrassom, via subxifoide às cegas, agulha em 45° apontada para o ombro esquerdo. Aspirar mesmo 20–50 mL já reverte a fisiologia — o objetivo é descomprimir, não drenar tudo. Se houver equipe cirúrgica, a toracotomia é definitiva; a punção é a ponte.":
    "TAPONAMIENTO CARDÍACO — pericardiocentesis de emergencia, preferentemente GUIADA POR ECOGRAFÍA (subxifoidea o paraesternal, por la ventana en que el derrame aparece mayor y más próximo). Sin ecografía, vía subxifoidea a ciegas, aguja a 45° apuntando al hombro izquierdo. Aspirar incluso 20–50 mL ya revierte la fisiología — el objetivo es descomprimir, no drenar todo. Si hay equipo quirúrgico, la toracotomía es definitiva; la punción es el puente.",
  "⚠️ TEP — SE FIBRINOLISAR, O COMPROMISSO É DE 60–90 MINUTOS DE RCP a partir da dose: o trombolítico precisa de tempo E de compressões para alcançar o trombo. Parar antes disso desperdiça a intervenção em vez de apenas arriscá-la. Decida sabendo o que a escolha custa em tempo de equipe. Critérios, dose e alternativas (embolectomia) no módulo TEP.":
    "⚠️ TEP — SI SE FIBRINOLIZA, EL COMPROMISO ES DE 60–90 MINUTOS DE RCP a partir de la dosis: el trombolítico necesita tiempo Y compresiones para alcanzar el trombo. Detenerse antes desperdicia la intervención en vez de solo arriesgarla. Decida sabiendo lo que la elección cuesta en tiempo de equipo. Criterios, dosis y alternativas (embolectomía) en el módulo TEP.",
  "PNEUMOTÓRAX HIPERTENSIVO — descompressão por agulha, e o COMPRIMENTO importa mais que o sítio: agulha de 4,5 cm falha em cerca de 1/3 dos adultos porque a parede torácica excede esse comprimento — usar cateter de pelo menos 7 cm quando disponível. SÍTIO: o ATLS 2018 passou a preferir o 4º/5º EIC na linha axilar anterior; o 2º EIC hemiclavicular segue válido e é a opção MAIS SEGURA À ESQUERDA, pelo risco de lesão cardíaca no sítio lateral. Em obeso, a parede é mais espessa no sítio lateral — ali o 2º EIC pode alcançar melhor. SE A AGULHA NÃO ALCANÇAR — e você saberá porque não sai ar nem há melhora — NÃO repita no mesmo sítio com a mesma agulha: ou troque por cateter mais longo, ou parta direto para a TORACOSTOMIA DIGITAL (incisão no 4º/5º EIC axilar anterior, divulsão romba e dedo na pleura), que é definitiva para o alívio e não depende de comprimento de agulha. Descomprimir é medida PONTE em qualquer via: o tratamento é o dreno torácico.":
    "NEUMOTÓRAX HIPERTENSIVO — descompresión con aguja, y la LONGITUD importa más que el sitio: una aguja de 4,5 cm falla en cerca de 1/3 de los adultos porque la pared torácica excede esa longitud — usar catéter de al menos 7 cm cuando esté disponible. SITIO: el ATLS 2018 pasó a preferir el 4º/5º EIC en la línea axilar anterior; el 2º EIC medioclavicular sigue siendo válido y es la opción MÁS SEGURA A LA IZQUIERDA, por el riesgo de lesión cardíaca en el sitio lateral. En el obeso la pared es más gruesa en el sitio lateral — allí el 2º EIC puede alcanzar mejor. SI LA AGUJA NO ALCANZA — y lo sabrá porque no sale aire ni hay mejoría — NO repita en el mismo sitio con la misma aguja: o cambie por un catéter más largo, o vaya directo a la TORACOSTOMÍA DIGITAL (incisión en el 4º/5º EIC axilar anterior, divulsión roma y dedo en la pleura), que es definitiva para el alivio y no depende de la longitud de la aguja. Descomprimir es medida PUENTE en cualquier vía: el tratamiento es el drenaje torácico.",
};
