/** ES — Choque: os pares que se confundem, o misto e o RUSH. */
export const choqueDiferencialEs: Record<string, string> = {
  "CHOQUE MISTO — mais de um mecanismo no mesmo paciente é COMUM: séptico que sangrou, cardiogênico que evoluiu com vasoplegia, politraumatizado com tamponamento, anafilaxia em quem já estava hipovolêmico. Este fluxo pede que você escolha UM caminho, e a escolha certa é o mecanismo DOMINANTE — o que está matando agora. Escolher um NÃO É NEGAR O OUTRO: trate o dominante pela via escolhida e o segundo em paralelo. O sinal de que há um segundo mecanismo é a resposta parcial — melhorou e parou de melhorar.":
    "CHOQUE MIXTO — más de un mecanismo en el mismo paciente es COMÚN: séptico que sangró, cardiogénico que evolucionó con vasoplejía, politraumatizado con taponamiento, anafilaxia en quien ya estaba hipovolémico. Este flujo pide que elija UN camino, y la elección correcta es el mecanismo DOMINANTE — el que está matando ahora. Elegir uno NO ES NEGAR EL OTRO: trate el dominante por la vía elegida y el segundo en paralelo. La señal de que hay un segundo mecanismo es la respuesta parcial — mejoró y dejó de mejorar.",
  "RUSH À BEIRA DO LEITO — é o exame que separa cardiogênico de obstrutivo em minutos, e são QUATRO janelas: (1) VCI — colabável sugere hipovolêmico ou distributivo; distendida e sem variação aponta obstrutivo ou cardiogênico. (2) PERICÁRDIO — derrame com colapso de câmaras direitas fecha TAMPONAMENTO, e aí volume é ponte até a drenagem. (3) VENTRÍCULO DIREITO — dilatado, maior que o esquerdo, com septo desviado, aponta TEP ou IAM de VD; nos dois, volume ajuda e diurético piora. (4) CONTRATILIDADE do ventrículo esquerdo — ruim, com linhas B difusas no pulmão, fecha CARDIOGÊNICO congesto, e aí volume afoga. ⚠️ A pergunta que o exame responde não é qual o diagnóstico — é ESTE PACIENTE ACEITA VOLUME?":
    "RUSH JUNTO A LA CAMA — es el examen que separa cardiogénico de obstructivo en minutos, y son CUATRO ventanas: (1) VCI — colapsable sugiere hipovolémico o distributivo; distendida y sin variación apunta a obstructivo o cardiogénico. (2) PERICARDIO — derrame con colapso de cavidades derechas cierra TAPONAMIENTO, y ahí el volumen es puente hasta el drenaje. (3) VENTRÍCULO DERECHO — dilatado, mayor que el izquierdo, con septo desviado, apunta a TEP o IAM de VD; en ambos el volumen ayuda y el diurético empeora. (4) CONTRACTILIDAD del ventrículo izquierdo — mala, con líneas B difusas en el pulmón, cierra CARDIOGÉNICO congestivo, y ahí el volumen ahoga. ⚠️ La pregunta que responde el examen no es cuál es el diagnóstico — es ¿ESTE PACIENTE ACEPTA VOLUMEN?",
  "⚠️ ANTES DE TRATAR COMO CARDIOGÊNICO, EXCLUA TAMPONAMENTO E TEP. Os três compartilham exatamente o que a beira do leito mostra — extremidades frias, jugular distendida, PVC alta e débito baixo —, e a CONDUTA É OPOSTA: no tamponamento e no TEP o volume é ponte de sobrevida; no cardiogênico congesto, afoga. Se o paciente PIORAR com diurético ou NÃO MELHORAR com inotrópico, o ramo estava errado: volte ao obstrutivo e faça o ultrassom.":
    "⚠️ ANTES DE TRATAR COMO CARDIOGÉNICO, DESCARTE TAPONAMIENTO Y TEP. Los tres comparten exactamente lo que muestra la cabecera — extremidades frías, yugular distendida, PVC alta y gasto bajo —, y la CONDUCTA ES OPUESTA: en el taponamiento y en el TEP el volumen es puente de supervivencia; en el cardiogénico congestivo, ahoga. Si el paciente EMPEORA con diurético o NO MEJORA con inotrópico, la rama estaba equivocada: vuelva al obstructivo y haga el ultrasonido.",
  "⚠️ DISTRIBUTIVO E HIPOVOLÊMICO ANDAM JUNTOS COM FREQUÊNCIA. O séptico perde volume por febre, taquipneia, vômito, diarreia e extravasamento capilar — e chega com os DOIS mecanismos. Tratar só a vasoplegia (vasopressor num paciente seco) ou só o volume (litros num paciente vasoplégico) deixa o paciente sem resposta, e o erro seguinte é concluir que o DIAGNÓSTICO está errado quando falta a outra metade.":
    "⚠️ EL DISTRIBUTIVO Y EL HIPOVOLÉMICO VAN JUNTOS CON FRECUENCIA. El séptico pierde volumen por fiebre, taquipnea, vómito, diarrea y extravasación capilar — y llega con los DOS mecanismos. Tratar solo la vasoplejía (vasopresor en un paciente seco) o solo el volumen (litros en un paciente vasopléjico) deja al paciente sin respuesta, y el error siguiente es concluir que el DIAGNÓSTICO está equivocado cuando falta la otra mitad.",
};
