/** ES — as três listas de contraindicação ao trombolítico. */
export const contraindicacaoTromboliseEs: Record<string, string> = {
  "🔒 COMUM ÀS TRÊS INDICAÇÕES — HEMORRAGIA INTRACRANIANA PRÉVIA, EM QUALQUER ÉPOCA. Não há janela: sangramento intracraniano prévio contraindica trombolítico no AVC, na síndrome coronariana e no TEP igualmente. Entram aqui a hemorragia subaracnóidea e as lesões estruturais que sangram — malformação arteriovenosa, aneurisma, neoplasia intracraniana.":
    "🔒 COMÚN A LAS TRES INDICACIONES — HEMORRAGIA INTRACRANEAL PREVIA, EN CUALQUIER ÉPOCA. No hay ventana: un sangrado intracraneal previo contraindica el trombolítico en el ACV, en el síndrome coronario y en el TEP por igual. Entran aquí la hemorragia subaracnoidea y las lesiones estructurales que sangran — malformación arteriovenosa, aneurisma, neoplasia intracraneal.",
  "🔒 COMUM ÀS TRÊS INDICAÇÕES — SANGRAMENTO ATIVO OU DIÁTESE HEMORRÁGICA (menstruação não conta). Sangramento em curso e distúrbio de coagulação contraindicam nas três indicações, sem janela de tempo. O que muda entre elas é o LABORATÓRIO que se exige antes — e isso está na lista de cada uma.":
    "🔒 COMÚN A LAS TRES INDICACIONES — SANGRADO ACTIVO O DIÁTESIS HEMORRÁGICA (la menstruación no cuenta). El sangrado en curso y el trastorno de coagulación contraindican en las tres indicaciones, sin ventana de tiempo. Lo que cambia entre ellas es el LABORATORIO que se exige antes — y eso está en la lista de cada una.",
  "CONTRAINDICAÇÕES AO ALTEPLASE NO AVC ISQUÊMICO — confira item a item, e o que você não conseguir excluir conta como presente. ABSOLUTAS: hemorragia intracraniana atual; hemorragia subaracnóidea; sangramento interno ativo; diátese hemorrágica; cirurgia intracraniana ou intraespinhal, OU traumatismo craniano grave, nos ÚLTIMOS 3 MESES; lesão intracraniana que aumente o risco de sangramento (neoplasia, malformação arteriovenosa, aneurisma); hipertensão grave não controlada. ADVERTÊNCIAS QUE PESAM COMO CONTRAINDICAÇÃO: plaquetas < 100.000/mm³; INR > 1,7; aPTT > 40 s; TP > 15 s; heparina de baixo peso nas últimas 24 h; anticoagulante oral direto, salvo laboratório específico normal ou mais de 48 h da última dose.":
    "CONTRAINDICACIONES AL ALTEPLASE EN EL ACV ISQUÉMICO — revise ítem por ítem, y lo que no logre excluir cuenta como presente. ABSOLUTAS: hemorragia intracraneal actual; hemorragia subaracnoidea; sangrado interno activo; diátesis hemorrágica; cirugía intracraneal o intraespinal, O traumatismo craneal grave, en los ÚLTIMOS 3 MESES; lesión intracraneal que aumente el riesgo de sangrado (neoplasia, malformación arteriovenosa, aneurisma); hipertensión grave no controlada. ADVERTENCIAS QUE PESAN COMO CONTRAINDICACIÓN: plaquetas < 100.000/mm³; INR > 1,7; aPTT > 40 s; TP > 15 s; heparina de bajo peso en las últimas 24 h; anticoagulante oral directo, salvo laboratorio específico normal o más de 48 h desde la última dosis.",
  "⚠️ E A PRESSÃO AQUI NÃO É CONTRAINDICAÇÃO — É ALVO. Diferente da síndrome coronariana e do TEP, onde a hipertensão grave é contraindicação relativa e permanece assim, no AVC isquêmico ela se TRATA: baixe para menos de 185/110 mmHg e trombolise. Confundir os dois transforma um paciente tratável num paciente excluído — e o módulo tem o passo do alvo pressórico logo adiante.":
    "⚠️ Y LA PRESIÓN AQUÍ NO ES CONTRAINDICACIÓN — ES META. A diferencia del síndrome coronario y del TEP, donde la hipertensión grave es contraindicación relativa y así permanece, en el ACV isquémico se TRATA: bájela a menos de 185/110 mmHg y trombolice. Confundir ambas convierte a un paciente tratable en un paciente excluido — y el módulo tiene el paso de la meta de presión más adelante.",
  "CONTRAINDICAÇÕES À FIBRINÓLISE NA SCA COM SUPRA — confira item a item. ABSOLUTAS: qualquer hemorragia intracerebral prévia; lesão vascular cerebral estrutural conhecida (malformação arteriovenosa); neoplasia intracraniana maligna conhecida, primária ou metastática; AVC ISQUÊMICO NOS ÚLTIMOS 3 MESES (com a exceção logo abaixo); suspeita de dissecção de aorta; sangramento ativo ou diátese hemorrágica (exceto menstruação); trauma craniano fechado ou facial significativo nos últimos 3 MESES; cirurgia intracraniana ou intraespinhal nos últimos 2 MESES. RELATIVAS: PAS > 180 ou PAD > 110 mmHg na apresentação; hipertensão crônica grave mal controlada; AVC isquêmico prévio há MAIS de 3 meses; demência; RCP traumática ou prolongada (> 10 min); cirurgia de grande porte há menos de 3 semanas; sangramento interno recente (2 a 4 semanas); punção vascular não compressível; gravidez; úlcera péptica ativa; uso de anticoagulante oral.":
    "CONTRAINDICACIONES A LA FIBRINÓLISIS EN EL SCA CON ELEVACIÓN — revise ítem por ítem. ABSOLUTAS: cualquier hemorragia intracerebral previa; lesión vascular cerebral estructural conocida (malformación arteriovenosa); neoplasia intracraneal maligna conocida, primaria o metastásica; ACV ISQUÉMICO EN LOS ÚLTIMOS 3 MESES (con la excepción de abajo); sospecha de disección de aorta; sangrado activo o diátesis hemorrágica (excepto menstruación); trauma craneal cerrado o facial significativo en los últimos 3 MESES; cirugía intracraneal o intraespinal en los últimos 2 MESES. RELATIVAS: PAS > 180 o PAD > 110 mmHg a la presentación; hipertensión crónica grave mal controlada; ACV isquémico previo hace MÁS de 3 meses; demencia; RCP traumática o prolongada (> 10 min); cirugía mayor hace menos de 3 semanas; sangrado interno reciente (2 a 4 semanas); punción vascular no compresible; embarazo; úlcera péptica activa; uso de anticoagulante oral.",
  "⚠️ A EXCEÇÃO QUE PARECE ERRO DE DIGITAÇÃO, E NÃO É: o AVC isquêmico nos últimos 3 meses contraindica a fibrinólise — EXCETO quando o AVC isquêmico é AGUDO, dentro de 4,5 h. A razão: nessa janela o trombolítico é o tratamento DAS DUAS coisas, e não uma droga que se dá apesar do AVC. Fora da janela de 4,5 h a exceção não vale, e o AVC recente volta a ser contraindicação absoluta. ⚠️ Isto é específico da SCA — não existe na lista do AVC nem na do TEP, e não faz sentido nelas.":
    "⚠️ LA EXCEPCIÓN QUE PARECE ERROR DE TIPEO, Y NO LO ES: el ACV isquémico en los últimos 3 meses contraindica la fibrinólisis — EXCEPTO cuando el ACV isquémico es AGUDO, dentro de 4,5 h. La razón: en esa ventana el trombolítico es el tratamiento DE LAS DOS cosas, y no una droga que se da a pesar del ACV. Fuera de la ventana de 4,5 h la excepción no vale, y el ACV reciente vuelve a ser contraindicación absoluta. ⚠️ Esto es específico del SCA — no existe en la lista del ACV ni en la del TEP, y no tiene sentido en ellas.",
  "CONTRAINDICAÇÕES À TROMBÓLISE NO TEP — confira item a item. ABSOLUTAS: doença intracraniana estrutural; hemorragia intracraniana; sangramento ativo; cirurgia cerebral ou de coluna recente; traumatismo craniano recente com fratura ou lesão encefálica; diátese hemorrágica; AVC isquêmico recente (a janela diverge entre as fontes — veja abaixo). RELATIVAS: PAS > 180 ou PAD > 110 mmHg; sangramento não intracraniano recente; cirurgia ou procedimento invasivo recente; AVC isquêmico há mais de 3 meses; anticoagulação em curso; RCP traumática; pericardite ou derrame pericárdico; retinopatia diabética; gravidez; idade > 65 anos; baixo peso corporal.":
    "CONTRAINDICACIONES A LA TROMBÓLISIS EN EL TEP — revise ítem por ítem. ABSOLUTAS: enfermedad intracraneal estructural; hemorragia intracraneal; sangrado activo; cirugía cerebral o de columna reciente; traumatismo craneal reciente con fractura o lesión encefálica; diátesis hemorrágica; ACV isquémico reciente (la ventana difiere entre las fuentes — vea abajo). RELATIVAS: PAS > 180 o PAD > 110 mmHg; sangrado no intracraneal reciente; cirugía o procedimiento invasivo reciente; ACV isquémico hace más de 3 meses; anticoagulación en curso; RCP traumática; pericarditis o derrame pericárdico; retinopatía diabética; embarazo; edad > 65 años; bajo peso corporal.",
  "⚠️ A JANELA DO AVC ISQUÊMICO RECENTE DIVERGE ENTRE AS FONTES, E ESTE APP NÃO ESCOLHE POR VOCÊ: o StatPearls (Thrombolytic Therapy) usa 3 MESES como contraindicação absoluta, e coloca o AVC de mais de 3 meses entre as relativas; o ESC 2019 de embolia pulmonar usa 6 MESES. Um paciente com AVC isquêmico há 4 meses é ABSOLUTAMENTE contraindicado por uma fonte e não pela outra. Decida pela referência que o seu serviço adota, registre qual usou — e, se houver tempo, discuta com quem vai assumir o paciente. ➜ Nas outras duas indicações deste app a janela é 3 meses, sem divergência.":
    "⚠️ LA VENTANA DEL ACV ISQUÉMICO RECIENTE DIFIERE ENTRE LAS FUENTES, Y ESTA APP NO ELIGE POR USTED: StatPearls (Thrombolytic Therapy) usa 3 MESES como contraindicación absoluta, y coloca el ACV de más de 3 meses entre las relativas; el ESC 2019 de embolia pulmonar usa 6 MESES. Un paciente con ACV isquémico hace 4 meses está ABSOLUTAMENTE contraindicado por una fuente y no por la otra. Decida por la referencia que su servicio adopta, registre cuál usó — y, si hay tiempo, discútalo con quien va a asumir al paciente. ➜ En las otras dos indicaciones de esta app la ventana es 3 meses, sin divergencia.",
  "⚠️ E O QUE FAZER COM O QUE VOCÊ NÃO CONSEGUIU EXCLUIR: item que você não consegue afastar conta como PRESENTE até que alguém o afaste — não como ausente porque ninguém perguntou. Isso não significa desistir da reperfusão: significa que o caminho passa a ser o alternativo (na SCA, transferir para angioplastia primária; no AVC, avaliar trombectomia; no TEP, embolectomia ou tratamento dirigido por cateter), e que a decisão precisa de quem vai assumir o paciente. Ligar para o serviço de referência AGORA custa minutos; trombolisar quem tinha contraindicação absoluta custa o desfecho.":
    "⚠️ Y QUÉ HACER CON LO QUE NO LOGRÓ EXCLUIR: el ítem que usted no puede descartar cuenta como PRESENTE hasta que alguien lo descarte — no como ausente porque nadie preguntó. Eso no significa renunciar a la reperfusión: significa que el camino pasa a ser el alternativo (en el SCA, trasladar para angioplastia primaria; en el ACV, evaluar trombectomía; en el TEP, embolectomía o tratamiento dirigido por catéter), y que la decisión necesita a quien va a asumir al paciente. Llamar al servicio de referencia AHORA cuesta minutos; trombolizar a quien tenía contraindicación absoluta cuesta el desenlace.",
  "Não sei dizer — abrir a lista":
    "No sé decir — abrir la lista",
  "Contraindicações ao alteplase — confira item a item":
    "Contraindicaciones al alteplase — revise ítem por ítem",
  "Contraindicações à fibrinólise — confira item a item":
    "Contraindicaciones a la fibrinólisis — revise ítem por ítem",
  "Contraindicações à trombólise — confira item a item":
    "Contraindicaciones a la trombólisis — revise ítem por ítem",
  "⏱ O RELÓGIO É QUEM ESCOLHE A REPERFUSÃO: ICP primária se o tempo porta-balão for ≤ 120 min (meta ≤ 90 min em centro com hemodinâmica). Acima disso, e com início ≤ 12 h, o caminho é FIBRINÓLISE — com meta de até 10 min entre o diagnóstico e a agulha. ⚠️ E O RELÓGIO CONTA DO PRIMEIRO CONTATO MÉDICO — não da chegada à sala de hemodinâmica nem da indicação do cateterismo. Contar do lugar errado ENCURTA O PRAZO PERCEBIDO e faz escolher ICP quando a fibrinólise já era a opção certa.":
    "⏱ EL RELOJ ES QUIEN ELIGE LA REPERFUSIÓN: ICP primaria si el tiempo puerta-balón es ≤ 120 min (meta ≤ 90 min en centro con hemodinámica). Por encima de eso, y con inicio ≤ 12 h, el camino es FIBRINÓLISIS — con meta de hasta 10 min entre el diagnóstico y la aguja. ⚠️ Y EL RELOJ CUENTA DESDE EL PRIMER CONTACTO MÉDICO — no desde la llegada a la sala de hemodinámica ni desde la indicación del cateterismo. Contar desde el lugar equivocado ACORTA EL PLAZO PERCIBIDO y hace elegir ICP cuando la fibrinólisis ya era la opción correcta.",
};
