/** ES — Convulsões: a gestante e a puérpera na tela, isoniazida/piridoxina, hiponatremia,
 *  e a janela pós-parto corrigida na Eclâmpsia. */
export const convulsoesGestanteEs: Record<string, string> = {
  "Manter MgSO₄ por 24 h após o parto ou após a última convulsão. ⚠️ AS 48 h NÃO SÃO O FIM DO RISCO — são a fronteira entre a eclâmpsia pós-parto PRECOCE e a TARDIA. A tardia existe e está descrita muito além disso: há relatos de até 23 dias e um caso com 8 semanas, e a pré-eclâmpsia pós-parto deve ser considerada em hipertensão de início novo entre 48 h e 6 semanas do parto. Convulsão em puérpera ALÉM das 48 h investiga trombose de seio venoso cerebral E CONTINUA investigando eclâmpsia tardia — as duas juntas, não uma no lugar da outra. É a puérpera que mais escapa, porque já não está grávida e ninguém pensa nisso.":
    "Mantener MgSO₄ durante 24 h después del parto o de la última convulsión. ⚠️ LAS 48 h NO SON EL FIN DEL RIESGO — son la frontera entre la eclampsia posparto PRECOZ y la TARDÍA. La tardía existe y está descrita mucho más allá: hay relatos de hasta 23 días y un caso con 8 semanas, y la preeclampsia posparto debe considerarse ante hipertensión de inicio nuevo entre 48 h y 6 semanas del parto. Una convulsión en puérpera MÁS ALLÁ de las 48 h investiga trombosis de seno venoso cerebral Y SIGUE investigando eclampsia tardía — las dos juntas, no una en lugar de la otra. Es la puérpera la que más se escapa, porque ya no está embarazada y nadie piensa en eso.",
  "⚠️ CRISE QUE NÃO CEDE A NADA — PERGUNTE POR ISONIAZIDA. Na intoxicação por isoniazida (tuberculostático; tentativa de autoextermínio ou erro de dose), a crise é REFRATÁRIA a benzodiazepínico e a antiepiléptico, porque o mecanismo é depleção de piridoxina — a isoniazida bloqueia a síntese de GABA, e nenhum anticonvulsivante repõe o que falta. O antídoto é PIRIDOXINA (vitamina B6) IV, grama por grama da dose ingerida; se a dose for desconhecida, 5 g. Sem ela, o paciente escala até o anestésico sem necessidade — e volta a convulsionar quando o anestésico sai.":
    "⚠️ CRISIS QUE NO CEDE A NADA — PREGUNTE POR ISONIAZIDA. En la intoxicación por isoniazida (tuberculostático; intento de autolesión o error de dosis), la crisis es REFRACTARIA a benzodiacepinas y a antiepilépticos, porque el mecanismo es depleción de piridoxina — la isoniazida bloquea la síntesis de GABA, y ningún anticonvulsivante repone lo que falta. El antídoto es PIRIDOXINA (vitamina B6) IV, gramo por gramo de la dosis ingerida; si la dosis es desconocida, 5 g. Sin ella, el paciente escala hasta el anestésico sin necesidad — y vuelve a convulsionar cuando el anestésico sale.",
  "⚠️ GESTANTE OU PUÉRPERA COM CRISE — PENSE EM ECLÂMPSIA, E NÃO PARE DE FAZER O QUE JÁ ESTÁ FAZENDO. A crise em curso se aborta com BENZODIAZEPÍNICO, como qualquer outra: isso não muda. O que MUDA é que falta um fármaco — o SULFATO DE MAGNÉSIO, que trata a eclâmpsia e previne a recorrência, e que nenhum antiepiléptico substitui. São dois papéis diferentes: o benzodiazepínico ABORTA a crise; o magnésio TRATA A CAUSA e impede a próxima. ⚠️ PUÉRPERA CONTA, e é a que mais escapa — a pessoa já não está grávida e ninguém pensa nisso; a eclâmpsia pós-parto TARDIA, além das 48 h, está descrita até semanas depois do parto. ⚠️ E ISTO NÃO FECHA DIAGNÓSTICO: gestante e puérpera convulsionam também por epilepsia prévia, hiponatremia, intoxicação, trombose venosa cerebral e AVC. O que este aviso obriga é a EXCLUIR eclâmpsia — medir a pressão, procurar proteinúria, edema, cefaleia, escotomas e dor epigástrica — e não a assumir que é ela. Tratar epiléptica grávida como eclâmptica é o erro inverso, e ele também existe.":
    "⚠️ EMBARAZADA O PUÉRPERA CON CRISIS — PIENSE EN ECLAMPSIA, Y NO DEJE DE HACER LO QUE YA ESTÁ HACIENDO. La crisis en curso se aborta con BENZODIACEPINA, como cualquier otra: eso no cambia. Lo que CAMBIA es que falta un fármaco — el SULFATO DE MAGNESIO, que trata la eclampsia y previene la recurrencia, y que ningún antiepiléptico sustituye. Son dos papeles distintos: la benzodiacepina ABORTA la crisis; el magnesio TRATA LA CAUSA e impide la próxima. ⚠️ LA PUÉRPERA CUENTA, y es la que más se escapa — la persona ya no está embarazada y nadie piensa en eso; la eclampsia posparto TARDÍA, más allá de las 48 h, está descrita hasta semanas después del parto. ⚠️ Y ESTO NO CIERRA EL DIAGNÓSTICO: embarazadas y puérperas también convulsionan por epilepsia previa, hiponatremia, intoxicación, trombosis venosa cerebral y ACV. Lo que este aviso obliga es a EXCLUIR eclampsia — medir la presión, buscar proteinuria, edema, cefalea, escotomas y dolor epigástrico — y no a asumir que es ella. Tratar a una epiléptica embarazada como eclámptica es el error inverso, y también existe.",
  "⚠️ O β-hCG NÃO É SÓ PARA REGISTRO: se for positivo — ou se a paciente pariu nas últimas semanas —, a eclâmpsia entra no diferencial e o sulfato de magnésio entra na conduta, ao lado do benzodiazepínico e não no lugar dele.":
    "⚠️ EL β-hCG NO ES SOLO PARA EL REGISTRO: si es positivo — o si la paciente dio a luz en las últimas semanas —, la eclampsia entra en el diferencial y el sulfato de magnesio entra en la conducta, junto a la benzodiacepina y no en su lugar.",
  "⚠️ SÓDIO BAIXO — A CRISE QUE O ANTIEPILÉPTICO NÃO RESOLVE. Na crise por hiponatremia, o que trata é o SÓDIO: salina hipertônica a 3% em bolus de resgate, repetida conforme a reavaliação. Anticonvulsivante sozinho não corrige o gradiente osmótico que está causando a crise, e insistir nele enquanto o sódio segue baixo é escalar em vão. Suspeitar sobretudo em uso de tiazídico, polidipsia, pós-operatório com soro hipotônico, SIADH e maratonista. ⚠️ A dose e o volume estão nas CORREÇÕES ELETROLÍTICAS, que os calculam — abra lá em vez de estimar, e reavalie o sódio em 1–2 h ou antes se houver piora.":
    "⚠️ SODIO BAJO — LA CRISIS QUE EL ANTIEPILÉPTICO NO RESUELVE. En la crisis por hiponatremia, lo que trata es el SODIO: solución salina hipertónica al 3% en bolo de rescate, repetida según la reevaluación. El anticonvulsivante por sí solo no corrige el gradiente osmótico que está causando la crisis, e insistir en él mientras el sodio sigue bajo es escalar en vano. Sospechar sobre todo en uso de tiazida, polidipsia, posoperatorio con suero hipotónico, SIADH y maratonista. ⚠️ La dosis y el volumen están en las CORRECCIONES ELECTROLÍTICAS, que los calculan — ábralas en vez de estimar, y reevalúe el sodio en 1–2 h o antes si hay empeoramiento.",
  "Gestante ou puérpera — o sulfato de magnésio não é substituível por antiepiléptico":
    "Embarazada o puérpera — el sulfato de magnesio no es sustituible por un antiepiléptico",
};
