/** ES — Coronárias: os quatro grupos sem supra, prazos com marco e apresentações. */
export const coronariasOclusaoEs: Record<string, string> = {
  "Preciso registrar as derivações extras (V7–V9 ou V3R–V4R)":
    "Necesito registrar las derivaciones extra (V7–V9 o V3R–V4R)",
  "Como registrar as derivações extras":
    "Cómo registrar las derivaciones extra",
  "V7–V9 quando houver suspeita de posterior; V3R–V4R em TODO infarto inferior. Registre e volte ao traçado.":
    "V7–V9 cuando haya sospecha de posterior; V3R–V4R en TODO infarto inferior. Registre y vuelva al trazado.",
  "WELLENS — O ÚNICO DESTA LISTA EM QUE O ERRO É FAZER ALGUMA COISA. ⚠️ NÃO É OCLUSÃO EM CURSO: é o padrão de REPERFUSÃO ESPONTÂNEA de uma estenose CRÍTICA da DA. Tipo A: T bifásica, positiva depois negativa (25% dos casos). Tipo B: T profunda e SIMETRICAMENTE invertida (75%). Em V2–V3, com R preservada, SEM ondas Q, e marcadores normais ou pouco elevados. O padrão aparece com o paciente SEM DOR — some ou se altera durante a dor.":
    "WELLENS — EL ÚNICO DE ESTA LISTA EN QUE EL ERROR ES HACER ALGO. ⚠️ NO ES OCLUSIÓN EN CURSO: es el patrón de REPERFUSIÓN ESPONTÁNEA de una estenosis CRÍTICA de la DA. Tipo A: T bifásica, positiva y luego negativa (25% de los casos). Tipo B: T profunda y SIMÉTRICAMENTE invertida (75%). En V2–V3, con R preservada, SIN ondas Q, y marcadores normales o poco elevados. El patrón aparece con el paciente SIN DOLOR — desaparece o se altera durante el dolor.",

  "Depois de varrer — o que você viu no traçado":
    "Después de barrer — qué vio en el trazado",
  "Achou algum destes padrões no ECG?":
    "¿Encontró alguno de estos patrones en el ECG?",
  "⚠️ RECONHECER UM DELES MUDA O DESTINO. De Winter, posterior isolado e T hiperaguda têm a mesma urgência do STEMI — não são \"sem supra\".":
    "⚠️ RECONOCER UNO DE ELLOS CAMBIA EL DESTINO. De Winter, posterior aislado y T hiperaguda tienen la misma urgencia del STEMI — no son \"sin elevación\".",
  "SIM — reconheci um dos padrões":
    "SÍ — reconocí uno de los patrones",
  "NÃO TENHO CERTEZA — o traçado é duvidoso":
    "NO ESTOY SEGURO — el trazado es dudoso",
  "NÃO — nenhum deles, o traçado é mesmo sem supra":
    "NO — ninguno de ellos, el trazado es realmente sin elevación",
  "Padrão de oclusão reconhecido — o relógio conta a partir de agora":
    "Patrón de oclusión reconocido — el reloj cuenta a partir de ahora",
  "A conduta passa a ser a do STEMI: reperfusão indicada, com a mesma urgência.":
    "La conducta pasa a ser la del STEMI: reperfusión indicada, con la misma urgencia.",
  "ACHOU UM DOS PADRÕES DE OCLUSÃO — a conduta passa a ser a do STEMI: reperfusão indicada, com a mesma urgência, e o relógio conta a partir de AGORA. ⚠️ DUAS RESSALVAS QUE MUDAM O QUE SE FAZ: no aVR com infra difusa a sala é urgente mas a FIBRINÓLISE ESTÁ FORA (é tronco ou multiarterial); e o WELLENS NÃO é oclusão em curso — nele o cateterismo é precoce e o erro clássico é mandar para teste ergométrico.":
    "ENCONTRÓ UNO DE LOS PATRONES DE OCLUSIÓN — la conducta pasa a ser la del STEMI: reperfusión indicada, con la misma urgencia, y el reloj cuenta a partir de AHORA. ⚠️ DOS SALVEDADES QUE CAMBIAN LO QUE SE HACE: en el aVR con infradesnivel difuso la sala es urgente pero la FIBRINÓLISIS QUEDA FUERA (es tronco o multiarterial); y el WELLENS NO es oclusión en curso — en él el cateterismo es precoz y el error clásico es mandar a prueba ergométrica.",
  "Traçado duvidoso — o seguinte é que resolve":
    "Trazado dudoso — el siguiente es el que resuelve",
  "Duvidar não impede repetir o ECG, colher troponina nem manter o paciente. Impede apenas liberar.":
    "Dudar no impide repetir el ECG, tomar troponina ni mantener al paciente. Impide solamente dar el alta.",
  "⚠️ NA DÚVIDA, O TRAÇADO SEGUINTE É QUE RESOLVE — e duvidar não impede nenhuma das três coisas: REPETIR o ECG e SERIAR, colher TROPONINA, e NÃO LIBERAR o paciente. Um ECG normal ou duvidoso em dor torácica ATIVA não encerra nada, e a T hiperaguda é justamente a fase em que o traçado seguinte pode já mostrar supra. ⚠️ ESTE APP NÃO FIXA O INTERVALO da repetição: as fontes abertas para este módulo tratam de reconhecimento, não de cadência. Use o intervalo do protocolo do seu serviço — e, na ausência dele, repita ANTES do que a sua vontade de fechar o caso sugerir. Manter monitorização contínua enquanto isso.":
    "⚠️ EN LA DUDA, EL TRAZADO SIGUIENTE ES EL QUE RESUELVE — y dudar no impide ninguna de las tres cosas: REPETIR el ECG y SERIAR, tomar TROPONINA, y NO DAR EL ALTA al paciente. Un ECG normal o dudoso en dolor torácico ACTIVO no cierra nada, y la T hiperaguda es justamente la fase en que el trazado siguiente puede ya mostrar elevación. ⚠️ ESTA APP NO FIJA EL INTERVALO de la repetición: las fuentes abiertas para este módulo tratan de reconocimiento, no de cadencia. Use el intervalo del protocolo de su servicio — y, en ausencia de él, repita ANTES de lo que su ganas de cerrar el caso sugiera. Mantener monitorización continua mientras tanto.",

  "COMO FAZER V3R–V4R: espelhe as precordiais para o lado direito do tórax — V4R vai no 5º espaço intercostal DIREITO, na linha hemiclavicular, e V3R entre V1 e V4R. CRITÉRIO: supra ≥ 1 mm em V3R–V6R fecha o diagnóstico (V4R isolada tem sensibilidade de 88% e especificidade de 78%); supra > 0,5 mm conta como achado de APOIO, mais sensível e menos específico. Na dúvida, com inferior + hipotensão, trate como VD.":
    "CÓMO HACER V3R–V4R: refleje las precordiales al lado derecho del tórax — V4R va en el 5.º espacio intercostal DERECHO, en la línea medioclavicular, y V3R entre V1 y V4R. CRITERIO: elevación ≥ 1 mm en V3R–V6R cierra el diagnóstico (V4R aislada tiene sensibilidad del 88% y especificidad del 78%); elevación > 0,5 mm cuenta como hallazgo de APOYO, más sensible y menos específico. Ante la duda, con inferior + hipotensión, trátelo como VD.",
  "COMO FAZER V7–V8–V9: todas no MESMO PLANO HORIZONTAL DE V6 — V7 na linha axilar posterior esquerda, V8 na ponta da escápula esquerda, V9 na região paravertebral esquerda. Basta reposicionar V4–V6 e registrar. ⚠️ O LIMIAR AQUI É OUTRO: supra de apenas 0,5 mm em V7–V9 já fecha infarto posterior. Aplicar o ≥ 1 mm das derivações padrão nestas derivações descarta o diagnóstico que se foi procurar.":
    "CÓMO HACER V7–V8–V9: todas en el MISMO PLANO HORIZONTAL DE V6 — V7 en la línea axilar posterior izquierda, V8 en la punta de la escápula izquierda, V9 en la región paravertebral izquierda. Basta reposicionar V4–V6 y registrar. ⚠️ EL UMBRAL AQUÍ ES OTRO: una elevación de solo 0,5 mm en V7–V9 ya cierra el infarto posterior. Aplicar el ≥ 1 mm de las derivaciones estándar en estas derivaciones descarta el diagnóstico que se fue a buscar.",
  "DE WINTER — OCLUSÃO AGUDA, sala agora. Infra de ST ASCENDENTE de 1–3 mm no ponto J em V1–V6, seguida de ondas T ALTAS, POSITIVAS E SIMÉTRICAS; pode haver supra de 1–2 mm em aVR. Indica oclusão PROXIMAL DA DA — aparece em cerca de 2% dos infartos anteriores extensos e tem valor preditivo positivo de 95–100% para oclusão. Não espere o padrão virar supra: ele pode não virar.":
    "DE WINTER — OCLUSIÓN AGUDA, sala ahora. Infradesnivel del ST ASCENDENTE de 1–3 mm en el punto J en V1–V6, seguido de ondas T ALTAS, POSITIVAS Y SIMÉTRICAS; puede haber elevación de 1–2 mm en aVR. Indica oclusión PROXIMAL DE LA DA — aparece en cerca del 2% de los infartos anteriores extensos y tiene valor predictivo positivo del 95–100% para oclusión. No espere que el patrón se convierta en elevación: puede no convertirse.",
  "INFARTO DE VD — procure em TODO infarto INFERIOR, sem exceção. Não é um diagnóstico diferente: é a EXTENSÃO do inferior para o ventrículo direito, e o que muda não é a reperfusão — é a farmacologia.":
    "INFARTO DE VD — búsquelo en TODO infarto INFERIOR, sin excepción. No es un diagnóstico distinto: es la EXTENSIÓN del inferior al ventrículo derecho, y lo que cambia no es la reperfusión — es la farmacología.",
  "POSTERIOR ISOLADO — OCLUSÃO AGUDA, e o mais traiçoeiro: na tela padrão parece isquemia subendocárdica. Suspeite quando V1–V3 mostrarem INFRA HORIZONTAL + onda R ALTA E LARGA (> 30 ms) + T POSITIVA, com R/S > 1 em V2. Confirme com as derivações posteriores.":
    "POSTERIOR AISLADO — OCLUSIÓN AGUDA, y el más traicionero: en el trazado estándar parece isquemia subendocárdica. Sospéchelo cuando V1–V3 muestren INFRADESNIVEL HORIZONTAL + onda R ALTA Y ANCHA (> 30 ms) + T POSITIVA, con R/S > 1 en V2. Confírmelo con las derivaciones posteriores.",
  "SUPRA EM aVR COM INFRA DIFUSA (≥ 6 derivações) — sugere lesão de TRONCO da coronária esquerda ou doença MULTIARTERIAL grave. ⚠️ NÃO É EQUIVALENTE DE STEMI e NÃO É INDICAÇÃO DE FIBRINÓLISE: o padrão de 2025 não o lista entre os equivalentes, e quem precisa de revascularização cirúrgica não se beneficia de trombolítico. A conduta é CATETERISMO URGENTE com discussão cirúrgica, não lise.":
    "ELEVACIÓN EN aVR CON INFRADESNIVEL DIFUSO (≥ 6 derivaciones) — sugiere lesión del TRONCO de la coronaria izquierda o enfermedad MULTIVASO grave. ⚠️ NO ES EQUIVALENTE DE STEMI y NO ES INDICACIÓN DE FIBRINÓLISIS: el estándar de 2025 no lo lista entre los equivalentes, y quien necesita revascularización quirúrgica no se beneficia de trombolítico. La conducta es CATETERISMO URGENTE con discusión quirúrgica, no lisis.",
  "T HIPERAGUDA — a fase MAIS PRECOCE da oclusão, e muitas vezes o ÚNICO achado. Não tem limiar em milímetros: o que a define é ser LARGA NA BASE, SIMÉTRICA e DESPROPORCIONAL ao QRS daquela derivação, agrupada no território de uma artéria. ⚠️ REPETIR O ECG É PARTE DA CONDUTA, não observação: o traçado seguinte pode já mostrar supra, e é por isso que um ECG normal em dor torácica ativa não encerra nada.":
    "T HIPERAGUDA — la fase MÁS PRECOZ de la oclusión, y muchas veces el ÚNICO hallazgo. No tiene umbral en milímetros: lo que la define es ser ANCHA EN LA BASE, SIMÉTRICA y DESPROPORCIONADA respecto al QRS de esa derivación, agrupada en el territorio de una arteria. ⚠️ REPETIR EL ECG ES PARTE DE LA CONDUCTA, no observación: el trazado siguiente puede mostrar ya elevación, y por eso un ECG normal con dolor torácico activo no cierra nada.",
  "WELLENS — ⚠️ NÃO É OCLUSÃO EM CURSO: é o padrão de REPERFUSÃO ESPONTÂNEA de uma estenose CRÍTICA da DA. Tipo A: T bifásica, positiva depois negativa (25% dos casos). Tipo B: T profunda e SIMETRICAMENTE invertida (75%). Em V2–V3, com R preservada, SEM ondas Q, e marcadores normais ou pouco elevados. O padrão aparece com o paciente SEM DOR — some ou se altera durante a dor.":
    "WELLENS — ⚠️ NO ES OCLUSIÓN EN CURSO: es el patrón de REPERFUSIÓN ESPONTÁNEA de una estenosis CRÍTICA de la DA. Tipo A: T bifásica, positiva y luego negativa (25% de los casos). Tipo B: T profunda y SIMÉTRICAMENTE invertida (75%). En V2–V3, con R preservada, SIN ondas Q, y marcadores normales o poco elevados. El patrón aparece con el paciente SIN DOLOR — desaparece o se altera durante el dolor.",
  "⚠️ AUSÊNCIA DE SUPRA NAS 12 DERIVAÇÕES PADRÃO NÃO EXCLUI OCLUSÃO. A própria diretriz de 2025 reconhece que o critério de supra na tela padrão PERDE uma minoria significativa de oclusões coronárias agudas. Os padrões abaixo são QUATRO GRUPOS COM QUATRO CONDUTAS — não são sinônimos de STEMI, e tratá-los como se fossem produz erro em direções opostas.":
    "⚠️ LA AUSENCIA DE ELEVACIÓN DEL ST EN LAS 12 DERIVACIONES ESTÁNDAR NO EXCLUYE OCLUSIÓN. La propia guía de 2025 reconoce que el criterio de elevación en el trazado estándar PIERDE una minoría significativa de oclusiones coronarias agudas. Los patrones siguientes son CUATRO GRUPOS CON CUATRO CONDUCTAS — no son sinónimos de STEMI, y tratarlos como si lo fueran produce error en direcciones opuestas.",
  "⚠️ VD CONFIRMADO OU SUSPEITO: NITRATO E MORFINA ESTÃO CONTRAINDICADOS. O ventrículo direito infartado é DEPENDENTE DE PRÉ-CARGA — qualquer agente que a reduza causa HIPOTENSÃO GRAVE, e o nitrato sublingual dado por reflexo na dor torácica é o mecanismo mais comum. Se houver hipotensão, a conduta é VOLUME, não vasodilatador nem vasopressor de largada.":
    "⚠️ VD CONFIRMADO O SOSPECHADO: EL NITRATO Y LA MORFINA ESTÁN CONTRAINDICADOS. El ventrículo derecho infartado es DEPENDIENTE DE PRECARGA — cualquier agente que la reduzca causa HIPOTENSIÓN GRAVE, y el nitrato sublingual dado por reflejo ante el dolor torácico es el mecanismo más común. Si hay hipotensión, la conducta es VOLUMEN, no vasodilatador ni vasopresor de entrada.",
  "Hipertensão grave na apresentação (> 180/110) que RESPONDE ao tratamento; AVC isquêmico há mais de 3 meses; demência; RCP prolongada (> 10 min) ou traumática; cirurgia de grande porte < 3 semanas; sangramento interno nas últimas 2–4 semanas; punção vascular não compressível; gestação; úlcera péptica ativa; anticoagulação oral em uso.":
    "Hipertensión grave en la presentación (> 180/110) que RESPONDE al tratamiento; ACV isquémico hace más de 3 meses; demencia; RCP prolongada (> 10 min) o traumática; cirugía mayor < 3 semanas; sangrado interno en las últimas 2–4 semanas; punción vascular no compresible; embarazo; úlcera péptica activa; anticoagulación oral en uso.",
  "Há contraindicação ABSOLUTA":
    "Hay contraindicación ABSOLUTA",
  "ICP primária é preferida quando o tempo porta-balão é ≤ 120 min (meta ≤ 90 min em centro com hemodinâmica). ⚠️ DE ONDE CONTA: o relógio começa no PRIMEIRO CONTATO MÉDICO — não na chegada ao hemodinâmica nem na indicação do cateterismo. Contar do lugar errado ENCURTA o prazo percebido e faz escolher ICP quando a fibrinólise já era a opção certa.":
    "La ICP primaria es preferida cuando el tiempo puerta-balón es ≤ 120 min (meta ≤ 90 min en centro con hemodinamia). ⚠️ DESDE DÓNDE SE CUENTA: el reloj empieza en el PRIMER CONTACTO MÉDICO — no en la llegada a hemodinamia ni en la indicación del cateterismo. Contar desde el lugar equivocado ACORTA el plazo percibido y hace elegir ICP cuando la fibrinólisis ya era la opción correcta.",
  "Sem contraindicação ABSOLUTA":
    "Sin contraindicación ABSOLUTA",
  "Sem supra de ST = SCA sem supra (NSTEMI ou angina instável) até definição pela troponina — ⚠️ MAS ANTES, descarte os padrões abaixo.":
    "Sin elevación del ST = SCA sin elevación (IAMSEST o angina inestable) hasta la definición por la troponina — ⚠️ PERO ANTES, descarte los patrones siguientes.",
  "── CONTRAINDICAÇÕES RELATIVAS — não proíbem, mudam a conta ──":
    "── CONTRAINDICACIONES RELATIVAS — no prohíben, cambian la cuenta ──",
  "⚠️ COM RELATIVA E SEM ABSOLUTA, A DECISÃO É DE RISCO-BENEFÍCIO, e o que pesa é o TEMPO ATÉ A ICP: se a transferência para hemodinâmica for viável dentro de 120 min do primeiro contato, prefira a ICP e evite a lise. Se NÃO for, um STEMI extenso nas primeiras horas costuma justificar a fibrinólise mesmo com relativa — o risco de não reperfundir é maior que o de sangrar. Discuta com a hemodinâmica, mas NÃO ADIE a decisão esperando resposta.":
    "⚠️ CON RELATIVA Y SIN ABSOLUTA, LA DECISIÓN ES DE RIESGO-BENEFICIO, y lo que pesa es el TIEMPO HASTA LA ICP: si el traslado a hemodinamia es viable dentro de 120 min del primer contacto, prefiera la ICP y evite la lisis. Si NO lo es, un STEMI extenso en las primeras horas suele justificar la fibrinólisis aun con relativa — el riesgo de no reperfundir es mayor que el de sangrar. Discuta con hemodinamia, pero NO DEMORE la decisión esperando respuesta.",
  "APRESENTAÇÃO — seringas PREENCHIDAS em degraus fixos: 20, 40, 60, 80 e 100 mg, todas a 100 mg/mL (ou seja, 60 mg = 0,6 mL). A dose por peso raramente cai num degrau exato: use a seringa graduada e DESPREZE o excedente, sem arredondar para o degrau de cima. ⚠️ Arredondar 68 mg para 80 mg é 18% de anticoagulante a mais em quem talvez já vá receber fibrinolítico e dupla antiagregação. Confira a graduação da seringa em uso antes de desprezar volume.":
    "PRESENTACIÓN — jeringas PRECARGADAS en escalones fijos: 20, 40, 60, 80 y 100 mg, todas a 100 mg/mL (es decir, 60 mg = 0,6 mL). La dosis por peso rara vez cae en un escalón exacto: use la jeringa graduada y DESECHE el excedente, sin redondear al escalón superior. ⚠️ Redondear 68 mg a 80 mg es un 18% más de anticoagulante en alguien que quizá reciba también fibrinolítico y doble antiagregación. Verifique la graduación de la jeringa en uso antes de desechar volumen.",
  "APRESENTAÇÃO E PREPARO — o TNK vem em PÓ LIOFILIZADO com diluente próprio (frasco de 50 mg = 10.000 U), e é reconstituído na hora. ⚠️ DUAS ESCALAS NO MESMO FRASCO: a dose se prescreve em MILIGRAMAS e o rótulo também traz UNIDADES — 1 mg = 200 U. Confundir as duas erra por um fator de 200, e o TNK é bolus ÚNICO: não há como corrigir depois. Confira no frasco o volume de reconstituição e o volume correspondente à dose calculada ANTES de aspirar, com um segundo profissional conferindo.":
    "PRESENTACIÓN Y PREPARACIÓN — el TNK viene en POLVO LIOFILIZADO con diluyente propio (frasco de 50 mg = 10.000 U), y se reconstituye en el momento. ⚠️ DOS ESCALAS EN EL MISMO FRASCO: la dosis se prescribe en MILIGRAMOS y la etiqueta también trae UNIDADES — 1 mg = 200 U. Confundirlas yerra por un factor de 200, y el TNK es bolo ÚNICO: no hay cómo corregir después. Verifique en el frasco el volumen de reconstitución y el volumen correspondiente a la dosis calculada ANTES de aspirar, con un segundo profesional verificando.",
  "⚠️ WELLENS: NUNCA TESTE ERGOMÉTRICO — E ESTA É A RAZÃO. O paciente está sem dor, com marcadores normais e um ECG que parece \"isquemia que já passou\": é exatamente essa APARÊNCIA DE ESTABILIDADE que faz alguém pedir o teste. Esses pacientes vão MAL com tratamento clínico e podem INFARTAR OU PARAR se estressados indevidamente — a DA crítica continua lá. A conduta é CATETERISMO PRECOCE, não estratificação não invasiva.":
    "⚠️ WELLENS: NUNCA PRUEBA ERGOMÉTRICA — Y ESTA ES LA RAZÓN. El paciente está sin dolor, con marcadores normales y un ECG que parece \"isquemia que ya pasó\": es exactamente el perfil que alguien enviaría a una prueba de esfuerzo. Pero la lesión crítica de la descendente anterior sigue ahí, y el esfuerzo puede ocluirla — infarto anterior extenso en la cinta. Wellens va a CORONARIOGRAFÍA, no a estratificación no invasiva.",
  "SOBRE \"OMI/NOMI\": há um enquadramento em consolidação que classifica por OCLUSÃO (occlusion MI × non-occlusion MI) em vez de por supra de ST, porque o supra na tela padrão perde oclusões — é a lógica dos padrões acima. A ACC/AHA 2025 MANTÉM STEMI/NSTEMI e incorpora só parte desse reconhecimento; as diretrizes australianas de 2025 adotaram a nomenclatura OMI. O app usa a nomenclatura corrente de propósito: é a que a equipe ao seu lado fala.":
    // ⚠️ D-81 RESOLVIDA (autor, 2026-08-23): o PORTUGUÊS vence. Ele informa que
    // o movimento OMI existe, NOMEIA quem adotou e DECLARA a escolha do app; o
    // espanhol apenas negava. Duas versões afirmando coisas diferentes sobre o
    // estado das diretrizes não era tradução — era conteúdo divergente.
    "SOBRE \"OMI/NOMI\": hay un encuadre en consolidación que clasifica por OCLUSIÓN (occlusion MI × non-occlusion MI) en lugar de por elevación del ST, porque la elevación en la pantalla pierde oclusiones — es la lógica de los patrones de arriba. La ACC/AHA 2025 MANTIENE STEMI/NSTEMI e incorpora solo parte de ese reconocimiento; las guías australianas de 2025 adoptaron la nomenclatura OMI. La app usa la nomenclatura corriente a propósito: es la que habla el equipo a su lado.",
};
