/** ES — EAP: o perfil quente × frio, o ramo misto e a saída de quem ainda não sabe o mecanismo. */
export const eapPerfilEs: Record<string, string> = {
  "AINDA NÃO SEI — POCUS/BNP pendentes":
    "AÚN NO SÉ — POCUS/BNP pendientes",
  "Ainda não sei o mecanismo — e dá para começar":
    "Aún no sé el mecanismo — y se puede empezar",
  "Edema misto — cardiogênico + lesão pulmonar":
    "Edema mixto — cardiogénico + lesión pulmonar",
  "MISTO — os dois mecanismos (sepse em cardiopata, pós-op, pneumonia em ICC)":
    "MIXTO — los dos mecanismos (sepsis en cardiópata, posoperatorio, neumonía en IC)",
  "O que muda desfecho na primeira meia hora é comum aos dois. O que espera o mecanismo é o que pode piorar quem está do outro lado.":
    "Lo que cambia el desenlace en la primera media hora es común a los dos. Lo que espera al mecanismo es lo que puede empeorar a quien está del otro lado.",
  "POCUS à beira do leito define a PROPORÇÃO — função de VE, linhas B, VCI — e é o que orienta quanto de cada tratamento.":
    "El POCUS a la cabecera define la PROPORCIÓN — función del VI, líneas B, VCI — y es lo que orienta cuánto de cada tratamiento.",
  "SUPORTE, comum aos dois: sentado, O₂, VNI com as contraindicações conferidas, monitor e acessos.":
    "SOPORTE, común a los dos: sentado, O₂, VNI con las contraindicaciones revisadas, monitor y accesos.",
  "Tratar o dominante NÃO é escolher um. Os dois erros são de omissão.":
    "Tratar el dominante NO es elegir uno. Los dos errores son de omisión.",
  "⚠️ E se houver hipotensão com hipoperfusão em qualquer um dos cenários, o caminho é o do choque cardiogênico — vasodilatador e diurético saem da mesa.":
    "⚠️ Y si hay hipotensión con hipoperfusión en cualquiera de los escenarios, el camino es el del choque cardiogénico — el vasodilatador y el diurético salen de la mesa.",
  "⚠️ Se houver sepse: antibiótico precoce e controle de foco NÃO esperam o ecocardiograma (ver módulo Sepse).":
    "⚠️ Si hay sepsis: el antibiótico precoz y el control del foco NO esperan al ecocardiograma (ver módulo Sepsis).",
  "EDEMA MISTO — CARDIOGÊNICO + LESÃO PULMONAR, e ele é comum: sepse em cardiopata, pneumonia em quem já tem fração de ejeção reduzida, pós-operatório cardíaco, transfusão maciça em disfunção diastólica. Suspeite quando os dois quadros se sobrepõem — infiltrado difuso COM cardiomegalia, BNP alto COM febre e foco infeccioso, ou congestão que não responde como deveria ao diurético. ⚠️ TRATAR O COMPONENTE DOMINANTE NÃO É ESCOLHER UM: escolher é o que este ramo existe para evitar, e os DOIS erros são de OMISSÃO. Quem rotula como SARA perde o vasodilatador e o diurético de uma congestão hidrostática REAL, e trata com restrição de volume um coração que precisa descongestionar. Quem rotula como cardiogênico restringe volume e diureiza um paciente que precisa de ANTIBIÓTICO PRECOCE e de RESSUSCITAÇÃO — e a sepse não espera a congestão melhorar. Conduza o dominante pela via dele e o segundo em paralelo: antibiótico e controle de foco não esperam o eco; ventilação protetora e vasodilatador não se anulam. ⚠️ O SINAL DE QUE HÁ DOIS MECANISMOS É A RESPOSTA PARCIAL — melhorou e parou de melhorar. E o que decide a proporção é o POCUS à beira do leito: função de VE, linhas B, VCI — não o rótulo escolhido na primeira tela.":
    "EDEMA MIXTO — CARDIOGÉNICO + LESIÓN PULMONAR, y es común: sepsis en cardiópata, neumonía en quien ya tiene fracción de eyección reducida, posoperatorio cardíaco, transfusión masiva en disfunción diastólica. Sospéchelo cuando los dos cuadros se superponen — infiltrado difuso CON cardiomegalia, BNP alto CON fiebre y foco infeccioso, o congestión que no responde como debería al diurético. ⚠️ TRATAR EL COMPONENTE DOMINANTE NO ES ELEGIR UNO: elegir es lo que este ramo existe para evitar, y los DOS errores son de OMISIÓN. Quien lo rotula como SDRA pierde el vasodilatador y el diurético de una congestión hidrostática REAL, y trata con restricción de volumen un corazón que necesita descongestionar. Quien lo rotula como cardiogénico restringe volumen y diureiza a un paciente que necesita ANTIBIÓTICO PRECOZ y REANIMACIÓN — y la sepsis no espera a que la congestión mejore. Conduzca el dominante por su vía y el segundo en paralelo: el antibiótico y el control del foco no esperan al eco; la ventilación protectora y el vasodilatador no se anulan. ⚠️ LA SEÑAL DE QUE HAY DOS MECANISMOS ES LA RESPUESTA PARCIAL — mejoró y dejó de mejorar. Y lo que decide la proporción es el POCUS a la cabecera: función del VI, líneas B, VCI — no la etiqueta elegida en la primera pantalla.",
  "NÃO PRECISA DEFINIR O MECANISMO PARA COMEÇAR — e boa parte do que muda desfecho na primeira meia hora é COMUM aos dois. FAÇA AGORA, vale para cardiogênico, SARA e misto: SENTAR o paciente (pernas pendentes, se não houver rebaixamento), O₂ para SpO₂ ≥ 94% (88–92% se DPOC), VNI se a saturação não subir — conferindo as contraindicações —, monitor, dois acessos, ECG de 12 derivações e gasometria. ⚠️ O QUE ESPERA O MECANISMO, e por isso não se faz no escuro: VASODILATADOR e DIURÉTICO (são do cardiogênico, e no SARA puro não tratam nada — o diurético em quem está hipovolêmico por sepse piora), e a RESTRIÇÃO DE VOLUME (que é o oposto do que a sepse precisa). O QUE DECIDE: ultrassom à beira do leito — função de VE, linhas B, VCI — e BNP/NT-proBNP. Nenhum dos dois demora, e os dois valem mais que o palpite. ⚠️ E REAVALIE: o mecanismo se declara em minutos a horas, e o rótulo da primeira tela não é sentença.":
    "NO HACE FALTA DEFINIR EL MECANISMO PARA EMPEZAR — y buena parte de lo que cambia el desenlace en la primera media hora es COMÚN a los dos. HAGA AHORA, vale para cardiogénico, SDRA y mixto: SENTAR al paciente (piernas colgando, si no hay deterioro de conciencia), O₂ para SpO₂ ≥ 94% (88–92% si EPOC), VNI si la saturación no sube — revisando las contraindicaciones —, monitor, dos accesos, ECG de 12 derivaciones y gasometría. ⚠️ LO QUE ESPERA AL MECANISMO, y por eso no se hace a ciegas: VASODILATADOR y DIURÉTICO (son del cardiogénico, y en el SDRA puro no tratan nada — el diurético en quien está hipovolémico por sepsis empeora), y la RESTRICCIÓN DE VOLUMEN (que es lo contrario de lo que la sepsis necesita). LO QUE DECIDE: ecografía a la cabecera — función del VI, líneas B, VCI — y BNP/NT-proBNP. Ninguno de los dos demora, y los dos valen más que la corazonada. ⚠️ Y REEVALÚE: el mecanismo se declara en minutos a horas, y la etiqueta de la primera pantalla no es sentencia.",
  "⚠️ ANTES DE VASODILATAR, DECIDA SE O PACIENTE ESTÁ QUENTE OU FRIO — e a PA NÃO responde isso. QUENTE-ÚMIDO (a maioria): congesto e bem perfundido — extremidades quentes, enchimento capilar normal, pressão de pulso ampla, lactato normal, diurese preservada, consciência clara. É o paciente do vasodilatador e do diurético. FRIO-ÚMIDO: congesto E mal perfundido — extremidades frias e pegajosas, enchimento capilar lento, PRESSÃO DE PULSO ESTREITA (< 25% da sistólica), sonolência, oligúria, lactato elevado, hiponatremia. Este precisa de INOTRÓPICO, e o vasodilatador o derruba. ⚠️ E O FRIO-ÚMIDO PODE TER PAS NORMAL — a pressão é débito × resistência, e a vasoconstrição sustenta o número enquanto o débito já caiu. Classificar só pela PA manda o frio de PAS 120 para o mesmo caminho do quente.":
    "⚠️ ANTES DE VASODILATAR, DECIDA SI EL PACIENTE ESTÁ CALIENTE O FRÍO — y la PA NO responde eso. CALIENTE-HÚMEDO (la mayoría): congestivo y bien perfundido — extremidades calientes, llenado capilar normal, presión de pulso amplia, lactato normal, diuresis conservada, conciencia clara. Es el paciente del vasodilatador y del diurético. FRÍO-HÚMEDO: congestivo Y mal perfundido — extremidades frías y pegajosas, llenado capilar lento, PRESIÓN DE PULSO ESTRECHA (< 25% de la sistólica), somnolencia, oliguria, lactato elevado, hiponatremia. Este necesita INOTRÓPICO, y el vasodilatador lo derrumba. ⚠️ Y EL FRÍO-HÚMEDO PUEDE TENER PAS NORMAL — la presión es gasto × resistencia, y la vasoconstricción sostiene el número mientras el gasto ya cayó. Clasificar solo por la PA manda al frío con PAS 120 por el mismo camino del caliente.",
  "⚠️ E SE O PERFIL ESTAVA ERRADO, O PACIENTE AVISA — reconheça o sinal em vez de insistir: se a PA CAIR com o vasodilatador, se a DIURESE NÃO VIER apesar do diurético, ou se as extremidades esfriarem e o lactato subir, o perfil era FRIO. Suspenda o vasodilatador, reduza ou pare o diurético e passe ao inotrópico — não aumente a dose do que não está funcionando. Débito baixo não responde a mais vasodilatação; responde a mais contração.":
    "⚠️ Y SI EL PERFIL ESTABA EQUIVOCADO, EL PACIENTE AVISA — reconozca la señal en vez de insistir: si la PA CAE con el vasodilatador, si la DIURESIS NO LLEGA pese al diurético, o si las extremidades se enfrían y el lactato sube, el perfil era FRÍO. Suspenda el vasodilatador, reduzca o detenga el diurético y pase al inotrópico — no aumente la dosis de lo que no está funcionando. El gasto bajo no responde a más vasodilatación; responde a más contracción.",
  "⚠️ NA DÚVIDA, ERRE PARA O LADO DO INOTRÓPICO — E O MOTIVO É A ASSIMETRIA. Vasodilatar quem está FRIO derruba o que já está baixo: a pressão cai, a perfusão coronariana piora, e o efeito é IMEDIATO, com o paciente ficando pior na sua frente em minutos. Inotrópico em quem está QUENTE-úmido é EXCESSO, não catástrofe: gasta droga, pode taquicardizar e aumentar consumo de oxigênio, e se corrige suspendendo. Os dois erros não têm o mesmo tamanho, e é por isso que a dúvida não se resolve no meio-termo — se você não consegue afirmar que o paciente está quente, trate-o como frio até provar o contrário.":
    "⚠️ ANTE LA DUDA, ERRE HACIA EL LADO DEL INOTRÓPICO — Y EL MOTIVO ES LA ASIMETRÍA. Vasodilatar a quien está FRÍO derrumba lo que ya está bajo: la presión cae, la perfusión coronaria empeora, y el efecto es INMEDIATO, con el paciente poniéndose peor delante de usted en minutos. El inotrópico en quien está CALIENTE-húmedo es EXCESO, no catástrofe: gasta droga, puede taquicardizar y aumentar el consumo de oxígeno, y se corrige suspendiéndolo. Los dos errores no tienen el mismo tamaño, y por eso la duda no se resuelve en el término medio — si usted no puede afirmar que el paciente está caliente, trátelo como frío hasta demostrar lo contrario.",
};
