/**
 * ES — limites de escore que mudaram de casa em 2026-08-27.
 *
 * ⚠️ ESTES SEIS TEXTOS PERDERAM O PONTEIRO "Abrir o módulo X" no português, e
 * a tradução acompanha: os módulos apontados foram removidos, e um app que
 * manda abrir o que não existe promete uma continuação e entrega um beco.
 * O corpo clínico é o mesmo de antes — só a instrução de navegação saiu.
 */
export const escoresLimitesMovidosEs: Record<string, string> = {
  "Rebaixamento neste nível exige AVALIAÇÃO imediata da via aérea — não intubação automática. A regra \"GCS ≤ 8 intuba\" erra justamente onde a causa é reversível em minutos: pós-ictal, hipoglicemia e intoxicação por opioide costumam recuperar a consciência com o tratamento específico, e o paciente acaba intubado por um número que já estava subindo. O que decide é a capacidade de proteger a via aérea, a trajetória (melhorando ou piorando) e a causa.":
    "El deterioro del nivel de conciencia en este rango exige EVALUACIÓN inmediata de la vía aérea — no intubación automática. La regla \"GCS ≤ 8 se intuba\" falla justamente donde la causa es reversible en minutos: pos-ictal, hipoglucemia e intoxicación por opioide suelen recuperar la consciencia con el tratamiento específico, y el paciente termina intubado por un número que ya estaba subiendo. Lo que decide es la capacidad de proteger la vía aérea, la trayectoria (mejorando o empeorando) y la causa.",
  "⚠️ O HEART estima risco de MACE e apoia a DISPOSIÇÃO — não indica coronariografia nem define o tempo dela. A estratégia invasiva e sua urgência dependem de supradesnivelamento de ST, instabilidade hemodinâmica ou elétrica, dor refratária e da estratificação pelo GRACE, que este escore não contém.":
    "⚠️ El HEART estima el riesgo de MACE y apoya la DISPOSICIÓN — no indica coronariografía ni define su tiempo. La estrategia invasiva y su urgencia dependen de elevación del ST, inestabilidad hemodinámica o eléctrica, dolor refractario y de la estratificación por GRACE, que este puntaje no contiene.",
  "⚠️ Antes de pedir a AngioTC: gestação, função renal e alergia a contraste mudam o exame, e o escore não pergunta nenhuma das três. Na gestante, começar por doppler venoso de membros inferiores (se positivo, trata sem irradiar) e, se negativo, discutir cintilografia de perfusão ou AngioTC com protocolo de dose reduzida. Na injúria renal ou na alergia ao contraste, a cintilografia V/Q é a alternativa.":
    "⚠️ Antes de pedir la AngioTC: embarazo, función renal y alergia al contraste cambian el examen, y el puntaje no pregunta ninguna de las tres. En la embarazada, comenzar por doppler venoso de miembros inferiores (si es positivo, se trata sin irradiar) y, si es negativo, discutir gammagrafía de perfusión o AngioTC con protocolo de dosis reducida. En la injuria renal o en la alergia al contraste, la gammagrafía V/Q es la alternativa.",
  "Esta faixa descreve a GRAVIDADE do déficit — não indica reperfusão. A decisão de trombolisar ou trombectomizar depende de o déficit ser INCAPACITANTE, da janela e das contraindicações, que esta tela não pergunta. Déficit incapacitante trombolisa mesmo com NIHSS baixo (afasia isolada, hemianopsia); NIHSS mais alto por déficits sensitivos difusos pode não ser incapacitante.":
    "Esta franja describe la GRAVEDAD del déficit — no indica reperfusión. La decisión de trombolizar o trombectomizar depende de que el déficit sea INCAPACITANTE, de la ventana y de las contraindicaciones, que esta pantalla no pregunta. Un déficit incapacitante se tromboliza incluso con NIHSS bajo (afasia aislada, hemianopsia); un NIHSS más alto por déficits sensitivos difusos puede no ser incapacitante.",
  "Agitação manda procurar CAUSA antes de sedar. Dor não tratada, delirium, hipóxia, hipoglicemia, retenção urinária, abstinência (álcool, benzodiazepínico, opioide, nicotina), tubo mal posicionado e VENTILAÇÃO ASSINCRÔNICA produzem agitação — e a assincronia se trata ajustando o ventilador, não subindo o sedativo. Sedar sem procurar mascara o problema que está causando a agitação, que é exatamente o erro que esta escala existe para prevenir. Analgesia primeiro.":
    "La agitación obliga a buscar la CAUSA antes de sedar. Dolor no tratado, delirium, hipoxia, hipoglucemia, retención urinaria, abstinencia (alcohol, benzodiacepina, opioide, nicotina), tubo mal posicionado y VENTILACIÓN ASINCRÓNICA producen agitación — y la asincronía se trata ajustando el ventilador, no subiendo el sedante. Sedar sin buscar enmascara el problema que está causando la agitación, que es exactamente el error que esta escala existe para prevenir. Analgesia primero.",
  "Mais profundo que a meta padrão de sedação leve (RASS −2 a 0, PADIS 2018). Existem indicações legítimas para descer — bloqueio neuromuscular, hipertensão intracraniana, SDRA grave, procedimento — e nesses casos a profundidade é o objetivo, não um desvio. Fora delas, sedação profunda associa-se a mais dias de ventilação, mais delirium e síndrome pós-terapia intensiva.":
    "Más profundo que la meta estándar de sedación ligera (RASS −2 a 0, PADIS 2018). Existen indicaciones legítimas para descender — bloqueo neuromuscular, hipertensión intracraneal, SDRA grave, procedimiento — y en esos casos la profundidad es el objetivo, no una desviación. Fuera de ellas, la sedación profunda se asocia a más días de ventilación, más delirium y síndrome pos-cuidados intensivos.",
  "Não desperta a estímulo físico. Pode ser sedação profunda, bloqueio neuromuscular em curso ou lesão neurológica — a escala não distingue os três. Sob bloqueio, RASS −5 é o alvo correto e não indica excesso de sedativo.":
    "No despierta al estímulo físico. Puede ser sedación profunda, bloqueo neuromuscular en curso o lesión neurológica — la escala no distingue los tres. Bajo bloqueo, RASS −5 es el objetivo correcto y no indica exceso de sedante.",
};
