/**
 * Limites dos escores — o que cada um NÃO decide (R-19).
 * Textos mudados de casa na deleção do sepsis-engine (D-22).
 */
export const ES_ESCORES_LIMITES: Record<string, string> = {
  "⚠️ A SSC 2026 NÃO recomenda o qSOFA como ferramenta ÚNICA de triagem: NEWS, MEWS e mesmo os critérios de SIRS têm sensibilidade maior para identificar quem vai deteriorar. O que mudou foi o PAPEL do escore, não o ponto de corte — o limiar ≥ 2 continua sendo o de Seymour 2016. Um qSOFA 0 ou 1 NÃO afasta sepse e não autoriza parar a investigação; qSOFA ≥ 2 identifica risco alto de desfecho adverso e obriga a avaliação completa.":
    "⚠️ La SSC 2026 NO recomienda el qSOFA como herramienta ÚNICA de cribado: NEWS, MEWS e incluso los criterios de SIRS tienen mayor sensibilidad para identificar a quien va a deteriorarse. Lo que cambió fue el PAPEL del escore, no el punto de corte — el umbral ≥ 2 sigue siendo el de Seymour 2016. Un qSOFA 0 o 1 NO descarta sepsis y no autoriza a detener la investigación; qSOFA ≥ 2 identifica alto riesgo de desenlace adverso y obliga a la evaluación completa.",
  "⚠️ O critério de UTI NÃO é o escore. O CURB-65 foi validado para decidir ambulatório × internação, e é isso que ele indica aqui — estima MORTALIDADE, não nível de cuidado, e tem desempenho fraco para prever necessidade de UTI. A terapia intensiva se decide pelos critérios MAIORES da ATS/IDSA (choque com necessidade de vasopressor OU insuficiência respiratória com ventilação mecânica) ou por ≥ 3 critérios MENORES. Um CURB-65 de 4 ou 5 pode vir só de idade, confusão, ureia e frequência respiratória, sem nenhum deles. Abrir o módulo Sepse para a estratificação de gravidade e a decisão de destino.":
    "⚠️ El criterio de UTI NO es el escore. El CURB-65 fue validado para decidir ambulatorio × internación, y es eso lo que indica aquí — estima MORTALIDAD, no nivel de cuidado, y tiene desempeño pobre para predecir necesidad de UCI. La terapia intensiva se decide por los criterios MAYORES de la ATS/IDSA (choque con necesidad de vasopresor O insuficiencia respiratoria con ventilación mecánica) o por ≥ 3 criterios MENORES. Un CURB-65 de 4 o 5 puede venir solo de edad, confusión, urea y frecuencia respiratoria, sin ninguno de ellos. Abrir el módulo Sepsis para la estratificación de gravedad y la decisión de destino.",
};
