/**
 * FRASES QUE O PROGRAMA MONTA — as chaves aqui são strings de RUNTIME.
 *
 * ⚠️ POR QUE ESTE ARQUIVO EXISTE SEPARADO DOS OUTROS 119. As chaves dos demais
 * módulos são literais: alguém as escreveu no fonte e elas viajam inteiras até a
 * tela. As 27 daqui NÃO EXISTEM EM NENHUM ARQUIVO — cada uma é o resultado de
 * uma concatenação, e só aparece depois de o programa rodar.
 *
 * Elas ficaram sete meses sem tradução com `npm run test:i18n` dizendo ZERO
 * pendências, porque a varredura lê o FONTE, onde há vários literais curtos e
 * cada um TEM a sua chave. Quem cobre isto é
 * `scripts/valida-traducao-runtime.cjs`, que lê o artefato COMPILADO. R-82.
 *
 * ── COMO ESTAS CHAVES FORAM ESCRITAS, e como escrever a próxima ─────────────
 *
 * NÃO foram digitadas. Foram COLETADAS do artefato compilado e emitidas por
 * `JSON.stringify`, porque redigitar 967 caracteres de português é o jeito mais
 * confiável de errar um travessão e produzir exatamente o defeito que este
 * arquivo conserta. Se precisar acrescentar uma, colete a string do runtime —
 * não a copie do fonte.
 *
 * ⚠️ E 11 DAS 27 NÃO FORAM TRADUZIDAS DE NOVO: elas COMEÇAM com uma chave que já
 * existia e já estava revisada. Nesses casos o espanhol reaproveita a tradução
 * antiga e traduz só o pedaço que cresceu — assim a frase não muda de vocabulário
 * no meio.
 *
 * ── A FRAGILIDADE, dita de frente ──────────────────────────────────────────
 *
 * Chave de frase composta é PERECÍVEL: qualquer acréscimo à concatenação a
 * invalida em silêncio. A saída melhor, quando houver oportunidade, é a constante
 * viajar INTEIRA (D-35) em vez de ser montada. Enquanto for montada, a trava de
 * runtime é o que impede a perda de virar invisível outra vez.
 */
export const ES_FRASES_MONTADAS: Record<string, string> = {
  "1 mg = UMA ampola inteira de adrenalina 1 mg/mL (1 mL) — sem diluir, seguida de flush de 20 mL e elevação do membro. É a apresentação nacional, e é a mesma ampola da anafilaxia: o que muda é a VIA e a dose (lá 0,5 mg IM). O \"1:10.000\" da literatura internacional é a mesma massa em 10 mL — não procure a ampola diluída, ela não é a padronizada aqui.":
    "1 mg = UNA ampolla entera de adrenalina 1 mg/mL (1 mL) — sin diluir, seguida de lavado de 20 mL y elevación del miembro. Es la presentación nacional, y es la misma ampolla de la anafilaxia: lo que cambia es la VÍA y la dosis (allí 0,5 mg IM). El “1:10.000” de la literatura internacional es la misma masa en 10 mL — no busque la ampolla diluida, no es la estandarizada aquí.",
  "HIPERVENTILAÇÃO DE 3ª LINHA — PaCO₂ 25–34 mmHg (protocolo institucional Einstein/SBIBAE, CPTW263.2) — e ela NÃO é a hiperventilação-ponte da herniação. ⚠️ DESCER ABAIXO DE PaCO₂ 30 SÓ COM MONITORIZAÇÃO ADICIONAL DE OXIGENAÇÃO CEREBRAL — saturação venosa jugular ou PtiO₂. Sem essa monitorização, o piso é 30 mmHg. O motivo do piso: a hiperventilação baixa a PIC por VASOCONSTRIÇÃO CEREBRAL, isto é, cortando fluxo — abaixo de 30 a queda de fluxo passa a produzir isquemia em tecido que já está em risco, e é por isso que não se desce \"só um pouco mais\" quando a PIC não cede. ⚠️ A LITERATURA ABERTA NÃO SUSTENTA ABAIXO DE 30 SEM MONITORIZAÇÃO: o consenso de hiperventilação no TCE adulto coloca a hiperventilação controlada como terapia de tier 2 com alvo 33–36 mmHg, dizendo \"avoid values <30 mmHg\" e \"should never decrease below PaCO2 values of 30 mmHg\". O 25–34 vem do protocolo institucional citado por este módulo, e vale COM a monitorização que ele mesmo exige.":
    "HIPERVENTILACIÓN DE 3ª LÍNEA — PaCO₂ 25–34 mmHg (protocolo institucional Einstein/SBIBAE, CPTW263.2) — y ella NO es la hiperventilación-puente de la herniación. ⚠️ BAJAR POR DEBAJO DE PaCO₂ 30 SOLO CON MONITORIZACIÓN ADICIONAL DE OXIGENACIÓN CEREBRAL — saturación venosa yugular o PtiO₂. Sin esa monitorización, el piso es 30 mmHg. El motivo del piso: la hiperventilación baja la PIC por VASOCONSTRICCIÓN CEREBRAL, es decir, cortando flujo — por debajo de 30 la caída de flujo pasa a producir isquemia en tejido que ya está en riesgo, y es por eso que no se baja “solo un poco más” cuando la PIC no cede. ⚠️ LA LITERATURA ABIERTA NO SUSTENTA POR DEBAJO DE 30 SIN MONITORIZACIÓN: el consenso de hiperventilación en el TCE del adulto ubica la hiperventilación controlada como terapia de tier 2 con objetivo 33–36 mmHg, diciendo “avoid values <30 mmHg” y “should never decrease below PaCO2 values of 30 mmHg”. El 25–34 viene del protocolo institucional citado por este módulo, y vale CON la monitorización que él mismo exige.",
  "HIPERCALEMIA — a sequência tem TRÊS tempos e o primeiro é o que salva: (1) ESTABILIZAR A MEMBRANA com cálcio, e os dois sais NÃO são intercambiáveis — cloreto de cálcio 10% 10 mL IV (preferido na parada, mais cálcio elementar e via central se houver) OU gluconato de cálcio 10% 30 mL IV; EQUIVALÊNCIA DOS SAIS: 1 g de cloreto de cálcio ≈ 3 g de gluconato de cálcio em cálcio elementar. Trocar um pelo outro em volume igual subdosa por três. (2) DESLOCAR o potássio para dentro da célula: insulina regular 10 U IV + glicose 25 g, mais bicarbonato de sódio se houver acidose. (3) REMOVER: diálise, que é a única que tira potássio do corpo — as duas primeiras só ganham tempo. Doses e ajustes completos no módulo Eletrólitos.":
    "HIPERCALEMIA — la secuencia tiene TRES tiempos y el primero es el que salva: (1) ESTABILIZAR LA MEMBRANA con calcio, y las dos sales NO son intercambiables — cloruro de calcio al 10% 10 mL IV (preferido en el paro, más calcio elemental y por vía central si la hay) O gluconato de calcio al 10% 30 mL IV; EQUIVALENCIA DE LAS SALES: 1 g de cloruro de calcio ≈ 3 g de gluconato de calcio en calcio elemental. Cambiar uno por otro en igual volumen subdosifica por tres. (2) DESPLAZAR el potasio hacia el interior de la célula: insulina regular 10 U IV + glucosa 25 g, más bicarbonato de sodio si hay acidosis. (3) REMOVER: diálisis, que es la única que saca potasio del cuerpo — las dos primeras solo ganan tiempo. Dosis y ajustes completos en el módulo Electrolitos.",
  "HIPERCALEMIA — a sequência tem TRÊS tempos e o primeiro é o que salva: (1) ESTABILIZAR A MEMBRANA com cálcio, e os dois sais NÃO são intercambiáveis — cloreto de cálcio 10% 10 mL IV (preferido na parada, mais cálcio elementar e via central se houver) OU gluconato de cálcio 10% 30 mL IV; EQUIVALÊNCIA DOS SAIS: 1 g de cloreto de cálcio ≈ 3 g de gluconato de cálcio em cálcio elementar. Trocar um pelo outro em volume igual subdosa por três. (2) DESLOCAR o potássio para dentro da célula: insulina regular 10 U IV + glicose 25 g, mais bicarbonato de sódio se houver acidose. (3) REMOVER: diálise, que é a única que tira potássio do corpo — as duas primeiras só ganham tempo. Doses e ajustes completos no módulo Eletrólitos. Gluconato de cálcio 10% 10 mL IV + insulina regular 10 U + glicose 50% 50 mL. Hipocalemia: reposição de KCl + magnésio.":
    "HIPERCALEMIA — la secuencia tiene TRES tiempos y el primero es el que salva: (1) ESTABILIZAR LA MEMBRANA con calcio, y las dos sales NO son intercambiables — cloruro de calcio al 10% 10 mL IV (preferido en el paro, más calcio elemental y por vía central si la hay) O gluconato de calcio al 10% 30 mL IV; EQUIVALENCIA DE LAS SALES: 1 g de cloruro de calcio ≈ 3 g de gluconato de calcio en calcio elemental. Cambiar uno por otro en igual volumen subdosifica por tres. (2) DESPLAZAR el potasio hacia el interior de la célula: insulina regular 10 U IV + glucosa 25 g, más bicarbonato de sodio si hay acidosis. (3) REMOVER: diálisis, que es la única que saca potasio del cuerpo — las dos primeras solo ganan tiempo. Dosis y ajustes completos en el módulo Electrolitos. Gluconato de calcio 10% 10 mL IV + insulina regular 10 U + glucosa 50% 50 mL. Hipocalemia: reposición de KCl + magnesio.",
  "\"Não está morto até estar quente e morto.\" Considerar ECMO para aquecimento em hipotermia grave. ABAIXO DE 30 °C não é só \"menos eficaz\" — muda a conduta: SUSPENDER as drogas IV (a adrenalina não age no miocárdio frio e ACUMULA, com toxicidade ao reaquecer) e LIMITAR a desfibrilação a até 3 choques, adiando novas tentativas até a temperatura passar de 30 °C. Manter a RCP sem interrupção enquanto aquece: a decisão de parar é pela temperatura, não pelo tempo. → Reaquecimento extracorpóreo (ECMO/CEC) tem o melhor desfecho na hipotermia grave com parada: acionar a equipe EM PARALELO à RCP, não depois dela.":
    "“No está muerto hasta estar caliente y muerto.” Considerar ECMO para calentamiento en hipotermia grave. POR DEBAJO DE 30 °C no es solo “menos eficaz” — cambia la conducta: SUSPENDER los fármacos IV (la adrenalina no actúa en el miocardio frío y ACUMULA, con toxicidad al recalentar) y LIMITAR la desfibrilación a hasta 3 choques, postergando nuevos intentos hasta que la temperatura pase de 30 °C. Mantener la RCP sin interrupción mientras se calienta: la decisión de detenerse es por la temperatura, no por el tiempo. → El recalentamiento extracorpóreo (ECMO/CEC) tiene el mejor desenlace en la hipotermia grave con paro: activar al equipo EN PARALELO a la RCP, no después de ella.",
  "PNEUMOTÓRAX HIPERTENSIVO — descompressão por agulha, e o COMPRIMENTO importa mais que o sítio: agulha de 4,5 cm falha em cerca de 1/3 dos adultos porque a parede torácica excede esse comprimento — usar cateter de pelo menos 7 cm quando disponível. SÍTIO: o ATLS 2018 passou a preferir o 4º/5º EIC na linha axilar anterior; o 2º EIC hemiclavicular segue válido e é a opção MAIS SEGURA À ESQUERDA, pelo risco de lesão cardíaca no sítio lateral. Em obeso, a parede é mais espessa no sítio lateral — ali o 2º EIC pode alcançar melhor. SE A AGULHA NÃO ALCANÇAR — e você saberá porque não sai ar nem há melhora — NÃO repita no mesmo sítio com a mesma agulha: ou troque por cateter mais longo, ou parta direto para a TORACOSTOMIA DIGITAL (incisão no 4º/5º EIC axilar anterior, divulsão romba e dedo na pleura), que é definitiva para o alívio e não depende de comprimento de agulha. Descomprimir é medida PONTE em qualquer via: o tratamento é o dreno torácico. Agulha 14G no 2º espaço intercostal, linha médio-clavicular. Seguida de drenagem torácica definitiva. Não aguardar RX.":
    "NEUMOTÓRAX HIPERTENSIVO — descompresión con aguja, y la LONGITUD importa más que el sitio: una aguja de 4,5 cm falla en cerca de 1/3 de los adultos porque la pared torácica excede esa longitud — usar catéter de al menos 7 cm cuando esté disponible. SITIO: el ATLS 2018 pasó a preferir el 4º/5º EIC en la línea axilar anterior; el 2º EIC medioclavicular sigue siendo válido y es la opción MÁS SEGURA A LA IZQUIERDA, por el riesgo de lesión cardíaca en el sitio lateral. En el obeso la pared es más gruesa en el sitio lateral — allí el 2º EIC puede alcanzar mejor. SI LA AGUJA NO ALCANZA — y lo sabrá porque no sale aire ni hay mejoría — NO repita en el mismo sitio con la misma aguja: o cambie por un catéter más largo, o vaya directo a la TORACOSTOMÍA DIGITAL (incisión en el 4º/5º EIC axilar anterior, divulsión roma y dedo en la pleura), que es definitiva para el alivio y no depende de la longitud de la aguja. Descomprimir es medida PUENTE en cualquier vía: el tratamiento es el drenaje torácico. Aguja 14G en el 2.º espacio intercostal, línea medioclavicular. Seguida de drenaje torácico definitivo. No esperar la radiografía.",
  "TAMPONAMENTO CARDÍACO — pericardiocentese de emergência, de preferência GUIADA POR ULTRASSOM (subxifoide ou paraesternal, pela janela em que o derrame aparece maior e mais próximo). Sem ultrassom, via subxifoide às cegas, agulha em 45° apontada para o ombro esquerdo. Aspirar mesmo 20–50 mL já reverte a fisiologia — o objetivo é descomprimir, não drenar tudo. Se houver equipe cirúrgica, a toracotomia é definitiva; a punção é a ponte. Pericardiocentese: agulha no ângulo xifoesternal, 45°, aspirar sangue. US-guiada se possível. Em trauma penetrante: toracotomia de ressuscitação.":
    "TAPONAMIENTO CARDÍACO — pericardiocentesis de emergencia, preferentemente GUIADA POR ECOGRAFÍA (subxifoidea o paraesternal, por la ventana en que el derrame aparece mayor y más próximo). Sin ecografía, vía subxifoidea a ciegas, aguja a 45° apuntando al hombro izquierdo. Aspirar incluso 20–50 mL ya revierte la fisiología — el objetivo es descomprimir, no drenar todo. Si hay equipo quirúrgico, la toracotomía es definitiva; la punción es el puente. Pericardiocentesis: aguja en el ángulo xifoesternal, 45°, aspirar sangre. Guiada por ecografía si es posible. En trauma penetrante: toracotomía de reanimación.",
  "⚠️ TEP — SE FIBRINOLISAR, O COMPROMISSO É DE 60–90 MINUTOS DE RCP a partir da dose: o trombolítico precisa de tempo E de compressões para alcançar o trombo. Parar antes disso desperdiça a intervenção em vez de apenas arriscá-la. Decida sabendo o que a escolha custa em tempo de equipe. Critérios, dose e alternativas (embolectomia) no módulo TEP. Fibrinólise é razoável na PCR por TEP confirmado, e pode ser considerada quando o TEP é apenas suspeito. A AHA 2025 não fixa esquema. SEM protocolo institucional, o mais usado e mais descrito é alteplase 50 mg IV em BÓLUS durante a RCP, repetindo 50 mg em 15–20 min se a parada persistir (ERC e séries publicadas — não é dose chancelada pela AHA; registre a fonte). MANTER RCP por 60–90 min após a dose antes de considerar encerrar. Considerar ECMO.":
    "⚠️ TEP — SI SE FIBRINOLIZA, EL COMPROMISO ES DE 60–90 MINUTOS DE RCP a partir de la dosis: el trombolítico necesita tiempo Y compresiones para alcanzar el trombo. Detenerse antes desperdicia la intervención en vez de solo arriesgarla. Decida sabiendo lo que la elección cuesta en tiempo de equipo. Criterios, dosis y alternativas (embolectomía) en el módulo TEP. La fibrinólisis es razonable en el paro por TEP confirmado, y puede considerarse cuando el TEP es solo sospechado. La AHA 2025 no fija un esquema. SIN protocolo institucional, el más usado y más descrito es alteplasa 50 mg IV en BOLO durante la RCP, repitiendo 50 mg en 15–20 min si el paro persiste (ERC y series publicadas — no es una dosis avalada por la AHA; registre la fuente). MANTENER la RCP por 60–90 min después de la dosis antes de considerar finalizar. Considerar ECMO.",
  "⚠️ QUANDO ABREVIAR — A DECISÃO É INTRAOPERATÓRIA, e não espera o paciente parar de responder: quem aguarda o \"não respondeu\" já passou do ponto. Os sinais somam e valem MAIS JUNTOS do que isoladamente: hipotermia (< 35 °C, e a temperatura cai rápido com abdome aberto), acidose que não corrige (pH < 7,2 ou lactato subindo apesar da reanimação), coagulopatia CLÍNICA — sangramento difuso em superfície cruenta e nas punções, que aparece antes de qualquer exame voltar —, transfusão acumulada em volume alto, e tempo de sala se estendendo sem hemostasia. Diante deles: controlar sangramento e contaminação, empacotar, fechar temporariamente e levar à UTI para corrigir a fisiologia. A reoperação programada é o plano, não a falha.":
    "⚠️ CUÁNDO ABREVIAR — LA DECISIÓN ES INTRAOPERATORIA, y no espera a que el paciente deje de responder: quien aguarda el “no respondió” ya pasó del punto. Los signos suman y valen MÁS JUNTOS que aisladamente: hipotermia (< 35 °C, y la temperatura cae rápido con el abdomen abierto), acidosis que no corrige (pH < 7,2 o lactato en ascenso a pesar de la reanimación), coagulopatía CLÍNICA — sangrado difuso en superficie cruenta y en las punciones, que aparece antes de que vuelva cualquier examen —, transfusión acumulada en volumen alto, y tiempo de sala que se extiende sin hemostasia. Ante ellos: controlar el sangrado y la contaminación, empaquetar, cerrar temporalmente y llevar a la UCI para corregir la fisiología. La reoperación programada es el plan, no la falla.",
  "4,5–9 h POR TEMPO, OU AO ACORDAR ATÉ 9 h DO PONTO MÉDIO DO SONO — critério de PERFUSÃO (EXTEND): core isquêmico < 70 mL, razão de mismatch > 1,2 e penumbra > 10 mL. ⚠️ AQUI A TC DE PERFUSÃO SERVE — o ensaio aceitou RM ou TC (\"MR-DWI or CT-CBF\"), e é este o caminho de quem não tem ressonância disponível.":
    "4,5–9 h POR TIEMPO, O AL DESPERTAR HASTA 9 h DEL PUNTO MEDIO DEL SUEÑO — criterio de PERFUSIÓN (EXTEND): core isquémico < 70 mL, razón de mismatch > 1,2 y penumbra > 10 mL. ⚠️ AQUÍ LA TC DE PERFUSIÓN SIRVE — el ensayo aceptó RM o TC (“MR-DWI or CT-CBF”), y este es el camino de quien no tiene resonancia disponible.",
  "O diagnóstico é CLÍNICO — não aguardar exames. Preencha UM dos três critérios WAO 2020. ⚠️ NA DÚVIDA, TRATE COMO ANAFILAXIA E DÊ ADRENALINA IM. Os critérios existem para reconhecer, não para adiar. O custo de dar sem precisar EXISTE — taquicardia, palpitação, e no coronariopata idoso pode ser isquemia — e é aceitável, porque não há contraindicação absoluta à adrenalina na anafilaxia. O custo de não dar quando precisava é a PARADA, e o atraso da primeira dose é o fator mais consistentemente associado à morte.":
    "El diagnóstico es CLÍNICO — no esperar exámenes. Cumpla UNO de los tres criterios WAO 2020. ⚠️ ANTE LA DUDA, TRATE COMO ANAFILAXIA Y DÉ ADRENALINA IM. Los criterios existen para reconocer, no para postergar. El costo de darla sin necesidad EXISTE — taquicardia, palpitaciones, y en el coronariópata anciano puede ser isquemia — y es aceptable, porque no hay contraindicación absoluta a la adrenalina en la anafilaxia. El costo de no darla cuando hacía falta es el PARO, y el retraso de la primera dosis es el factor más consistentemente asociado a la muerte.",
  "Qualquer progressão sistêmica exige adrenalina IM imediata — não aguardar piora completa. PROGRESSÃO SISTÊMICA É O SURGIMENTO DE QUALQUER UM DESTES: hipotensão, broncoespasmo, estridor, síncope, disfagia, ansiedade intensa, vômitos repetidos ou taquicardia persistente não explicada. ⚠️ NA DÚVIDA SOBRE A RESPOSTA, TRATE COMO PIORA — repita a adrenalina IM e reavalie em 5 min. A anafilaxia bifásica melhora ANTES de voltar, e \"parece que melhorou\" é a leitura que precede a recaída. Repetir a dose tem custo conhecido e pequeno; considerar melhora quem está progredindo perde a janela em que a IM ainda resolve sozinha.":
    "Cualquier progresión sistémica exige adrenalina IM inmediata — no aguardar el empeoramiento completo. PROGRESIÓN SISTÉMICA ES LA APARICIÓN DE CUALQUIERA DE ESTOS: hipotensión, broncoespasmo, estridor, síncope, disfagia, ansiedad intensa, vómitos repetidos o taquicardia persistente no explicada. ⚠️ ANTE LA DUDA SOBRE LA RESPUESTA, TRATE COMO EMPEORAMIENTO — repita la adrenalina IM y reevalúe en 5 min. La anafilaxia bifásica mejora ANTES de volver, y “parece que mejoró” es la lectura que precede la recaída. Repetir la dosis tiene un costo conocido y pequeño; considerar mejoría a quien está progresando pierde la ventana en que la IM todavía resuelve sola.",
  "Reavaliar via aérea, respiração, circulação e consciência para decidir o próximo pacote de suporte. ⚠️ NA DÚVIDA SOBRE A RESPOSTA, TRATE COMO PIORA — repita a adrenalina IM e reavalie em 5 min. A anafilaxia bifásica melhora ANTES de voltar, e \"parece que melhorou\" é a leitura que precede a recaída. Repetir a dose tem custo conhecido e pequeno; considerar melhora quem está progredindo perde a janela em que a IM ainda resolve sozinha.":
    "Reevaluar vía aérea, respiración, circulación y conciencia para decidir el siguiente paquete de soporte. ⚠️ ANTE LA DUDA SOBRE LA RESPUESTA, TRATE COMO EMPEORAMIENTO — repita la adrenalina IM y reevalúe en 5 min. La anafilaxia bifásica mejora ANTES de volver, y “parece que mejoró” es la lectura que precede la recaída. Repetir la dosis tiene un costo conocido y pequeño; considerar mejoría a quien está progresando pierde la ventana en que la IM todavía resuelve sola.",
  "Reavaliar PA, SpO₂, esforço respiratório e nível de consciência. ⚠️ SINTOMAS QUE PERSISTEM SEM PIORAR PEDEM A SEGUNDA DOSE IM — e não se escala antes de administrá-la. ⚠️ NA DÚVIDA SOBRE A RESPOSTA, TRATE COMO PIORA — repita a adrenalina IM e reavalie em 5 min. A anafilaxia bifásica melhora ANTES de voltar, e \"parece que melhorou\" é a leitura que precede a recaída. Repetir a dose tem custo conhecido e pequeno; considerar melhora quem está progredindo perde a janela em que a IM ainda resolve sozinha.":
    "Reevaluar PA, SpO₂, esfuerzo respiratorio y nivel de conciencia. ⚠️ LOS SÍNTOMAS QUE PERSISTEN SIN EMPEORAR PIDEN LA SEGUNDA DOSIS IM — y no se escala antes de administrarla. ⚠️ ANTE LA DUDA SOBRE LA RESPUESTA, TRATE COMO EMPEORAMIENTO — repita la adrenalina IM y reevalúe en 5 min. La anafilaxia bifásica mejora ANTES de volver, y “parece que mejoró” es la lectura que precede la recaída. Repetir la dosis tiene un costo conocido y pequeño; considerar mejoría a quien está progresando pierde la ventana en que la IM todavía resuelve sola.",
  "Falha após 2 doses IM + fluidos = indicação de adrenalina IV contínua e UTI. ⚠️ NA DÚVIDA SOBRE A RESPOSTA, TRATE COMO PIORA — repita a adrenalina IM e reavalie em 5 min. A anafilaxia bifásica melhora ANTES de voltar, e \"parece que melhorou\" é a leitura que precede a recaída. Repetir a dose tem custo conhecido e pequeno; considerar melhora quem está progredindo perde a janela em que a IM ainda resolve sozinha.":
    "Falla tras 2 dosis IM + líquidos = indicación de adrenalina IV continua y UCI. ⚠️ ANTE LA DUDA SOBRE LA RESPUESTA, TRATE COMO EMPEORAMIENTO — repita la adrenalina IM y reevalúe en 5 min. La anafilaxia bifásica mejora ANTES de volver, y “parece que mejoró” es la lectura que precede la recaída. Repetir la dosis tiene un costo conocido y pequeño; considerar mejoría a quien está progresando pierde la ventana en que la IM todavía resuelve sola.",
  "EAP REFRATÁRIO OU EXAUSTÃO RESPIRATÓRIA PEDEM VIA AÉREA DEFINITIVA e cuidado intensivo. ⚠️ RESPOSTA PARCIAL É RESPOSTA INADEQUADA. Na dúvida, trate como REFRATÁRIO e escale. Diurese abaixo de 0,5 mL/kg/h após a furosemida já é resposta inadequada por critério — e o paciente que \"melhorou um pouco\" e parou de melhorar é exatamente o que chega exausto à intubação.":
    "EL EAP REFRACTARIO O EL AGOTAMIENTO RESPIRATORIO PIDEN VÍA AÉREA DEFINITIVA y cuidado intensivo. ⚠️ RESPUESTA PARCIAL ES RESPUESTA INADECUADA. Ante la duda, trate como REFRACTARIO y escale. Diuresis por debajo de 0,5 mL/kg/h después de la furosemida ya es respuesta inadecuada por criterio — y el paciente que “mejoró un poco” y dejó de mejorar es exactamente el que llega exhausto a la intubación.",
  "PEEP: titular por gravidade — leve 5–8 · moderada 8–13 · grave 13–18 cmH₂O. A tabela PEEP/FiO₂ do ARDSNet está no módulo de Ventilação Mecânica (passo \"Tabela PEEP/FiO₂\"), com os valores deste app ao lado.":
    "PEEP: titular por gravedad — leve 5–8 · moderada 8–13 · grave 13–18 cmH₂O. La tabla PEEP/FiO₂ del ARDSNet está en el módulo de Ventilación Mecánica (paso “Tabla PEEP/FiO₂”), con los valores de esta app al lado.",
  "Isto arma o relógio da VIGILÂNCIA — a tríade de segurança a cada 20 min na 1ª hora e depois de hora em hora, por 24 h. Se o ataque acabou de ser feito aqui, marque \"agora\".":
    "Esto activa el reloj de la VIGILANCIA — la tríada de seguridad cada 20 min en la 1ª hora y luego cada hora, por 24 h. Si la dosis de ataque acaba de administrarse aquí, marque “ahora”.",
  "PROCURE O SANGUE nos cinco locais: tórax, abdome, pelve/retroperitônio, ossos longos e externo — \"no chão e mais 4\". FAST e radiografias de tórax e pelve à beira do leito.":
    "BUSQUE LA SANGRE en los cinco sitios: tórax, abdomen, pelvis/retroperitoneo, huesos largos y externo — “en el piso y 4 más”. FAST y radiografías de tórax y pelvis a la cabecera.",
  "Sinais de herniação: cabeceira 30°, normocapnia (PaCO₂ 35–40 mmHg), salina hipertônica/manitol.":
    "Signos de herniación: cabecera 30°, normocapnia (PaCO₂ 35–40 mmHg), solución salina hipertónica/manitol.",
  "2ª linha — VASOPRESSINA — 0,03 U/min, DOSE FIXA: não se titula. Ela poupa catecolamina, e a lógica é ADICIONAR à noradrenalina em vez de escalar a noradrenalina sozinha. No VASST a infusão ia de 0,01 até o máximo de 0,03 U/min — acima disso não é a estratégia estudada.":
    "2ª línea — VASOPRESINA — 0,03 U/min, DOSIS FIJA: no se titula. Ahorra catecolaminas, y la lógica es AGREGAR a la noradrenalina en vez de escalar la noradrenalina sola. En el VASST la infusión iba de 0,01 hasta el máximo de 0,03 U/min — por encima de eso no es la estrategia estudiada.",
  "3ª linha — ADRENALINA em infusão contínua — iniciar em 0,05 mcg/kg/min e titular pela PAM; a faixa de referência no choque vai de 0,01 a 2 mcg/kg/min. Abaixo de ~0,05 o efeito é predominantemente INOTRÓPICO; acima, vasopressor.":
    "3ª línea — ADRENALINA en infusión continua — iniciar en 0,05 mcg/kg/min y titular por la PAM; el rango de referencia en el choque va de 0,01 a 2 mcg/kg/min. Por debajo de ~0,05 el efecto es predominantemente INOTRÓPICO; por encima, vasopresor.",
  "⚠️ RESPONDER \"NÃO\" AQUI FECHA ESTA PORTA: o fluxo segue para o cardiogênico, que compartilha com o obstrutivo o frio, a jugular distendida e o débito baixo — e tem conduta OPOSTA quanto a volume. Na dúvida, faça o ultrassom ANTES de responder.":
    "⚠️ RESPONDER “NO” AQUÍ CIERRA ESTA PUERTA: el flujo sigue hacia el cardiogénico, que comparte con el obstructivo el frío, la yugular distendida y el gasto bajo — y tiene conducta OPUESTA en cuanto a volumen. Ante la duda, haga la ecografía ANTES de responder.",
  "⚠️ o app adota degrau conservador em relação à tabela ARDSNet; PEEP acima disso requer titulação individualizada e monitorização hemodinâmica.":
    "⚠️ la app adopta un escalón conservador en relación con la tabla ARDSNet; PEEP por encima de eso requiere titulación individualizada y monitorización hemodinámica.",
  "Fonte: ARDSNet (ARMA). N Engl J Med. 2000;342:1301–1308 — tabela low-PEEP/high-FiO₂, braço de controle do ensaio.":
    "Fuente: ARDSNet (ARMA). N Engl J Med. 2000;342:1301–1308 — tabla low-PEEP/high-FiO₂, brazo de control del ensayo.",
  "Alvos: SpO₂ ≥ 90%, PaCO₂ 35–40 mmHg (NORMOventilação), PPC 60–70 mmHg, PIC < 22 mmHg.":
    "Metas: SpO₂ ≥ 90%, PaCO₂ 35–40 mmHg (NORMOventilación), PPC 60–70 mmHg, PIC < 22 mmHg.",
  "Cabeceira 30°; PEEP 5–10 cmH₂O — até 15 cmH₂O SOMENTE em paciente estável, euvolêmico e com neuromonitorização — condição que raramente existe na emergência; sem isso, o alvo é 5–10.":
    "Cabecera 30°; PEEP 5–10 cmH₂O — hasta 15 cmH₂O SOLO en paciente estable, euvolémico y con neuromonitorización — condición que raramente existe en la emergencia; sin eso, la meta es 5–10.",
};
