/** ES — Intoxicações: LAST e emulsão lipídica (D-29), os dois tetos do flumazenil,
 *  o agente desconhecido e a saída de não tratar. Fecha também a dívida herdada
 *  de texto composto de poisoning, rsi e anaphylaxis (D-35). */
export const intoxicacoesLastEs: Record<string, string> = {
  "⚠️ CADA ANTÍDOTO REVERTE UMA CLASSE SÓ. Naloxona age no receptor opioide e NÃO reverte benzodiazepínico, álcool, barbitúrico ou outro depressor central. Flumazenil age no receptor do benzodiazepínico e NÃO reverte opioide, barbitúrico nem álcool. CONSEQUÊNCIA PRÁTICA, que é onde o raciocínio erra: em intoxicação mista, \"não respondeu ao antídoto\" significa PROCURAR A OUTRA SUBSTÂNCIA — não escalar a dose do antídoto que já falhou. Uma reversão parcial é a assinatura da coingestão. E cuidado com a direção oposta: anular o benzodiazepínico numa mista pode DESMASCARAR a toxicidade do outro fármaco, com convulsão ou arritmia, sobretudo com antidepressivo cíclico.":
    "⚠️ CADA ANTÍDOTO REVIERTE UNA SOLA CLASE. La naloxona actúa en el receptor opioide y NO revierte benzodiacepina, alcohol, barbitúrico u otro depresor central. El flumazenil actúa en el receptor de la benzodiacepina y NO revierte opioide, barbitúrico ni alcohol. CONSECUENCIA PRÁCTICA, que es donde el razonamiento falla: en la intoxicación mixta, \"no respondió al antídoto\" significa BUSCAR LA OTRA SUSTANCIA — no escalar la dosis del antídoto que ya falló. Una reversión parcial es la firma de la coingesta. Y cuidado con la dirección opuesta: anular la benzodiacepina en una mixta puede DESENMASCARAR la toxicidad del otro fármaco, con convulsión o arritmia, sobre todo con antidepresivo cíclico.",
  "Etiologias: LSD, MDMA, quetamina, mescalina, psilocibina (cogumelos).":
    "Etiologías: LSD, MDMA, ketamina, mescalina, psilocibina (hongos).",
  "RECONHECER LAST — toxicidade sistêmica por anestésico local. O quadro clássico começa pelo SISTEMA NERVOSO: gosto metálico, zumbido, dormência perioral, agitação ou confusão, e depois convulsão; a toxicidade cardiovascular costuma vir DEPOIS da neurológica, com bradicardia, bloqueio, arritmia ventricular, hipotensão e assistolia. ⚠️ MAS NÃO CONTE COM O CLÁSSICO: cerca de 40% dos casos publicados tiveram apresentação ATÍPICA, e o colapso cardiovascular pode ser a primeira manifestação. Em toda deterioração súbita de paciente que recebeu anestésico local — bloqueio, infiltração, peridural, tumescente, tópico em mucosa —, LAST entra no diferencial ANTES de qualquer outra coisa.":
    "RECONOCER LAST — toxicidad sistémica por anestésico local. El cuadro clásico empieza por el SISTEMA NERVIOSO: sabor metálico, zumbido, adormecimiento perioral, agitación o confusión, y luego convulsión; la toxicidad cardiovascular suele venir DESPUÉS de la neurológica, con bradicardia, bloqueo, arritmia ventricular, hipotensión y asistolia. ⚠️ PERO NO CUENTE CON EL CLÁSICO: cerca del 40% de los casos publicados tuvieron presentación ATÍPICA, y el colapso cardiovascular puede ser la primera manifestación. En todo deterioro súbito de un paciente que recibió anestésico local — bloqueo, infiltración, peridural, tumescente, tópico en mucosa —, el LAST entra en el diferencial ANTES que cualquier otra cosa.",
  "⚠️ NÃO É SÓ DURANTE A INJEÇÃO. O quadro costuma começar logo após a injeção, mas o LAST \"lento\" — por dose alta, absorção excessiva, metabolismo reduzido ou menor ligação proteica — PODE APARECER ATÉ 30 MINUTOS DEPOIS, e há apresentações descritas DIAS após a injeção. O atraso é a regra em quem está com INFUSÃO CONTÍNUA de anestésico local (cateter perineural, peridural contínua, lidocaína IV para analgesia): quase todos os casos de início tardio de uma revisão recente estavam nesse cenário, por acúmulo de dose e por migração de cateter. CONSEQUÊNCIA PRÁTICA: o paciente cujo bloqueio \"deu certo\" não está fora de risco, e a monitorização não termina quando o bloqueio pega.":
    "⚠️ NO ES SOLO DURANTE LA INYECCIÓN. El cuadro suele empezar justo después de la inyección, pero el LAST \"lento\" — por dosis alta, absorción excesiva, metabolismo reducido o menor unión proteica — PUEDE APARECER HASTA 30 MINUTOS DESPUÉS, y hay presentaciones descritas DÍAS después de la inyección. El retraso es la regla en quien está con INFUSIÓN CONTINUA de anestésico local (catéter perineural, peridural continua, lidocaína IV para analgesia): casi todos los casos de inicio tardío de una revisión reciente estaban en ese escenario, por acumulación de dosis y por migración del catéter. CONSECUENCIA PRÁCTICA: el paciente cuyo bloqueo \"salió bien\" no está fuera de riesgo, y la monitorización no termina cuando el bloqueo prende.",
  "CHAME AJUDA E, NO MESMO MOMENTO, ACIONE A EQUIPE DE CIRCULAÇÃO EXTRACORPÓREA. Não é exagero nem etapa final: a ASRA moveu o aviso à equipe de CEC para o alto do checklist, junto com o pedido de ajuda, exatamente porque montar circulação extracorpórea leva tempo que não existe depois que o colapso se instalou. Acionar cedo e cancelar é barato; descobrir tarde que era necessário não tem conserto. Pegue o kit de LAST e a emulsão lipídica enquanto isso.":
    "PIDA AYUDA Y, EN EL MISMO MOMENTO, ACTIVE AL EQUIPO DE CIRCULACIÓN EXTRACORPÓREA. No es exageración ni etapa final: la ASRA movió el aviso al equipo de CEC a la parte alta del checklist, junto con el pedido de ayuda, precisamente porque montar la circulación extracorpórea lleva un tiempo que no existe una vez instalado el colapso. Activar temprano y cancelar es barato; descubrir tarde que era necesario no tiene arreglo. Traiga el kit de LAST y la emulsión lipídica mientras tanto.",
  "EMULSÃO LIPÍDICA 20% — APRESENTAÇÃO: frasco de 500 mL (também há 100 e 250 mL). A dose se prescreve em MILILITROS, direto do frasco, sem diluir. QUANDO: ao PRIMEIRO SINAL de evento grave de LAST — não se espera a parada. ACIMA DE 70 kg (dose FIXA, sem calcular): bolus de 100 mL em 2–3 min, seguido de infusão de 200–250 mL em 15–20 min. ABAIXO DE 70 kg (por peso): bolus de 1,5 mL/kg em 2–3 min, seguido de 0,25 mL/kg/min. SE NÃO ESTABILIZAR: repetir o bolus OU dobrar a infusão. DEPOIS DE ESTABILIZAR: manter a infusão por cerca de 10 minutos. TETO: 12 mL/kg como limite superior — com a ressalva da própria ASRA de que doses menores são a norma. ⚠️ Volume e velocidade exatos NÃO são cruciais — a ASRA simplificou o esquema justamente para que ninguém perca tempo calculando. Em ressuscitação prolongada, o volume total pode se aproximar de 1 LITRO: tenha mais de um frasco à mão.":
    "EMULSIÓN LIPÍDICA 20% — PRESENTACIÓN: frasco de 500 mL (también hay de 100 y 250 mL). La dosis se prescribe en MILILITROS, directo del frasco, sin diluir. CUÁNDO: ante el PRIMER SIGNO de un evento grave de LAST — no se espera al paro. POR ENCIMA DE 70 kg (dosis FIJA, sin calcular): bolo de 100 mL en 2–3 min, seguido de infusión de 200–250 mL en 15–20 min. POR DEBAJO DE 70 kg (por peso): bolo de 1,5 mL/kg en 2–3 min, seguido de 0,25 mL/kg/min. SI NO ESTABILIZA: repetir el bolo O duplicar la infusión. DESPUÉS DE ESTABILIZAR: mantener la infusión unos 10 minutos. TECHO: 12 mL/kg como límite superior — con la salvedad de la propia ASRA de que las dosis menores son la norma. ⚠️ El volumen y la velocidad exactos NO son cruciales — la ASRA simplificó el esquema justamente para que nadie pierda tiempo calculando. En reanimación prolongada, el volumen total puede acercarse a 1 LITRO: tenga más de un frasco a mano.",
  "⚠️ PROPOFOL NÃO É EMULSÃO LIPÍDICA TERAPÊUTICA — e a confusão é previsível, porque ele é branco, tem veículo lipídico e costuma estar na sala quando o frasco de emulsão a 20% não está. NÃO SERVE, por duas razões INDEPENDENTES. (1) O conteúdo lipídico do propofol é baixo demais para produzir o efeito: para chegar perto da dose de lipídio necessária seria preciso infundir uma quantidade de propofol que é, ela própria, uma superdose — num paciente que já está em colapso cardiovascular. (2) O propofol é cardiodepressor, e o seu uso é desaconselhado quando há risco de progressão para colapso — que é exatamente a situação. ⚠️ ESTA RAZÃO É DIFERENTE DA DE EVITÁ-LO NA CONVULSÃO: lá o problema é a instabilidade hemodinâmica que ele agrava; aqui é que ele NÃO TRATA. Não confunda as duas — não use propofol como sucedâneo, em nenhuma dose.":
    "⚠️ EL PROPOFOL NO ES EMULSIÓN LIPÍDICA TERAPÉUTICA — y la confusión es previsible, porque es blanco, tiene vehículo lipídico y suele estar en la sala cuando el frasco de emulsión al 20% no está. NO SIRVE, por dos razones INDEPENDIENTES. (1) El contenido lipídico del propofol es demasiado bajo para producir el efecto: para acercarse a la dosis de lípido necesaria habría que infundir una cantidad de propofol que es, en sí misma, una sobredosis — en un paciente que ya está en colapso cardiovascular. (2) El propofol es cardiodepresor, y su uso se desaconseja cuando hay riesgo de progresión al colapso — que es exactamente la situación. ⚠️ ESTA RAZÓN ES DISTINTA DE LA DE EVITARLO EN LA CONVULSIÓN: allí el problema es la inestabilidad hemodinámica que agrava; aquí es que NO TRATA. No confunda las dos — no use propofol como sucedáneo, en ninguna dosis.",
  "⚠️ A RESSUSCITAÇÃO NO LAST É DIFERENTE DO ACLS PADRÃO — a ASRA destaca isso no topo do checklist, com as modificações de dose. Além da emulsão lipídica, mudam a dose da adrenalina e a lista de fármacos a evitar. Se a parada por LAST for conduzida como ACLS de rotina, o tratamento que funciona não é dado e alguns dos que se daria pioram o quadro. E a RCP pode ser LONGA: mantenha, porque a recuperação depois de ressuscitação prolongada com emulsão está descrita.":
    "⚠️ LA REANIMACIÓN EN EL LAST ES DIFERENTE DEL ACLS ESTÁNDAR — la ASRA lo destaca en la parte alta del checklist, con las modificaciones de dosis. Además de la emulsión lipídica, cambian la dosis de la adrenalina y la lista de fármacos a evitar. Si el paro por LAST se conduce como un ACLS de rutina, el tratamiento que funciona no se administra y algunos de los que se darían empeoran el cuadro. Y la RCP puede ser LARGA: manténgala, porque la recuperación tras reanimación prolongada con emulsión está descrita.",
  "⚠️ O QUE EVITAR NA PARADA POR LAST: VASOPRESSINA, BLOQUEADOR DE CANAL DE CÁLCIO e BETABLOQUEADOR — a ASRA os exclui explicitamente. E NÃO administrar mais ANESTÉSICO LOCAL: a LIDOCAÍNA é contraindicada aqui, ainda que seja antiarrítmico habitual em outros contextos. ADRENALINA: se for necessária, em DOSE PEQUENA, MENOR QUE 1 mcg/kg — a dose convencional do ACLS piora a troca gasosa e a função cardíaca no LAST, e prejudica a própria ressuscitação com lipídio. CONVULSÃO: benzodiazepínico é a primeira escolha; evita-se o propofol pela depressão cardiovascular, e, se a convulsão não ceder, pequenas doses de bloqueador neuromuscular evitam a hipóxia e a acidose que agravam tudo.":
    "⚠️ QUÉ EVITAR EN EL PARO POR LAST: VASOPRESINA, BLOQUEADOR DE CANAL DE CALCIO y BETABLOQUEANTE — la ASRA los excluye explícitamente. Y NO administrar más ANESTÉSICO LOCAL: la LIDOCAÍNA está contraindicada aquí, aunque sea antiarrítmico habitual en otros contextos. ADRENALINA: si es necesaria, en DOSIS PEQUEÑA, MENOR QUE 1 mcg/kg — la dosis convencional del ACLS empeora el intercambio gaseoso y la función cardíaca en el LAST, y perjudica la propia reanimación con lípido. CONVULSIÓN: la benzodiacepina es la primera elección; se evita el propofol por la depresión cardiovascular, y, si la convulsión no cede, pequeñas dosis de bloqueante neuromuscular evitan la hipoxia y la acidosis que agravan todo.",
  "⚠️ ATENÇÃO À REGRA QUE SE INVERTE AQUI: no LAST, a AMIODARONA é o antiarrítmico preferido, e a LIDOCAÍNA é contraindicada. É o oposto do que vale na intoxicação por cocaína, tricíclico e carbamazepina — lá se evita amiodarona porque o tóxico já bloqueia o canal de sódio e ela bloqueia também. Aqui o tóxico É o anestésico local: dar lidocaína é dar mais do veneno, e a amiodarona não pertence à classe que causou o quadro. Toxinas diferentes, condutas diferentes — não transporte a regra de uma para a outra.":
    "⚠️ ATENCIÓN A LA REGLA QUE SE INVIERTE AQUÍ: en el LAST, la AMIODARONA es el antiarrítmico preferido, y la LIDOCAÍNA está contraindicada. Es lo opuesto de lo que vale en la intoxicación por cocaína, tricíclico y carbamazepina — allí se evita la amiodarona porque el tóxico ya bloquea el canal de sodio y ella también lo bloquea. Aquí el tóxico ES el anestésico local: dar lidocaína es dar más del veneno, y la amiodarona no pertenece a la clase que causó el cuadro. Toxinas distintas, conductas distintas — no traslade la regla de una a la otra.",
  "DEPOIS DE ESTABILIZAR, A VIGILÂNCIA CONTINUA — e por horas, não por minutos: a recorrência depois da melhora está descrita, e o anestésico local continua sendo liberado do tecido. A ASRA recomenda tempos específicos de observação, ESTRATIFICADOS PELA GRAVIDADE do evento — evento cardiovascular exige mais que evento neurológico limitado. ⚠️ Este app NÃO fixa o número de horas: os valores estão no gráfico do checklist, que não foi aberto em sessão, e uma fonte secundária diz 12–24 h sem que se pudesse confirmar na primária. Consulte o checklist da ASRA do seu serviço para a janela, e no mínimo mantenha monitorização contínua e leito com capacidade de ressuscitação. Registre também que o uso da emulsão como antídoto é off-label pela FDA — o que não muda a indicação, e explica por que a bula do produto não a descreve.":
    "DESPUÉS DE ESTABILIZAR, LA VIGILANCIA CONTINÚA — y por horas, no por minutos: la recurrencia tras la mejoría está descrita, y el anestésico local sigue liberándose del tejido. La ASRA recomienda tiempos específicos de observación, ESTRATIFICADOS POR LA GRAVEDAD del evento — un evento cardiovascular exige más que un evento neurológico limitado. ⚠️ Esta app NO fija el número de horas: los valores están en el gráfico del checklist, que no se abrió en sesión, y una fuente secundaria dice 12–24 h sin que se pudiera confirmar en la primaria. Consulte el checklist de la ASRA de su servicio para la ventana, y como mínimo mantenga monitorización continua y una cama con capacidad de reanimación. Registre también que el uso de la emulsión como antídoto es off-label según la FDA — lo que no cambia la indicación, y explica por qué el prospecto del producto no la describe.",
  "FAÇA AGORA, e vale para qualquer agente: via aérea conforme o nível de consciência, O₂, monitorização contínua, dois acessos, GLICEMIA CAPILAR, ECG de 12 derivações e temperatura.":
    "HAGA AHORA, y vale para cualquier agente: vía aérea según el nivel de conciencia, O₂, monitorización continua, dos accesos, GLUCEMIA CAPILAR, ECG de 12 derivaciones y temperatura.",
  "O ECG É O EXAME QUE MAIS APONTA AGENTE SEM QUE VOCÊ SAIBA QUAL É: QRS alargado indica bloqueio de canal de sódio (tricíclico, cocaína, carbamazepina) e pede bicarbonato; QT prolongado indica bloqueio do efluxo de potássio e pede correção de eletrólitos e cuidado com fármacos que alarguem mais.":
    "EL ECG ES EL EXAMEN QUE MÁS APUNTA AL AGENTE SIN QUE USTED SEPA CUÁL ES: el QRS ancho indica bloqueo del canal de sodio (tricíclico, cocaína, carbamazepina) y pide bicarbonato; el QT prolongado indica bloqueo del eflujo de potasio y pide corrección de electrolitos y cuidado con fármacos que lo alarguen más.",
  "DOSAR PARACETAMOL E SALICILATO EM TODOS — as duas intoxicações são silenciosas, comuns e têm conduta tempo-dependente. É a exceção à regra de não pedir triagem ampla.":
    "DOSAR PARACETAMOL Y SALICILATO EN TODOS — las dos intoxicaciones son silenciosas, comunes y tienen conducta tiempo-dependiente. Es la excepción a la regla de no pedir tamizaje amplio.",
  "REEXAMINE PROCURANDO A TOXIDROME QUE AINDA NÃO APARECEU: pupilas, pele (seca ou úmida), ruídos hidroaéreos, temperatura, reflexos e clonus. Elas se declaram com o tempo, e o exame de agora não é o de daqui a uma hora.":
    "REEXAMINE BUSCANDO EL TOXÍNDROME QUE AÚN NO APARECIÓ: pupilas, piel (seca o húmeda), ruidos hidroaéreos, temperatura, reflejos y clonus. Se declaran con el tiempo, y el examen de ahora no es el de dentro de una hora.",
  "LIGUE PARA O CIATox/CEATOX — é o recurso mais subutilizado da toxicologia de emergência, e a orientação é em tempo real, com o caso na mão. Não é preciso ter o diagnóstico para ligar; a dúvida já é motivo.":
    "LLAME AL CENTRO DE INFORMACIÓN TOXICOLÓGICA — es el recurso más subutilizado de la toxicología de emergencia, y la orientación es en tiempo real, con el caso en la mano. No hace falta tener el diagnóstico para llamar; la duda ya es motivo.",
  "PROCURE A HISTÓRIA ONDE ELA ESTÁ: acompanhante, socorristas, receitas e caixas trazidas, farmácia da casa, prontuário eletrônico, e o que havia ao redor do paciente. Em tentativa de autoextermínio, o que foi tomado costuma estar no domicílio.":
    "BUSQUE LA HISTORIA DONDE ESTÁ: acompañante, personal prehospitalario, recetas y cajas traídas, botiquín de la casa, historia clínica electrónica, y lo que había alrededor del paciente. En el intento de autolesión, lo que se tomó suele estar en el domicilio.",
  "⚠️ NÃO FECHE EM INTOXICAÇÃO SEM DESCARTAR O QUE A IMITA: trauma craniano, hipoglicemia, hipóxia, hipotermia, AVC, infecção do SNC e distúrbio metabólico. Rebaixamento com história ambígua não é diagnóstico de intoxicação.":
    "⚠️ NO CIERRE EN INTOXICACIÓN SIN DESCARTAR LO QUE LA IMITA: traumatismo craneal, hipoglucemia, hipoxia, hipotermia, ACV, infección del SNC y trastorno metabólico. El deterioro de conciencia con historia ambigua no es diagnóstico de intoxicación.",
  "⚠️ E SE HOUVE ANESTÉSICO LOCAL EM QUALQUER MOMENTO — bloqueio, peridural, infiltração, tópico em mucosa —, pense em LAST antes de seguir procurando.":
    "⚠️ Y SI HUBO ANESTÉSICO LOCAL EN CUALQUIER MOMENTO — bloqueo, peridural, infiltración, tópico en mucosa —, piense en LAST antes de seguir buscando.",
  "⚠️ SE HOUVE ANESTÉSICO LOCAL, PENSE EM LAST: deterioração súbita — convulsão, arritmia, colapso — em quem recebeu bloqueio, peridural, infiltração ou anestésico tópico em mucosa. O antídoto é EMULSÃO LIPÍDICA 20% (acima de 70 kg: bolus de 100 mL em 2–3 min + 200–250 mL em 15–20 min; abaixo de 70 kg: 1,5 mL/kg + 0,25 mL/kg/min), e ele não tem substituto — propofol NÃO serve. Abra Intoxicações Exógenas para a conduta completa.":
    "⚠️ SI HUBO ANESTÉSICO LOCAL, PIENSE EN LAST: deterioro súbito — convulsión, arritmia, colapso — en quien recibió bloqueo, peridural, infiltración o anestésico tópico en mucosa. El antídoto es EMULSIÓN LIPÍDICA 20% (por encima de 70 kg: bolo de 100 mL en 2–3 min + 200–250 mL en 15–20 min; por debajo de 70 kg: 1,5 mL/kg + 0,25 mL/kg/min), y no tiene sustituto — el propofol NO sirve. Abra Intoxicaciones Exógenas para la conducta completa.",
  "Benzodiazepínico → Flumazenil — o teto depende do cenário, e o uso é EXCEPCIONAL.":
    "Benzodiacepina → Flumazenil — el techo depende del escenario, y el uso es EXCEPCIONAL.",
  "⚠️ O TETO DO FLUMAZENIL DEPENDE DO CENÁRIO, e confundi-los subdosa o antídoto. NA SUPERDOSAGEM (intoxicação): 0,2 mg IV em 15 s; sem resposta, 0,3 mg e depois 0,5 mg a cada minuto, até TETO CUMULATIVO DE 3 mg. NA REVERSÃO DE SEDAÇÃO CONSCIENTE (o paciente que a própria equipe sedou): 0,2 mg, repetindo até TETO DE 1 mg — porque ali se quer acordar, não competir com uma superdose. Usar o teto de 1 mg na intoxicação é parar no terço do caminho; usar o de 3 mg em quem foi sedado pela equipe é reversão abrupta desnecessária. ⚠️ NOS DOIS CENÁRIOS, A RESSEDAÇÃO É REGRA: a duração do flumazenil é MENOR que a da maioria dos benzodiazepínicos, e o rebaixamento volta depois de o paciente ter acordado — chegar ao teto não encerra o caso, e a vigilância é por horas.":
    "⚠️ EL TECHO DEL FLUMAZENIL DEPENDE DEL ESCENARIO, y confundirlos subdosifica el antídoto. EN LA SOBREDOSIS (intoxicación): 0,2 mg IV en 15 s; sin respuesta, 0,3 mg y luego 0,5 mg cada minuto, hasta un TECHO ACUMULADO DE 3 mg. EN LA REVERSIÓN DE SEDACIÓN CONSCIENTE (el paciente que el propio equipo sedó): 0,2 mg, repitiendo hasta un TECHO DE 1 mg — porque allí se quiere despertar, no competir con una sobredosis. Usar el techo de 1 mg en la intoxicación es detenerse en un tercio del camino; usar el de 3 mg en quien fue sedado por el equipo es una reversión abrupta innecesaria. ⚠️ EN LOS DOS ESCENARIOS, LA RESEDACIÓN ES LA REGLA: la duración del flumazenil es MENOR que la de la mayoría de las benzodiacepinas, y el deterioro de conciencia vuelve después de que el paciente despertó — llegar al techo no cierra el caso, y la vigilancia es por horas.",
  "Anestésico local (LAST) → EMULSÃO LIPÍDICA 20% — o antídoto é único e não tem substituto; ver o passo próprio de LAST.":
    "Anestésico local (LAST) → EMULSIÓN LIPÍDICA 20% — el antídoto es único y no tiene sustituto; ver el paso propio de LAST.",
  "QUANDO NÃO HÁ INDICAÇÃO DE TRATAMENTO: dose abaixo da tóxica para o peso, substância de baixa toxicidade, exposição antiga já fora da janela de risco, e paciente ASSINTOMÁTICO com sinais vitais, ECG e glicemia normais.":
    "CUÁNDO NO HAY INDICACIÓN DE TRATAMIENTO: dosis por debajo de la tóxica para el peso, sustancia de baja toxicidad, exposición antigua ya fuera de la ventana de riesgo, y paciente ASINTOMÁTICO con signos vitales, ECG y glucemia normales.",
  "⚠️ QUEM CONFIRMA ISSO NÃO É VOCÊ SOZINHO: ligue para o CIATox/CEATOX. Dose tóxica por peso e tempo de risco variam por produto, e é exatamente o que eles respondem em minutos. \"Parece pouco\" não é critério.":
    "⚠️ QUIEN CONFIRMA ESO NO ES USTED SOLO: llame al centro de información toxicológica. La dosis tóxica por peso y el tiempo de riesgo varían por producto, y es exactamente lo que ellos responden en minutos. \"Parece poco\" no es criterio.",
  "O QUE SE FAZ MESMO SEM TRATAR: observar pelo TEMPO DE RISCO DA SUBSTÂNCIA — e ele é definido pela farmacocinética, não pelo quanto o paciente parece bem. Formulação de LIBERAÇÃO PROLONGADA, fármaco de ação longa e coingestão que retarda o esvaziamento gástrico esticam esse tempo.":
    "LO QUE SE HACE AUNQUE NO SE TRATE: observar por el TIEMPO DE RIESGO DE LA SUSTANCIA — y lo define la farmacocinética, no lo bien que parece estar el paciente. La formulación de LIBERACIÓN PROLONGADA, el fármaco de acción larga y la coingesta que retrasa el vaciamiento gástrico alargan ese tiempo.",
  "⚠️ AS EXCEÇÕES QUE PARECEM BENIGNAS E NÃO SÃO: paracetamol e salicilato (silenciosos, com dano já em curso enquanto o paciente conversa), álcoois tóxicos (o intervalo lúcido é característico), ferro, e formulações de liberação prolongada. Nesses, \"assintomático agora\" não autoriza alta.":
    "⚠️ LAS EXCEPCIONES QUE PARECEN BENIGNAS Y NO LO SON: paracetamol y salicilato (silenciosos, con daño ya en curso mientras el paciente conversa), alcoholes tóxicos (el intervalo lúcido es característico), hierro, y las formulaciones de liberación prolongada. En esos, \"asintomático ahora\" no autoriza el alta.",
  "AVALIAÇÃO PSIQUIÁTRICA antes da alta em toda tentativa de autoextermínio — a ausência de toxicidade clínica não é ausência de risco, e é o motivo mais comum de o paciente voltar.":
    "EVALUACIÓN PSIQUIÁTRICA antes del alta en todo intento de autolesión — la ausencia de toxicidad clínica no es ausencia de riesgo, y es el motivo más común de que el paciente vuelva.",
  "ALTA COM ORIENTAÇÃO ESCRITA, acompanhante e retorno imediato se rebaixamento, vômitos, dor abdominal, dor torácica ou convulsão. E notificação conforme a legislação local.":
    "ALTA CON INDICACIONES ESCRITAS, acompañante y regreso inmediato si hay deterioro de conciencia, vómitos, dolor abdominal, dolor torácico o convulsión. Y notificación según la legislación local.",
  "⚠️ NÃO PEDIR TRIAGEM TOXICOLÓGICA AMPLA PARA \"TER CERTEZA\" — ela não muda o desfecho e não é o que autoriza a alta. O que autoriza é dose, tempo e paciente assintomático.":
    "⚠️ NO PEDIR TAMIZAJE TOXICOLÓGICO AMPLIO PARA \"TENER CERTEZA\" — no cambia el desenlace y no es lo que autoriza el alta. Lo que autoriza es la dosis, el tiempo y un paciente asintomático.",
  "Ajustes por cenário: TCE → PaCO₂ 35–40 mmHg, PEEP 5–10 cmH₂O (hiperventilar só em herniação aguda); SARA → VC 4–6 mL/kg, PEEP alto, driving pressure ≤ 15; asma/DPOC → FR 8–12, tempo expiratório longo, PEEP 3–5, hipercapnia permissiva.":
    "Ajustes por escenario: TCE → PaCO₂ 35–40 mmHg, PEEP 5–10 cmH₂O (hiperventilar solo en herniación aguda); SDRA → Vt 4–6 mL/kg, PEEP alta, driving pressure ≤ 15; asma/EPOC → FR 8–12, tiempo espiratorio largo, PEEP 3–5, hipercapnia permisiva.",
  "Sintomas iniciais fáceis de subestimar: coceira nas palmas, plantas ou couro cabeludo; formigamento nos lábios; sensação de \"algo errado\"; ansiedade súbita.":
    "Síntomas iniciales fáciles de subestimar: picazón en palmas, plantas o cuero cabelludo; hormigueo perioral; sensación de muerte inminente.",
  "  • Autoinjector adulto: EpiPen 0,3 mg (≥ 30 kg).":
    "  • Autoinyector adulto: EpiPen 0,3 mg (≥ 30 kg).",
  "Tricíclicos: bicarbonato 1–2 mEq/kg. Opioides: naloxona 0,4–2 mg IV se o opioide for desconhecido — fentanil e análogos podem exigir mais de 2 mg ou infusão; se a equipe deu o opioide, titular 0,1–0,2 mg. A meia-vida da naloxona é MENOR que a da maioria dos opioides: a depressão respiratória PODE VOLTAR depois de o paciente já ter acordado — vigiar por horas. Organofosforados: atropina em altas doses. Intoxicação grave: considerar ECMO. ⚠️ ANESTÉSICO LOCAL (LAST) — E ESTE VAI INLINE, ao contrário do resto: bloqueio, peridural, infiltração ou tópico em mucosa, com convulsão, arritmia ou colapso. EMULSÃO LIPÍDICA 20%, sem diluir, direto do frasco: ACIMA DE 70 kg, bolus de 100 mL em 2–3 min + 200–250 mL em 15–20 min; ABAIXO DE 70 kg, 1,5 mL/kg + 0,25 mL/kg/min. Repetir o bolus ou dobrar a infusão se não estabilizar; manter 10 min após estabilizar; teto de 12 mL/kg. ⚠️ PROPOFOL NÃO SUBSTITUI — o conteúdo lipídico é baixo demais e ele é cardiodepressor. ADRENALINA em dose MENOR que 1 mcg/kg (a dose padrão do ACLS piora o LAST); EVITAR vasopressina, bloqueador de canal de cálcio, betabloqueador e mais anestésico local. ACIONE A EQUIPE DE CIRCULAÇÃO EXTRACORPÓREA junto com o pedido de ajuda — montar leva tempo que não existe depois do colapso. → O resto da toxicologia é específico de cada agente, e listar alguns aqui criaria a mesma lista parcial que este módulo existe para evitar: abrir Intoxicações Exógenas.":
    "Tricíclicos: bicarbonato 1–2 mEq/kg. Opioides: naloxona 0,4–2 mg IV si el opioide es desconocido — el fentanilo y sus análogos pueden exigir más de 2 mg o infusión; si el equipo dio el opioide, titular 0,1–0,2 mg. La vida media de la naloxona es MENOR que la de la mayoría de los opioides: la depresión respiratoria PUEDE VOLVER después de que el paciente ya despertó — vigilar por horas. Organofosforados: atropina en dosis altas. Intoxicación grave: considerar ECMO. ⚠️ ANESTÉSICO LOCAL (LAST) — Y ESTE VA INLINE, a diferencia del resto: bloqueo, peridural, infiltración o tópico en mucosa, con convulsión, arritmia o colapso. EMULSIÓN LIPÍDICA 20%, sin diluir, directo del frasco: POR ENCIMA DE 70 kg, bolo de 100 mL en 2–3 min + 200–250 mL en 15–20 min; POR DEBAJO DE 70 kg, 1,5 mL/kg + 0,25 mL/kg/min. Repetir el bolo o duplicar la infusión si no estabiliza; mantener 10 min tras estabilizar; techo de 12 mL/kg. ⚠️ EL PROPOFOL NO SUSTITUYE — su contenido lipídico es demasiado bajo y es cardiodepresor. ADRENALINA en dosis MENOR que 1 mcg/kg (la dosis estándar del ACLS empeora el LAST); EVITAR vasopresina, bloqueador de canal de calcio, betabloqueante y más anestésico local. ACTIVE AL EQUIPO DE CIRCULACIÓN EXTRACORPÓREA junto con el pedido de ayuda — montarla lleva un tiempo que no existe después del colapso. → El resto de la toxicología es específico de cada agente, y listar algunos aquí crearía la misma lista parcial que este módulo existe para evitar: abrir Intoxicaciones Exógenas.",
  "A toxidrome orienta, mas não é pré-requisito. O que muda desfecho na primeira hora é o suporte, e ele é o mesmo em quase todas as intoxicações.":
    "El toxíndrome orienta, pero no es un prerrequisito. Lo que cambia el desenlace en la primera hora es el soporte, y es el mismo en casi todas las intoxicaciones.",
  "Convulsão ou colapso após bloqueio/infiltração — ANESTÉSICO LOCAL (LAST)":
    "Convulsión o colapso tras bloqueo/infiltración — ANESTÉSICO LOCAL (LAST)",
  "Antídoto ÚNICO, time-critical e sem substituto: emulsão lipídica 20%. A ressuscitação é diferente do ACLS padrão.":
    "Antídoto ÚNICO, tiempo-crítico y sin sustituto: emulsión lipídica 20%. La reanimación es diferente del ACLS estándar.",
  "Boa parte das exposições atendidas não precisa de descontaminação, antídoto nem eliminação. O que elas precisam é de tempo de observação certo e de quem confirme que é este o caso.":
    "Buena parte de las exposiciones atendidas no necesita descontaminación, antídoto ni eliminación. Lo que necesitan es el tiempo de observación correcto y que alguien confirme que este es el caso.",
  "Exposição sem indicação de tratamento — o que ainda assim se faz":
    "Exposición sin indicación de tratamiento — lo que aun así se hace",
  "LAST — toxicidade por anestésico local":
    "LAST — toxicidad por anestésico local",
  "NÃO SEI o que foi — quadro sem toxidrome definida":
    "NO SÉ qué fue — cuadro sin toxíndrome definido",
  "Não sei o agente — e não precisa saber para começar":
    "No sé el agente — y no hace falta saberlo para empezar",
  "Não tratar também é conduta":
    "No tratar también es conducta",
  "SEI qual substância — só não reconheci a toxidrome":
    "SÉ qué sustancia — solo no reconocí el toxíndrome",
};
