/** ES — Metas do cuidado pós-parada (lib/metas-pos-parada + rótulos do módulo). */
export const metasPosParadaEs: Record<string, string> = {
  "FEBRE — o limiar é 37,5 °C, o MESMO teto da faixa de controle: acima disso já não se está cumprindo a meta declarada. Monitorar temperatura central continuamente e tratar ativamente, não observar.":
    "FIEBRE — el umbral es 37,5 °C, el MISMO techo del rango de control: por encima de eso ya no se está cumpliendo la meta declarada. Monitorizar la temperatura central de forma continua y tratar activamente, no observar.",
  "GLICEMIA — faixa-alvo 140–180 mg/dL. ⚠️ NÃO existe alvo pós-parada próprio: a AHA registra que o benefício de qualquer faixa-alvo específica é INCERTO (Classe IIb) — aplica-se aqui a meta geral de terapia intensiva. Isso tem consequência prática: 175 mg/dL não é problema a corrigir com agressividade. ⚠️ O que a fonte PROÍBE é o controle estrito de 80–110 mg/dL, pelo risco de hipoglicemia iatrogênica. Dentro da faixa, o piso importa: hipoglicemia (< 70 mg/dL) é tão lesiva quanto hiperglicemia, e o limite inferior não é um segundo alvo — é o chão.":
    "GLUCEMIA — rango objetivo 140–180 mg/dL. ⚠️ NO existe un objetivo propio del pos-paro: la AHA registra que el beneficio de cualquier rango objetivo específico es INCIERTO (Clase IIb) — aquí se aplica la meta general de terapia intensiva. Esto tiene consecuencia práctica: 175 mg/dL no es un problema a corregir con agresividad. ⚠️ Lo que la fuente PROHÍBE es el control estricto de 80–110 mg/dL, por el riesgo de hipoglucemia iatrogénica. Dentro del rango, el piso importa: la hipoglucemia (< 70 mg/dL) es tan lesiva como la hiperglucemia, y el límite inferior no es un segundo objetivo — es el suelo.",
  "OXIGENAÇÃO — O₂ a 100% até estabilizar e conseguir medir com confiança; depois titular para SpO₂ 90–98% (ou PaO₂ 60–105 mmHg). Evitar hiperóxia E hipoxemia: as duas pioram o desfecho neurológico.":
    "OXIGENACIÓN — O₂ al 100% hasta estabilizar y poder medir con confianza; después titular a SpO₂ 90–98% (o PaO₂ 60–105 mmHg). Evitar hiperoxia E hipoxemia: ambas empeoran el desenlace neurológico.",
  "PRESSÃO — PAM ≥ 65 mmHg e PAS ≥ 90 mmHg. Hipotensão pós-ROSC é preditor independente de morte. ⚠️ SOBRE O ALVO DE PAM ≥ 80: foi proposto em documento conjunto AHA/Neurocritical Care Society de 2023 e as diretrizes de 2025 NÃO o endossaram — não há evidência de benefício em mirar mais alto. Se você ouviu falar nele, é isto: proposto, não confirmado. O alvo é 65.":
    "PRESIÓN — PAM ≥ 65 mmHg y PAS ≥ 90 mmHg. La hipotensión pos-RCE es predictor independiente de muerte. ⚠️ SOBRE EL OBJETIVO DE PAM ≥ 80: fue propuesto en un documento conjunto AHA/Neurocritical Care Society de 2023 y las guías de 2025 NO lo respaldaron — no hay evidencia de beneficio en apuntar más alto. Si oyó hablar de él, es esto: propuesto, no confirmado. El objetivo es 65.",
  "PROGNÓSTICO NEUROLÓGICO — não concluir antes de 72 h após a normotermia, e nunca por um exame isolado. Sedação e bloqueio neuromuscular residuais invalidam o exame clínico; avaliar responsividade só depois que saírem.":
    "PRONÓSTICO NEUROLÓGICO — no concluir antes de 72 h tras la normotermia, y nunca con una sola prueba. La sedación y el bloqueo neuromuscular residuales invalidan el examen clínico; evaluar la respuesta solo después de que se eliminen.",
  "TEMPERATURA — se não segue comandos após o ROSC: CONTROLE ATIVO em 32–37,5 °C por pelo menos 36 h, com dispositivo e temperatura central contínua. DEPOIS das 36 h, o cuidado MUDA: não é manter o controle ativo, é PREVENIR FEBRE — manter ≤ 37,5 °C até completar pelo menos 72 h. Hipotermia induzida de rotina deixou de ser preferida em 2025; o que se busca é normotermia controlada.":
    "TEMPERATURA — si no obedece órdenes tras el RCE: CONTROL ACTIVO en 32–37,5 °C durante al menos 36 h, con dispositivo y temperatura central continua. DESPUÉS de las 36 h el cuidado CAMBIA: no es mantener el control activo, es PREVENIR LA FIEBRE — mantener ≤ 37,5 °C hasta completar al menos 72 h. La hipotermia inducida de rutina dejó de ser preferida en 2025; lo que se busca es normotermia controlada.",
  "VENTILAÇÃO — PaCO₂ 35–45 mmHg (normocapnia). ⚠️ Hiperventilar é a armadilha mais comum do pós-PCR: baixa a PaCO₂, causa vasoconstrição cerebral e piora o prognóstico do órgão que se está tentando salvar.":
    "VENTILACIÓN — PaCO₂ 35–45 mmHg (normocapnia). ⚠️ Hiperventilar es la trampa más común del pos-paro: baja la PaCO₂, causa vasoconstricción cerebral y empeora el pronóstico del órgano que se intenta salvar.",
  "Limiar de febre": "Umbral de fiebre",
  "Oxigenação": "Oxigenación",
  "Pressão": "Presión",
  "Ventilação": "Ventilación",
  "METAS": "METAS",
};
