/** ES — as regras de "na dúvida" (bloco do sistema de hesitação). */
export const naDuvidaEs: Record<string, string> = {
  "⚠️ SE VOCÊ ESTÁ SE PERGUNTANDO SE AINDA OXIGENA, A RESPOSTA É NÃO. Trate como CICO e vá para a via aérea cirúrgica. Hesitar aqui custa os segundos que a dessaturação não devolve — e a tentativa a mais é o que transforma hipóxia em parada. Ninguém se arrependeu de uma cricotireoidostomia feita cedo demais; o inverso acontece (máxima de ensino de via aérea, não dado de estudo).":
    "⚠️ SI USTED SE ESTÁ PREGUNTANDO SI TODAVÍA OXIGENA, LA RESPUESTA ES NO. Trátelo como CICO y vaya a la vía aérea quirúrgica. Dudar aquí cuesta los segundos que la desaturación no devuelve — y el intento de más es lo que convierte hipoxia en paro. Nadie se arrepintió de una cricotiroidotomía hecha demasiado pronto; lo contrario sí ocurre (máxima de enseñanza de vía aérea, no dato de estudio).",
  "⚠️ NA DÚVIDA SOBRE O PERFIL, INDUZA COMO INSTÁVEL — cetamina em dose reduzida ou etomidato, nunca propofol. O choque mascarado pela vasoconstrição some quando o indutor tira o tônus simpático: a pressão cai DEPOIS da droga, e aí você tem uma via aérea aberta num paciente hipotenso. Dose menor num estável adia a intubação por segundos; dose plena num instável faz parada pós-indução.":
    "⚠️ ANTE LA DUDA SOBRE EL PERFIL, INDUZCA COMO INESTABLE — ketamina en dosis reducida o etomidato, nunca propofol. El choque enmascarado por la vasoconstricción desaparece cuando el inductor quita el tono simpático: la presión cae DESPUÉS de la droga, y entonces usted tiene una vía aérea abierta en un paciente hipotenso. Una dosis menor en un estable retrasa la intubación unos segundos; la dosis plena en un inestable provoca paro posinducción.",
  "⚠️ NA DÚVIDA, ROCURÔNIO. Succinilcolina em hipercalemia não suspeitada é PARADA CARDÍACA na indução — e as situações de risco são justamente as que ninguém confirma na emergência: imobilização há mais de 48–72 h, queimadura, esmagamento, distrofia não diagnosticada. O rocurônio custa bloqueio mais longo, e o plano de resgate já está pronto.":
    "⚠️ ANTE LA DUDA, ROCURONIO. Succinilcolina en hipercalemia no sospechada es PARO CARDÍACO en la inducción — y las situaciones de riesgo son justamente las que nadie confirma en la emergencia: inmovilización de más de 48–72 h, quemadura, aplastamiento, distrofia no diagnosticada. El rocuronio cuesta un bloqueo más prolongado, y el plan de rescate ya está listo.",
  "⚠️ MOVIMENTO AMBÍGUO NÃO É CRISE CESSADA. Na dúvida, trate como PERSISTE e escale. O que engana é a crise que perde a manifestação motora e continua no EEG: o paciente \"acalma\", a equipe respira aliviada, e o cérebro segue convulsionando. Escalar sem necessidade custa uma dose; não escalar custa neurônio por minuto.":
    "⚠️ MOVIMIENTO AMBIGUO NO ES CRISIS CESADA. Ante la duda, trátelo como PERSISTE y escale. Lo que engaña es la crisis que pierde la manifestación motora y continúa en el EEG: el paciente \"se calma\", el equipo respira aliviado, y el cerebro sigue convulsionando. Escalar sin necesidad cuesta una dosis; no escalar cuesta neuronas por minuto.",
  "⚠️ CONSCIÊNCIA FLUTUANTE NÃO É RECUPERAÇÃO. Na dúvida, trate como NÃO RECUPEROU e peça EEG. O pós-ictal melhora progressivamente; o estado de mal não convulsivo oscila e não melhora. Se você ainda está em dúvida 30 minutos depois, isso já é o achado.":
    "⚠️ CONCIENCIA FLUCTUANTE NO ES RECUPERACIÓN. Ante la duda, trátelo como NO RECUPERÓ y pida EEG. El posictal mejora progresivamente; el estado de mal no convulsivo oscila y no mejora. Si usted sigue en duda 30 minutos después, eso ya es el hallazgo.",
  "⚠️ NA DÚVIDA, TRATE COMO ANAFILAXIA E DÊ ADRENALINA IM. Os critérios existem para reconhecer, não para adiar. O custo de dar sem precisar EXISTE — taquicardia, palpitação, e no coronariopata idoso pode ser isquemia — e é aceitável, porque não há contraindicação absoluta à adrenalina na anafilaxia. O custo de não dar quando precisava é a PARADA, e o atraso da primeira dose é o fator mais consistentemente associado à morte.":
    "⚠️ ANTE LA DUDA, TRATE COMO ANAFILAXIA Y DÉ ADRENALINA IM. Los criterios existen para reconocer, no para postergar. El costo de darla sin necesitarla EXISTE — taquicardia, palpitaciones, y en el coronariopata anciano puede ser isquemia — y es aceptable, porque no hay contraindicación absoluta a la adrenalina en la anafilaxia. El costo de no darla cuando hacía falta es el PARO, y el retraso de la primera dosis es el factor más consistentemente asociado a la muerte.",
  "⚠️ NA DÚVIDA SOBRE A RESPOSTA, TRATE COMO PIORA — repita a adrenalina IM e reavalie em 5 min. A anafilaxia bifásica melhora ANTES de voltar, e \"parece que melhorou\" é a leitura que precede a recaída. Repetir a dose tem custo conhecido e pequeno; considerar melhora quem está progredindo perde a janela em que a IM ainda resolve sozinha.":
    "⚠️ ANTE LA DUDA SOBRE LA RESPUESTA, TRÁTELA COMO EMPEORAMIENTO — repita la adrenalina IM y reevalúe en 5 min. La anafilaxia bifásica mejora ANTES de volver, y \"parece que mejoró\" es la lectura que precede a la recaída. Repetir la dosis tiene un costo conocido y pequeño; considerar mejoría a quien está progresando pierde la ventana en que la IM todavía resuelve sola.",
  "⚠️ RESPOSTA PARCIAL É RESPOSTA INADEQUADA. Na dúvida, trate como REFRATÁRIO e escale. Diurese abaixo de 0,5 mL/kg/h após a furosemida já é resposta inadequada por critério — e o paciente que \"melhorou um pouco\" e parou de melhorar é exatamente o que chega exausto à intubação.":
    "⚠️ RESPUESTA PARCIAL ES RESPUESTA INADECUADA. Ante la duda, trátelo como REFRACTARIO y escale. Una diuresis por debajo de 0,5 mL/kg/h tras la furosemida ya es respuesta inadecuada por criterio — y el paciente que \"mejoró un poco\" y dejó de mejorar es exactamente el que llega exhausto a la intubación.",
  "⚠️ NA DÚVIDA ENTRE PE COM E SEM CRITÉRIOS DE GRAVIDADE, TRATE COMO GRAVE E SULFATE. O sulfato de magnésio previne a convulsão que ainda não aconteceu, e depois dela o desfecho é outro. Sulfatar quem não precisava exige a vigilância da tríade — reflexo, frequência respiratória e diurese —, que este módulo ensina e que o gluconato de cálcio cobre; não sulfatar quem precisava é eclâmpsia.":
    "⚠️ ANTE LA DUDA ENTRE PE CON Y SIN CRITERIOS DE GRAVEDAD, TRÁTELA COMO GRAVE Y SULFATE. El sulfato de magnesio previene la convulsión que todavía no ocurrió, y después de ella el desenlace es otro. Sulfatar a quien no lo necesitaba exige la vigilancia de la tríada — reflejo, frecuencia respiratoria y diuresis —, que este módulo enseña y que el gluconato de calcio cubre; no sulfatar a quien lo necesitaba es eclampsia.",
  "⚠️ RESPOSTA TRANSITÓRIA É NÃO-RESPOSTA. Na dúvida se ele estabilizou, trate como sangramento ativo e vá para o controle da fonte. O respondedor transitório é justamente quem PARECE estável na hora de decidir e descompensa dentro do aparelho de tomografia — e instável não vai para a tomografia.":
    "⚠️ RESPUESTA TRANSITORIA ES NO RESPUESTA. Ante la duda de si se estabilizó, trátelo como sangrado activo y vaya al control de la fuente. El respondedor transitorio es justamente quien PARECE estable en el momento de decidir y se descompensa dentro del tomógrafo — y un inestable no va al tomógrafo.",
  "⚠️ NA DÚVIDA, NÃO É BAIXO RISCO. Baixo risco é a única saída deste nó que manda alguém para casa. Sem sPESI zerado item a item, sem função de VD conferida e sem biomarcador, classifique como intermediário e interne — a mortalidade do intermediário-alto está longe do 1% do baixo risco.":
    "⚠️ ANTE LA DUDA, NO ES BAJO RIESGO. Bajo riesgo es la única salida de este nodo que manda a alguien a casa. Sin sPESI en cero ítem por ítem, sin función del VD comprobada y sin biomarcador, clasifique como intermedio e ingrese — la mortalidad del intermedio-alto está lejos del 1% del bajo riesgo.",
  "⚠️ SE VOCÊ ESTÁ EM DÚVIDA, ISSO JÁ É \"DIAGNÓSTICO INDEFINIDO\" — que é critério de SIM nesta mesma pergunta. Dor abdominal persistente sem diagnóstico não se observa em casa: reavalia-se, com hora marcada e com a cirurgia ciente do caso.":
    "⚠️ SI USTED ESTÁ EN DUDA, ESO YA ES \"DIAGNÓSTICO INDEFINIDO\" — que es criterio de SÍ en esta misma pregunta. El dolor abdominal persistente sin diagnóstico no se observa en casa: se reevalúa, con hora marcada y con la cirugía al tanto del caso.",
};
