/** ES — oclusão de grande vaso (AVC) e os padrões sem supra (SCA). */
export const oclusaoGrandeVasoEs: Record<string, string> = {
  "COMO SABER SE HÁ OCLUSÃO DE GRANDE VASO — E VOCÊ PROVAVELMENTE JÁ COLETOU OS SINAIS. Não reexamine o paciente: volte ao NIHSS que você acabou de pontuar. QUATRO ITENS DELE SÃO OS SINAIS CORTICAIS, e é a presença deles, somada à fraqueza de braço, que levanta a suspeita: ITEM 2 (melhor olhar conjugado) — desvio do olhar para um lado; ITEM 3 (campos visuais) — hemianopsia; ITEM 9 (linguagem) — afasia; ITEM 11 (extinção/negligência) — o paciente ignora um lado do corpo ou do espaço. ⚠️ FRAQUEZA DE BRAÇO + PELO MENOS UM DESSES QUATRO É O QUE DEFINE A SUSPEITA — é o formato VAN (visão, afasia, negligência), que é positivo ou negativo, sem pontuação a calcular. Um paciente com hemiparesia isolada e nenhum item cortical tem probabilidade bem menor; um com afasia global e desvio do olhar tem alta.":
    "CÓMO SABER SI HAY OCLUSIÓN DE GRAN VASO — Y USTED PROBABLEMENTE YA RECOGIÓ LOS SIGNOS. No reexamine al paciente: vuelva al NIHSS que acaba de puntuar. CUATRO ÍTEMS DE ÉL SON LOS SIGNOS CORTICALES, y es la presencia de ellos, sumada a la debilidad del brazo, lo que levanta la sospecha: ÍTEM 2 (mejor mirada conjugada) — desviación de la mirada hacia un lado; ÍTEM 3 (campos visuales) — hemianopsia; ÍTEM 9 (lenguaje) — afasia; ÍTEM 11 (extinción/negligencia) — el paciente ignora un lado del cuerpo o del espacio. ⚠️ DEBILIDAD DE BRAZO + AL MENOS UNO DE ESOS CUATRO ES LO QUE DEFINE LA SOSPECHA — es el formato VAN (visión, afasia, negligencia), que es positivo o negativo, sin puntaje que calcular. Un paciente con hemiparesia aislada y ningún ítem cortical tiene probabilidad bastante menor; uno con afasia global y desviación de la mirada, alta.",
  "⚠️ E O NIHSS ALTO CONTA — MAS NÃO EXISTE UM NÚMERO QUE DEFINA. O NIHSS medido no hospital prediz oclusão de grande vaso melhor que qualquer escala de triagem pré-hospitalar (AUROC 0,86 contra 0,80–0,81 delas), E A MESMA FONTE NÃO ESTABELECE PONTO DE CORTE para esse fim. Por isso este app não escreve \"NIHSS ≥ tanto\": seria inventar precisão que a evidência não dá. Leia o escore como PROBABILIDADE — quanto mais alto, mais provável, sobretudo quando a pontuação vem dos itens corticais e não só da força — e deixe a confirmação para a imagem.":
    "⚠️ Y EL NIHSS ALTO CUENTA — PERO NO EXISTE UN NÚMERO QUE LO DEFINA. El NIHSS medido en el hospital predice oclusión de gran vaso mejor que cualquier escala de triaje prehospitalario (AUROC 0,86 contra 0,80–0,81 de ellas), Y LA MISMA FUENTE NO ESTABLECE PUNTO DE CORTE para ese fin. Por eso esta app no escribe \"NIHSS ≥ tanto\": sería inventar una precisión que la evidencia no da. Lea el puntaje como PROBABILIDAD — cuanto más alto, más probable, sobre todo cuando el puntaje viene de los ítems corticales y no solo de la fuerza — y deje la confirmación para la imagen.",
  "SOBRE AS ESCALAS DE TRIAGEM (RACE, LAMS, FAST-ED, C-STAT, PASS, G-FAST) — ELAS EXISTEM, SÃO VALIDADAS, E NÃO SÃO PARA ESTA TELA. Foram desenhadas para o PRÉ-HOSPITALAR: servem para decidir se a ambulância leva o paciente direto a um centro com trombectomia, contornando o hospital mais próximo. Aqui, com angioTC disponível, elas responderiam por estimativa o que a imagem responde por observação direta. ➜ Se você está numa unidade SEM angioTC, a pergunta muda: aí o que decide é o TRANSPORTE, e o contato com o centro de referência vem antes de qualquer escala.":
    "SOBRE LAS ESCALAS DE TRIAJE (RACE, LAMS, FAST-ED, C-STAT, PASS, G-FAST) — EXISTEN, ESTÁN VALIDADAS, Y NO SON PARA ESTA PANTALLA. Fueron diseñadas para el PREHOSPITALARIO: sirven para decidir si la ambulancia lleva al paciente directo a un centro con trombectomía, evitando el hospital más cercano. Aquí, con angioTC disponible, responderían por estimación lo que la imagen responde por observación directa. ➜ Si usted está en una unidad SIN angioTC, la pregunta cambia: ahí lo que decide es el TRASLADO, y el contacto con el centro de referencia viene antes de cualquier escala.",
  "O QUE A ANGIOTC RESPONDE, E QUE O EXAME NÃO RESPONDE: se existe oclusão, QUAL vaso (carótida interna, M1 ou M2 da cerebral média, basilar), ONDE exatamente, e a extensão do trombo — que é o que o neurointervencionista precisa para decidir e para planejar o acesso. Ela também mostra a circulação colateral, que pesa no prognóstico. Peça JUNTO com a tomografia sem contraste, na mesma ida à sala: são poucos minutos a mais no mesmo aparelho, e a creatinina não precisa voltar antes — o risco de contraste é menor que o de perder a janela.":
    "LO QUE LA ANGIOTC RESPONDE, Y QUE EL EXAMEN NO RESPONDE: si existe oclusión, CUÁL vaso (carótida interna, M1 o M2 de la cerebral media, basilar), DÓNDE exactamente, y la extensión del trombo — que es lo que el neurointervencionista necesita para decidir y planificar el acceso. También muestra la circulación colateral, que pesa en el pronóstico. Pídala JUNTO con la tomografía sin contraste, en la misma ida a la sala: son pocos minutos más en el mismo aparato, y la creatinina no necesita volver antes — el riesgo del contraste es menor que el de perder la ventana.",
  "⚠️ E O QUE NÃO SE ESPERA PELA ANGIOTC: NÃO ESPERE O LAUDO PARA TROMBOLISAR quem já é elegível — a trombólise não depende de saber qual vaso está ocluído, e as duas terapias se somam. NÃO ESPERE para ACIONAR o centro de trombectomia: ligue com a suspeita clínica, porque a equipe leva tempo para se reunir e esse tempo corre em paralelo ao seu exame. NÃO ESPERE a creatinina. E não pare a monitorização nem os alvos pressóricos enquanto o paciente está na sala de imagem. ⚠️ A angioTC informa a DECISÃO DE QUEM VAI PUNCIONAR; ela não é pré-requisito para o que já está indicado agora.":
    "⚠️ Y LO QUE NO SE ESPERA POR LA ANGIOTC: NO ESPERE EL INFORME PARA TROMBOLIZAR a quien ya es elegible — la trombólisis no depende de saber qué vaso está ocluido, y las dos terapias se suman. NO ESPERE para ACTIVAR el centro de trombectomía: llame con la sospecha clínica, porque el equipo tarda en reunirse y ese tiempo corre en paralelo a su examen. NO ESPERE la creatinina. Y no detenga la monitorización ni las metas de presión mientras el paciente está en la sala de imagen. ⚠️ La angioTC informa la DECISIÓN DE QUIEN VA A PUNCIONAR; no es requisito previo para lo que ya está indicado ahora.",
  "⚠️ NÃO CLASSIFIQUE COMO \"SEM SUPRA\" AINDA. Cinco padrões ocluem a coronária SEM elevar o ST nas 12 derivações padrão — e três deles são sala de hemodinâmica AGORA, não amanhã. Percorra os cinco abaixo antes de seguir pela via do NSTEMI: se qualquer um estiver presente, o caminho é REPERFUSÃO IMEDIATA e não estratificação por troponina. E lembre que dois deles só aparecem em derivações que ninguém colocou ainda — V7–V9 e V3R–V4R —, então \"não vi\" pode significar apenas \"não olhei\".":
    "⚠️ NO LO CLASIFIQUE COMO \"SIN ELEVACIÓN\" TODAVÍA. Cinco patrones ocluyen la coronaria SIN elevar el ST en las 12 derivaciones estándar — y tres de ellos son sala de hemodinamia AHORA, no mañana. Recorra los cinco de abajo antes de seguir por la vía del NSTEMI: si cualquiera está presente, el camino es REPERFUSIÓN INMEDIATA y no estratificación por troponina. Y recuerde que dos de ellos solo aparecen en derivaciones que nadie colocó aún — V7–V9 y V3R–V4R —, así que \"no lo vi\" puede significar apenas \"no miré\".",
  "Como reconhecer a oclusão de grande vaso":
    "Cómo reconocer la oclusión de gran vaso",
  "Não sei dizer — como reconhecer a oclusão":
    "No sé decir — cómo reconocer la oclusión",
  "Não sei dizer — ver os padrões que NÃO fazem supra":
    "No sé decir — ver los patrones que NO elevan el ST",
  "Não — descartei os padrões sem supra":
    "No — descarté los patrones sin elevación",
  "Antes de chamar de \"sem supra\" — os padrões que ocluem sem elevar":
    "Antes de llamarlo \"sin elevación\" — los patrones que ocluyen sin elevar",
  "Fora das 4,5 h, quem decide é a IMAGEM — e o critério muda conforme o exame disponível. ⚠️ ANTES DE TUDO: SE HÁ OCLUSÃO DE GRANDE VASO E O PACIENTE É CANDIDATO A TROMBECTOMIA, ESTE NÃO É O CAMINHO — vá para a trombectomia; nos dois ensaios que sustentam a janela estendida, ser candidato a trombectomia era critério de EXCLUSÃO. ⏱ E O PRAZO, EM UMA LINHA: a trombólise guiada por imagem vai até 9 h (do último-visto-bem, ou do ponto médio do sono) — depois disso mismatch NÃO abre trombólise, e de 9 a 24 h o que resta é trombectomia. Os critérios de cada janela estão nos detalhes abaixo.":
    "Fuera de las 4,5 h, quien decide es la IMAGEN — y el criterio cambia según el examen disponible. ⚠️ ANTES QUE NADA: SI HAY OCLUSIÓN DE GRAN VASO Y EL PACIENTE ES CANDIDATO A TROMBECTOMÍA, ESTE NO ES EL CAMINO — vaya a la trombectomía; en los dos ensayos que sustentan la ventana extendida, ser candidato a trombectomía era criterio de EXCLUSIÓN. ⏱ Y EL PLAZO, EN UNA LÍNEA: la trombólisis guiada por imagen va hasta 9 h (del último-visto-bien, o del punto medio del sueño) — después de eso el mismatch NO abre trombólisis, y de 9 a 24 h lo que queda es trombectomía. Los criterios de cada ventana están en los detalles de abajo.",
  "⏱ O RELÓGIO É QUEM ESCOLHE A REPERFUSÃO: ICP primária se o tempo porta-balão for ≤ 120 min (meta ≤ 90 min em centro com hemodinâmica). Acima disso, e com início ≤ 12 h, o caminho é FIBRINÓLISE — com meta de até 10 min entre o diagnóstico e a agulha. ⚠️ E o relógio conta do PRIMEIRO CONTATO MÉDICO, não da chegada à sala de hemodinâmica: os detalhes de onde ele começa estão abaixo.":
    "⏱ EL RELOJ ES QUIEN ELIGE LA REPERFUSIÓN: ICP primaria si el tiempo puerta-balón es ≤ 120 min (meta ≤ 90 min en centro con hemodinamia). Por encima de eso, y con inicio ≤ 12 h, el camino es FIBRINÓLISIS — con meta de hasta 10 min entre el diagnóstico y la aguja. ⚠️ Y el reloj cuenta desde el PRIMER CONTACTO MÉDICO, no desde la llegada a la sala de hemodinamia: los detalles de dónde empieza están abajo.",
  "PAS informada: {pas} mmHg · SpO₂ {spo2}%. ⚠️ ANTES DE VASODILATAR, DECIDA SE O PACIENTE ESTÁ QUENTE OU FRIO — e a PA NÃO responde isso: o frio-úmido pode ter PAS normal, porque a vasoconstrição sustenta o número enquanto o débito já caiu. Extremidades frias, enchimento lento, pressão de pulso estreita e oligúria mandam para o INOTRÓPICO, não para o vasodilatador — que nesse paciente derruba o que já está baixo. Os sinais de cada perfil estão nos detalhes abaixo.":
    "PAS informada: {pas} mmHg · SpO₂ {spo2}%. ⚠️ ANTES DE VASODILATAR, DECIDA SI EL PACIENTE ESTÁ CALIENTE O FRÍO — y la PA NO responde eso: el frío-húmedo puede tener PAS normal, porque la vasoconstricción sostiene el número mientras el gasto ya cayó. Extremidades frías, llenado lento, presión de pulso estrecha y oliguria mandan al INOTRÓPICO, no al vasodilatador — que en ese paciente derriba lo que ya está bajo. Los signos de cada perfil están en los detalles de abajo.",
  "⚠️ COM CONTRAINDICAÇÃO RELATIVA E SEM ABSOLUTA, QUEM DECIDE É O TEMPO ATÉ A ICP: se a transferência para hemodinâmica for viável em ≤ 120 min, ela é preferível — a relativa deixa de importar. Se não for, a conta é entre o risco de sangramento e o de não reperfundir, e ela pende para reperfundir quanto maior o infarto e mais precoce o quadro.":
    "⚠️ CON CONTRAINDICACIÓN RELATIVA Y SIN ABSOLUTA, QUIEN DECIDE ES EL TIEMPO HASTA LA ICP: si el traslado a hemodinamia es viable en ≤ 120 min, es preferible — la relativa deja de importar. Si no lo es, la cuenta es entre el riesgo de sangrado y el de no reperfundir, y se inclina a reperfundir cuanto mayor sea el infarto y más precoz el cuadro.",
};
