/** ES — OVACE: sequência 2025, exceções, ponte para a PCR. */
export const ovaceEs: Record<string, string> = {
  "AVALIAÇÃO MÉDICA É NECESSÁRIA MESMO EM QUEM FICOU ASSINTOMÁTICO — sair andando não descarta nada. Três motivos: lesão de via aérea pelo objeto ou pela manobra, corpo estranho residual que não foi expelido inteiro, e lesão visceral pelas compressões abdominais. Mantenha a vítima em observação até a chegada do serviço médico de emergência.":
    "LA EVALUACIÓN MÉDICA ES NECESARIA INCLUSO EN QUIEN QUEDÓ ASINTOMÁTICO — irse caminando no descarta nada. Tres motivos: lesión de la vía aérea por el objeto o por la maniobra, cuerpo extraño residual que no se expulsó entero, y lesión visceral por las compresiones abdominales. Mantenga a la víctima en observación hasta la llegada del servicio médico de emergencia.",
  "Abrir PCR no adulto": "Abrir paro cardíaco en el adulto",
  "Faça ciclos repetidos: 5 golpes (tapas) firmes entre as escápulas, com a base da mão, seguidos de 5 compressões abdominais. Repita até o objeto ser expelido ou a vítima ficar inconsciente. ONDE COMPRIMIR: punho fechado ACIMA DO UMBIGO e ABAIXO do apêndice xifoide, envolvido pela outra mão, com tração rápida para dentro e para cima. Comprimir alto demais é o mecanismo da lesão visceral — e é o erro de quem nunca fez a manobra.":
    "Haga ciclos repetidos: 5 golpes firmes entre las escápulas, con el talón de la mano, seguidos de 5 compresiones abdominales. Repita hasta que el objeto sea expulsado o la víctima quede inconsciente. DÓNDE COMPRIMIR: puño cerrado POR ENCIMA DEL OMBLIGO y POR DEBAJO del apéndice xifoides, envuelto por la otra mano, con tracción rápida hacia adentro y hacia arriba. Comprimir demasiado alto es el mecanismo de la lesión visceral — y es el error de quien nunca hizo la maniobra.",
  "Inicie a RCP imediatamente e siga o algoritmo de SBV do adulto até a chegada do suporte avançado. Comece pelas COMPRESSÕES.":
    "Inicie la RCP de inmediato y siga el algoritmo de SVB del adulto hasta la llegada del soporte avanzado. Comience por las COMPRESIONES.",
  "Na gestação em fase final — ou sempre que o socorrista não conseguir circundar o abdome da vítima — as 5 compressões são TORÁCICAS, não abdominais. ONDE: na METADE INFERIOR DO ESTERNO — a MESMA referência da compressão da RCP, que você já conhece. Os 5 golpes nas costas continuam iguais.":
    "En la gestación avanzada — o siempre que el reanimador no logre rodear el abdomen de la víctima — las 5 compresiones son TORÁCICAS, no abdominales. DÓNDE: en la MITAD INFERIOR DEL ESTERNÓN — la MISMA referencia de la compresión de la RCP, que usted ya conoce. Los 5 golpes en la espalda siguen iguales.",
  "Virou parada — o que muda na RCP": "Se volvió paro — qué cambia en la RCP",
  "VIA AÉREA POR CORPO ESTRANHO": "VÍA AÉREA POR CUERPO EXTRAÑO",
  "A CAUSA REVERSÍVEL JÁ ESTÁ IDENTIFICADA: esta é hipóxia por corpo estranho. Não gaste tempo procurando os 5 Hs e 5 Ts do zero — o app já marcou a hipóxia como SUSPEITA no painel de causas. ⚠️ Ela só passa a ABORDADA quando o objeto sair: enquanto ele estiver lá, a causa está identificada e NÃO resolvida. A mudança é manual, por desenho — o app não promove status sozinho.":
    "LA CAUSA REVERSIBLE YA ESTÁ IDENTIFICADA: esta es hipoxia por cuerpo extraño. No pierda tiempo buscando las 5 H y 5 T desde cero — la app ya marcó la hipoxia como SOSPECHADA en el panel de causas. ⚠️ Solo pasa a ABORDADA cuando el objeto salga: mientras siga allí, la causa está identificada y NO resuelta. El cambio es manual, por diseño — la app no promueve el estado sola.",
  "PARADA POR ENGASGO — A RCP É A PADRÃO: mesma profundidade, mesmo ritmo, mesma relação 30:2. Há UMA única diferença: APÓS CADA 30 COMPRESSÕES, ANTES das 2 ventilações, olhe dentro da boca e retire o objeto SOMENTE se estiver visível. ⚠️ NUNCA varredura digital às cegas — empurra o corpo estranho mais fundo. As compressões podem deslocar o objeto, mas não é para isso que se comprime: comprime-se para manter perfusão, e a boca se olha porque a via aérea pode ter mudado desde o último ciclo.":
    "PARO POR ATRAGANTAMIENTO — LA RCP ES LA ESTÁNDAR: misma profundidad, mismo ritmo, misma relación 30:2. Hay UNA sola diferencia: DESPUÉS DE CADA 30 COMPRESIONES, ANTES de las 2 ventilaciones, mire dentro de la boca y retire el objeto SOLO si está visible. ⚠️ NUNCA barrido digital a ciegas — empuja el cuerpo extraño más adentro. Las compresiones pueden desplazar el objeto, pero no es para eso que se comprime: se comprime para mantener la perfusión, y la boca se mira porque la vía aérea puede haber cambiado desde el último ciclo.",
};
