/**
 * Precauções de isolamento na sepse (S4) — PT → ES.
 */
export const ES_PRECAUCOES: Record<string, string> = {
  "PRECAUÇÕES DE ISOLAMENTO — decidir AGORA, pela SÍNDROME, sem esperar cultura. As precauções abaixo são SEMPRE somadas às precauções-padrão (higiene de mãos, luvas e avental conforme exposição a fluidos), nunca as substituem, e podem ser combinadas entre si. É a única conduta deste fluxo que protege TERCEIROS — equipe, o leito ao lado, o próximo atendimento.":
    "PRECAUCIONES DE AISLAMIENTO — decidir AHORA, por el SÍNDROME, sin esperar el cultivo. Las precauciones siguientes SIEMPRE se suman a las precauciones estándar (higiene de manos, guantes y bata según exposición a fluidos), nunca las sustituyen, y pueden combinarse entre sí. Es la única conducta de este flujo que protege a TERCEROS — el equipo, la cama de al lado, la próxima atención.",
  "GOTÍCULAS (máscara cirúrgica a menos de 1 m; quarto individual ou coorte): suspeita de MENINGITE bacteriana ou MENINGOCOCCEMIA — manter até 24 h de antibiótico eficaz. Também em influenza e outros vírus respiratórios. ⚠️ Na doença meningocócica, a exposição sem proteção obriga PROFILAXIA da equipe, independentemente do estado vacinal — então o atraso em isolar cria um segundo problema, não só um risco.":
    "GOTITAS (mascarilla quirúrgica a menos de 1 m; habitación individual o cohorte): sospecha de MENINGITIS bacteriana o MENINGOCOCEMIA — mantener hasta 24 h de antibiótico eficaz. También en influenza y otros virus respiratorios. ⚠️ En la enfermedad meningocócica, la exposición sin protección obliga a PROFILAXIS del equipo, independientemente del estado de vacunación — así que el retraso en aislar crea un segundo problema, no solo un riesgo.",
  "AÉREO (máscara N95/PFF2 para a equipe; quarto com pressão negativa — AIIR): suspeita de TUBERCULOSE pulmonar ou laríngea, sarampo, varicela/zóster disseminado. São patógenos que permanecem infectantes suspensos no ar e transmitem a longa distância. ⚠️ Se não houver quarto com pressão negativa, isolar no melhor recurso disponível e acionar a CCIH imediatamente — a ausência de estrutura não suspende a precaução.":
    "AÉREO (mascarilla N95/FFP2 para el equipo; habitación con presión negativa — AIIR): sospecha de TUBERCULOSIS pulmonar o laríngea, sarampión, varicela/zóster diseminado. Son patógenos que permanecen infectantes suspendidos en el aire y se transmiten a larga distancia. ⚠️ Si no hay habitación con presión negativa, aislar en el mejor recurso disponible y activar al comité de infecciones de inmediato — la ausencia de estructura no suspende la precaución.",
  "CONTATO (luvas e avental na entrada; equipamento dedicado): colonização ou infecção conhecida/suspeita por MDR — KPC, VRE, Acinetobacter, MRSA —, diarreia aguda com suspeita de C. difficile (higiene de mãos com ÁGUA E SABÃO, o álcool não elimina esporos), feridas com drenagem não contida e lesões cutâneas extensas. Gatilhos de suspeita: internação ou antibiótico nos últimos 90 dias, transferência de outro serviço ou de ILPI, diálise, colonização prévia documentada.":
    "CONTACTO (guantes y bata al entrar; equipo dedicado): colonización o infección conocida/sospechada por MDR — KPC, VRE, Acinetobacter, MRSA —, diarrea aguda con sospecha de C. difficile (higiene de manos con AGUA Y JABÓN, el alcohol no elimina las esporas), heridas con drenaje no contenido y lesiones cutáneas extensas. Desencadenantes de sospecha: hospitalización o antibiótico en los últimos 90 días, traslado de otro servicio o de residencia de mayores, diálisis, colonización previa documentada.",
  "⚠️ NÃO fazer isolamento protetor (\"reverso\") de rotina no imunossuprimido — foi descontinuado como prática geral, e o que protege esse paciente é a precaução-padrão bem executada, mais o quarto individual quando indicado. Exceção: receptor de transplante de células-tronco hematopoéticas, que tem ambiente próprio protocolizado.":
    "⚠️ NO hacer aislamiento protector (\"inverso\") de rutina en el inmunosuprimido — fue descontinuado como práctica general, y lo que protege a ese paciente es la precaución estándar bien ejecutada, más la habitación individual cuando esté indicada. Excepción: receptor de trasplante de células madre hematopoyéticas, que tiene un ambiente propio protocolizado.",
};
