/** ES — quando o algoritmo não fecha: os dois destinos de fim de cascata. */
export const quandoNaoFechaEs: Record<string, string> = {
  "O QUE VOCÊ ESTÁ PROCURANDO: vasodilatação com débito preservado ou ALTO. À beira do leito isso é o oposto do perfil frio que você viu no cardiogênico — extremidades QUENTES, pressão de pulso AMPLA (a diastólica cai mais que a sistólica), enchimento capilar RÁPIDO, tudo isso APESAR da hipotensão. Hipotensão com pele quente e enchimento rápido não é falha de bomba: é vaso aberto. O lactato pode subir mesmo com débito alto, porque o problema é de distribuição, não de fluxo total.":
    "LO QUE USTED ESTÁ BUSCANDO: vasodilatación con gasto cardíaco preservado o ALTO. A la cabecera esto es lo opuesto del perfil frío que vio en el cardiogénico — extremidades CALIENTES, presión de pulso AMPLIA (la diastólica cae más que la sistólica), llenado capilar RÁPIDO, todo eso A PESAR de la hipotensión. Hipotensión con piel caliente y llenado rápido no es falla de bomba: es vaso abierto. El lactato puede subir incluso con gasto alto, porque el problema es de distribución, no de flujo total.",
  "⚠️ POR QUE O VASOPRESSOR ENTRA CEDO — E ISSO NÃO É MOTIVO PARA SEGURAR VOLUME. O leito vascular dilatou, então há HIPOVOLEMIA RELATIVA de verdade: o continente cresceu e o conteúdo precisa acompanhar. Volume é PARTE do tratamento e não é erro. O ponto é outro: ele é NECESSÁRIO E INSUFICIENTE. Quem só repõe persegue uma meta de pressão que a vasodilatação desfaz enquanto se infunde — e o preço de insistir só com volume é congestão, hemodiluição e tempo perdido com o paciente hipoperfundido. Por isso os dois andam juntos: expanda E comece a noradrenalina, sem esperar terminar a expansão para titular.":
    "⚠️ POR QUÉ EL VASOPRESOR ENTRA TEMPRANO — Y ESO NO ES MOTIVO PARA RETENER VOLUMEN. El lecho vascular se dilató, así que hay HIPOVOLEMIA RELATIVA real: el continente creció y el contenido debe acompañarlo. El volumen es PARTE del tratamiento y no es error. El punto es otro: es NECESARIO E INSUFICIENTE. Quien solo repone persigue una meta de presión que la vasodilatación deshace mientras se infunde — y el precio de insistir solo con volumen es congestión, hemodilución y tiempo perdido con el paciente hipoperfundido. Por eso ambos van juntos: expanda Y comience la noradrenalina, sin esperar a terminar la expansión para titular.",
  "⚠️ ANTES DE PROCURAR CAUSA RARA, RECONSIDERE O CAMINHO. Você respondeu NÃO a seis perguntas para chegar aqui, e depois de seis negativas a explicação mais provável não é uma doença exótica — é uma das respostas anteriores estar errada. Volte e reconsidere as três que dependem de julgamento: (1) HIPOVOLEMIA — o sangramento oculto não se vê: retroperitônio, pelve, TGI alto, fêmur; hematócrito normal na primeira hora não exclui nada; (2) OBSTRUTIVO — tamponamento e TEP são os que mais escapam, e o ultrassom à beira do leito responde os dois em minutos; (3) CARDIOGÊNICO — a bomba pode falhar sem dor torácica e sem congestão evidente, sobretudo no idoso e no diabético. Só depois disso a busca por causa distributiva incomum faz sentido.":
    "⚠️ ANTES DE BUSCAR UNA CAUSA RARA, RECONSIDERE EL CAMINO. Usted respondió NO a seis preguntas para llegar aquí, y tras seis negativas la explicación más probable no es una enfermedad exótica — es que una de las respuestas anteriores esté equivocada. Vuelva y reconsidere las tres que dependen de juicio: (1) HIPOVOLEMIA — el sangrado oculto no se ve: retroperitoneo, pelvis, tubo digestivo alto, fémur; un hematocrito normal en la primera hora no excluye nada; (2) OBSTRUCTIVO — taponamiento y TEP son los que más se escapan, y el ultrasonido a la cabecera responde ambos en minutos; (3) CARDIOGÉNICO — la bomba puede fallar sin dolor torácico y sin congestión evidente, sobre todo en el anciano y en el diabético. Solo después de eso tiene sentido buscar una causa distributiva poco común.",
  "⚠️ E ESTA LISTA NÃO É EXAUSTIVA — o app não fecha o diferencial do choque distributivo não séptico, e dizer isso é mais honesto que sugerir que quatro causas o esgotam. O que sustenta o paciente enquanto o diagnóstico não vem é o que está acima: reconhecer o perfil, expandir, vasopressor cedo e reavaliar. ➜ ONDE CONTINUAR: cortisol basal antes da hidrocortisona quando houver suspeita de insuficiência adrenal, revisão da lista de medicamentos em uso (anti-hipertensivos, sedativos, vasodilatadores), história de corticoterapia crônica interrompida, e a discussão com a terapia intensiva — que é onde este paciente vai.":
    "⚠️ Y ESTA LISTA NO ES EXHAUSTIVA — la app no cierra el diferencial del choque distributivo no séptico, y decirlo es más honesto que sugerir que cuatro causas lo agotan. Lo que sostiene al paciente mientras no llega el diagnóstico es lo de arriba: reconocer el perfil, expandir, vasopresor temprano y reevaluar. ➜ DÓNDE CONTINUAR: cortisol basal antes de la hidrocortisona cuando haya sospecha de insuficiencia suprarrenal, revisión de la lista de medicamentos en uso (antihipertensivos, sedantes, vasodilatadores), antecedente de corticoterapia crónica interrumpida, y la discusión con terapia intensiva — que es adonde va este paciente.",
  "O QUE SOBROU DEPOIS DE EXCLUIR AS COMUNS, e como pensar: dispneia sem padrão pulmonar nem cardíaco claro costuma ser um dos três — (1) DEMANDA aumentada por acidose metabólica, em que o pulmão está compensando e não doente (Kussmaul: respiração profunda, sem esforço acessório proporcional); (2) TRANSPORTE de oxigênio comprometido com pulmão normal — anemia grave, intoxicação por monóxido ou metemoglobinemia, em que a SpO₂ engana; (3) MISTO, o paciente com duas doenças parciais, que é o mais comum dos três no idoso. A ansiedade é diagnóstico de EXCLUSÃO e vem depois destes, nunca antes.":
    "LO QUE QUEDÓ TRAS EXCLUIR LAS COMUNES, y cómo pensarlo: la disnea sin patrón pulmonar ni cardíaco claro suele ser una de tres — (1) DEMANDA aumentada por acidosis metabólica, en que el pulmón está compensando y no enfermo (Kussmaul: respiración profunda, sin esfuerzo accesorio proporcional); (2) TRANSPORTE de oxígeno comprometido con pulmón normal — anemia grave, intoxicación por monóxido o metahemoglobinemia, donde la SpO₂ engaña; (3) MIXTO, el paciente con dos enfermedades parciales, que es el más común de los tres en el anciano. La ansiedad es diagnóstico de EXCLUSIÓN y viene después de estos, nunca antes.",
  "⚠️ ANTES DE AMPLIAR EXAMES, RECONSIDERE O CAMINHO. Você respondeu NÃO a onze perguntas para chegar aqui — e a explicação mais provável não é causa rara, é uma resposta anterior errada. Reconsidere as três em que mais se erra com o paciente ofegante: (1) TEP — a apresentação clássica é minoria; taquicardia isolada, síncope ou piora súbita sem ausculta alterada bastam para suspeitar, e o fator de risco pode não ser lembrado no primeiro momento; (2) CHIADO — nem todo sibilo é asma ou DPOC: o EAP silba, e chamá-lo de broncoespasmo leva a broncodilatador em quem precisa de vasodilatador e diurético; (3) CREPITANTES — a ausculta do taquipneico engana, e crepitante bilateral com jugular cheia é congestão até prova em contrário. Se qualquer uma dessas mudar, volte ao ramo dela.":
    "⚠️ ANTES DE AMPLIAR EXÁMENES, RECONSIDERE EL CAMINO. Usted respondió NO a once preguntas para llegar aquí — y la explicación más probable no es una causa rara, es que una respuesta anterior esté equivocada. Reconsidere las tres en que más se yerra con el paciente que jadea: (1) TEP — la presentación clásica es minoría; taquicardia aislada, síncope o empeoramiento súbito sin auscultación alterada bastan para sospechar, y el factor de riesgo puede no recordarse en el primer momento; (2) SIBILANCIA — no todo sibilo es asma o EPOC: el edema pulmonar silba, y llamarlo broncoespasmo lleva a broncodilatador en quien necesita vasodilatador y diurético; (3) CREPITANTES — la auscultación del taquipneico engaña, y crepitantes bilaterales con yugulares llenas son congestión hasta prueba en contrario. Si alguna de esas cambia, vuelva a su rama.",
  "Não — descartei distributivo":
    "No — descarté distributivo",
  "Não — descartei hipoventilação":
    "No — descarté hipoventilación",
  "Está sonolento, difícil de acordar, ou confuso — sem outra explicação para isso?":
    "¿Está somnoliento, difícil de despertar o confuso — sin otra explicación para eso?",
  "A respiração está LENTA ou superficial (menos de 10 por minuto, ou movimento pequeno do tórax)?":
    "¿La respiración está LENTA o superficial (menos de 10 por minuto, o movimiento pequeño del tórax)?",
  "Recebeu opioide, benzodiazepínico, sedativo ou álcool nas últimas horas?":
    "¿Recibió opioide, benzodiacepina, sedante o alcohol en las últimas horas?",
  "Tem doença neuromuscular, fraqueza que está piorando, ou dificuldade para tossir e engolir?":
    "¿Tiene enfermedad neuromuscular, debilidad que empeora, o dificultad para toser y tragar?",
  "É obeso, ronca muito, para de respirar dormindo, ou acorda com dor de cabeça?":
    "¿Es obeso, ronca mucho, deja de respirar al dormir, o se despierta con dolor de cabeza?",
};
