/** ES — Sepse: vasopressina, adrenalina no choque, hidrocortisona e o ponteiro de ISR. */
export const sepseVasoativosEs: Record<string, string> = {
  "A sepse é a causa clínica que mais leva à via aérea — e a indução muda com o choque.":
    "La sepsis es la causa clínica que más lleva a la vía aérea — y la inducción cambia con el choque.",
  "Doses de indução e bloqueio, escolha do hipnótico no choque, pré-oxigenação e checklist: módulo de ISR (Intubação em Sequência Rápida).":
    "Dosis de inducción y bloqueo, elección del hipnótico en el choque, preoxigenación y checklist: módulo de ISR (Intubación de Secuencia Rápida).",
  "NE ≥ 0,25 mcg/kg/min por ≥ 4 h é REFERÊNCIA DE PRÁTICA e o critério dos ensaios, útil como parâmetro — mas NÃO É PORTÃO, e não deve impedir a indicação em quem já tem necessidade persistente. A SSC 2021 condicionava a esse limiar; a SSC 2026 REMOVEU o gatilho de dose e de duração, e recomenda corticoide no choque séptico sem número de entrada.":
    "NA ≥ 0,25 mcg/kg/min durante ≥ 4 h es REFERENCIA DE PRÁCTICA y el criterio de los ensayos, útil como parámetro — pero NO ES UNA PUERTA, y no debe impedir la indicación en quien ya tiene necesidad persistente. La SSC 2021 lo condicionaba a ese umbral; la SSC 2026 ELIMINÓ el disparador de dosis y de duración, y recomienda corticoide en el choque séptico sin número de entrada.",
  "OPÇÃO A — dobutamina somada à noradrenalina:":
    "OPCIÓN A — dobutamina sumada a la noradrenalina:",
  "OPÇÃO B — adrenalina isolada, em pé de igualdade pela SSC 2026:":
    "OPCIÓN B — adrenalina sola, en igualdad de condiciones según la SSC 2026:",
  "Se precisar intubar":
    "Si necesita intubar",
  "→ Abrir o módulo de ISR pelo menu de módulos. O fluxo da sepse continua: intubar não encerra o tratamento da sepse.":
    "→ Abrir el módulo de ISR desde el menú de módulos. El flujo de la sepsis continúa: intubar no termina el tratamiento de la sepsis.",
  "⚠️ COM DISFUNÇÃO CARDÍACA CONCOMITANTE — e só nesse caso — a SSC 2026 sugere noradrenalina OU adrenalina como 1ª linha. Sem disfunção cardíaca, a 1ª linha é noradrenalina.":
    "⚠️ CON DISFUNCIÓN CARDÍACA CONCOMITANTE — y solo en ese caso — la SSC 2026 sugiere noradrenalina O adrenalina como 1.ª línea. Sin disfunción cardíaca, la 1.ª línea es noradrenalina.",
  "⚠️ NÃO reduza a dose do BLOQUEADOR por causa do choque — reduzir bloqueio piora a laringoscopia. O que se reduz é o HIPNÓTICO.":
    "⚠️ NO reduzca la dosis del BLOQUEADOR por el choque — reducir el bloqueo empeora la laringoscopia. Lo que se reduce es el HIPNÓTICO.",
  "ADRENALINA em infusão contínua — iniciar em 0,05 mcg/kg/min e titular pela PAM; a faixa de referência no choque vai de 0,01 a 2 mcg/kg/min. Abaixo de ~0,05 o efeito é predominantemente INOTRÓPICO; acima, vasopressor.":
    "ADRENALINA en infusión continua — iniciar en 0,05 mcg/kg/min y titular por la PAM; el rango de referencia en el choque va de 0,01 a 2 mcg/kg/min. Por debajo de ~0,05 el efecto es predominantemente INOTRÓPICO; por encima, vasopresor.",
  "QUANDO: no choque séptico é agente de 3ª linha, depois de noradrenalina e vasopressina. COM DISFUNÇÃO CARDÍACA concomitante, sobe de posição — ver a ressalva de 1ª linha.":
    "CUÁNDO: en el choque séptico es agente de 3.ª línea, después de noradrenalina y vasopresina. CON DISFUNCIÓN CARDÍACA concomitante sube de posición — ver la salvedad de 1.ª línea.",
  "⚠️ 0,5 E 1 mcg/kg/min NÃO SÃO TETO — são marcadores de gravidade. Acima de 0,5 é o limiar que os ensaios usam para chamar de DOSE ALTA; acima de 1 observou-se mortalidade em torno de 90%, o que descreve a gravidade de quem chegou lá, não uma proibição. Não existe dose máxima estabelecida. O que muda acima desses valores é a vigilância — isquemia mesentérica e digital, taquiarritmia, lactato — e a pergunta sobre causa não tratada, nunca a decisão de subdosar.":
    "⚠️ 0,5 Y 1 mcg/kg/min NO SON TECHO — son marcadores de gravedad. Por encima de 0,5 es el umbral que los ensayos usan para llamarla DOSIS ALTA; por encima de 1 se observó una mortalidad cercana al 90%, lo que describe la gravedad de quien llegó allí, no una prohibición. No existe dosis máxima establecida. Lo que cambia por encima de esos valores es la vigilancia — isquemia mesentérica y digital, taquiarritmia, lactato — y la pregunta sobre la causa no tratada, nunca la decisión de subdosificar.",
  "APRESENTAÇÃO E PREPARO: ampola de 1 mL com 20 U (20 U/mL) — NUNCA infundir sem diluir. Diluir em SF 0,9% ou SG 5% para 0,1 U/mL ou 1 U/mL, conforme a bomba e a restrição de volume. Repare na ordem de grandeza: UMA ampola tem mais de 600 vezes a dose de um minuto, e é por isso que erro de diluição aqui não perdoa.":
    "PRESENTACIÓN Y PREPARACIÓN: ampolla de 1 mL con 20 U (20 U/mL) — NUNCA infundir sin diluir. Diluir en SF 0,9% o SG 5% a 0,1 U/mL o 1 U/mL, según la bomba y la restricción de volumen. Note el orden de magnitud: UNA ampolla tiene más de 600 veces la dosis de un minuto, y por eso un error de dilución aquí no perdona.",
  "QUANDO ASSOCIAR: a prática comum associa a partir de noradrenalina ≈ 0,25 mcg/kg/min (faixa usual de início 0,25–0,5). ⚠️ Este número é REFERÊNCIA DE PRÁTICA, não portão: a SSC 2026 não estabelece limiar de dose para associar a vasopressina — ela diz que a noradrenalina é a primeira linha e que a adrenalina entra quando a PAM segue inadequada apesar de noradrenalina E vasopressina. Não espere alcançar 0,25 para associar se a escalada já estiver evidente.":
    "CUÁNDO ASOCIAR: la práctica común la asocia a partir de noradrenalina ≈ 0,25 mcg/kg/min (rango usual de inicio 0,25–0,5). ⚠️ Este número es REFERENCIA DE PRÁCTICA, no una puerta: la SSC 2026 no establece umbral de dosis para asociar la vasopresina — dice que la noradrenalina es la primera línea y que la adrenalina entra cuando la PAM sigue inadecuada pese a noradrenalina Y vasopresina. No espere alcanzar 0,25 para asociar si la escalada ya es evidente.",
  "VASOPRESSINA — 0,03 U/min, DOSE FIXA: não se titula. Ela poupa catecolamina, e a lógica é ADICIONAR à noradrenalina em vez de escalar a noradrenalina sozinha. No VASST a infusão ia de 0,01 até o máximo de 0,03 U/min — acima disso não é a estratégia estudada.":
    "VASOPRESINA — 0,03 U/min, DOSIS FIJA: no se titula. Ahorra catecolamina, y la lógica es AÑADIRLA a la noradrenalina en vez de escalar la noradrenalina sola. En el VASST la infusión iba de 0,01 hasta el máximo de 0,03 U/min — por encima de eso no es la estrategia estudiada.",
  "⚠️ RECOMENDAÇÃO FRACA. A SSC 2026 sugere INOTRÓPICO versus nenhum inotrópico no choque séptico com disfunção cardíaca e hipoperfusão persistente apesar de volume e PA adequados — e, como sugestão fraca, adicionar dobutamina à noradrenalina OU usar adrenalina isolada. A escolha do agente foi REBAIXADA em relação a 2021, e NÃO LOCALIZAMOS recomendação que decida entre dobutamina e milrinona — a formulação anterior atribuía essa incerteza à SSC 2026, e o texto integral está atrás de assinatura (R-5: não afirmar o que a fonte diz sem conseguir lê-la). Verificação pendente. Não é a resposta certa: é a opção razoável com a evidência que existe.":
    "⚠️ RECOMENDACIÓN DÉBIL. La SSC 2026 sugiere INOTRÓPICO frente a ningún inotrópico en el choque séptico con disfunción cardíaca e hipoperfusión persistente pese a volumen y presión adecuados — y, como sugerencia débil, añadir dobutamina a la noradrenalina O usar adrenalina sola. La elección del agente fue DEGRADADA respecto a 2021, y NO LOCALIZAMOS una recomendación que decida entre dobutamina y milrinona — la formulación anterior atribuía esa incertidumbre a la SSC 2026, y el texto íntegro está tras suscripción (R-5: no afirmar lo que la fuente dice sin poder leerla). Verificación pendiente.",
  "APRESENTAÇÃO: succinato sódico de hidrocortisona, PÓ LIOFILIZADO em frasco-ampola de 100 mg e de 500 mg — as duas padronizadas pelo SUS. ⚠️ NÃO VEM PRONTA: precisa ser reconstituída antes de qualquer coisa, e é aí que se perde tempo no choque refratário. CONFIRA O VOLUME DE RECONSTITUIÇÃO NO PRÓPRIO FRASCO — ele varia por apresentação e por fabricante, e o frasco com diluente acoplado (Act-O-Vial) não se reconstitui como o frasco simples. No rótulo, 134 mg de succinato equivalem a 100 mg de hidrocortisona base: a dose que se prescreve é a da BASE.":
    "PRESENTACIÓN: succinato sódico de hidrocortisona, POLVO LIOFILIZADO en frasco-ampolla de 100 mg y de 500 mg — ambas estandarizadas por el SUS. ⚠️ NO VIENE LISTA: hay que reconstituirla antes que nada, y es ahí donde se pierde tiempo en el choque refractario. CONFIRME EL VOLUMEN DE RECONSTITUCIÓN EN EL PROPIO FRASCO — varía según la presentación y el fabricante, y el frasco con diluyente acoplado (Act-O-Vial) no se reconstituye como el frasco simple. En la etiqueta, 134 mg de succinato equivalen a 100 mg de hidrocortisona base: la dosis que se prescribe es la de la BASE.",
  "0,03 U/min, dose FIXA (não titular) — a partir de noradrenalina ≈ 0,25 mcg/kg/min (faixa usual de início 0,25–0,5) — REFERÊNCIA DE PRÁTICA, NÃO É PORTÃO: a SSC 2026 não fixa limiar de dose para associar. Associar em vez de escalar a noradrenalina sozinha. Considerar hidrocortisona 200 mg/dia se a dose se mantiver ≥ 0,25 por pelo menos 4 h.":
    "0,03 U/min, dosis FIJA (no titular) — a partir de noradrenalina ≈ 0,25 mcg/kg/min (rango usual de inicio 0,25–0,5) — REFERENCIA DE PRÁCTICA, NO ES UNA PUERTA: la SSC 2026 no fija umbral de dosis para asociar. Asociar en vez de escalar la noradrenalina sola. Considerar hidrocortisona 200 mg/día si la dosis se mantiene ≥ 0,25 durante al menos 4 h.",
  "Noradrenalina ≥ 0,25 mcg/kg/min — janela para associar VASOPRESSINA 0,03 U/min (dose FIXA, não titular). A faixa usual de início é 0,25–0,5 mcg/kg/min — REFERÊNCIA DE PRÁTICA (SSC 2021, texto de prática, nunca recomendação graduada), NÃO É PORTÃO. A SSC 2026 retirou o número: o gatilho passou a ser dose em ESCALADA. Se a noradrenalina está subindo, associar poupa alfa — não esperar chegar a 0,5.":
    "Noradrenalina ≥ 0,25 mcg/kg/min — ventana para asociar VASOPRESINA 0,03 U/min (dosis FIJA, no titular). El rango usual de inicio es 0,25–0,5 mcg/kg/min — REFERENCIA DE PRÁCTICA (SSC 2021, texto de práctica, nunca recomendación graduada), NO ES UNA PUERTA. La SSC 2026 retiró el número: el disparador pasó a ser \"dosis en escalada\". Si la noradrenalina está subiendo, asociar ahorra alfa — no esperar a llegar a 0,5.",
  "QUANDO ENTRA, NO CHOQUE SÉPTICO: quando a PAM segue inadequada APESAR de noradrenalina E VASOPRESSINA — não depois da noradrenalina apenas. ⚠️ A ORDEM IMPORTA E A LISTA DESTA TELA NÃO A REFLETE: a vasopressina vem ANTES da adrenalina na escalada, mesmo aparecendo depois dela aqui. ➜ A EXCEÇÃO, DELIMITADA: com DISFUNÇÃO CARDÍACA concomitante — e só nesse caso — a SSC 2026 sugere noradrenalina OU adrenalina como 1ª linha; sem disfunção cardíaca, a 1ª linha é noradrenalina.":
    "CUÁNDO ENTRA, EN EL CHOQUE SÉPTICO: cuando la PAM sigue inadecuada A PESAR de noradrenalina Y VASOPRESINA — no después de la noradrenalina solamente. ⚠️ EL ORDEN IMPORTA Y LA LISTA DE ESTA PANTALLA NO LO REFLEJA: la vasopresina viene ANTES de la adrenalina en la escalada, aunque aparezca después de ella aquí. ➜ LA EXCEPCIÓN, DELIMITADA: con DISFUNCIÓN CARDÍACA concomitante — y solo en ese caso — la SSC 2026 sugiere noradrenalina O adrenalina como 1ª línea; sin disfunción cardíaca, la 1ª línea es noradrenalina.",
  "Risco de taquiarritmia e aumento de consumo miocárdico — reservar para choque refratário a noradrenalina E vasopressina.":
    "Riesgo de taquiarritmia y aumento del consumo miocárdico — reservar para choque refractario a noradrenalina Y vasopresina.",
};
