/**
 * ES — Taquicardia no ACLS: adenosina, amiodarona com pulso, magnésio no
 * torsades e a conduta de recorrência.
 *
 * A indisponibilidade do isoproterenol é declarada como brasileira no texto ES
 * ("no Brasil") de propósito: quem lê em espanhol pode estar em outro país, e
 * omitir o "onde" transformaria um fato de mercado local em afirmação global.
 */
export const taquicardiaFarmacosEs: Record<string, string> = {
  // ── árvore ──────────────────────────────────────────────────────────────
  "ANTIARRÍTMICO se a TV MONOMÓRFICA persistir apesar dos choques:":
    "ANTIARRÍTMICO si la TV MONOMÓRFICA persiste pese a las descargas:",
  "CONDUTA, e não conselho: QRS largo = TV até prova em contrário. A prova em contrário vem de eletrofisiologia ou de ECG prévio idêntico com o mesmo padrão de bloqueio de ramo — não de impressão à beira do leito.":
    "CONDUCTA, y no consejo: QRS ancho = TV mientras no se demuestre lo contrario. Esa prueba viene de electrofisiología o de un ECG previo idéntico con el mismo patrón de bloqueo de rama — no de la impresión junto a la cama.",
  "ELEVAM a suspeita de TV, e só nessa direção: idade acima de 35 anos, cardiopatia estrutural conhecida, IAM prévio, insuficiência cardíaca, e o próprio paciente dizer que já teve TV.":
    "ELEVAN la sospecha de TV, y solo en esa dirección: edad mayor de 35 años, cardiopatía estructural conocida, IAM previo, insuficiencia cardíaca, y que el propio paciente refiera haber tenido TV.",
  "PERNA 1 — CORRIGIR O EPISÓDIO:": "PATA 1 — CORREGIR EL EPISODIO:",
  "Se QRS estreito e regular, considerar adenosina enquanto prepara o cardioversor — no esquema e na técnica do ramo de QRS estreito regular. NÃO atrasar a cardioversão por causa dela.":
    "Si el QRS es estrecho y regular, considerar adenosina mientras se prepara el cardioversor — con el esquema y la técnica de la rama de QRS estrecho regular. NO retrasar la cardioversión por ella.",
  "TORSADES DE POINTES (QT longo) — a conduta tem TRÊS PERNAS, e tratar só o episódio devolve o paciente ao mesmo substrato:":
    "TORSADES DE POINTES (QT largo) — la conducta tiene TRES PATAS, y tratar solo el episodio devuelve al paciente al mismo sustrato:",
  "TV POLIMÓRFICA (torsades): choque NÃO sincronizado em alta energia — a morfologia variável impede o sincronismo. Depois do choque, a conduta tem três pernas, e nenhuma sozinha fecha o ciclo.":
    "TV POLIMÓRFICA (torsades): descarga NO sincronizada de alta energía — la morfología variable impide el sincronismo. Tras la descarga, la conducta tiene tres patas, y ninguna sola cierra el ciclo.",
  "Tratar uma TSV-com-aberrância COMO TV custa uma amiodarona desnecessária num paciente que ia reverter de outro jeito. Tratar uma TV COMO TSV — verapamil ou diltiazem — pode matar: bloqueio nodal em TV causa colapso hemodinâmico. É por isso que a regra é assimétrica, e não conservadorismo acadêmico: o erro tem preços diferentes.":
    "Tratar una TSV-con-aberrancia COMO TV cuesta una amiodarona innecesaria en un paciente que iba a revertir de otro modo. Tratar una TV COMO TSV — verapamilo o diltiazem — puede matar: el bloqueo nodal en TV causa colapso hemodinámico. Por eso la regla es asimétrica, y no conservadurismo académico: el error tiene precios distintos.",
  "── É TV OU TSV COM ABERRÂNCIA? O CUSTO DE ERRAR NÃO É O MESMO NOS DOIS LADOS ──":
    "── ¿ES TV O TSV CON ABERRANCIA? EL COSTO DE EQUIVOCARSE NO ES EL MISMO EN LOS DOS LADOS ──",
  "⚠️ E A RESSALVA QUE FAZ ESSES DADOS SEREM USÁVEIS: nenhum deles EXCLUI TV. São elevadores de suspeita, não critérios de exclusão — paciente jovem e sem cardiopatia conhecida também tem TV. Ausência de fatores de risco NÃO autoriza tratar como TSV.":
    "⚠️ Y LA SALVEDAD QUE HACE UTILIZABLES ESTOS DATOS: ninguno EXCLUYE TV. Son elevadores de sospecha, no criterios de exclusión — un paciente joven y sin cardiopatía conocida también tiene TV. La ausencia de factores de riesgo NO autoriza tratarlo como TSV.",
  "⚠️ NÃO usar amiodarona no torsades: ela prolonga o QT, que é o substrato da arritmia.":
    "⚠️ NO usar amiodarona en el torsades: prolonga el QT, que es el sustrato de la arritmia.",

  // ── Farmacologia ────────────────────────────────────────────────────────
  "Assistolia prolongada e FV já foram relatadas, com desfechos fatais, sobretudo em uso de digoxina ou digoxina + verapamil.":
    "Se han descrito asistolia prolongada y FV, con desenlaces fatales, sobre todo con digoxina o digoxina + verapamilo.",
  "Como administrar (é a técnica, não o detalhe)":
    "Cómo administrar (es la técnica, no el detalle)",
  "Esquema": "Esquema",
  "Manutenção — regime COM PULSO (NÃO é esquema pós-ROSC)":
    "Mantenimiento — régimen CON PULSO (NO es esquema pos-RCE)",
  "Não reverte flutter, FA nem TV: nesses ritmos causa apenas desaceleração transitória da resposta ventricular — o efeito é diagnóstico, não terapêutico.":
    "No revierte flutter, FA ni TV: en esos ritmos solo produce desaceleración transitoria de la respuesta ventricular — el efecto es diagnóstico, no terapéutico.",
  "Se recorrer durante a infusão": "Si recurre durante la infusión",
  "Torsades de Pointes: NÃO usar amiodarona (prolonga o QT) — o fármaco ali é o sulfato de magnésio, com dose e tempo no módulo de Taquicardia":
    "Torsades de Pointes: NO usar amiodarona (prolonga el QT) — allí el fármaco es el sulfato de magnesio, con dosis y tiempo en el módulo de Taquicardia",

  // ── lib/adenosina ───────────────────────────────────────────────────────
  "ADENOSINA — 6 mg IV em bolus rápido. Se não reverter em 1–2 min: 12 mg. Se ainda não reverter: o mesmo 12 mg pode ser repetido uma segunda vez (esquema 6–12–12 do Resuscitation Council UK; a AHA descreve 6–12 e, na falha, reavaliar o diagnóstico). ⚠️ Doses acima de 12 mg NÃO são recomendadas, nem em adultos nem em pediatria.":
    "ADENOSINA — 6 mg IV en bolo rápido. Si no revierte en 1–2 min: 12 mg. Si aún no revierte: los mismos 12 mg pueden repetirse una segunda vez (esquema 6–12–12 del Resuscitation Council UK; la AHA describe 6–12 y, ante el fallo, reevaluar el diagnóstico). ⚠️ Dosis superiores a 12 mg NO se recomiendan, ni en adultos ni en pediatría.",
  "ANTES DE REPETIR, descarte falha de administração: bolus lento, veia periférica fina ou flush insuficiente simulam ausência de resposta. Confirme também registro contínuo do ECG (é a resposta que dá o diagnóstico, mesmo quando o ritmo não reverte), ritmo regular e ausência de pré-excitação.":
    "ANTES DE REPETIR, descarte un fallo de administración: bolo lento, vena periférica fina o lavado insuficiente simulan ausencia de respuesta. Confirme también registro continuo del ECG (es la respuesta la que da el diagnóstico, incluso cuando el ritmo no revierte), ritmo regular y ausencia de preexcitación.",
  "COMO SE DÁ (é a técnica, não o detalhe): apresentação 6 mg/2 mL — 6 mg é UMA ampola inteira, 12 mg são DUAS. NUNCA diluir. Acesso PROXIMAL e calibroso (fossa antecubital ou central), injeção em 1–2 s e FLUSH DE 20 mL de salina IMEDIATAMENTE, com o braço elevado. A meia-vida é menor que 10 segundos: com acesso distal, flush pequeno ou injeção lenta, o fármaco se degrada antes de chegar ao coração — e o quadro é idêntico ao de uma dose que não funcionou.":
    "CÓMO SE DA (es la técnica, no el detalle): presentación 6 mg/2 mL — 6 mg es UNA ampolla entera, 12 mg son DOS. NUNCA diluir. Acceso PROXIMAL y de buen calibre (fosa antecubital o central), inyección en 1–2 s y LAVADO DE 20 mL de salino INMEDIATAMENTE, con el brazo elevado. La vida media es menor de 10 segundos: con acceso distal, lavado escaso o inyección lenta, el fármaco se degrada antes de llegar al corazón — y el cuadro es idéntico al de una dosis que no funcionó.",
  "INTERAÇÕES QUE MUDAM A DOSE: teofilina e cafeína ANTAGONIZAM — pode ser necessária dose maior, ou o fármaco pode simplesmente não funcionar. Dipiridamol POTENCIALIZA: doses menores podem bastar. Cautela com digoxina, ou digoxina + verapamil (relatos raros de FV nessa associação); carbamazepina aumenta o grau de bloqueio. Individualizar também no transplante cardíaco.":
    "INTERACCIONES QUE CAMBIAN LA DOSIS: teofilina y cafeína ANTAGONIZAN — puede hacer falta una dosis mayor, o el fármaco simplemente no funciona. El dipiridamol POTENCIA: dosis menores pueden bastar. Cautela con digoxina, o digoxina + verapamilo (informes raros de FV en esa asociación); la carbamazepina aumenta el grado de bloqueo. Individualizar también en el trasplante cardíaco.",
  "⚠️ Atropina NÃO bloqueia a adenosina — não serve como antídoto. A meia-vida é menor que 10 s e os efeitos são autolimitados: pausa, bloqueio e o desconforto passam sozinhos. Avisar o paciente antes da injeção sobre rubor, dispneia e opressão torácica transitórios.":
    "⚠️ La atropina NO bloquea la adenosina — no sirve como antídoto. La vida media es menor de 10 s y los efectos son autolimitados: la pausa, el bloqueo y el malestar ceden solos. Avisar al paciente antes de la inyección sobre rubor, disnea y opresión torácica transitorios.",
  "⚠️ CONTRAINDICADA em BAV de 2º ou 3º grau e na doença do nó sinusal, exceto com marca-passo funcionante. NÃO usar em FA ou flutter com PRÉ-EXCITAÇÃO (WPW) — risco de FV. Evitar em broncoconstrição ou broncoespasmo (asma); com cautela na DPOC sem broncoespasmo. ⚠️ Quem desenvolver bloqueio de alto grau com uma dose NÃO deve receber doses adicionais.":
    "⚠️ CONTRAINDICADA en BAV de 2.º o 3.er grado y en la enfermedad del nódulo sinusal, salvo con marcapasos funcionante. NO usar en FA o flutter con PREEXCITACIÓN (WPW) — riesgo de FV. Evitar en broncoconstricción o broncoespasmo (asma); con cautela en la EPOC sin broncoespasmo. ⚠️ Quien desarrolle bloqueo de alto grado con una dosis NO debe recibir dosis adicionales.",

  // ── lib/amiodarona-com-pulso ────────────────────────────────────────────
  "AMIODARONA — 150 mg IV em 10 min (diluídos em 100 mL de SG5%). ⚠️ Este é o regime do paciente COM PULSO. NÃO é o da PCR, onde a 1ª dose é 300 mg em bolus.":
    "AMIODARONA — 150 mg IV en 10 min (diluidos en 100 mL de SG5%). ⚠️ Este es el régimen del paciente CON PULSO. NO es el del paro, donde la 1.ª dosis son 300 mg en bolo.",
  "MANUTENÇÃO, que é do regime COM PULSO — não é esquema de pós-PCR: 1 mg/min por 6 h (360 mg), depois 0,5 mg/min por 18 h (540 mg) — cerca de 1 g nas primeiras 24 h. Passadas as 24 h, mantém-se 0,5 mg/min (720 mg/dia), e a bula admite até 2–3 semanas nessa taxa, independentemente de idade, função renal ou função ventricular.":
    "MANTENIMIENTO, que es del régimen CON PULSO — no es esquema pos-paro: 1 mg/min durante 6 h (360 mg), después 0,5 mg/min durante 18 h (540 mg) — cerca de 1 g en las primeras 24 h. Pasadas las 24 h se mantiene 0,5 mg/min (720 mg/día), y la ficha técnica admite hasta 2–3 semanas a esa velocidad, con independencia de la edad, la función renal o la función ventricular.",
  "SE A ARRITMIA RECORRER durante a infusão: 150 mg suplementares em 100 mL de SG5%, infundidos em 10 min — a mesma carga, repetida. Não é preciso reiniciar o esquema: a manutenção continua na taxa em que estava.":
    "SI LA ARRITMIA RECURRE durante la infusión: 150 mg suplementarios en 100 mL de SG5%, infundidos en 10 min — la misma carga, repetida. No hace falta reiniciar el esquema: el mantenimiento sigue a la velocidad en que estaba.",
  "VIGIAR: PA (hipotensão é o efeito adverso limitante e é dose e velocidade-dependente — não acelerar a carga), bradicardia, bloqueio AV e QT. ⚠️ EVITAR em torsades e em QT longo: a amiodarona prolonga o QT, e ali o fármaco é o magnésio. NÃO usar em FA pré-excitada (WPW). Sem teto máximo declarado em bula, mas doses médias diárias acima de ~2100 mg associaram-se a mais hipotensão em ensaios controlados — é observação de ensaio, não limite regulatório.":
    "VIGILAR: PA (la hipotensión es el efecto adverso limitante y depende de la dosis y de la velocidad — no acelerar la carga), bradicardia, bloqueo AV y QT. ⚠️ EVITAR en torsades y en QT largo: la amiodarona prolonga el QT, y allí el fármaco es el magnesio. NO usar en FA preexcitada (WPW). Sin techo máximo declarado en la ficha técnica, pero dosis medias diarias por encima de ~2100 mg se asociaron a más hipotensión en ensayos controlados — es observación de ensayo, no límite regulatorio.",

  // ── lib/magnesio-torsades ───────────────────────────────────────────────
  "APRESENTAÇÃO: sulfato de magnésio 50% (500 mg/mL), ampola de 10 mL = 5 g. 2 g são 4 mL — a ampola inteira é MAIS que o dobro da dose. Diluir em 50–100 mL de SF ou SG5% para infundir.":
    "PRESENTACIÓN: sulfato de magnesio al 50% (500 mg/mL), ampolla de 10 mL = 5 g. 2 g son 4 mL — la ampolla entera es MÁS del doble de la dosis. Diluir en 50–100 mL de SF o SG5% para infundir.",
  "DEPOIS DA CARGA, se o torsades recorrer: infusão de 1–4 g/h, com alvo de magnésio acima de 2 mmol/L. Reduzir acima de 2,5 mmol/L e SUSPENDER acima de 3 mmol/L — toxicidade grave (confusão, depressão respiratória, coma) aparece acima de 3,5. Vigiar reflexos, frequência cardíaca e padrão respiratório à beira do leito, que respondem antes do laboratório.":
    "TRAS LA CARGA, si el torsades recurre: infusión de 1–4 g/h, con objetivo de magnesio por encima de 2 mmol/L. Reducir por encima de 2,5 mmol/L y SUSPENDER por encima de 3 mmol/L — la toxicidad grave (confusión, depresión respiratoria, coma) aparece por encima de 3,5. Vigilar reflejos, frecuencia cardíaca y patrón respiratorio junto a la cama, que responden antes que el laboratorio.",
  "SULFATO DE MAGNÉSIO — 1–2 g IV/IO em 1–2 min. Aqui o paciente está em PARADA: não há pressão a proteger, e a ressalva de infusão lenta do torsades COM pulso não se aplica.":
    "SULFATO DE MAGNESIO — 1–2 g IV/IO en 1–2 min. Aquí el paciente está en PARO: no hay presión que proteger, y la salvedad de infusión lenta del torsades CON pulso no se aplica.",
  "SULFATO DE MAGNÉSIO — 2 g IV, infundidos em 10–20 min. Se o paciente estiver instável, é razoável dar em push LENTO: o tempo é o que se troca pela tolerância. ⚠️ POR QUE NÃO CORRER: magnésio vasodilata e freia o nó AV — infusão rápida causa hipotensão e bradicardia, e no torsades você está tratando alguém que já pode não ter pressão sobrando. Pode repetir 2 g uma vez se não houver efeito clínico.":
    "SULFATO DE MAGNESIO — 2 g IV, infundidos en 10–20 min. Si el paciente está inestable, es razonable darlo en push LENTO: el tiempo es lo que se cambia por la tolerancia. ⚠️ POR QUÉ NO CORRER: el magnesio vasodilata y frena el nódulo AV — la infusión rápida causa hipotensión y bradicardia, y en el torsades está tratando a alguien que quizá ya no tenga presión de sobra. Puede repetir 2 g una vez si no hay efecto clínico.",

  // ── lib/torsades-recorrente ─────────────────────────────────────────────
  "As doses de reposição de potássio e magnésio — via, velocidade máxima e limites por acesso — estão no módulo de Eletrólitos. Aqui vale o alvo: K⁺ em 4,5–5,0 mEq/L e magnésio reposto mesmo com nível normal.":
    "Las dosis de reposición de potasio y magnesio — vía, velocidad máxima y límites por acceso — están en el módulo de Electrolitos. Aquí vale el objetivo: K⁺ en 4,5–5,0 mEq/L y magnesio repuesto aunque el nivel sea normal.",
  "PERNA 2 — IMPEDIR A RECORRÊNCIA: ACELERAR O CORAÇÃO. O torsades adquirido é pausa-dependente: encurtar o ciclo suprime o substrato. Alvo de 90–110 bpm (ocasionalmente até 140). MARCA-PASSO DE SOBRE-ESTIMULAÇÃO é a via principal — TRANSCUTÂNEO é o que está na sala de emergência e serve de ponte, mas é mal tolerado no paciente acordado e EXIGE analgesia e sedação para capturar de fato; TRANSVENOSO é o definitivo, e é para ele que se caminha, com o tempo e a equipe que ele exige. ⚠️ ISOPROTERENOL (5 mcg/min, titulado ~30 bpm acima do ritmo próprio) é a alternativa farmacológica da literatura, mas NÃO há produto industrializado com registro ativo no Brasil — encontra-se por manipulação ou importação, o que o inviabiliza na emergência. Conte com o marca-passo. E ele é CONTRAINDICADO no QT longo congênito.":
    "PATA 2 — IMPEDIR LA RECURRENCIA: ACELERAR EL CORAZÓN. El torsades adquirido es pausa-dependiente: acortar el ciclo suprime el sustrato. Objetivo de 90–110 lpm (ocasionalmente hasta 140). EL MARCAPASOS DE SOBREESTIMULACIÓN es la vía principal — el TRANSCUTÁNEO es el que está en la sala de emergencia y sirve de puente, pero se tolera mal en el paciente despierto y EXIGE analgesia y sedación para capturar de verdad; el TRANSVENOSO es el definitivo, y es hacia él que se camina, con el tiempo y el equipo que exige. ⚠️ El ISOPROTERENOL (5 mcg/min, titulado ~30 lpm por encima del ritmo propio) es la alternativa farmacológica de la literatura, pero NO hay producto industrializado con registro activo en Brasil — se consigue por formulación magistral o importación, lo que lo inviabiliza en la emergencia; verifique la disponibilidad en su país. Y está CONTRAINDICADO en el QT largo congénito.",
  "PERNA 3 — REMOVER A CAUSA, que é o que fecha o ciclo. Torsades adquirido é quase sempre DROGA QUE PROLONGA O QT somada a DISTÚRBIO ELETROLÍTICO. SUSPENDER o agente agora: antiarrítmicos (classes IA e III — inclusive amiodarona), antipsicóticos (haloperidol IV, quetiapina), antidepressivos (citalopram, tricíclicos), macrolídeos e quinolonas, antieméticos (ondansetrona, domperidona), metadona, antifúngicos azólicos. REPOR agressivamente: K⁺ com alvo em 4,5–5,0 mEq/L, e magnésio mesmo com nível normal. Rever também bradicardia e BAV — se houver, são a pausa que dispara a arritmia.":
    "PATA 3 — RETIRAR LA CAUSA, que es lo que cierra el ciclo. El torsades adquirido es casi siempre un FÁRMACO QUE PROLONGA EL QT sumado a un TRASTORNO ELECTROLÍTICO. SUSPENDER el agente ahora: antiarrítmicos (clases IA y III — incluida la amiodarona), antipsicóticos (haloperidol IV, quetiapina), antidepresivos (citalopram, tricíclicos), macrólidos y quinolonas, antieméticos (ondansetrón, domperidona), metadona, antifúngicos azólicos. REPONER de forma agresiva: K⁺ con objetivo de 4,5–5,0 mEq/L, y magnesio aunque el nivel sea normal. Revisar también bradicardia y BAV — si los hay, son la pausa que dispara la arritmia.",
};
