/**
 * ES — TCE: as linhas de METAS que voltaram a ser literais (D-35), a escalada
 * em etapas na superfície de ação, a hiperventilação de 3ª linha com a
 * monitorização como condição, e a leitura da evidência sobre TC de rotina.
 */
export const tceAlvosEs: Record<string, string> = {
  "Normocapnia: PaCO₂ 35–40 mmHg. NÃO hiperventilar profilaticamente — o porquê e a exceção da herniação vêm no passo de neuroproteção.":
    "Normocapnia: PaCO₂ 35–40 mmHg. NO hiperventilar de forma profiláctica — el porqué y la excepción de la herniación vienen en el paso de neuroprotección.",

  "Metas: PAS ≥ 110 mmHg (BTF: ≥ 110 para 15–49 e > 70 anos; ≥ 100 para 50–69 anos) · SpO₂ ≥ 90% · PaCO₂ 35–40 mmHg · normotermia (evitar febre) · normoglicemia · sódio normal-alto.":
    "Metas: PAS ≥ 110 mmHg (BTF: ≥ 110 para 15–49 y > 70 años; ≥ 100 para 50–69 años) · SpO₂ ≥ 90% · PaCO₂ 35–40 mmHg · normotermia (evitar la fiebre) · normoglucemia · sodio normal-alto.",

  "Ventilação: Vt 6–8 mL/kg PBW com platô < 30 cmH₂O. PEEP 5–10 cmH₂O — até 15 cmH₂O SOMENTE em paciente estável, euvolêmico e com neuromonitorização — condição que raramente existe na emergência; sem isso, o alvo é 5–10.":
    "Ventilación: Vt 6–8 mL/kg de peso predicho con meseta < 30 cmH₂O. PEEP 5–10 cmH₂O — hasta 15 cmH₂O SOLO en paciente estable, euvolémico y con neuromonitorización — condición que raramente existe en la emergencia; sin eso, el objetivo es 5–10.",

  "Metas mantidas: PIC < 22 mmHg, PPC 60–70 mmHg, PaCO₂ 35–40 mmHg, SpO₂ ≥ 90%, PAS ≥ 110 mmHg (BTF: ≥ 110 para 15–49 e > 70 anos; ≥ 100 para 50–69 anos), normotermia e normoglicemia.":
    "Metas mantenidas: PIC < 22 mmHg, PPC 60–70 mmHg, PaCO₂ 35–40 mmHg, SpO₂ ≥ 90%, PAS ≥ 110 mmHg (BTF: ≥ 110 para 15–49 y > 70 años; ≥ 100 para 50–69 años), normotermia y normoglucemia.",

  "HIC REFRATÁRIA às medidas acima — 2ª ETAPA: aprofundar sedação e analgesia, terapia hiperosmolar para natremia mais alta, e avaliação de craniectomia descompressiva com o neurocirurgião. ⚠️ Antes de subir de etapa, refazer a checagem das causas extracranianas — a resistência ao tratamento costuma ter causa remediável.":
    "HIC REFRACTARIA a las medidas anteriores — 2.ª ETAPA: profundizar la sedación y la analgesia, terapia hiperosmolar para natremia más alta, y evaluación de craniectomía descompresiva con el neurocirujano. ⚠️ Antes de subir de etapa, rehacer la revisión de las causas extracraneales — la resistencia al tratamiento suele tener causa remediable.",

  "HIC refratária — 3ª ETAPA, medidas de RESGATE (maior risco, e é por isso que vêm por último): titular sedação até surto-supressão no EEG (surtos de 5–20 s, ou 50% do traçado em supressão); tiopental em bólus de 5–15 mg/kg em 30 min a 2 h, seguido de 1–4 mg/kg/h; hipotermia moderada com temperatura central de 32–34 °C.":
    "HIC refractaria — 3.ª ETAPA, medidas de RESCATE (mayor riesgo, y por eso vienen al final): titular la sedación hasta brote-supresión en el EEG (brotes de 5–20 s, o 50% del trazado en supresión); tiopental en bolo de 5–15 mg/kg en 30 min a 2 h, seguido de 1–4 mg/kg/h; hipotermia moderada con temperatura central de 32–34 °C.",

  "HIC REFRATÁRIA: a escalada em etapas está no passo de conduta da herniação — 1ª etapa (medidas gerais, osmoterapia, drenagem), 2ª (sedação profunda, natremia mais alta, craniectomia) e 3ª (surto-supressão, hipotermia). Aqui se MANTÉM o que foi escalado e se reavalia a cada piora.":
    "HIC REFRACTARIA: la escalada por etapas está en el paso de conducta de la herniación — 1.ª etapa (medidas generales, osmoterapia, drenaje), 2.ª (sedación profunda, natremia más alta, craniectomía) y 3.ª (brote-supresión, hipotermia). Aquí se MANTIENE lo que se escaló y se reevalúa ante cada empeoramiento.",

  'HIPERVENTILAÇÃO DE 3ª LINHA — PaCO₂ 25–34 mmHg (protocolo institucional Einstein/SBIBAE, CPTW263.2) — e ela NÃO é a hiperventilação-ponte da herniação. ⚠️ DESCER ABAIXO DE PaCO₂ 30 SÓ COM MONITORIZAÇÃO ADICIONAL DE OXIGENAÇÃO CEREBRAL — saturação venosa jugular ou PtiO₂. Sem essa monitorização, o piso é 30 mmHg. O motivo do piso: a hiperventilação baixa a PIC por VASOCONSTRIÇÃO CEREBRAL, isto é, cortando fluxo — abaixo de 30 a queda de fluxo passa a produzir isquemia em tecido que já está em risco, e é por isso que não se desce "só um pouco mais" quando a PIC não cede. ⚠️ A LITERATURA ABERTA NÃO SUSTENTA ABAIXO DE 30 SEM MONITORIZAÇÃO: o consenso de hiperventilação no TCE adulto coloca a hiperventilação controlada como terapia de tier 2 com alvo 33–36 mmHg, dizendo "avoid values <30 mmHg" e "should never decrease below PaCO2 values of 30 mmHg". O 25–34 vem do protocolo institucional citado por este módulo, e vale COM a monitorização que ele mesmo exige.':
    'HIPERVENTILACIÓN DE 3.ª LÍNEA — PaCO₂ 25–34 mmHg (protocolo institucional Einstein/SBIBAE, CPTW263.2) — y NO es la hiperventilación-puente de la herniación. ⚠️ BAJAR POR DEBAJO DE PaCO₂ 30 SOLO CON MONITORIZACIÓN ADICIONAL DE OXIGENACIÓN CEREBRAL — saturación venosa yugular o PtiO₂. Sin esa monitorización, el piso es 30 mmHg. El motivo del piso: la hiperventilación baja la PIC por VASOCONSTRICCIÓN CEREBRAL, es decir, cortando flujo — por debajo de 30 la caída de flujo pasa a producir isquemia en tejido que ya está en riesgo, y por eso no se baja "solo un poco más" cuando la PIC no cede. ⚠️ LA LITERATURA ABIERTA NO SOSTIENE BAJAR DE 30 SIN MONITORIZACIÓN: el consenso de hiperventilación en el TCE del adulto sitúa la hiperventilación controlada como terapia de tier 2 con objetivo 33–36 mmHg, diciendo "avoid values <30 mmHg" y "should never decrease below PaCO2 values of 30 mmHg". El 25–34 viene del protocolo institucional citado por este módulo, y vale CON la monitorización que él mismo exige.',

  "SOBRE A TC DE ROTINA — O QUE A EVIDÊNCIA DIZ, E DE QUEM ELA FALA: o gatilho que manda é o CLÍNICO. Em TCE LEVE estável, o rendimento da repetição de rotina é baixo — num estudo prospectivo de centro único com 231 casos, a repetição programada levou à cirurgia em 3,5%, e nenhum paciente de alta com Glasgow > 13 sem repetir deteriorou; num retrospectivo de 144 pacientes anticoagulados ou antiagregados com TCE leve e TC inicial NORMAL, houve 0,7% de hemorragia tardia, sem necessidade de intervenção. ⚠️ ESTES NÚMEROS NÃO VALEM PARA O TCE MODERADO OU GRAVE, nem para quem já tem sangramento na primeira TC — não há evidência de mesmo porte ali, e a assimetria de dano continua mandando: TC a mais custa radiação e tempo; hematoma tardio não visto custa o paciente.":
    "SOBRE LA TC DE RUTINA — LO QUE DICE LA EVIDENCIA, Y DE QUIÉN HABLA: el disparador que manda es el CLÍNICO. En TCE LEVE estable, el rendimiento de la repetición de rutina es bajo — en un estudio prospectivo de centro único con 231 casos, la repetición programada llevó a cirugía en 3,5%, y ningún paciente dado de alta con Glasgow > 13 sin repetir se deterioró; en un retrospectivo de 144 pacientes anticoagulados o antiagregados con TCE leve y TC inicial NORMAL, hubo 0,7% de hemorragia tardía, sin necesidad de intervención. ⚠️ ESTOS NÚMEROS NO VALEN PARA EL TCE MODERADO O GRAVE, ni para quien ya tiene sangrado en la primera TC — no hay evidencia de la misma magnitud allí, y la asimetría de daño sigue mandando: una TC de más cuesta radiación y tiempo; un hematoma tardío no visto cuesta el paciente.",

  "HIPERVENTILAÇÃO NA HIC REFRATÁRIA — usar apenas como RESGATE, não como rotina. No algoritmo SIBICC, hiperventilação leve com PaCO₂ 32–35 mmHg é opção de tier 2; PaCO₂ 30–32 mmHg aparece apenas no tier 3 e, no algoritmo com monitorização de oxigênio cerebral, somente quando não há hipoxia tecidual cerebral. A LITERATURA ABERTA NÃO SUSTENTA adotar alvo abaixo de 30 mmHg como regra geral de resgate. Evitar PaCO₂ <30 mmHg e NÃO usar PaCO₂ ≤25 mmHg de forma profilática ou prolongada. Reavaliar PIC, PPC e oxigenação cerebral quando disponível e reverter a hipocapnia assim que a medida de resgate deixar de ser necessária.":
    "HIPERVENTILACIÓN EN LA HIC REFRACTARIA — usar solo como RESCATE, no como rutina. En el algoritmo SIBICC, la hiperventilación leve con PaCO₂ 32–35 mmHg es una opción de tier 2; PaCO₂ 30–32 mmHg aparece solo en tier 3 y, en el algoritmo con monitorización de oxígeno cerebral, únicamente cuando no hay hipoxia tisular cerebral. LA LITERATURA ABIERTA NO RESPALDA adoptar un objetivo por debajo de 30 mmHg como regla general de rescate. Evitar PaCO₂ <30 mmHg y NO usar PaCO₂ ≤25 mmHg de forma profiláctica o prolongada. Reevaluar PIC, PPC y oxigenación cerebral cuando esté disponible y revertir la hipocapnia tan pronto como la medida de rescate deje de ser necesaria.",
};
