/** ES — TEP: o choque normotenso (construto que faltava) e a equivalência que perde granularidade (R-63). */
export const tepChoqueNormotensoEs: Record<string, string> = {
  "⚠️ PRESSÃO NORMAL NÃO É PERFUSÃO NORMAL — E ESTE É O PACIENTE QUE A CLASSIFICAÇÃO ANTIGA NÃO ENXERGAVA. Existe um estado, entre o TEP estável e o TEP com choque declarado, em que a PRESSÃO AINDA ESTÁ PRESERVADA e a PERFUSÃO JÁ FALHOU: o ventrículo direito está falhando, o débito caiu, e a vasoconstrição sustenta o número do monitor enquanto os órgãos já não recebem sangue. É o CHOQUE NORMOTENSO, e reconhecê-lo cedo é o motivo pelo qual a classificação de 2026 substituiu \"maciço/submaciço\" — os rótulos antigos só tinham duas caixas, e este paciente caía na de baixo. ⚠️ COMO SUSPEITAR, SEM DEPENDER DA PRESSÃO: sinais de má perfusão em quem está normotenso — lactato que sobe, diurese que cai, extremidades frias, confusão, taquicardia desproporcional — somados a disfunção de VD na imagem e biomarcador elevado. ⚠️ E O QUE ISSO MUDA: ele NÃO é um TEP intermediário estável que se observa; é um paciente em deterioração, que exige vigilância intensiva, acionamento do time de resposta (PERT) e decisão precoce sobre reperfusão — antes de a pressão cair, porque quando ela cai a mortalidade já é outra. Reavalie de perto: a piora costuma ser de horas, não de dias.":
    "⚠️ PRESIÓN NORMAL NO ES PERFUSIÓN NORMAL — Y ESTE ES EL PACIENTE QUE LA CLASIFICACIÓN ANTIGUA NO VEÍA. Existe un estado, entre el TEP estable y el TEP con choque declarado, en el que la PRESIÓN AÚN ESTÁ PRESERVADA y la PERFUSIÓN YA FALLÓ: el ventrículo derecho está fallando, el gasto cayó, y la vasoconstricción sostiene el número del monitor mientras los órganos ya no reciben sangre. Es el CHOQUE NORMOTENSO, y reconocerlo temprano es el motivo por el cual la clasificación de 2026 sustituyó \"masivo/submasivo\" — las etiquetas antiguas solo tenían dos cajas, y este paciente caía en la de abajo. ⚠️ CÓMO SOSPECHARLO, SIN DEPENDER DE LA PRESIÓN: signos de mala perfusión en quien está normotenso — lactato que sube, diuresis que cae, extremidades frías, confusión, taquicardia desproporcionada — sumados a disfunción del VD en la imagen y biomarcador elevado. ⚠️ Y QUÉ CAMBIA ESO: NO es un TEP intermedio estable que se observa; es un paciente en deterioro, que exige vigilancia intensiva, activación del equipo de respuesta (PERT) y decisión precoz sobre reperfusión — antes de que la presión caiga, porque cuando cae la mortalidad ya es otra. Reevalúe de cerca: el empeoramiento suele ser de horas, no de días.",
  "⚠️ PROCEDÊNCIA: a classificação AHA/ACC 2026 define este estado com CRITÉRIOS NUMÉRICOS de hipoperfusão, e este app AINDA NÃO OS REPRODUZ — o texto integral da diretriz não foi aberto, e reproduzir critério a partir de resumo de terceiro é o erro que esta auditoria recusa. O que está escrito acima é o construto clínico e a conduta que decorre dele. Para os pontos de corte, consulte a diretriz de 2026 diretamente.":
    "⚠️ PROCEDENCIA: la clasificación AHA/ACC 2026 define este estado con CRITERIOS NUMÉRICOS de hipoperfusión, y esta app AÚN NO LOS REPRODUCE — el texto integral de la guía no se abrió, y reproducir un criterio a partir del resumen de un tercero es el error que esta auditoría rechaza. Lo que está escrito arriba es el constructo clínico y la conducta que se deriva de él. Para los puntos de corte, consulte la guía de 2026 directamente.",
  "AHA/ACC 2026 — nova classificação A–E: A subclínico (assintomático) · B baixa gravidade · C gravidade elevada (biomarcador e/ou disfunção de VD → internar) · D falência incipiente (instabilidade TRANSITÓRIA) · E falência cardiopulmonar (hipotensão/choque persistente). Equivalência APROXIMADA com o esquema antigo: A–B ≈ baixo risco, C ≈ intermediário, D–E ≈ alto risco. ⚠️ E A EQUIVALÊNCIA PERDE O QUE A REVISÃO ACRESCENTOU: achatar cinco categorias em três apaga justamente o estado que a classificação de 2026 foi criada para nomear — o paciente com PRESSÃO PRESERVADA e PERFUSÃO JÁ FALHANDO. Use o esquema novo para decidir, e a equivalência só para conversar com quem ainda fala em maciço/submaciço.":
    "AHA/ACC 2026 — nueva clasificación A–E: A subclínico (asintomático) · B baja gravedad · C gravedad elevada (biomarcador y/o disfunción del VD → internar) · D falla incipiente (inestabilidad TRANSITORIA) · E falla cardiopulmonar (hipotensión/choque persistente). Equivalencia APROXIMADA con el esquema antiguo: A–B ≈ bajo riesgo, C ≈ intermedio, D–E ≈ alto riesgo. ⚠️ Y LA EQUIVALENCIA PIERDE LO QUE LA REVISIÓN AGREGÓ: aplanar cinco categorías en tres borra justamente el estado que la clasificación de 2026 fue creada para nombrar — el paciente con PRESIÓN PRESERVADA y PERFUSIÓN YA FALLANDO. Use el esquema nuevo para decidir, y la equivalencia solo para conversar con quien todavía habla de masivo/submasivo.",
};
