/** ES — TEP: regimes de enoxaparina, HNF e contraindicações relativas. */
export const tepAnticoagulacaoEs: Record<string, string> = {
  "ENOXAPARINA NO IAM COM FIBRINÓLISE — < 75 anos: bolus IV de 30 mg + 1 mg/kg SC 12/12h. ≥ 75 anos: SEM bolus IV, 0,75 mg/kg SC 12/12h. ⚠️ O bolus e o corte por idade são DESTE contexto: o bolus existe para cobrir o momento do trombolítico, e a redução no idoso veio do excesso de hemorragia intracraniana em quem foi trombolisado. Fora da fibrinólise, nenhum dos dois se aplica.":
    "ENOXAPARINA EN EL IAM CON FIBRINÓLISIS — < 75 años: bolo IV de 30 mg + 1 mg/kg SC cada 12 h. ≥ 75 años: SIN bolo IV, 0,75 mg/kg SC cada 12 h. ⚠️ El bolo y el corte por edad son DE ESTE contexto: el bolo existe para cubrir el momento del trombolítico, y la reducción en el anciano vino del exceso de hemorragia intracraneal en quien fue trombolizado. Fuera de la fibrinólisis, ninguno de los dos se aplica.",
  "ENOXAPARINA NO TEP/TVP — 1 mg/kg SC 12/12h, SEM bolus IV e SEM redução por idade: aqui ela é a anticoagulação em si, não adjuvante de trombolítico. Alternativa em dose única diária: 1,5 mg/kg 24/24h. ⚠️ AJUSTE RENAL: com ClCr < 30 mL/min, espaçar para 1 mg/kg 24/24h — a enoxaparina é de eliminação renal e acumula.":
    "ENOXAPARINA EN EL TEP/TVP — 1 mg/kg SC cada 12 h, SIN bolo IV y SIN reducción por edad: aquí es la anticoagulación en sí, no adyuvante de trombolítico. Alternativa en dosis única diaria: 1,5 mg/kg cada 24 h. ⚠️ AJUSTE RENAL: con ClCr < 30 mL/min, espaciar a 1 mg/kg cada 24 h — la enoxaparina es de eliminación renal y se acumula.",
  "Idade > 75 anos; anticoagulação oral em uso; gestação e primeira semana pós-parto; RCP prolongada ou traumática; punção vascular não compressível; HAS grave não controlada (> 180/110); doença hepática avançada; endocardite infecciosa; úlcera péptica ativa; cirurgia de grande porte < 3 semanas; sangramento interno recente (2–4 semanas).":
    "Edad > 75 años; anticoagulación oral en uso; embarazo y primera semana posparto; RCP prolongada o traumática; punción vascular no compresible; HTA grave no controlada (> 180/110); enfermedad hepática avanzada; endocarditis infecciosa; úlcera péptica activa; cirugía mayor < 3 semanas; sangrado interno reciente (2–4 semanas).",
  "⚠️ EM PCR OU COLAPSO IMINENTE, AS RELATIVAS TORNAM-SE ACEITÁVEIS — a conta inverte: o risco de sangrar perde para o risco de morrer nos próximos minutos. Fora dessa situação, com relativa e sem absoluta, pese o tamanho do TEP contra o sítio de sangramento e considere a via de CATETER, que usa dose menor.":
    "⚠️ EN PARO O COLAPSO INMINENTE, LAS RELATIVAS SE VUELVEN ACEPTABLES — la cuenta se invierte: el riesgo de sangrar pierde frente al riesgo de morir en los próximos minutos. Fuera de esa situación, con relativa y sin absoluta, pese el tamaño del TEP contra el sitio de sangrado y considere la vía por CATÉTER, que usa dosis menor.",
  "APRESENTAÇÃO E PREPARO — heparina sódica 5.000 UI/mL: o frasco-ampola de 5 mL tem 25.000 UI. ⚠️ CONFIRA O RÓTULO: convivem na mesma gaveta o frasco para BOMBA (5.000 UI/mL) e o de uso SUBCUTÂNEO, com aparência parecida. A dose se prescreve em MILHARES de unidades e o volume é pequeno — um bolus de 5.600 U cabe em pouco mais de 1 mL, e errar uma casa na diluição é um fator de DEZ num anticoagulante pleno. Diluir a solução de bomba em SF ou SG5% conforme o protocolo da unidade, e conferir a programação com um segundo profissional.":
    "PRESENTACIÓN Y PREPARACIÓN — heparina sódica 5.000 UI/mL: el frasco-ampolla de 5 mL tiene 25.000 UI. ⚠️ VERIFIQUE LA ETIQUETA: conviven en el mismo cajón el frasco para BOMBA (5.000 UI/mL) y el de uso SUBCUTÁNEO, de aspecto parecido. La dosis se prescribe en MILES de unidades y el volumen es pequeño — un bolo de 5.600 U cabe en poco más de 1 mL, y errar una casilla en la dilución es un factor de DIEZ en un anticoagulante pleno. Diluir la solución de bomba en SF o SG5% según el protocolo de la unidad, y verificar la programación con un segundo profesional.",
};
